from fastapi import APIRouter, Request
from fastapi.responses import JSONResponse

router = APIRouter()

_ROUTES = {
    "/v2/chat-context": ("POST",),
    "/v2/chat/initial-message": ("POST",),
    "/v2/chat/generate-title": ("POST",),
    "/v2/chat-sessions": ("GET", "POST"),
    "/v2/chat-sessions/{id}": ("GET", "PATCH", "DELETE"),
    "/v1/advice": ("GET", "POST"),
    "/v1/advice/{id}": ("PATCH", "DELETE"),
    "/v1/advice/mark-all-read": ("POST",),
    "/v1/focus-sessions": ("GET", "POST"),
    "/v1/focus-sessions/{id}": ("DELETE",),
    "/v1/focus-stats": ("GET",),
    "/v1/folders": ("GET", "POST"),
    "/v1/folders/{id}": ("PATCH", "DELETE"),
    "/v1/folders/reorder": ("POST",),
    "/v1/folders/{id}/conversations/bulk-move": ("POST",),
    "/v1/conversations/{id}/folder": ("PATCH",),
    "/v1/goals": ("POST",),
    "/v1/goals/all": ("GET",),
    "/v1/goals/completed": ("GET",),
    "/v1/goals/{id}": ("PATCH", "DELETE"),
    "/v1/goals/{id}/progress": ("PATCH",),
    "/v1/goals/{id}/history": ("GET",),
    "/v1/daily-score": ("GET",),
    "/v1/scores": ("GET",),
    "/v1/users/people": ("GET", "POST"),
    "/v1/users/people/{person_id}": ("DELETE",),
    "/v1/users/people/{person_id}/name": ("PATCH",),
    "/v1/conversations/{conversation_id}/segments/assign-bulk": ("PATCH",),
    "/v1/personas": ("GET", "POST", "PATCH", "DELETE"),
    "/v1/personas/generate-prompt": ("POST",),
    "/v1/personas/check-username": ("GET",),
    "/v1/knowledge-graph": ("GET", "DELETE"),
    "/v1/knowledge-graph/rebuild": ("POST",),
    "/v1/users/me/llm-usage": ("POST",),
    "/v1/users/me/llm-usage/total": ("GET",),
    "/v1/users/stats/chat-messages": ("GET",),
    "/v1/apps": ("GET",),
    "/v1/approved-apps": ("GET",),
    "/v1/apps/popular": ("GET",),
    "/v1/apps/{app_id}": ("GET",),
    "/v1/apps/{app_id}/reviews": ("GET",),
    "/v2/apps": ("GET",),
    "/v2/apps/search": ("GET",),
    "/v1/apps/enable": ("POST",),
    "/v1/apps/disable": ("POST",),
    "/v1/apps/enabled": ("GET",),
    "/v1/apps/review": ("POST",),
    "/v1/app-categories": ("GET",),
    "/v1/app-capabilities": ("GET",),
    "/v1/conversations": ("GET",),
    "/v1/conversations/count": ("GET",),
    "/v1/conversations/search": ("POST",),
    "/v1/conversations/merge": ("POST",),
    "/v1/conversations/from-segments": ("POST",),
    "/v1/conversations/{id}/reprocess": ("POST",),
    "/v1/conversations/{id}/starred": ("PATCH",),
    "/v1/conversations/{id}/visibility": ("PATCH",),
    "/v1/conversations/{id}/shared": ("GET",),
    "/v1/conversations/{id}": ("GET", "PATCH", "DELETE"),
    "/v2/messages": ("GET", "POST", "DELETE"),
    "/v2/messages/{id}/rating": ("PATCH",),
    "/v1/action-items": ("GET", "POST"),
    "/v1/action-items/batch": ("POST", "PATCH"),
    "/v1/action-items/batch-scores": ("PATCH",),
    "/v1/action-items/share": ("POST",),
    "/v1/action-items/shared/{token}": ("GET",),
    "/v1/action-items/accept": ("POST",),
    "/v1/action-items/{id}": ("GET", "PATCH", "DELETE"),
    "/v1/action-items/{id}/soft-delete": ("POST",),
    "/v3/memories": ("GET", "POST", "DELETE"),
    "/v3/memories/mark-all-read": ("POST",),
    "/v3/memories/visibility": ("PATCH",),
    "/v3/memories/{id}": ("DELETE", "PATCH"),
    "/v3/memories/{id}/visibility": ("PATCH",),
    "/v3/memories/{id}/review": ("POST",),
    "/v3/memories/{id}/read": ("PATCH",),
    "/v1/staged-tasks": ("GET", "POST"),
    "/v1/staged-tasks/batch-scores": ("PATCH",),
    "/v1/staged-tasks/promote": ("POST",),
    "/v1/staged-tasks/migrate": ("POST",),
    "/v1/staged-tasks/migrate-conversation-items": ("POST",),
    "/v1/staged-tasks/{id}": ("DELETE",),
    "/v1/users/daily-summary-settings": ("GET", "PATCH"),
    "/v1/users/transcription-preferences": ("GET", "PATCH"),
    "/v1/users/language": ("GET", "PATCH"),
    "/v1/users/store-recording-permission": ("GET", "POST"),
    "/v1/users/private-cloud-sync": ("GET", "POST"),
    "/v1/users/notification-settings": ("GET", "PATCH"),
    "/v1/users/profile": ("GET", "PATCH"),
    "/v1/users/ai-profile": ("GET", "PATCH"),
    "/v1/users/assistant-settings": ("GET", "PATCH"),
    "/v1/users/delete-account": ("DELETE",),
    "/v1/proxy/deepgram/v1/listen": ("POST",),
    "/v1/proxy/deepgram/ws/v1/listen": ("GET", "POST"),
}


async def deprecated_handler(request: Request) -> JSONResponse:
    method = request.method
    path = request.url.path
    return JSONResponse(
        status_code=410,
        content={
            "error": "gone",
            "message": (
                f"This endpoint ({method} {path}) is deprecated and no longer served by the desktop backend. "
                "See https://api.omi.me for supported endpoints."
            ),
            "migration": "https://api.omi.me",
        },
    )


for route_path, route_methods in _ROUTES.items():
    router.add_api_route(route_path, deprecated_handler, methods=list(route_methods))
