// GENERATED by codegen/generate.mjs from contract/bridge.json (v1). DO NOT EDIT.
// Regenerate: node codegen/generate.mjs

export type CaptureState = "idle" | "starting" | "recording" | "error";

export interface StartCaptureParams {
  deviceId?: string | null;
  sampleRateHz: number;
}

export interface StartCaptureResult {
  sessionId: string;
  state: CaptureState;
}

export interface ReadSettingParams {
  key: string;
}

export interface ReadSettingResult {
  key: string;
  value?: string | null;
}

export interface OpenExternalParams {
  url: string;
}

export interface OpenExternalResult {
  opened: boolean;
}

export interface CaptureStatusEvent {
  sessionId?: string | null;
  state: CaptureState;
  elapsedMs: number;
  levelDb: number;
}

export interface BridgeEvents {
  captureStatus: CaptureStatusEvent;
}

const HANDLER = "OmiShellBridge";
const GLOBAL = "__OmiShellBridge";

type Pending = { resolve: (v: unknown) => void; reject: (e: Error) => void };

class Bridge {
  #seq = 0;
  #pending = new Map<string, Pending>();
  #listeners = new Map<string, Set<(p: unknown) => void>>();
  readonly available: boolean;

  constructor() {
    const w = window as unknown as Record<string, unknown>;
    w[GLOBAL] = {
      __reply: (m: { id: string; ok: boolean; result?: unknown; error?: string }) => {
        const p = this.#pending.get(m.id);
        if (!p) return;
        this.#pending.delete(m.id);
        m.ok ? p.resolve(m.result) : p.reject(new Error(m.error ?? "bridge error"));
      },
      __event: (m: { event: string; payload: unknown }) => {
        for (const cb of this.#listeners.get(m.event) ?? []) cb(m.payload);
      },
    };
    const wk = (window as any).webkit;
    this.available = Boolean(wk?.messageHandlers?.[HANDLER]);
  }

  #call<T>(method: string, params: unknown): Promise<T> {
    if (!this.available) return Promise.reject(new Error("native bridge unavailable (running in a plain browser)"));
    const id = String(++this.#seq);
    return new Promise<T>((resolve, reject) => {
      this.#pending.set(id, { resolve: resolve as (v: unknown) => void, reject });
      (window as any).webkit.messageHandlers[HANDLER].postMessage({ id, method, params });
    });
  }

  on<K extends keyof BridgeEvents>(event: K, cb: (p: BridgeEvents[K]) => void): () => void {
    const key = event as string;
    if (!this.#listeners.has(key)) this.#listeners.set(key, new Set());
    const set = this.#listeners.get(key)!;
    set.add(cb as (p: unknown) => void);
    return () => set.delete(cb as (p: unknown) => void);
  }

  startCapture(params: StartCaptureParams): Promise<StartCaptureResult> {
    return this.#call<StartCaptureResult>("startCapture", params);
  }
  readSetting(params: ReadSettingParams): Promise<ReadSettingResult> {
    return this.#call<ReadSettingResult>("readSetting", params);
  }
  openExternal(params: OpenExternalParams): Promise<OpenExternalResult> {
    return this.#call<OpenExternalResult>("openExternal", params);
  }
}

export const bridge = new Bridge();
