[application]
name = "framework-comparisonruntimesdioxus_shell-ui"
default_platform = "web"
out_dir = "dist"
asset_dir = "assets"

[web.app]
title = "Tauri + Dioxus App"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]