apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.api.namePrefix }}-config
  labels:
{{ include "deepgram-self-hosted.labels" . | indent 4}}
    {{- range $key, $val := .Values.engine.additionalLabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
data:
  api.toml: |
    [license]
      server_url = [
        {{- if .Values.licenseProxy.enabled }}
        "https://{{ .Values.licenseProxy.namePrefix }}-internal:{{ .Values.licenseProxy.server.port}}{{ .Values.licenseProxy.server.baseUrl }}"
        {{- end }}
        {{- if or (not .Values.licenseProxy.enabled) .Values.licenseProxy.keepUpstreamServerAsBackup }}
        {{- if .Values.licenseProxy.enabled -}},{{- end -}}"https://license.deepgram.com"
        {{- end }}
      ]

    [server]
      base_url = "{{ .Values.api.server.baseUrl }}"
      host = "{{ .Values.api.server.host }}"
      port = {{ .Values.api.server.port }}
      callback_conn_timeout = "{{ .Values.api.server.callbackConnTimeout }}"
      callback_timeout = "{{ .Values.api.server.callbackTimeout }}"
      fetch_conn_timeout = "{{ .Values.api.server.fetchConnTimeout }}"
      fetch_timeout = "{{ .Values.api.server.fetchTimeout }}"

    [resolver]
      {{- if .Values.api.resolver.nameservers }}
      {{- if gt (len .Values.api.resolver.nameservers) 0 }}
      nameservers = [
        {{- range $index, $element := .Values.api.resolver.nameservers }}
          {{- if ne $index 0}},{{ end }}"{{ $element }}"
        {{- end -}}
      ]
      {{- end }}
      {{- end }}
      {{- if .Values.api.resolver.maxTTL }}
      max_ttl = {{ .Values.api.resolver.maxTTL }}
      {{- end }}

    [features]
      topic_detection = true
      summarization = true
      entity_detection = {{ .Values.api.features.entityDetection }}
      entity_redaction = {{ .Values.api.features.entityRedaction }}
      speak_streaming = true

      {{- if .Values.api.features.diskBufferPath }}
      disk_buffer_path = "{{ .Values.api.features.diskBufferPath }}"
      {{- end }}

    [[driver_pool.standard]]
      url = "https://{{ .Values.engine.namePrefix }}-internal:{{ .Values.engine.server.port}}/v2"
      timeout_backoff = {{ .Values.api.driverPool.standard.timeoutBackoff }}
      retry_sleep = "{{ .Values.api.driverPool.standard.retrySleep }}"
      retry_backoff = {{ .Values.api.driverPool.standard.retryBackoff }}
      max_response_size = {{ int .Values.api.driverPool.standard.maxResponseSize }}


