platform :osx, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'ephemeral', 'Flutter-Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure \"flutter pub get\" is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Flutter-Generated.xcconfig, then run \"flutter pub get\""
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_macos_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_macos_pods File.dirname(File.realpath(__FILE__))
  
  pod 'Mixpanel-swift', :git => 'https://github.com/beastoin/mixpanel-swift.git', :commit => '5fd6584'
  pod 'Sparkle', '~> 2.0'
end

pre_install do |installer|
  # Stub flutter_sound for macOS since it's not natively supported
  flutter_sound_path = File.expand_path('../LocalPods/flutter_sound', __FILE__)
  symlink_path = File.expand_path('../Flutter/ephemeral/.symlinks/plugins/flutter_sound/macos', __FILE__)
  
  # Create the stub files in the symlink path
  FileUtils.mkdir_p(File.join(symlink_path, 'Classes'))
  
  # Copy podspec
  podspec_content = <<-PODSPEC
Pod::Spec.new do |s|
  s.name             = 'flutter_sound'
  s.version          = '9.25.1'
  s.summary          = 'Flutter Sound - macOS stub'
  s.description      = 'Flutter Sound stub for macOS'
  s.homepage         = 'https://github.com/Canardoux/flutter_sound'
  s.license          = { :type => 'MIT' }
  s.author           = { 'Stub' => 'stub@example.com' }
  s.source           = { :path => '.' }
  s.source_files = 'Classes/**/*'
  s.dependency 'FlutterMacOS'
  s.platform = :osx, '10.13'
  s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES' }
  s.swift_version = '5.0'
end
PODSPEC
  File.write(File.join(symlink_path, 'flutter_sound.podspec'), podspec_content)
  
  # Copy swift stub
  swift_content = <<-SWIFT
import FlutterMacOS

public class FlutterSoundPlugin: NSObject, FlutterPlugin {
    public static func register(with registrar: FlutterPluginRegistrar) {
        let channel = FlutterMethodChannel(name: "com.dooboolab.flutter_sound", binaryMessenger: registrar.messenger)
        let instance = FlutterSoundPlugin()
        registrar.addMethodCallDelegate(instance, channel: channel)
    }
    
    public func handle(_ call: FlutterMethodCall, result: @escaping FlutterResult) {
        result(FlutterMethodNotImplemented)
    }
}
SWIFT
  File.write(File.join(symlink_path, 'Classes', 'FlutterSoundPlugin.swift'), swift_content)
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_macos_build_settings(target)
  end
end