// AUTO-GENERATED by backend/scripts/generate_integration_sdks.py from docs/api-reference/integration-public-openapi.json.
// Do not edit by hand. Re-run the generator after OpenAPI changes.
// Spec sha256[0:16]=726f4b3a685da076


package omiintegration

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)

const DefaultBaseURL = "https://api.omi.me"

// Client talks to the Omi Integration API.
type Client struct {
	APIKey     string
	AppID      string
	BaseURL    string
	HTTPClient *http.Client
}

// New creates a Client. apiKey and appID are required.
func New(apiKey, appID string) *Client {
	return &Client{
		APIKey:  apiKey,
		AppID:   appID,
		BaseURL: DefaultBaseURL,
		HTTPClient: &http.Client{
			Timeout: 30 * time.Second,
		},
	}
}

// APIError is a non-2xx Integration API response.
type APIError struct {
	StatusCode int
	Body       []byte
}

func (e *APIError) Error() string {
	return fmt.Sprintf("omi integration api: HTTP %d: %s", e.StatusCode, strings.TrimSpace(string(e.Body)))
}

func (c *Client) request(ctx context.Context, method, path string, query url.Values, body any) (json.RawMessage, error) {
	if c.APIKey == "" {
		return nil, fmt.Errorf("omi integration: api key is required")
	}
	if c.AppID == "" {
		return nil, fmt.Errorf("omi integration: app id is required")
	}
	base := c.BaseURL
	if base == "" {
		base = DefaultBaseURL
	}
	base = strings.TrimRight(base, "/")
	u, err := url.Parse(base + path)
	if err != nil {
		return nil, err
	}
	if query != nil {
		u.RawQuery = query.Encode()
	}
	var rdr io.Reader
	if body != nil {
		b, err := json.Marshal(body)
		if err != nil {
			return nil, err
		}
		rdr = bytes.NewReader(b)
	}
	req, err := http.NewRequestWithContext(ctx, method, u.String(), rdr)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Authorization", "Bearer "+c.APIKey)
	req.Header.Set("Accept", "application/json")
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	httpClient := c.HTTPClient
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	res, err := httpClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer res.Body.Close()
	data, err := io.ReadAll(res.Body)
	if err != nil {
		return nil, err
	}
	if res.StatusCode < 200 || res.StatusCode >= 300 {
		return nil, &APIError{StatusCode: res.StatusCode, Body: data}
	}
	if len(data) == 0 {
		return json.RawMessage("null"), nil
	}
	return json.RawMessage(data), nil
}

// SendNotificationV1 Send App Notification To User
func (c *Client) SendNotificationV1(ctx context.Context, body any) (json.RawMessage, error) {
	return c.request(ctx, "POST", "/v1/integrations/notification", nil, body)
}

// ListConversationsOptions holds optional query parameters for ListConversations.
type ListConversationsOptions struct {
	Limit *int
	Offset *int
	IncludeDiscarded *bool
	Statuses []string
	StartDate *string
	EndDate *string
	MaxTranscriptSegments *int
}

// ListConversations Get Conversations Via Integration
func (c *Client) ListConversations(ctx context.Context, uid string, opts *ListConversationsOptions) (json.RawMessage, error) {
	q := url.Values{}
	q.Set("uid", uid)
	if opts != nil {
		if opts.Limit != nil { q.Set("limit", fmt.Sprintf("%d", *opts.Limit)) }
		if opts.Offset != nil { q.Set("offset", fmt.Sprintf("%d", *opts.Offset)) }
		if opts.IncludeDiscarded != nil { q.Set("include_discarded", fmt.Sprintf("%t", *opts.IncludeDiscarded)) }
		for _, item := range opts.Statuses { q.Add("statuses", item) }
		if opts.StartDate != nil { q.Set("start_date", *opts.StartDate) }
		if opts.EndDate != nil { q.Set("end_date", *opts.EndDate) }
		if opts.MaxTranscriptSegments != nil { q.Set("max_transcript_segments", fmt.Sprintf("%d", *opts.MaxTranscriptSegments)) }
	}
	return c.request(ctx, "GET", "/v2/integrations/" + c.AppID + "/conversations", q, nil)
}

// ListMemoriesOptions holds optional query parameters for ListMemories.
type ListMemoriesOptions struct {
	Limit *int
	Offset *int
}

// ListMemories Get Memories Via Integration
func (c *Client) ListMemories(ctx context.Context, uid string, opts *ListMemoriesOptions) (json.RawMessage, error) {
	q := url.Values{}
	q.Set("uid", uid)
	if opts != nil {
		if opts.Limit != nil { q.Set("limit", fmt.Sprintf("%d", *opts.Limit)) }
		if opts.Offset != nil { q.Set("offset", fmt.Sprintf("%d", *opts.Offset)) }
	}
	return c.request(ctx, "GET", "/v2/integrations/" + c.AppID + "/memories", q, nil)
}

// SendNotification Send Notification Via Integration
func (c *Client) SendNotification(ctx context.Context, message string, uid string) (json.RawMessage, error) {
	q := url.Values{}
	q.Set("message", message)
	q.Set("uid", uid)
	return c.request(ctx, "POST", "/v2/integrations/" + c.AppID + "/notification", q, nil)
}

// SearchConversationsOptions holds optional query parameters for SearchConversations.
type SearchConversationsOptions struct {
	MaxTranscriptSegments *int
}

// SearchConversations Search Conversations Via Integration
func (c *Client) SearchConversations(ctx context.Context, uid string, body any, opts *SearchConversationsOptions) (json.RawMessage, error) {
	q := url.Values{}
	q.Set("uid", uid)
	if opts != nil {
		if opts.MaxTranscriptSegments != nil { q.Set("max_transcript_segments", fmt.Sprintf("%d", *opts.MaxTranscriptSegments)) }
	}
	return c.request(ctx, "POST", "/v2/integrations/" + c.AppID + "/search/conversations", q, body)
}

// ListTasksOptions holds optional query parameters for ListTasks.
type ListTasksOptions struct {
	Limit *int
	Offset *int
	Completed *bool
	ConversationId *string
	StartDate *string
	EndDate *string
	DueStartDate *string
	DueEndDate *string
}

// ListTasks Get Tasks Via Integration
func (c *Client) ListTasks(ctx context.Context, uid string, opts *ListTasksOptions) (json.RawMessage, error) {
	q := url.Values{}
	q.Set("uid", uid)
	if opts != nil {
		if opts.Limit != nil { q.Set("limit", fmt.Sprintf("%d", *opts.Limit)) }
		if opts.Offset != nil { q.Set("offset", fmt.Sprintf("%d", *opts.Offset)) }
		if opts.Completed != nil { q.Set("completed", fmt.Sprintf("%t", *opts.Completed)) }
		if opts.ConversationId != nil { q.Set("conversation_id", *opts.ConversationId) }
		if opts.StartDate != nil { q.Set("start_date", *opts.StartDate) }
		if opts.EndDate != nil { q.Set("end_date", *opts.EndDate) }
		if opts.DueStartDate != nil { q.Set("due_start_date", *opts.DueStartDate) }
		if opts.DueEndDate != nil { q.Set("due_end_date", *opts.DueEndDate) }
	}
	return c.request(ctx, "GET", "/v2/integrations/" + c.AppID + "/tasks", q, nil)
}

// CreateConversation Create Conversation Via Integration
func (c *Client) CreateConversation(ctx context.Context, uid string, body any) (json.RawMessage, error) {
	q := url.Values{}
	q.Set("uid", uid)
	return c.request(ctx, "POST", "/v2/integrations/" + c.AppID + "/user/conversations", q, body)
}

// CreateMemories Create Memories Via Integration
func (c *Client) CreateMemories(ctx context.Context, uid string, body any) (json.RawMessage, error) {
	q := url.Values{}
	q.Set("uid", uid)
	return c.request(ctx, "POST", "/v2/integrations/" + c.AppID + "/user/memories", q, body)
}

