{{- if .Values.engine.modelManager.volumes.aws.efs.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.engine.modelManager.volumes.aws.efs.namePrefix }}-aws-efs-pv
  labels:
{{ include "deepgram-self-hosted.labels" . | indent 4}}
spec:
  capacity:
    # EFS will grow and shrink as files are added.
    # This is just a starting request.
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  claimRef:
    name: {{ .Values.engine.modelManager.volumes.aws.efs.namePrefix }}-aws-efs-pvc
    namespace: {{ .Release.Namespace }}
  storageClassName: aws-efs-sc
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ required "Missing AWS EFS fileSystemId, see `.engine.modelManager.volumes.aws.efs`" .Values.engine.modelManager.volumes.aws.efs.fileSystemId }}
{{- end }}
