#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT_DIR"

export ENCRYPTION_SECRET="omi_ZwB2ZNqB2HHpMK6wStk7sTpavJiPTFg7gXUHnc4tFABPU6pZ2c2DKgehtfgi4RZv"

pytest tests/unit/test_transcript_segment.py -v
pytest tests/unit/test_text_similarity.py -v
pytest tests/unit/test_text_containment.py -v
pytest tests/unit/test_speaker_sample.py -v
pytest tests/unit/test_speaker_sample_migration.py -v
pytest tests/unit/test_short_audio_embedding.py -v
pytest tests/unit/test_users_add_sample_transaction.py -v
pytest tests/unit/test_voice_message_language.py -v
pytest tests/unit/test_speaker_assignment.py -v
pytest tests/unit/test_speaker_id_pipeline.py -v
pytest tests/unit/test_user_speaker_embedding.py -v
pytest tests/unit/test_parakeet_diarization.py -v
pytest tests/unit/test_diarizer_embedding_decoder_bypass.py -v
pytest tests/unit/test_parakeet_prerecorded.py -v
pytest tests/unit/test_parakeet_nim.py -v
pytest tests/unit/test_parakeet_stream_session.py -v
pytest tests/unit/test_parakeet_gpu_worker.py -v
pytest tests/unit/test_parakeet_batch_engine.py -v
pytest tests/unit/test_parakeet_batch_routing.py -v
pytest tests/unit/test_parakeet_endpoints.py -v
pytest tests/unit/test_audiobuffer_guard.py -v
pytest tests/unit/test_memory_leak_buffers.py -v
pytest tests/unit/test_mcp_search_memories.py -v
pytest tests/unit/test_mcp_memory_filters.py -v
pytest tests/unit/test_mcp_client_tool_result.py -v
pytest tests/unit/test_mcp_data_endpoints.py -v
pytest tests/unit/test_memory_temporal_brain.py -v
pytest tests/unit/test_memory_category_auto.py -v
pytest tests/unit/test_memories_validation.py -v
pytest tests/unit/test_memories_user_review.py -v
pytest tests/unit/test_short_term_lifecycle.py -v
pytest tests/unit/test_v17_product_memory_items.py -v
pytest tests/unit/test_v17_product_memory_read_service.py -v
pytest tests/unit/test_v17_default_read_rollout_decision.py -v
pytest tests/unit/test_v17_rollout_schema_readiness.py -v
pytest tests/unit/test_v17_chat_memory_adapter.py -v
pytest tests/unit/test_v17_chat_memory_tool_caller.py -v
pytest tests/unit/test_v17_tools_agent_route_response_shape.py -v
pytest tests/unit/test_v17_tools_rest_memory_runtime_adapter.py -v
pytest tests/unit/test_v17_p1_5_tools_fastapi_testclient_readiness.py -v
pytest tests/unit/test_v17_developer_memory_adapter.py -v
pytest tests/unit/test_v17_mcp_memory_adapter.py -v
pytest tests/unit/test_v17_product_memory_router.py -v
pytest tests/unit/test_v17_product_authorization.py -v
pytest tests/unit/test_v17_app_key_grant_store.py -v
pytest tests/unit/test_v17_app_key_memory_grant_assignment_readiness.py -v
pytest tests/unit/test_v17_developer_auth_context_static.py -v
pytest tests/unit/test_v17_mcp_auth_context_static.py -v
pytest tests/unit/test_v17_mcp_api_key_auth_context.py -v
pytest tests/unit/test_v17_mcp_api_key_scope_readiness.py -v
pytest tests/unit/test_v17_short_term_lifecycle_worker.py -v
pytest tests/unit/test_v17_short_term_lifecycle_firestore_store.py -v
pytest tests/unit/test_v17_memory_contracts.py -v
pytest tests/unit/test_v17_working_memory_extractor.py -v
pytest tests/unit/test_v17_durable_memory_patches.py -v
pytest tests/unit/test_v17_patch_adapter.py -v
pytest tests/unit/test_v17_read_api.py -v
pytest tests/unit/test_v17_projections.py -v
pytest tests/unit/test_v17_vector_metadata.py -v
pytest tests/unit/test_v17_vector_filters.py -v
pytest tests/unit/test_v17_vector_search_service.py -v
pytest tests/unit/test_v17_vector_repair_outbox_worker.py -v
pytest tests/unit/test_v17_vector_repair_outbox_telemetry.py -v
pytest tests/unit/test_v17_vector_repair_outbox_worker_entrypoint.py -v
pytest tests/unit/test_v17_vector_repair_outbox_deployment_contract.py -v
pytest tests/unit/test_v17_vector_repair_outbox_oidc_iam_proof.py -v
pytest tests/unit/test_v17_firestore_rules_iam_proof.py -v
pytest tests/unit/test_v17_pinecone_repair_validation_readiness.py -v
pytest tests/unit/test_v17_shared_ns2_legacy_isolation_readiness.py -v
pytest tests/unit/test_v17_vector_search_provider_readiness.py -v
pytest tests/unit/test_v17_t20_repair_projection_consistency_readiness.py -v
pytest tests/unit/test_v17_t21_v3_compatibility_cursor_readiness.py -v
pytest tests/unit/test_v17_t22_t23_external_writes_caller_coverage_readiness.py -v
pytest tests/unit/test_v17_p1_3_caller_api_compatibility_readiness.py -v
pytest tests/unit/test_v17_p1_3_v3_external_compatibility_readiness.py -v
pytest tests/unit/test_v17_v3_compatibility.py -v
pytest tests/unit/test_v17_v3_cursor.py -v
pytest tests/unit/test_v17_v3_projection_readiness.py -v
pytest tests/unit/test_v17_v3_memory_read_service.py -v
pytest tests/unit/test_v17_v3_write_convergence.py -v
pytest tests/unit/test_v17_v3_response_adapter.py -v
pytest tests/unit/test_v17_v3_request_adapter.py -v
pytest tests/unit/test_v17_cutover_evidence_readiness.py -v
pytest tests/unit/test_v17_vector_repair_outbox_emulator_harness.py -v
pytest tests/unit/test_v17_firestore_indexes.py -v
pytest tests/unit/test_v17_normative_foundations.py -v
pytest tests/unit/test_v17_typed_synthesis.py -v
pytest tests/unit/test_v17_memory_operations.py -v
pytest tests/unit/test_v17_atomic_apply.py -v
pytest tests/unit/test_v17_search_gateway.py -v
pytest tests/unit/test_v17_firestore_apply_store.py -v
pytest tests/unit/test_v17_firestore_security_rules.py -v
pytest tests/unit/test_v17_firestore_emulator_harness.py -v
pytest tests/unit/test_v17_firestore_transaction_emulator_harness.py -v
pytest tests/unit/test_v17_firestore_python_adapter_emulator_harness.py -v
pytest tests/unit/test_v17_firestore_iam_deployment_doc.py -v
pytest tests/unit/test_v17_non_active_routes.py -v
pytest tests/unit/test_v17_non_active_route_audit.py -v
pytest tests/unit/test_v17_non_active_route_report.py -v
pytest tests/unit/test_v17_non_active_route_admin_endpoint.py -v
pytest tests/unit/test_v17_review_queue_non_active_routes.py -v
pytest tests/unit/test_memory_ingestion_pipeline.py -v
pytest tests/unit/test_working_memory_candidate_schema.py -v
pytest tests/unit/test_llm_usage_tracker.py -v
pytest tests/unit/test_process_conversation_usage_context.py -v
pytest tests/unit/test_high_priority_usage_tracking.py -v
pytest tests/unit/test_new_usage_tracking_gaps.py -v
pytest tests/unit/test_llm_usage_db.py -v
pytest tests/unit/test_llm_usage_endpoints.py -v
pytest tests/unit/test_app_uid_keyerror.py -v
pytest tests/unit/test_daily_summary_race_condition.py -v
pytest tests/unit/test_daily_summary_regenerate.py -v
pytest tests/unit/test_chat_tools_messages.py -v
pytest tests/unit/test_prompt_caching.py -v
pytest tests/unit/test_mentor_notifications.py -v
pytest tests/unit/test_proactive_notification_language.py -v
pytest tests/unit/test_notification_token_cleanup.py -v
pytest tests/unit/test_conversations_to_string.py -v
pytest tests/unit/test_conversation_render_factory.py -v
pytest tests/unit/test_conversation_redact_enrich.py -v
pytest tests/unit/test_folder_name_enrichment.py -v
pytest tests/unit/test_conversations_count.py -v
pytest tests/unit/test_prompt_cache_optimization.py -v
pytest tests/unit/test_prompt_cache_integration.py -v
pytest tests/unit/test_task_sharing.py -v
pytest tests/unit/test_firmware_pagination.py -v
pytest tests/unit/test_vad_gate.py -v
pytest tests/unit/test_vad_onnx.py -v
pytest tests/unit/test_log_sanitizer.py -v
pytest tests/unit/test_file_upload_security.py -v
pytest tests/unit/test_file_upload_endpoint_security.py -v
pytest tests/unit/test_auth_redirect_uri.py -v
pytest tests/unit/test_pusher_heartbeat.py -v
pytest tests/unit/test_pusher_conversation_retry.py -v
pytest tests/unit/test_listen_fallback_removal.py -v
pytest tests/unit/test_desktop_updates.py -v
pytest tests/unit/test_translation_optimization.py -v
pytest tests/unit/test_translation_cost_optimization.py -v
pytest tests/unit/test_conversation_source_unknown.py -v
pytest tests/unit/test_conversation_model_split.py -v
pytest tests/unit/test_transcribe_conversation_cache.py -v
pytest tests/unit/test_pusher_private_cloud_data_protection.py -v
pytest tests/unit/test_pusher_batch_upload.py -v
pytest tests/unit/test_storage_upload_audio_chunk_data_protection.py -v
pytest tests/unit/test_optional_audio_codecs.py -v
pytest tests/unit/test_storage_opus_encoding.py -v
pytest tests/unit/test_speech_profile_existence.py -v
pytest tests/unit/test_storage_fanout_limits.py -v
pytest tests/unit/test_deferred_blob_janitor.py -v
pytest tests/unit/test_audio_merge_tasks.py -v
pytest tests/unit/test_people_conversations_500s.py -v
pytest tests/unit/test_firestore_read_ops_cache.py -v
pytest tests/unit/test_ws_auth_handshake.py -v
pytest tests/unit/test_streaming_deepgram_backoff.py -v
pytest tests/unit/test_executors.py -v
pytest tests/unit/test_modulate_stt.py -v
pytest tests/unit/test_batch_upload_storage.py -v
pytest tests/unit/test_action_item_date_validation.py -v
pytest tests/unit/test_conversation_structure_timezone.py -v
pytest tests/unit/test_action_item_dedup.py -v
pytest tests/unit/test_action_item_reminder_cancel_on_complete.py -v
pytest tests/unit/test_action_item_idempotency.py -v
pytest tests/unit/test_goals_id_fallback.py -v
pytest tests/unit/test_tools_router.py -v
pytest tests/unit/test_kg_user_type_mismatch.py -v
pytest tests/unit/test_kg_edge_id_sanitization.py -v
pytest tests/unit/test_goal_extraction_batch.py -v
pytest tests/unit/test_listen_pipeline.py -v
pytest tests/unit/test_fair_use_models.py -v
pytest tests/unit/test_fair_use_engine.py -v
pytest tests/unit/test_fair_use_classifier.py -v
pytest tests/unit/test_fair_use_async.py -v
pytest tests/unit/test_dg_usage_batch.py -v
pytest tests/unit/test_billable_transcription_seconds.py -v
pytest tests/unit/test_sync_fair_use_gate.py -v
pytest tests/unit/test_sync_pcm_decode.py -v
pytest tests/unit/test_sync_opus_decode.py -v
pytest tests/unit/test_transcribe_lc3_optional.py -v
pytest tests/unit/test_sync_silent_failure.py -v
pytest tests/unit/test_sync_ordered_assignment.py -v
pytest tests/unit/test_fair_use_free_tier.py -v
pytest tests/unit/test_fair_use_upgrade.py -v
pytest tests/unit/test_skip_classifier_restrict.py -v
pytest tests/unit/test_timeout_middleware.py -v
pytest tests/unit/test_pusher_circuit_breaker.py -v
pytest tests/unit/test_pusher_ghost_connections.py -v
pytest tests/unit/test_async_tasks.py -v
pytest tests/unit/test_lock_bypass_fixes.py -v
pytest tests/unit/test_integration_malformed_records.py -v
pytest tests/unit/test_dev_api_lock_bypass.py -v
pytest tests/unit/test_dev_api_folder_filters.py -v
pytest tests/unit/test_dev_api_memories_pagination.py -v
pytest tests/unit/test_rate_limiting.py -v
pytest tests/unit/test_memories_batch.py -v
pytest tests/unit/test_memories_create.py -v
pytest tests/unit/test_sync_v2.py -v
pytest tests/unit/test_sync_cloud_tasks.py -v
pytest tests/unit/test_sync_transcription_prefs.py -v
pytest tests/unit/test_sync_record_usage.py -v
pytest tests/unit/test_vision_stream_async.py -v
pytest tests/unit/test_desktop_transcribe.py -v
pytest tests/unit/test_desktop_migration.py -v
pytest tests/unit/test_staged_tasks_batch_scores.py -v
pytest tests/unit/test_staged_tasks_dedup.py -v
pytest tests/unit/test_dg_start_guard.py -v
pytest tests/unit/test_available_plans_resilience.py -v
pytest tests/unit/test_subscription_restructure.py -v
pytest tests/unit/test_chat_quota.py -v
pytest tests/unit/test_subscription_plans.py -v
pytest tests/unit/test_payment_available_plans_source.py -v
pytest tests/unit/test_payment_promotion_codes.py -v
pytest tests/unit/test_stripe_webhook_none_guard.py -v
pytest tests/unit/test_stripe_webhook_behavioral.py -v
pytest tests/unit/test_voice_duration_limiter.py -v
pytest tests/unit/test_async_webhooks.py -v
pytest tests/unit/test_async_app_integrations.py -v
pytest tests/unit/test_async_geocoding.py -v
pytest tests/unit/test_geocoding_cache.py -v
pytest tests/unit/test_realtime_integrations_usage_tracking.py -v
pytest tests/unit/test_async_auth.py -v
pytest tests/unit/test_thread_join_elimination.py -v
pytest tests/unit/test_async_http_infrastructure.py -v
pytest tests/unit/test_clean_sweep_migrations.py -v
pytest tests/unit/test_omi_qos_tiers.py -v
pytest tests/unit/test_byok_security.py -v
pytest tests/unit/test_paywall_reconnect_gate.py -v
pytest tests/unit/test_trial_metadata.py -v
pytest tests/unit/test_neo_desktop_grandfather.py -v
pytest tests/unit/test_vertex_ai_system_role.py -v
pytest tests/unit/test_tts.py -v
pytest tests/unit/test_webhook_auto_disable.py -v
pytest tests/unit/test_merge_validation.py -v
pytest tests/unit/test_phone_calls.py -v
pytest tests/unit/test_twilio_service.py -v
pytest tests/unit/test_twilio_account_deletion.py -v
pytest tests/unit/test_conversation_search_date_validation.py -v
pytest tests/unit/test_conversation_hybrid_search.py -v
pytest tests/unit/test_delete_account_stripe_cancel.py -v
pytest tests/unit/test_delete_account_purge_storage.py -v
pytest tests/unit/test_apps_review_reply_validation.py -v

# Fair-use integration tests (require Redis; skip gracefully if unavailable)
if redis-cli ping >/dev/null 2>&1; then
  pytest tests/integration/test_fair_use_live.py -v
  pytest tests/integration/test_fair_use_api.py -v
else
  echo "SKIP: fair-use integration tests (Redis not available)"
fi
