apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.engine.namePrefix }}-metrics
  labels:
{{ include "deepgram-self-hosted.labels" . | indent 4}}
    {{- range $key, $val := .Values.engine.additionalLabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
spec:
  selector:
    app: deepgram-engine
    {{ include "deepgram-self-hosted.selectorLabels" . }}
  type: NodePort
  ports:
    - name: "metrics"
      port: {{ .Values.engine.metricsServer.port }}
      targetPort: {{ .Values.engine.metricsServer.port }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.engine.namePrefix }}-internal
  labels:
{{ include "deepgram-self-hosted.labels" . | indent 4}}
    {{- range $key, $val := .Values.engine.additionalLabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
spec:
  selector:
    app: deepgram-engine
    {{ include "deepgram-self-hosted.selectorLabels" . }}
  ports:
    - name: "primary"
      port: {{ .Values.engine.server.port }}
      targetPort: {{ .Values.engine.server.port }}

