#!/usr/bin/env python3
"""Generate Swift Codable DTOs from an OpenAPI schema.

Mirrors backend/scripts/generate_ts_openapi_types.py but emits Swift. Output is
pure wire-shape DTOs (snake_case CodingKeys, no behavior) that the desktop's
domain models adapt. The app-client OpenAPI spec is the schema authority.

Generated DTOs use `decodeIfPresent` for optional fields and tolerate unknown
keys (the backend may add fields), so the desktop's tolerant domain-model
defaults are preserved by adapting from the generated wire type.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

ROOT_DIR = Path(__file__).resolve().parents[2]
DEFAULT_SPEC_PATH = ROOT_DIR / 'docs' / 'api-reference' / 'app-client-openapi.json'
DEFAULT_OUTPUT = ROOT_DIR / 'desktop' / 'macos' / 'Desktop' / 'Sources' / 'Generated' / 'OmiApi.generated.swift'

# Schemas to generate. Keep this the high-traffic desktop read surface; expand
# as the desktop Codable migration progresses. Each entry pulls in transitive
# $ref dependencies automatically.
TARGET_SCHEMAS = (
    'Conversation',
    'Structured',
    'ActionItem',
    'ActionItemResponse',
    'ActionItemCreateRequest',
    'ActionItemUpdateRequest',
    'ActionItemsResponse',
    'Event',
    'TranscriptSegment',
    'Geolocation',
    'ConversationPhoto',
    'AppResult',
    'PluginResult',
    'AudioFile',
    'MemoryDB',
    'MemoryCategory',
    'MemoryLayer',
    'SubjectAttribution',
    'Evidence',
    'Translation',
    'GoalResponse',
    'GoalUpdate',
    'GoalType',
    'GoalDetailProjection',
    'GoalProgressEvent',
    'CandidateRecord',
    'CandidateListResponse',
    'CandidateResolutionReceipt',
    'CandidateCreate',
    'TaskCreateCandidate',
    'TaskUpdateCandidate',
    'TaskCompleteCandidate',
    'TaskCancelCandidate',
    'TaskSupersedeCandidate',
    'CandidateResolutionRequest',
    'TaskWorkflowControl',
    'Workstream',
    'WorkstreamCreateCandidate',
    'WorkstreamUpdate',
    'WorkstreamDetailProjection',
    'WorkstreamEvent',
    'WorkstreamEventCreate',
    'ArtifactDescriptor',
    'ArtifactDescriptorCreate',
    'ArtifactStatusTransitionRequest',
    'ContinuationCheckpoint',
    'ContinuationCheckpointUpsert',
    'ConversationSource',
    'ConversationStatus',
    'CategoryEnum',
)

PRESENCE_AWARE_PATCH_SCHEMAS = {
    'ActionItemUpdateRequest',
    'GoalUpdate',
    'WorkstreamUpdate',
}

HEADER_PRE = """// GENERATED CODE - DO NOT EDIT.
// Generated by backend/scripts/generate_swift_openapi_types.py from {spec_path}
// Swift wire DTOs for the desktop app's backend REST surface. Domain models
// (ServerConversation, ServerMemory, Goal, ActionItem) adapt from these types;
// they do not replace them wholesale. All generated types are namespaced under
// `OmiAPI` so they don't collide with the domain models in APIClient.swift.

import Foundation

"""


HEADER_NAMESPACE_OPEN = """
/// Namespace for generated backend REST wire DTOs. Domain models in
/// APIClient.swift adapt from `OmiAPI.*` types; consumers should not construct
/// these directly outside the adapter layer.
public enum OmiAPI {

"""


FOOTER = "}\n"


def _ref_name(ref: str) -> str:
    return ref.rsplit('/', 1)[-1]


def _swift_type_name(schema_name: str) -> str:
    parts = [part for part in re.split(r'[^A-Za-z0-9_]+', schema_name) if part]
    if len(parts) == 1:
        return parts[0]
    return ''.join(part[:1].upper() + part[1:] for part in parts)


def _swift_type(schema: dict[str, Any], required: bool = False) -> tuple[str, bool]:
    """Return (swift type expression, is_optional).

    Tolerant decoding: optional unless the field is required AND has a non-null
    primitive shape. Refs to generated structs are decodeIfPresent-tolerant.
    """
    if '$ref' in schema:
        name = _swift_type_name(_ref_name(schema['$ref']))
        return name, not required
    if 'anyOf' in schema or 'oneOf' in schema:
        parts = schema.get('anyOf') or schema.get('oneOf') or []
        non_null = [p for p in parts if p.get('type') != 'null']
        ref_names = {_ref_name(p['$ref']) for p in non_null if '$ref' in p}
        if ref_names == {'TaskCreatePayload', 'TaskChangePayload'}:
            return 'CandidateTaskChange', True
        if len(non_null) == 1 and len(non_null) != len(parts):
            inner, _ = _swift_type(non_null[0], required=True)
            return inner, True
        return 'OmiAnyCodable', not required
    if 'type' not in schema:
        return 'OmiAnyCodable', not required
    t = schema['type']
    if t == 'string':
        return 'String', not required
    if t == 'integer':
        if schema.get('format') in ('int32', 'int64'):
            return 'Int', not required
        return 'Int', not required
    if t == 'number':
        return 'Double', not required
    if t == 'boolean':
        return 'Bool', not required
    if t == 'array':
        items = schema.get('items', {})
        inner, _ = _swift_type(items, required=True)
        return f'[{inner}]', not required
    if t == 'object':
        ap = schema.get('additionalProperties')
        if isinstance(ap, dict):
            val_type, _ = _swift_type(ap, required=True)
            return f'[String: {val_type}]', not required
        return '[String: OmiAnyCodable]', not required
    return 'OmiAnyCodable', not required


def _render_enum(name: str, schema: dict[str, Any]) -> str:
    name = _swift_type_name(name)
    values = schema.get('enum') or []
    lines = [f'public enum {name}: String, Codable, CaseIterable {{']
    for v in values:
        if re.match(r'^[A-Za-z_][A-Za-z0-9_]*$', v):
            case_name = v if v not in SWIFT_RESERVED else v + '_'
            if case_name == v:
                lines.append(f'  case {v}')
            else:
                lines.append(f'  case {case_name} = "{v}"')
        else:
            lines.append(f'  case {re.sub(r"[^A-Za-z0-9_]", "_", v)} = "{v}"')
    # Tolerant fallback: unknown enum values decode to a synthetic case rather
    # than throwing, preserving the desktop's tolerant parsing.
    lines.append('  case _unknown = "__unknown__"')
    lines.append('  public init(from decoder: Decoder) throws {')
    lines.append('    let c = try decoder.singleValueContainer()')
    lines.append(f'    let raw = try c.decode(String.self)')
    lines.append(f'    self = {name}(rawValue: raw) ?? ._unknown')
    lines.append('  }')
    lines.append('}')
    return '\n'.join(lines) + '\n\n'


SWIFT_RESERVED = {
    'description',
    'repeat',
    'class',
    'struct',
    'enum',
    'protocol',
    'extension',
    'init',
    'deinit',
    'func',
    'var',
    'let',
    'where',
    'return',
    'switch',
    'case',
    'default',
    'break',
    'continue',
    'if',
    'else',
    'guard',
    'while',
    'for',
    'in',
    'do',
    'try',
    'catch',
    'throw',
    'throws',
    'rethrows',
    'as',
    'is',
    'nil',
    'true',
    'false',
    'self',
    'super',
    'private',
    'public',
    'internal',
    'fileprivate',
    'static',
    'final',
    'open',
    'lazy',
    'weak',
    'unowned',
    'inout',
    'mutating',
    'nonmutating',
    'override',
    'operator',
    'precedencegroup',
    'associativity',
    'left',
    'right',
    'none',
    'Type',
    'Any',
    'AnyObject',
    'subscript',
    'typealias',
    'import',
    'defer',
    'fallthrough',
    '#available',
    '#selector',
}


def _swift_property(swift_name: str, wire_name: str, type_expr: str, optional: bool) -> str:
    decl = f'public let {swift_name}: {type_expr}' + ('?' if optional else '')
    if swift_name == wire_name:
        return f'    {decl}'
    return f'    {decl}\n    // wire: "{wire_name}"'


def _render_struct(name: str, schema: dict[str, Any]) -> str:
    name = _swift_type_name(name)
    props = schema.get('properties') or {}
    required = set(schema.get('required') or [])

    # Build CodingKeys + decode body.
    fields: list[tuple[str, str, str, bool]] = []  # (swift_name, wire_name, type, optional)
    for wire_name, prop_schema in sorted(props.items()):
        swift_name = _swift_prop_name(wire_name)
        type_expr, optional = _swift_type(prop_schema, required=wire_name in required)
        fields.append((swift_name, wire_name, type_expr, optional))

    lines = [f'public struct {name}: Codable {{']
    for swift_name, wire_name, type_expr, optional in fields:
        decl = f'  public let {swift_name}: {type_expr}' + ('?' if optional else '')
        lines.append(decl)
    lines.append('')

    # CodingKeys
    needs_coding_keys = any(sn != wn for sn, wn, _, _ in fields)
    if needs_coding_keys:
        lines.append('  private enum CodingKeys: String, CodingKey {')
        for swift_name, wire_name, _, _ in fields:
            if swift_name == wire_name:
                lines.append(f'    case {swift_name}')
            else:
                lines.append(f'    case {swift_name} = "{wire_name}"')
        lines.append('  }')
        lines.append('')

    # init(from:) using decodeIfPresent for optionals + tolerant defaults.
    lines.append('  public init(from decoder: Decoder) throws {')
    lines.append('    let c = try decoder.container(keyedBy: CodingKeys.self)')
    for swift_name, wire_name, type_expr, optional in fields:
        if name == 'CandidateRecord' and wire_name == 'task_change':
            lines.append('    if try !c.contains(.taskChange) || c.decodeNil(forKey: .taskChange) {')
            lines.append('      taskChange = nil')
            lines.append('    } else {')
            lines.append('      switch proposedAction {')
            lines.append('      case .create where subjectKind == .task:')
            lines.append('        taskChange = .create(try c.decode(TaskCreatePayload.self, forKey: .taskChange))')
            lines.append('      case .update, .complete, .cancel, .supersede:')
            lines.append('        taskChange = .change(try c.decode(TaskChangePayload.self, forKey: .taskChange))')
            lines.append('      default:')
            lines.append('        taskChange = nil')
            lines.append('      }')
            lines.append('    }')
            continue
        if optional:
            lines.append(f'    {swift_name} = try c.decodeIfPresent({type_expr}.self, forKey: .{swift_name})')
        else:
            lines.append(f'    {swift_name} = try c.decode({type_expr}.self, forKey: .{swift_name})')
    lines.append('  }')
    lines.append('')

    # Memberwise init for adapter construction.
    param_list = ', '.join(f'{sn}: {te}' + ('?' if opt else '') for sn, _, te, opt in fields)
    lines.append(f'  public init({param_list}) {{')
    for swift_name, _, _, _ in fields:
        lines.append(f'    self.{swift_name} = {swift_name}')
    lines.append('  }')
    lines.append('}')
    return '\n'.join(lines) + '\n\n'


def _render_candidate_task_change() -> str:
    return '''public enum CandidateTaskChange: Codable {
  case create(TaskCreatePayload)
  case change(TaskChangePayload)

  public init(from decoder: Decoder) throws {
    if let create = try? TaskCreatePayload(from: decoder) {
      self = .create(create)
    } else {
      self = .change(try TaskChangePayload(from: decoder))
    }
  }

  public func encode(to encoder: Encoder) throws {
    switch self {
    case .create(let payload): try payload.encode(to: encoder)
    case .change(let payload): try payload.encode(to: encoder)
    }
  }
}

'''


def _render_candidate_create() -> str:
    return '''public enum CandidateCreate: Codable {
  case taskCreate(TaskCreateCandidate)
  case taskUpdate(TaskUpdateCandidate)
  case taskComplete(TaskCompleteCandidate)
  case taskCancel(TaskCancelCandidate)
  case taskSupersede(TaskSupersedeCandidate)
  case workstreamCreate(WorkstreamCreateCandidate)

  private enum DiscriminatorKeys: String, CodingKey {
    case subjectKind = "subject_kind"
    case proposedAction = "proposed_action"
  }

  public init(from decoder: Decoder) throws {
    let c = try decoder.container(keyedBy: DiscriminatorKeys.self)
    let subjectKind = try c.decode(String.self, forKey: .subjectKind)
    let proposedAction = try c.decode(String.self, forKey: .proposedAction)
    switch (subjectKind, proposedAction) {
    case ("task", "create"): self = .taskCreate(try TaskCreateCandidate(from: decoder))
    case ("task", "update"): self = .taskUpdate(try TaskUpdateCandidate(from: decoder))
    case ("task", "complete"): self = .taskComplete(try TaskCompleteCandidate(from: decoder))
    case ("task", "cancel"): self = .taskCancel(try TaskCancelCandidate(from: decoder))
    case ("task", "supersede"): self = .taskSupersede(try TaskSupersedeCandidate(from: decoder))
    case ("workstream", "create"): self = .workstreamCreate(try WorkstreamCreateCandidate(from: decoder))
    default:
      throw DecodingError.dataCorruptedError(
        forKey: .proposedAction,
        in: c,
        debugDescription: "Unsupported Candidate discriminator"
      )
    }
  }

  public func encode(to encoder: Encoder) throws {
    switch self {
    case .taskCreate(let value): try value.encode(to: encoder)
    case .taskUpdate(let value): try value.encode(to: encoder)
    case .taskComplete(let value): try value.encode(to: encoder)
    case .taskCancel(let value): try value.encode(to: encoder)
    case .taskSupersede(let value): try value.encode(to: encoder)
    case .workstreamCreate(let value): try value.encode(to: encoder)
    }
  }
}

'''


def _render_patch_field() -> str:
    return '''public enum OmiPatchField<Value: Codable>: Codable {
  case omitted
  case value(Value)
  case null

  public init(from decoder: Decoder) throws {
    let c = try decoder.singleValueContainer()
    if c.decodeNil() { self = .null }
    else { self = .value(try c.decode(Value.self)) }
  }

  public func encode(to encoder: Encoder) throws {
    var c = encoder.singleValueContainer()
    switch self {
    case .omitted: try c.encodeNil()
    case .value(let value): try c.encode(value)
    case .null: try c.encodeNil()
    }
  }
}

'''


def _render_patch_struct(name: str, schema: dict[str, Any]) -> str:
    name = _swift_type_name(name)
    props = schema.get('properties') or {}
    fields: list[tuple[str, str, str]] = []
    for wire_name, prop_schema in sorted(props.items()):
        swift_name = _swift_prop_name(wire_name)
        type_expr, _ = _swift_type(prop_schema, required=True)
        fields.append((swift_name, wire_name, type_expr))

    lines = [f'public struct {name}: Codable {{']
    for swift_name, _, type_expr in fields:
        lines.append(f'  public let {swift_name}: OmiPatchField<{type_expr}>')
    lines.append('')
    lines.append('  private enum CodingKeys: String, CodingKey {')
    for swift_name, wire_name, _ in fields:
        if swift_name == wire_name:
            lines.append(f'    case {swift_name}')
        else:
            lines.append(f'    case {swift_name} = "{wire_name}"')
    lines.append('  }')
    lines.append('')
    lines.append('  public init(from decoder: Decoder) throws {')
    lines.append('    let c = try decoder.container(keyedBy: CodingKeys.self)')
    for swift_name, _, type_expr in fields:
        lines.append(f'    if !c.contains(.{swift_name}) {{ {swift_name} = .omitted }}')
        lines.append(f'    else if try c.decodeNil(forKey: .{swift_name}) {{ {swift_name} = .null }}')
        lines.append(f'    else {{ {swift_name} = .value(try c.decode({type_expr}.self, forKey: .{swift_name})) }}')
    lines.append('  }')
    lines.append('')
    params = ', '.join(f'{swift_name}: OmiPatchField<{type_expr}> = .omitted' for swift_name, _, type_expr in fields)
    lines.append(f'  public init({params}) {{')
    for swift_name, _, _ in fields:
        lines.append(f'    self.{swift_name} = {swift_name}')
    lines.append('  }')
    lines.append('')
    lines.append('  public func encode(to encoder: Encoder) throws {')
    lines.append('    var c = encoder.container(keyedBy: CodingKeys.self)')
    for swift_name, _, _ in fields:
        lines.append(f'    switch {swift_name} {{')
        lines.append(f'    case .omitted: break')
        lines.append(f'    case .value(let value): try c.encode(value, forKey: .{swift_name})')
        lines.append(f'    case .null: try c.encodeNil(forKey: .{swift_name})')
        lines.append('    }')
    lines.append('  }')
    lines.append('}')
    return '\n'.join(lines) + '\n\n'


def _swift_prop_name(wire_name: str) -> str:
    parts = re.split(r'[_\W]+', wire_name)
    if not parts:
        return wire_name
    first = parts[0]
    rest = ''.join(p[:1].upper() + p[1:] for p in parts[1:])
    candidate = first + rest
    if candidate in SWIFT_RESERVED:
        candidate = candidate + '_'
    return candidate


def _collect_deps(schemas: dict[str, Any], targets: tuple[str, ...]) -> list[str]:
    """Topo-collect target schemas + transitive $ref deps, sorted alphabetically."""
    seen: set[str] = set()
    order: list[str] = []

    def visit(name: str) -> None:
        if name in seen or name not in schemas:
            return
        seen.add(name)
        schema = schemas[name]
        for prop in (schema.get('properties') or {}).values():
            _visit_refs(prop, visit)
        if 'items' in schema:
            _visit_refs(schema['items'], visit)
        for part in schema.get('anyOf', []) or schema.get('oneOf', []) or []:
            _visit_refs(part, visit)
        order.append(name)

    def _visit_refs(node: Any, visit) -> None:
        if isinstance(node, dict):
            if '$ref' in node:
                visit(_ref_name(node['$ref']))
            for v in node.values():
                _visit_refs(v, visit)
        elif isinstance(node, list):
            for v in node:
                _visit_refs(v, visit)

    for t in targets:
        visit(t)
    return sorted(set(order))


# --- Client method generation -------------------------------------------------

SKIP_SWIFT_CONTENT_PREFIXES = (
    'application/octet-stream',
    'text/event-stream',
    'text/plain',
    'text/html',
    'application/xml',
    'audio/',
    'image/',
    'multipart/form-data',
)

_SWIFT_BUILTIN_TYPES = {
    'String',
    'Int',
    'Double',
    'Bool',
    'OmiAnyCodable',
}


def _swift_func_name(op_id: str) -> str:
    """Clean an operationId into a valid camelCase Swift function name."""
    candidate = _swift_prop_name(op_id)
    if candidate and candidate[0].isdigit():
        candidate = '_' + candidate
    return candidate


def _swift_string_literal(s: str) -> str:
    """Render a Swift double-quoted string literal, escaping backslashes and quotes."""
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def _resolve_type(type_expr: str, emitted: set[str]) -> str:
    """Resolve a Swift type expression against emitted struct/enum names.

    If every referenced identifier is a builtin Swift/OmiAnyCodable type or a
    schema the Swift generator actually emitted, return it unchanged (strong
    typing). Otherwise fall back to OmiAnyCodable (preserving array-ness) so the
    emitted client method still compiles without forcing a change to the DTO
    generation scope.
    """
    refs = set(re.findall(r'[A-Za-z_][A-Za-z0-9_]*', type_expr))
    missing = [r for r in refs if r not in _SWIFT_BUILTIN_TYPES and r not in emitted]
    if not missing:
        return type_expr
    # Preserve array shape: [Message] -> [OmiAnyCodable].
    if type_expr.startswith('[') and type_expr.endswith(']') and ':' not in type_expr:
        return '[OmiAnyCodable]'
    return 'OmiAnyCodable'


def _swift_response_type(operation: dict[str, Any]) -> str | None:
    """Return the Swift type for an operation's success response, or None to skip.

    None => non-JSON success (binary/streaming/xml/multipart): skip the op.
    'Void' => 204-style no-content (or empty success content).
    """
    responses = operation.get('responses', {})
    if not isinstance(responses, dict):
        return 'Void'
    for status in ('200', '201', 'default'):
        resp = responses.get(status)
        if not isinstance(resp, dict):
            continue
        content = resp.get('content', {})
        if not isinstance(content, dict) or not content:
            return 'Void'  # 204-style no content
        json_content = content.get('application/json')
        if isinstance(json_content, dict):
            type_expr, _ = _swift_type(json_content.get('schema', {}), required=True)
            return type_expr
        # Non-JSON success response -> skip this operation entirely.
        for ct in content:
            if any(ct.startswith(p) or ct == p for p in SKIP_SWIFT_CONTENT_PREFIXES):
                return None
    if '204' in responses:
        return 'Void'
    return 'Void'


def _swift_request_body(operation: dict[str, Any]) -> tuple[str | None, bool]:
    """Return (body type expr, required) for an operation's JSON requestBody, or (None, False)."""
    req_body = operation.get('requestBody', {})
    if not isinstance(req_body, dict):
        return None, False
    content = req_body.get('content', {})
    if not isinstance(content, dict):
        return None, False
    json_content = content.get('application/json')
    if not isinstance(json_content, dict):
        return None, False
    type_expr, _ = _swift_type(json_content.get('schema', {}), required=True)
    return type_expr, bool(req_body.get('required', False))


def generate_swift_client_methods(spec: dict[str, Any]) -> str:
    """Emit typed Swift async client funcs (URLRequest + JSONDecoder) for each JSON op.

    Each emitted func takes a shared `OmiApiClient` (baseURL + optional bearer
    token), the operation's path/query params, and an optional Codable body,
    builds a URLRequest, runs it via URLSession, validates the HTTP status, and
    decodes the JSON success body into a typed value (or Void for 204). Mirrors
    generate_ts_openapi_types.generate_client_methods.
    """
    paths = spec.get('paths', {})
    if not isinstance(paths, dict):
        return ''

    schemas = spec.get('components', {}).get('schemas', {})
    emitted = {
        _swift_type_name(name) for name in _collect_deps(schemas, tuple(t for t in TARGET_SCHEMAS if t in schemas))
    }

    lines: list[str] = [
        '',
        '// --- Client methods (typed URLRequest + async wrappers). GENERATED - DO NOT EDIT. ---',
        '',
        '/// Shared client configuration for the generated async API funcs.',
        'public struct OmiApiClient {',
        '  public let baseURL: String',
        '  public let token: String?',
        '  public init(baseURL: String, token: String? = nil) {',
        '    self.baseURL = baseURL',
        '    self.token = token',
        '  }',
        '}',
        '',
        '/// Errors thrown by the generated client funcs.',
        'public enum OmiApiError: Error {',
        '  case invalidURL',
        '  case httpError(status: Int, data: Data)',
        '}',
        '',
    ]

    method_count = 0
    for path in sorted(paths):
        path_item = paths[path]
        if not isinstance(path_item, dict):
            continue
        for http_method in ('get', 'post', 'put', 'patch', 'delete'):
            operation = path_item.get(http_method)
            if not isinstance(operation, dict):
                continue
            op_id = operation.get('operationId')
            if not isinstance(op_id, str):
                continue

            raw_return = _swift_response_type(operation)
            if raw_return is None:
                continue  # non-JSON success response -> skip
            return_type = 'Void' if raw_return == 'Void' else _resolve_type(raw_return, emitted)

            fn_name = _swift_func_name(op_id)

            # Parse parameters into path (required) and query (required/optional) lists.
            raw_params = operation.get('parameters', [])
            path_params: list[tuple[str, str]] = []  # (wire name, swift type)
            query_params: list[tuple[str, str, bool]] = []  # (wire name, swift type, required)
            if isinstance(raw_params, list):
                for p in raw_params:
                    if not isinstance(p, dict):
                        continue
                    location = p.get('in')
                    pname = p.get('name', '')
                    required = bool(p.get('required', False))
                    ptype, _ = _swift_type(p.get('schema', {}), required=True)
                    ptype = _resolve_type(ptype, emitted)
                    if ptype not in ('String', 'Int', 'Double', 'Bool'):
                        ptype = 'String'
                    if location == 'path':
                        path_params.append((pname, ptype))
                    elif location == 'query':
                        query_params.append((pname, ptype, required))

            # Parse JSON requestBody.
            raw_body, body_required = _swift_request_body(operation)
            body_type = _resolve_type(raw_body, emitted) if raw_body else None

            # Build the function signature.
            sig_parts: list[str] = ['client: OmiApiClient']
            for pname, ptype in path_params:
                sig_parts.append(f'{_swift_prop_name(pname)}: {ptype}')
            for pname, qtype, required in query_params:
                sw = _swift_prop_name(pname)
                if required:
                    sig_parts.append(f'{sw}: {qtype}')
                else:
                    sig_parts.append(f'{sw}: {qtype}? = nil')
            if body_type:
                if body_required:
                    sig_parts.append(f'body: {body_type}')
                else:
                    sig_parts.append(f'body: {body_type}? = nil')
            sig = ', '.join(sig_parts)

            # Interpolate path params into the URL template via Swift \() interpolation.
            # Escape literal path characters first, THEN inject interpolation so the
            # interpolation backslash survives unescaped into the emitted literal.
            url_path = path.replace('\\', '\\\\').replace('"', '\\"')
            for pname, _ in path_params:
                url_path = url_path.replace('{' + pname + '}', '\\(' + _swift_prop_name(pname) + ')')
            path_literal = '"' + url_path + '"'

            body_lines = [
                f'public static func {fn_name}({sig}) async throws -> {return_type} {{',
                f'  let _path = {path_literal}',
                '  guard var components = URLComponents(string: client.baseURL + _path) else {',
                '    throw OmiApiError.invalidURL',
                '  }',
            ]
            if query_params:
                body_lines.append('  var queryItems: [URLQueryItem] = []')
                for pname, qtype, required in query_params:
                    sw = _swift_prop_name(pname)
                    name_lit = _swift_string_literal(pname)
                    if required:
                        body_lines.append(f'  queryItems.append(URLQueryItem(name: {name_lit}, value: String({sw})))')
                    else:
                        body_lines.append(f'  if let {sw} {{')
                        body_lines.append(f'    queryItems.append(URLQueryItem(name: {name_lit}, value: String({sw})))')
                        body_lines.append('  }')
                body_lines.append('  if !queryItems.isEmpty { components.queryItems = queryItems }')
            body_lines.append('  guard let url = components.url else { throw OmiApiError.invalidURL }')
            body_lines.append('  var req = URLRequest(url: url)')
            body_lines.append(f'  req.httpMethod = {_swift_string_literal(http_method.upper())}')
            body_lines.append('  if let token = client.token {')
            body_lines.append('    req.setValue("Bearer " + token, forHTTPHeaderField: "Authorization")')
            body_lines.append('  }')
            if body_type:
                body_lines.append('  req.setValue("application/json", forHTTPHeaderField: "Content-Type")')
                body_lines.append('  req.httpBody = try JSONEncoder().encode(body)')
            body_lines.append('  let (data, resp) = try await URLSession.shared.data(for: req)')
            body_lines.append('  guard let http = resp as? HTTPURLResponse else { throw OmiApiError.invalidURL }')
            body_lines.append('  guard (200..<300).contains(http.statusCode) else {')
            body_lines.append('    throw OmiApiError.httpError(status: http.statusCode, data: data)')
            body_lines.append('  }')
            if return_type == 'Void':
                body_lines.append('  return')
            else:
                body_lines.append(f'  return try JSONDecoder().decode({return_type}.self, from: data)')
            body_lines.append('}')
            body_lines.append('')

            lines.extend(body_lines)
            method_count += 1

    lines.append(f'// Total: {method_count} Swift client methods generated.')
    return '\n'.join(lines)


def generate(spec: dict[str, Any], spec_path: str) -> str:
    schemas = spec.get('components', {}).get('schemas', {})
    targets = tuple(t for t in TARGET_SCHEMAS if t in schemas)
    names = _collect_deps(schemas, targets)

    out = [HEADER_PRE.format(spec_path=spec_path)]
    # OmiAnyCodable helper for opaque JSON values — module scope, outside OmiAPI.
    out.append(ANY_CODABLE)
    out.append(HEADER_NAMESPACE_OPEN)
    candidate_union = _render_candidate_task_change()
    out.append('\n'.join(('  ' + line) if line else line for line in candidate_union.split('\n')) + '\n')
    candidate_create = _render_candidate_create()
    out.append('\n'.join(('  ' + line) if line else line for line in candidate_create.split('\n')) + '\n')
    patch_field = _render_patch_field()
    out.append('\n'.join(('  ' + line) if line else line for line in patch_field.split('\n')) + '\n')
    for name in names:
        schema = schemas[name]
        block = ''
        if schema.get('type') == 'string' and 'enum' in schema:
            block = _render_enum(_swift_type_name(name), schema)
        elif schema.get('type') == 'object' or 'properties' in schema:
            if name in PRESENCE_AWARE_PATCH_SCHEMAS:
                block = _render_patch_struct(_swift_type_name(name), schema)
            else:
                block = _render_struct(_swift_type_name(name), schema)
        else:
            continue
        # Indent the block by 2 spaces to nest inside `enum OmiAPI`.
        indented = '\n'.join(('  ' + line) if line else line for line in block.split('\n'))
        out.append(indented + '\n')
    # Typed async client funcs (URLRequest + JSONDecoder) for each JSON op,
    # appended inside the OmiAPI namespace so they resolve the DTOs directly.
    client_block = generate_swift_client_methods(spec)
    if client_block:
        indented = '\n'.join(('  ' + line) if line else line for line in client_block.split('\n'))
        out.append(indented + '\n')
    out.append(FOOTER)
    return ''.join(out)


ANY_CODABLE = '''/// Type-erased Codable for opaque backend JSON values (open maps, anyOf unions
/// the generator does not narrow further). Round-trips through JSONSerialization.
public struct OmiAnyCodable: Codable, Equatable {
  public let value: Any

  public init(_ value: Any) { self.value = value }

  public init(from decoder: Decoder) throws {
    let c = try decoder.singleValueContainer()
    if c.decodeNil() { value = NSNull() }
    else if let v = try? c.decode(Bool.self) { value = v }
    else if let v = try? c.decode(Double.self) { value = v }
    else if let v = try? c.decode(String.self) { value = v }
    else if let v = try? c.decode([OmiAnyCodable].self) { value = v.map { $0.value } }
    else if let v = try? c.decode([String: OmiAnyCodable].self) { value = v.mapValues { $0.value } }
    else { value = NSNull() }
  }

  public func encode(to encoder: Encoder) throws {
    var c = encoder.singleValueContainer()
    switch value {
    case is NSNull: try c.encodeNil()
    case let v as Bool: try c.encode(v)
    case let v as Double: try c.encode(v)
    case let v as Int: try c.encode(v)
    case let v as String: try c.encode(v)
    case let v as [Any]: try c.encode(v.map { OmiAnyCodable($0) })
    case let v as [String: Any]: try c.encode(v.mapValues { OmiAnyCodable($0) })
    default: try c.encodeNil()
    }
  }

  public static func == (lhs: OmiAnyCodable, rhs: OmiAnyCodable) -> Bool {
    let lhsData = try? JSONSerialization.data(withJSONObject: [lhs.value], options: [.sortedKeys])
    let rhsData = try? JSONSerialization.data(withJSONObject: [rhs.value], options: [.sortedKeys])
    return lhsData == rhsData
  }
}

'''


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--spec', type=Path, default=DEFAULT_SPEC_PATH)
    p.add_argument('--output', type=Path, default=DEFAULT_OUTPUT)
    p.add_argument('--check', action='store_true', help='verify generated file is fresh')
    return p.parse_args()


def main() -> int:
    args = parse_args()
    spec = json.loads(args.spec.read_text())
    generated = generate(spec, str(args.spec.relative_to(ROOT_DIR)) if args.spec.is_absolute() else str(args.spec))

    if args.check:
        existing = args.output.read_text() if args.output.exists() else ''
        if existing != generated:
            rel = args.output.relative_to(ROOT_DIR) if args.output.is_absolute() else args.output
            print(f'{rel} is out of date. Run: python {Path(__file__).name}', file=sys.stderr)
            return 1
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generated)
    print(f'wrote {args.output}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
