"""Generate the desktop Gemini lane/workload/platform constants for every consumer.

Source of truth: ``backend/config/desktop_gemini_attribution.json``. ``--check``
is the hermetic drift guard.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ATTRIBUTION_PATH = ROOT / 'backend' / 'config' / 'desktop_gemini_attribution.json'

PYTHON_PATH = ROOT / 'backend' / 'config' / 'desktop_gemini_attribution_generated.py'
SWIFT_PATH = ROOT / 'desktop' / 'macos' / 'Desktop' / 'Sources' / 'ProactiveAssistants' / 'Core' / 'GeminiLane.swift'
TYPESCRIPT_PATH = ROOT / 'desktop' / 'windows' / 'src' / 'shared' / 'geminiAttribution.ts'

GENERATED_NOTICE = 'Generated by backend/scripts/generate_desktop_gemini_attribution.py'
SOURCE_NOTICE = 'from backend/config/desktop_gemini_attribution.json'

_WIRE_VALUE = re.compile(r'[a-z][a-z0-9_]*')


def validate_attribution(data: dict) -> dict:
    lanes = data['lanes']
    assert isinstance(lanes, dict) and lanes, 'lanes must be a non-empty object'
    assert len(set(lanes.values())) == len(lanes), 'duplicate lane wire values'
    for key, wire in lanes.items():
        assert key and key[0].islower() and key.isidentifier(), f'bad lane key: {key!r}'
        assert isinstance(wire, str) and _WIRE_VALUE.fullmatch(wire), f'bad lane wire value: {wire!r}'
    for field in ('workloads', 'platforms'):
        values = data[field]
        assert isinstance(values, list) and values, f'{field} must be a non-empty list'
        assert len(values) == len(set(values)), f'{field} has duplicates'
    return data


def load_attribution() -> dict:
    with ATTRIBUTION_PATH.open(encoding='utf-8') as handle:
        return validate_attribution(json.load(handle))


def render_python(data: dict) -> str:
    lanes = data['lanes']
    lane_lines = '\n'.join(f"    {key!r}: {wire!r}," for key, wire in lanes.items())
    workload_items = ', '.join(repr(workload) for workload in data['workloads'])
    platform_items = ', '.join(repr(platform) for platform in data['platforms'])
    return f'''# {GENERATED_NOTICE} {SOURCE_NOTICE}.
# Do not edit by hand.

from __future__ import annotations

from typing import Final

GEMINI_LANE_WIRE_VALUES: Final[dict[str, str]] = {{
{lane_lines}
}}

GEMINI_LANES: Final[frozenset[str]] = frozenset(GEMINI_LANE_WIRE_VALUES.values())
GEMINI_WORKLOADS: Final[frozenset[str]] = frozenset({{{workload_items}}})
GEMINI_CLIENT_PLATFORMS: Final[frozenset[str]] = frozenset({{{platform_items}}})
'''


def render_swift(data: dict) -> str:
    lane_cases = '\n'.join(f'  case {key} = "{wire}"' for key, wire in data['lanes'].items())
    workload_cases = '\n'.join(f'  case {workload} = "{workload}"' for workload in data['workloads'])
    return f'''// {GENERATED_NOTICE} {SOURCE_NOTICE}.
// Do not edit by hand.

enum GeminiLane: String, CaseIterable, Sendable {{
{lane_cases}
}}

enum GeminiWorkloadClass: String, CaseIterable, Sendable {{
{workload_cases}
}}
'''


def render_typescript(data: dict) -> str:
    lanes = data['lanes']
    lane_entries = '\n'.join(f"  {key}: '{wire}'," for key, wire in lanes.items())
    lane_entries = lane_entries[:-1]
    workload_items = ', '.join(f"'{workload}'" for workload in data['workloads'])
    return f'''// {GENERATED_NOTICE} {SOURCE_NOTICE}.
// Do not edit by hand.

export const GeminiLane = {{
{lane_entries}
}} as const
export type GeminiLane = (typeof GeminiLane)[keyof typeof GeminiLane]

export const GEMINI_WORKLOADS = [{workload_items}] as const
export type GeminiWorkload = (typeof GEMINI_WORKLOADS)[number]
'''


GENERATED_FILES = (
    (PYTHON_PATH, render_python),
    (SWIFT_PATH, render_swift),
    (TYPESCRIPT_PATH, render_typescript),
)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Fail if any generated file is stale.')
    args = parser.parse_args()

    data = load_attribution()
    stale: list[Path] = []
    for path, render in GENERATED_FILES:
        expected = render(data)
        if args.check:
            if not path.exists() or path.read_text(encoding='utf-8') != expected:
                stale.append(path)
        else:
            path.write_text(expected, encoding='utf-8', newline='\n')
            print(f'wrote {path.relative_to(ROOT)}')
    if stale:
        for path in stale:
            print(f'stale generated file: {path.relative_to(ROOT)}')
        raise SystemExit(1)


if __name__ == '__main__':
    main()
