#!/usr/bin/env bash
# generate_state_graph.sh
# Scans lib/main.dart provider registrations and lib/providers/** to regenerate
# state-management.providers.yaml.
#
# Usage (from repo root):
#   bash app/scripts/agent/generate_state_graph.sh
#
# Output:
#   app/docs/flows/generated/state-management.providers.yaml

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
LIB_DIR="${APP_DIR}/lib"
OUT_FILE="${APP_DIR}/docs/flows/generated/state-management.providers.yaml"

echo "→ Scanning lib/main.dart and lib/providers/**..."

# ── Count registrations ───────────────────────────────────────────────────────
MAIN_DART="${LIB_DIR}/main.dart"
total_registrations=0
proxy_providers=0

if [[ -f "${MAIN_DART}" ]]; then
  total_registrations=$(grep -c 'ChangeNotifierProvider\|ChangeNotifierProxyProvider\|Provider(' "${MAIN_DART}" || true)
  proxy_providers=$(grep -c 'ProxyProvider' "${MAIN_DART}" || true)
fi

# ── Header ────────────────────────────────────────────────────────────────────
cat > "${OUT_FILE}" <<YAML
# Auto-generated by scripts/agent/generate_state_graph.sh
# DO NOT EDIT MANUALLY — regenerate with: bash scripts/agent/generate_state_graph.sh
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

meta:
  generated_by: generate_state_graph.sh
  generated_at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
  total_registrations: ${total_registrations}
  proxy_providers: ${proxy_providers}

providers:
YAML

# ── Scan lib/providers/*.dart ─────────────────────────────────────────────────
PROVIDERS_DIR="${LIB_DIR}/providers"
if [[ -d "${PROVIDERS_DIR}" ]]; then
  find "${PROVIDERS_DIR}" -name "*.dart" | sort | while read -r file; do
    rel="lib/${file#"${LIB_DIR}/"}"
    class_name=$(grep -oP 'class \K\w+(?=\s+extends\s+(ChangeNotifier|StateNotifier))' "${file}" | head -1 || true)
    if [[ -z "${class_name}" ]]; then
      continue
    fi

    # Detect ProxyProvider usage in main.dart
    ptype="ChangeNotifierProvider"
    if [[ -f "${MAIN_DART}" ]] && grep -q "ProxyProvider.*${class_name}" "${MAIN_DART}" 2>/dev/null; then
      ptype="ChangeNotifierProxyProvider"
    fi

    # Detect upstream dependencies from main.dart
    deps=$(grep -oP "ChangeNotifierProxyProvider[^<]*<[^>]*${class_name}[^>]*>" "${MAIN_DART}" 2>/dev/null | head -1 || true)

    cat >> "${OUT_FILE}" <<YAML
  - name: ${class_name}
    class: ${class_name}
    file: ${rel}
    type: ${ptype}
YAML
  done
fi

# ── High blast-radius reminder ────────────────────────────────────────────────
cat >> "${OUT_FILE}" <<YAML

high_blast_radius_note: >
  Review blast_radius_files counts manually in state-management.md after
  significant refactoring. This script does not compute file counts automatically.
YAML

echo "✓ Written: ${OUT_FILE}"
echo ""
echo "Next step: review the output and update app/docs/flows/state-management.md if"
echo "provider dependencies or mutations changed. Commit both files together."
