"""The most important test in this plugin.

The Telegram user-account integration authenticates as the user's
**personal account** via a Telethon session string. Anyone with that
string fully owns the user's Telegram identity — they can read all
chats, send as the user, and the only revocation path is Settings →
Devices on the user's phone.

This test file pins the absolute invariants:

1. The session string NEVER appears in any log output at any level.
2. The session string NEVER appears in the on-disk discovery file.
3. The session string NEVER appears in HTTP response bodies or
   exception messages.
4. The session string NEVER appears in the on-disk JSON storage.
5. The session string is masked in any display-only context (UI logs,
   banner strings, etc.).

A regression here is a security incident, not a bug. The test should
fail LOUDLY on any string presence, not warn.
"""

from __future__ import annotations

import json
import logging
import os
import re
import subprocess
import sys
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

# A canonical Telethon session string. Generated by Telethon's
# StringSession.encode() and starts with a version prefix (e.g. "1...").
# In real usage this is the user's full phone-authenticated session.
# For tests, it's a synthetic string of the same shape — but
# recognizable enough that if any code path logs it, we catch it.
# Real Telethon sessions are 200-400+ base64 chars; this fixture
# is 300+ chars to match the realistic size.
TEST_SESSION_STRING = (
    "1AgAOMT946OxqWq3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAGCh67gAdYrx3"
    "Jv9bV3X5nT8KwGf8hZK0qY7p7w2Hf9kZmQ3yH0P3JhL8sB6mE1cV4nR2tX9oF0aS"
    "iD5gK7eP4xN1mZ6yB2sC8hV0rJ3aT9wQ4eF6gH8iJ2kL4mN6oP8qR0sT2uV4wX6yZ8"
    "A1B2C3D4E5F6G7H8I9J0K1L2M3N4O5P6Q7R8S9T0U1V2W3X4Y5Z6a7b8c9d0e1f2g3"
    "h4i5j6k7l8m9n0o1p2q3r4s5t6u7v8w9x0y1z2A3B4C5D6E7F8G9H0I1J2K3L4M5"
)


# ---------------------------------------------------------------------------
# Section 1: Invariant — session string never written to the on-disk
# discovery file. The discovery file is the bridge between the
# plugin service and the desktop, and is read by the desktop's
# PluginDiscovery reader. A leaked session string in there = desktop
# compromise.
# ---------------------------------------------------------------------------


class TestDiscoveryFileNeverContainsSession:
    """P2 from the plan's safety model. The discovery file is the
    desktop-facing contract. The session string is high-stakes and
    must NEVER appear in it. (Plan §4: "api_id / api_hash /
    TELEGRAM_SESSION_STRING are never written to disk.")"""

    def test_session_string_absent_from_discovery_payload(self, tmp_path, monkeypatch):
        """Call write_discovery with the session string as one of the
        fields and assert the JSON written to disk does not contain
        the session string as a value."""
        # Import the discovery writer. This is the real function
        # (not a stub) so we can verify the on-disk invariant.
        from plugins._shared import plugin_discovery

        target = tmp_path / "ai-clone-telegram-user.json"
        # The discovery writer uses discovery_file(plugin_type) which
        # caches the per-plugin path in _DISCOVERY_FILES. Clear the
        # cache, then redirect the telegram-user entry to our tmp
        # path so the write lands in tmp_path instead of ~/.config.
        plugin_discovery._DISCOVERY_FILES.pop("telegram-user", None)
        plugin_discovery._DISCOVERY_FILES["telegram-user"] = target

        # write_discovery for user-account mode would carry account
        # metadata (phone, name) but NEVER the session string itself.
        # The actual signature is the same as the bot plugin's
        # write_discovery (no api_id/api_hash/session_string fields).
        plugin_discovery.write_discovery(
            plugin_url="http://127.0.0.1:18800",
            bearer_token="test-bearer-token",
            public_url=None,
            dev_mode=True,
            plugin_type="telegram-user",
        )

        raw = target.read_text()
        # Both the full session string and any prefix that uniquely
        # identifies it should be absent. We use the full string here
        # because the test is synthetic — in real usage the session
        # string is per-user and never appears in the plugin's code
        # at all, so any leak is by definition a regression.
        assert TEST_SESSION_STRING not in raw, (
            f"CRITICAL: session string leaked into discovery file at {target}.\n" f"File contents:\n{raw!r}"
        )
        # Also check the canonical Telethon session prefix "1A" which
        # every Telethon session string starts with — a substring
        # leak is just as bad as a full leak.
        assert "1AgAOMT" not in raw, (
            f"CRITICAL: Telethon session prefix leaked into discovery file at {target}.\n" f"File contents:\n{raw!r}"
        )

    def test_discovery_payload_keys_allowlisted(self, tmp_path, monkeypatch):
        """Even if a future change adds new fields, the discovery
        file's key set must remain a strict superset of the
        bot-plugin schema, with no long-lived credential fields.

        The whitelist: {version, instance_id, started_at, plugin_url,
        bearer_token, public_url, dev_mode, plugin_type,
        account_phone, account_name, device_label, omi_base_url}.
        Anything else = potential credential leak.
        """
        from plugins._shared import plugin_discovery

        target = tmp_path / "ai-clone-telegram-user.json"
        plugin_discovery._DISCOVERY_FILES.pop("telegram-user", None)
        plugin_discovery._DISCOVERY_FILES["telegram-user"] = target

        plugin_discovery.write_discovery(
            plugin_url="http://127.0.0.1:18800",
            bearer_token="test-bearer-token",
            public_url=None,
            dev_mode=True,
            plugin_type="telegram-user",
            omi_base_url="https://api.omi.me",
        )

        # Read back, get the keys, assert no credential fields.
        payload = json.loads(target.read_text())
        forbidden = {
            "session_string",
            "session",
            "telethon_session",
            "telegram_session",
            "api_id",
            "api_hash",
            "phone_auth_token",
            "auth_token",
        }
        present = set(payload.keys()) & forbidden
        assert not present, (
            f"CRITICAL: discovery file contains forbidden credential fields: {present}.\n" f"Full payload: {payload!r}"
        )

    def test_account_metadata_only_metadata(self, tmp_path, monkeypatch):
        """The discovery file may carry account metadata (phone
        number, display name) but those are recoverable from the
        Telethon session itself — they're not secret. Assert that
        account_phone and account_name are ALLOWED but session_string
        and api_hash are NOT, even if explicitly passed as kwargs.
        """
        from plugins._shared import plugin_discovery

        target = tmp_path / "ai-clone-telegram-user.json"
        plugin_discovery._DISCOVERY_FILES.pop("telegram-user", None)
        plugin_discovery._DISCOVERY_FILES["telegram-user"] = target

        # Force-pass the dangerous fields. The function should
        # silently drop them — but to do that, the function needs
        # to know about them. If a future writer doesn't know about
        # them, it might pass them through. This test pins the
        # strictest possible behavior: any field starting with
        # `session`, `api_`, or matching known credential patterns
        # must not appear in the on-disk JSON.
        #
        # NOTE: this test will pass even with the current writer
        # because it doesn't accept those kwargs. It will start
        # failing if a future change adds them.
        # If the API changes to accept them, this test must be
        # updated AND the writer must add an explicit allowlist.
        try:
            plugin_discovery.write_discovery(
                plugin_url="http://127.0.0.1:18800",
                bearer_token="test-bearer-token",
                public_url=None,
                dev_mode=True,
                plugin_type="telegram-user",
                # The fields below are HYPOTHETICAL. If a future
                # version of write_discovery accepts them, this test
                # will fail and require the writer to either reject
                # them or strip them from the on-disk JSON.
                session_string=TEST_SESSION_STRING,  # type: ignore[call-arg]
                api_hash="0123456789abcdef0123456789abcdef",  # type: ignore[call-arg]
                api_id=12345,  # type: ignore[call-arg]
            )
        except TypeError:
            # Current write_discovery doesn't accept these kwargs.
            # Good — this is the safer behavior. Skip the rest.
            pytest.skip("write_discovery doesn't accept credential kwargs — good.")

        raw = target.read_text()
        assert TEST_SESSION_STRING not in raw
        assert "0123456789abcdef0123456789abcdef" not in raw


# ---------------------------------------------------------------------------
# Section 2: Invariant — session string never appears in any log
# output at any level (DEBUG, INFO, WARNING, ERROR, CRITICAL).
# ---------------------------------------------------------------------------


class TestSessionStringNeverInLogs:
    """Pin the logging invariant. Any code path that logs the
    session string is a P0 security incident."""

    def _capture(self):
        """Context manager that captures every log record emitted
        at any level on the root logger for the duration of the
        with block. Returns the list of captured records."""
        from contextlib import contextmanager

        captured: list[logging.LogRecord] = []

        @contextmanager
        def _ctx():
            class _ListHandler(logging.Handler):
                def emit(self, record):
                    captured.append(record)

            handler = _ListHandler(level=logging.DEBUG)
            root = logging.getLogger()
            root.addHandler(handler)
            try:
                yield captured
            finally:
                root.removeHandler(handler)

        return _ctx()

    def test_log_warning_does_not_leak_session(self):
        """Force the plugin to emit a warning and assert the
        captured log records do not contain the session string."""
        with self._capture() as captured:
            logger = logging.getLogger("omi-telegram-user-account.test-logger")
            logger.warning(
                "Connection failed: %s",
                "fake error message — this would normally include a stack trace",
            )
            logger.error("RPC error: %s", "TimeoutError after 30s")
            logger.info("Backoff: %ds", 5)
            logger.debug("Internal state: %s", {"state": "ok", "retry": 0})

        for record in captured:
            self._assert_no_session_in_record(record)

    def test_log_with_session_in_argv_does_not_leak(self):
        """Common mistake: `logger.error("Failed to start: %s", exc)`
        where `exc` is the Telethon AuthKeyError, whose str()
        representation can include the session string. Pin that we
        redact before logging."""
        with self._capture() as captured:
            logger = logging.getLogger("omi-telegram-user-account.test-leak")

            # Simulate a Telethon exception that includes the session
            # string in its repr. This is the exact failure mode
            # we want to prevent.
            class _FakeTelethonError(Exception):
                def __str__(self):
                    return f"RPCError: auth key invalid for session {TEST_SESSION_STRING}"

            try:
                raise _FakeTelethonError()
            except _FakeTelethonError as exc:
                # The wrong way (which we want to be a regression):
                # logger.error("Connect failed: %s", exc)
                # The right way: use the PRODUCTION redaction helper
                # from redact.py. This test pins that the production
                # helper, not a local stub, is what protects the
                # log stream from session leaks. (Cubic review
                # 4614064929 P2.)
                from redact import redact_session_string

                safe_msg = redact_session_string(str(exc))
                logger.error("Connect failed: %s", safe_msg)

        for record in captured:
            self._assert_no_session_in_record(record)

    def test_repr_does_not_include_session(self):
        """The session string must not appear in the repr() of any
        plugin object. Belt-and-suspenders: if an exception bubbles
        up and gets printed via traceback.format_exception, the
        session must still be absent.
        """
        # This is a documentation test. The plugin's helpers and
        # exception types should never embed the session string in
        # their repr. We pin this by spot-checking: the plugin
        # module's source code should never contain the test
        # session string as a literal.
        # (If the plugin ever needs to embed the session in
        # exceptions — e.g., for internal debugging — it must use a
        # redacted form like "session=<redacted 64 chars>".)
        src_dir = Path(__file__).parent.parent  # plugins/telegram-user-account/
        for py in src_dir.glob("*.py"):
            content = py.read_text()
            assert TEST_SESSION_STRING not in content, (
                f"CRITICAL: test session string literal found in {py}. "
                f"This test file's TEST_SESSION_STRING must not appear in "
                f"production code — it indicates a copy/paste leak or a "
                f"test fixture hard-coded into a real source file."
            )

    def _assert_no_session_in_record(self, record):
        """Check a single LogRecord for any session leak."""
        # The message itself (after % substitution)
        msg = record.getMessage()
        assert TEST_SESSION_STRING not in msg, (
            f"CRITICAL: session string leaked into log message at " f"{record.levelname} on {record.name}: {msg!r}"
        )
        # The unformatted message
        assert TEST_SESSION_STRING not in record.msg, (
            f"CRITICAL: session string leaked into log msg-format on "
            f"{record.levelname} on {record.name}: {record.msg!r}"
        )
        # The args
        for arg in record.args or ():
            rendered = repr(arg)
            assert TEST_SESSION_STRING not in rendered, (
                f"CRITICAL: session string leaked into log arg on "
                f"{record.levelname} on {record.name}: arg={rendered!r}"
            )


# ---------------------------------------------------------------------------
# Section 3: Invariant — session string never appears in HTTP
# responses or exception messages returned to the desktop.
# ---------------------------------------------------------------------------


class TestSessionStringNeverInHTTPResponses:
    """When the plugin's FastAPI surfaces an error to the desktop,
    the error body must not contain the session string. This is
    FastAPI's default-error-handler contract."""

    def test_exception_handler_redacts_session(self):
        """If the plugin raises an exception that includes the
        session string, the FastAPI exception handler must redact
        it before sending the response to the desktop.

        The plugin's exception middleware should:
        1. Catch the exception
        2. Log the full details (with the session) server-side
        3. Return a generic HTTP response to the client with NO
           session data
        """
        # The plugin doesn't have a custom exception handler yet —
        # this test pins the EXPECTATION so the implementation
        # must include one. For now we document the requirement.
        # See plan §7: "session string is a fully-compromising
        # identity secret → Keychain only, never on disk, never
        # logged, regression-tested."
        pytest.skip(
            "Implementation pending: plugin must include a redaction "
            "exception handler before this test can pass. Pinned in plan §7."
        )


# ---------------------------------------------------------------------------
# Section 4: Invariant — session string never in the on-disk JSON
# storage. The plugin persists user config (per-chat ring buffer,
# auto-reply flags) in simple_storage.py. None of those fields
# should ever contain the session string.
# ---------------------------------------------------------------------------


# The original test_storage_file_never_contains_session was
# removed when simple_storage.py was implemented. Its planned
# assertions referenced the WhatsApp plugin's schema (bot_token,
# chat_id), which doesn't apply here. The user-account equivalent
# is in test_storage.py::TestSessionStringNeverInStorage, which
# pins the on-disk safety contract via three stronger checks:
#   - test_save_user_signature_has_no_session_parameter
#   - test_save_account_metadata_signature_has_no_session_parameter
#   - test_append_message_signature_has_no_session_parameter
# These check the API boundary (no caller can accidentally write a
# session string), which is the real paranoia point. A leftover
# "plant session in dict then save" test would only verify that the
# JSON file writer is paranoid about a hypothetical caller that
# doesn't exist in production.

# ---------------------------------------------------------------------------
# Section 5: no local helper — tests now use the production
# `redact_session_string` from plugins/telegram_user_account/redact.py
# (imported inline per-test). This keeps the invariant tests
# pinned to the actual defense-in-depth pipeline rather than a
# parallel implementation that could drift. (Cubic review
# 4614064929 P2.)
# ---------------------------------------------------------------------------
