"""Curated global country database for Omi Wearables.

Provides zero-latency, offline-resilient country profiles, capitals,
currencies, languages, regional borders, and demographic facts.
"""

from typing import Any, Dict, List, Optional, Tuple

COUNTRIES_DB: List[Dict[str, Any]] = [
    {
        "name": "Afghanistan",
        "official_name": "Islamic Republic of Afghanistan",
        "cca2": "AF",
        "cca3": "AFG",
        "capital": "Kabul",
        "region": "Asia",
        "subregion": "Southern Asia",
        "population": 40218234,
        "area_sq_km": 652230,
        "currencies": {"AFN": {"name": "Afghan afghani", "symbol": "؋"}},
        "languages": {"prs": "Dari", "pus": "Pashto", "tuk": "Turkmen"},
        "borders": ["IRN", "PAK", "TKM", "UZB", "TJK", "CHN"],
        "flag": "🇦🇫",
        "demonym": "Afghan",
        "timezones": ["UTC+04:30"],
    },
    {
        "name": "Albania",
        "official_name": "Republic of Albania",
        "cca2": "AL",
        "cca3": "ALB",
        "capital": "Tirana",
        "region": "Europe",
        "subregion": "Southeast Europe",
        "population": 2837743,
        "area_sq_km": 28748,
        "currencies": {"ALL": {"name": "Albanian lek", "symbol": "L"}},
        "languages": {"sqi": "Albanian"},
        "borders": ["MNE", "GRC", "MKD", "UNK"],
        "flag": "🇦🇱",
        "demonym": "Albanian",
        "timezones": ["UTC+01:00"],
    },
    {
        "name": "Algeria",
        "official_name": "People's Democratic Republic of Algeria",
        "cca2": "DZ",
        "cca3": "DZA",
        "capital": "Algiers",
        "region": "Africa",
        "subregion": "Northern Africa",
        "population": 44700000,
        "area_sq_km": 2381741,
        "currencies": {"DZD": {"name": "Algerian dinar", "symbol": "د.ج"}},
        "languages": {"ara": "Arabic", "ber": "Berber"},
        "borders": ["TUN", "LBY", "NER", "ESH", "MRT", "MLI", "MAR"],
        "flag": "🇩🇿",
        "demonym": "Algerian",
        "timezones": ["UTC+01:00"],
    },
    {
        "name": "Andorra",
        "official_name": "Principality of Andorra",
        "cca2": "AD",
        "cca3": "AND",
        "capital": "Andorra la Vella",
        "region": "Europe",
        "subregion": "Southern Europe",
        "population": 77265,
        "area_sq_km": 468,
        "currencies": {"EUR": {"name": "Euro", "symbol": "€"}},
        "languages": {"cat": "Catalan"},
        "borders": ["FRA", "ESP"],
        "flag": "🇦🇩",
        "demonym": "Andorran",
        "timezones": ["UTC+01:00"],
    },
    {
        "name": "Angola",
        "official_name": "Republic of Angola",
        "cca2": "AO",
        "cca3": "AGO",
        "capital": "Luanda",
        "region": "Africa",
        "subregion": "Middle Africa",
        "population": 32866268,
        "area_sq_km": 1246700,
        "currencies": {"AOA": {"name": "Angolan kwanza", "symbol": "Kz"}},
        "languages": {"por": "Portuguese"},
        "borders": ["COG", "COD", "ZMB", "NAM"],
        "flag": "🇦🇴",
        "demonym": "Angolan",
        "timezones": ["UTC+01:00"],
    },
    {
        "name": "Argentina",
        "official_name": "Argentine Republic",
        "cca2": "AR",
        "cca3": "ARG",
        "capital": "Buenos Aires",
        "region": "Americas",
        "subregion": "South America",
        "population": 45376763,
        "area_sq_km": 2780400,
        "currencies": {"ARS": {"name": "Argentine peso", "symbol": "$"}},
        "languages": {"spa": "Spanish", "grn": "Guaraní"},
        "borders": ["BOL", "BRA", "CHL", "PRY", "URY"],
        "flag": "🇦🇷",
        "demonym": "Argentine",
        "timezones": ["UTC-03:00"],
    },
    {
        "name": "Armenia",
        "official_name": "Republic of Armenia",
        "cca2": "AM",
        "cca3": "ARM",
        "capital": "Yerevan",
        "region": "Asia",
        "subregion": "Western Asia",
        "population": 2963234,
        "area_sq_km": 29743,
        "currencies": {"AMD": {"name": "Armenian dram", "symbol": "֏"}},
        "languages": {"hye": "Armenian"},
        "borders": ["AZE", "GEO", "IRN", "TUR"],
        "flag": "🇦🇲",
        "demonym": "Armenian",
        "timezones": ["UTC+04:00"],
    },
    {
        "name": "Australia",
        "official_name": "Commonwealth of Australia",
        "cca2": "AU",
        "cca3": "AUS",
        "capital": "Canberra",
        "region": "Oceania",
        "subregion": "Australia and New Zealand",
        "population": 25687041,
        "area_sq_km": 7692024,
        "currencies": {"AUD": {"name": "Australian dollar", "symbol": "$"}},
        "languages": {"eng": "English"},
        "borders": [],
        "flag": "🇦🇺",
        "demonym": "Australian",
        "timezones": ["UTC+08:00", "UTC+09:30", "UTC+10:00"],
    },
    {
        "name": "Austria",
        "official_name": "Republic of Austria",
        "cca2": "AT",
        "cca3": "AUT",
        "capital": "Vienna",
        "region": "Europe",
        "subregion": "Central Europe",
        "population": 8917205,
        "area_sq_km": 83871,
        "currencies": {"EUR": {"name": "Euro", "symbol": "€"}},
        "languages": {"deu": "German"},
        "borders": ["CZE", "DEU", "HUN", "ITA", "LIE", "SVK", "SVN", "CHE"],
        "flag": "🇦🇹",
        "demonym": "Austrian",
        "timezones": ["UTC+01:00"],
    },
    {
        "name": "Azerbaijan",
        "official_name": "Republic of Azerbaijan",
        "cca2": "AZ",
        "cca3": "AZE",
        "capital": "Baku",
        "region": "Asia",
        "subregion": "Western Asia",
        "population": 10110116,
        "area_sq_km": 86600,
        "currencies": {"AZN": {"name": "Azerbaijani manat", "symbol": "₼"}},
        "languages": {"aze": "Azerbaijani"},
        "borders": ["ARM", "GEO", "IRN", "RUS", "TUR"],
        "flag": "🇦🇿",
        "demonym": "Azerbaijani",
        "timezones": ["UTC+04:00"],
    },
    {
        "name": "Bahamas",
        "official_name": "Commonwealth of the Bahamas",
        "cca2": "BS",
        "cca3": "BHS",
        "capital": "Nassau",
        "region": "Americas",
        "subregion": "Caribbean",
        "population": 393248,
        "area_sq_km": 13943,
        "currencies": {"BSD": {"name": "Bahamian dollar", "symbol": "$"}},
        "languages": {"eng": "English"},
        "borders": [],
        "flag": "🇧🇸",
        "demonym": "Bahamian",
        "timezones": ["UTC-05:00"],
    },
    {
        "name": "Bahrain",
        "official_name": "Kingdom of Bahrain",
        "cca2": "BH",
        "cca3": "BHR",
        "capital": "Manama",
        "region": "Asia",
        "subregion": "Western Asia",
        "population": 1701583,
        "area_sq_km": 765,
        "currencies": {"BHD": {"name": "Bahraini dinar", "symbol": ".د.ب"}},
        "languages": {"ara": "Arabic"},
        "borders": [],
        "flag": "🇧🇭",
        "demonym": "Bahraini",
        "timezones": ["UTC+03:00"],
    },
    {
        "name": "Bangladesh",
        "official_name": "People's Republic of Bangladesh",
        "cca2": "BD",
        "cca3": "BGD",
        "capital": "Dhaka",
        "region": "Asia",
        "subregion": "Southern Asia",
        "population": 164689383,
        "area_sq_km": 147570,
        "currencies": {"BDT": {"name": "Bangladeshi taka", "symbol": "৳"}},
        "languages": {"ben": "Bengali"},
        "borders": ["MMR", "IND"],
        "flag": "🇧🇩",
        "demonym": "Bangladeshi",
        "timezones": ["UTC+06:00"],
    },
    {
        "name": "Barbados",
        "official_name": "Barbados",
        "cca2": "BB",
        "cca3": "BRB",
        "capital": "Bridgetown",
        "region": "Americas",
        "subregion": "Caribbean",
        "population": 287371,
        "area_sq_km": 430,
        "currencies": {"BBD": {"name": "Barbadian dollar", "symbol": "$"}},
        "languages": {"eng": "English"},
        "borders": [],
        "flag": "🇧🇧",
        "demonym": "Barbadian",
        "timezones": ["UTC-04:00"],
    },
    {
        "name": "Belarus",
        "official_name": "Republic of Belarus",
        "cca2": "BY",
        "cca3": "BLR",
        "capital": "Minsk",
        "region": "Europe",
        "subregion": "Eastern Europe",
        "population": 9398861,
        "area_sq_km": 207600,
        "currencies": {"BYN": {"name": "Belarusian ruble", "symbol": "Br"}},
        "languages": {"bel": "Belarusian", "rus": "Russian"},
        "borders": ["LVA", "LTU", "POL", "RUS", "UKR"],
        "flag": "🇧🇾",
        "demonym": "Belarusian",
        "timezones": ["UTC+03:00"],
    },
    {
        "name": "Belgium",
        "official_name": "Kingdom of Belgium",
        "cca2": "BE",
        "cca3": "BEL",
        "capital": "Brussels",
        "region": "Europe",
        "subregion": "Western Europe",
        "population": 11589623,
        "area_sq_km": 30528,
        "currencies": {"EUR": {"name": "Euro", "symbol": "€"}},
        "languages": {"nld": "Dutch", "fra": "French", "deu": "German"},
        "borders": ["FRA", "DEU", "LUX", "NLD"],
        "flag": "🇧🇪",
        "demonym": "Belgian",
        "timezones": ["UTC+01:00"],
    },
    {
        "name": "Belize",
        "official_name": "Belize",
        "cca2": "BZ",
        "cca3": "BLZ",
        "capital": "Belmopan",
        "region": "Americas",
        "subregion": "Central America",
        "population": 397621,
        "area_sq_km": 22966,
        "currencies": {"BZD": {"name": "Belize dollar", "symbol": "$"}},
        "languages": {"eng": "English", "spa": "Spanish"},
        "borders": ["GTM", "MEX"],
        "flag": "🇧🇿",
        "demonym": "Belizean",
        "timezones": ["UTC-06:00"],
    },
    {
        "name": "Benin",
        "official_name": "Republic of Benin",
        "cca2": "BJ",
        "cca3": "BEN",
        "capital": "Porto-Novo",
        "region": "Africa",
        "subregion": "Western Africa",
        "population": 12123198,
        "area_sq_km": 112622,
        "currencies": {"XOF": {"name": "West African CFA franc", "symbol": "Fr"}},
        "languages": {"fra": "French"},
        "borders": ["BFA", "NER", "NGA", "TGO"],
        "flag": "🇧🇯",
        "demonym": "Beninese",
        "timezones": ["UTC+01:00"],
    },
    {
        "name": "Bhutan",
        "official_name": "Kingdom of Bhutan",
        "cca2": "BT",
        "cca3": "BTN",
        "capital": "Thimphu",
        "region": "Asia",
        "subregion": "Southern Asia",
        "population": 771612,
        "area_sq_km": 38394,
        "currencies": {"BTN": {"name": "Bhutanese ngultrum", "symbol": "Nu."}, "INR": {"name": "Indian rupee", "symbol": "₹"}},
        "languages": {"dzo": "Dzongkha"},
        "borders": ["CHN", "IND"],
        "flag": "🇧🇹",
        "demonym": "Bhutanese",
        "timezones": ["UTC+06:00"],
    },
    {
        "name": "Bolivia",
        "official_name": "Plurinational State of Bolivia",
        "cca2": "BO",
        "cca3": "BOL",
        "capital": "Sucre",
        "region": "Americas",
        "subregion": "South America",
        "population": 11673029,
        "area_sq_km": 1098581,
        "currencies": {"BOB": {"name": "Bolivian boliviano", "symbol": "Bs."}},
        "languages": {"spa": "Spanish", "aym": "Aymara", "que": "Quechua"},
        "borders": ["ARG", "BRA", "CHL", "PRY", "PER"],
        "flag": "🇧🇴",
        "demonym": "Bolivian",
        "timezones": ["UTC-04:00"],
    },
    {
        "name": "Bosnia and Herzegovina",
        "official_name": "Bosnia and Herzegovina",
        "cca2": "BA",
        "cca3": "BIH",
        "capital": "Sarajevo",
        "region": "Europe",
        "subregion": "Southeast Europe",
        "population": 3280815,
        "area_sq_km": 51209,
        "currencies": {"BAM": {"name": "Convertible mark", "symbol": "KM"}},
        "languages": {"bos": "Bosnian", "hrv": "Croatian", "srp": "Serbian"},
        "borders": ["HRV", "MNE", "SRB"],
        "flag": "🇧🇦",
        "demonym": "Bosnian",
        "timezones": ["UTC+01:00"],
    },
    {
        "name": "Botswana",
        "official_name": "Republic of Botswana",
        "cca2": "BW",
        "cca3": "BWA",
        "capital": "Gaborone",
        "region": "Africa",
        "subregion": "Southern Africa",
        "population": 2351625,
        "area_sq_km": 581730,
        "currencies": {"BWP": {"name": "Botswana pula", "symbol": "P"}},
        "languages": {"eng": "English", "tsn": "Tswana"},
        "borders": ["NAM", "ZAF", "ZMB", "ZWE"],
        "flag": "🇧🇼",
        "demonym": "Motswana",
        "timezones": ["UTC+02:00"],
    },
    {
        "name": "Brazil",
        "official_name": "Federative Republic of Brazil",
        "cca2": "BR",
        "cca3": "BRA",
        "capital": "Brasília",
        "region": "Americas",
        "subregion": "South America",
        "population": 212559409,
        "area_sq_km": 8515767,
        "currencies": {"BRL": {"name": "Brazilian real", "symbol": "R$"}},
        "languages": {"por": "Portuguese"},
        "borders": ["ARG", "BOL", "COL", "GUF", "GUY", "PRY", "PER", "SUR", "URY", "VEN"],
        "flag": "🇧🇷",
        "demonym": "Brazilian",
        "timezones": ["UTC-05:00", "UTC-04:00", "UTC-03:00", "UTC-02:00"],
    },
    {
        "name": "Bulgaria",
        "official_name": "Republic of Bulgaria",
        "cca2": "BG",
        "cca3": "BGR",
        "capital": "Sofia",
        "region": "Europe",
        "subregion": "Southeast Europe",
        "population": 6927288,
        "area_sq_km": 110879,
        "currencies": {"BGN": {"name": "Bulgarian lev", "symbol": "лв"}},
        "languages": {"bul": "Bulgarian"},
        "borders": ["GRC", "MKD", "ROU", "SRB", "TUR"],
        "flag": "🇧🇬",
        "demonym": "Bulgarian",
        "timezones": ["UTC+02:00"],
    },
    {
        "name": "Canada",
        "official_name": "Canada",
        "cca2": "CA",
        "cca3": "CAN",
        "capital": "Ottawa",
        "region": "Americas",
        "subregion": "North America",
        "population": 38005238,
        "area_sq_km": 9984670,
        "currencies": {"CAD": {"name": "Canadian dollar", "symbol": "$"}},
        "languages": {"eng": "English", "fra": "French"},
        "borders": ["USA"],
        "flag": "🇨🇦",
        "demonym": "Canadian",
        "timezones": ["UTC-08:00", "UTC-07:00", "UTC-06:00", "UTC-05:00", "UTC-04:00", "UTC-03:30"],
    },
    {
        "name": "Chile",
        "official_name": "Republic of Chile",
        "cca2": "CL",
        "cca3": "CHL",
        "capital": "Santiago",
        "region": "Americas",
        "subregion": "South America",
        "population": 19116209,
        "area_sq_km": 756102,
        "currencies": {"CLP": {"name": "Chilean peso", "symbol": "$"}},
        "languages": {"spa": "Spanish"},
        "borders": ["ARG", "BOL", "PER"],
        "flag": "🇨🇱",
        "demonym": "Chilean",
        "timezones": ["UTC-06:00", "UTC-04:00"],
    },
    {
        "name": "China",
        "official_name": "People's Republic of China",
        "cca2": "CN",
        "cca3": "CHN",
        "capital": "Beijing",
        "region": "Asia",
        "subregion": "Eastern Asia",
        "population": 1402112000,
        "area_sq_km": 9706961,
        "currencies": {"CNY": {"name": "Chinese yuan", "symbol": "¥"}},
        "languages": {"zho": "Mandarin"},
        "borders": ["AFG", "BTN", "MMR", "HKG", "IND", "KAZ", "PRK", "KGZ", "LAO", "MAC", "MNG", "NPL", "PAK", "RUS", "TJK", "VNM"],
        "flag": "🇨🇳",
        "demonym": "Chinese",
        "timezones": ["UTC+08:00"],
    },
    {
        "name": "Colombia",
        "official_name": "Republic of Colombia",
        "cca2": "CO",
        "cca3": "COL",
        "capital": "Bogotá",
        "region": "Americas",
        "subregion": "South America",
        "population": 50882884,
        "area_sq_km": 1141748,
        "currencies": {"COP": {"name": "Colombian peso", "symbol": "$"}},
        "languages": {"spa": "Spanish"},
        "borders": ["BRA", "ECU", "PAN", "PER", "VEN"],
        "flag": "🇨🇴",
        "demonym": "Colombian",
        "timezones": ["UTC-05:00"],
    },
    {
        "name": "Costa Rica",
        "official_name": "Republic of Costa Rica",
        "cca2": "CR",
        "cca3": "CRI",
        "capital": "San José",
        "region": "Americas",
        "subregion": "Central America",
        "population": 5094114,
        "area_sq_km": 51100,
        "currencies": {"CRC": {"name": "Costa Rican colón", "symbol": "₡"}},
        "languages": {"spa": "Spanish"},
        "borders": ["NIC", "PAN"],
        "flag": "🇨🇷",
        "demonym": "Costa Rican",
        "timezones": ["UTC-06:00"],
    },
    {
        "name": "Croatia",
        "official_name": "Republic of Croatia",
        "cca2": "HR",
        "cca3": "HRV",
        "capital": "Zagreb",
        "region": "Europe",
        "subregion": "Southeast Europe",
        "population": 4047200,
        "area_sq_km": 56594,
        "currencies": {"EUR": {"name": "Euro", "symbol": "€"}},
        "languages": {"hrv": "Croatian"},
        "borders": ["BIH", "HUN", "MNE", "SRB", "SVN"],
        "flag": "🇭🇷",
        "demonym": "Croatian",
        "timezones": ["UTC+01:00"],
    },
    {
        "name": "Cuba",
        "official_name": "Republic of Cuba",
        "cca2": "CU",
        "cca3": "CUB",
        "capital": "Havana",
        "region": "Americas",
        "subregion": "Caribbean",
        "population": 11326616,
        "area_sq_km": 109884,
        "currencies": {"CUP": {"name": "Cuban peso", "symbol": "$"}},
        "languages": {"spa": "Spanish"},
        "borders": [],
        "flag": "🇨🇺",
        "demonym": "Cuban",
        "timezones": ["UTC-05:00"],
    },
    {
        "name": "Cyprus",
        "official_name": "Republic of Cyprus",
        "cca2": "CY",
        "cca3": "CYP",
        "capital": "Nicosia",
        "region": "Europe",
        "subregion": "Southern Europe",
        "population": 1207361,
        "area_sq_km": 9251,
        "currencies": {"EUR": {"name": "Euro", "symbol": "€"}},
        "languages": {"ell": "Greek", "tur": "Turkish"},
        "borders": ["GBR"],
        "flag": "🇨🇾",
        "demonym": "Cypriot",
        "timezones": ["UTC+02:00"],
    },
    {
        "name": "Czech Republic",
        "official_name": "Czech Republic",
        "cca2": "CZ",
        "cca3": "CZE",
        "capital": "Prague",
        "region": "Europe",
        "subregion": "Central Europe",
        "population": 10698896,
        "area_sq_km": 78865,
        "currencies": {"CZK": {"name": "Czech koruna", "symbol": "Kč"}},
        "languages": {"ces": "Czech"},
        "borders": ["AUT", "DEU", "POL", "SVK"],
        "flag": "🇨🇿",
        "demonym": "Czech",
        "timezones": ["UTC+01:00"],
    },
    {
        "name": "Denmark",
        "official_name": "Kingdom of Denmark",
        "cca2": "DK",
        "cca3": "DNK",
        "capital": "Copenhagen",
        "region": "Europe",
        "subregion": "Northern Europe",
        "population": 5831404,
        "area_sq_km": 43094,
        "currencies": {"DKK": {"name": "Danish krone", "symbol": "kr"}},
        "languages": {"dan": "Danish"},
        "borders": ["DEU"],
        "flag": "🇩🇰",
        "demonym": "Danish",
        "timezones": ["UTC+01:00"],
    },
    {
        "name": "Egypt",
        "official_name": "Arab Republic of Egypt",
        "cca2": "EG",
        "cca3": "EGY",
        "capital": "Cairo",
        "region": "Africa",
        "subregion": "Northern Africa",
        "population": 102334403,
        "area_sq_km": 1002450,
        "currencies": {"EGP": {"name": "Egyptian pound", "symbol": "£"}},
        "languages": {"ara": "Arabic"},
        "borders": ["ISR", "LBY", "PSE", "SDN"],
        "flag": "🇪🇬",
        "demonym": "Egyptian",
        "timezones": ["UTC+02:00"],
    },
    {
        "name": "Estonia",
        "official_name": "Republic of Estonia",
        "cca2": "EE",
        "cca3": "EST",
        "capital": "Tallinn",
        "region": "Europe",
        "subregion": "Northern Europe",
        "population": 1331057,
        "area_sq_km": 45227,
        "currencies": {"EUR": {"name": "Euro", "symbol": "€"}},
        "languages": {"est": "Estonian"},
        "borders": ["LVA", "RUS"],
        "flag": "🇪🇪",
        "demonym": "Estonian",
        "timezones": ["UTC+02:00"],
    },
    {
        "name": "Ethiopia",
        "official_name": "Federal Democratic Republic of Ethiopia",
        "cca2": "ET",
        "cca3": "ETH",
        "capital": "Addis Ababa",
        "region": "Africa",
        "subregion": "Eastern Africa",
        "population": 114963583,
        "area_sq_km": 1104300,
        "currencies": {"ETB": {"name": "Ethiopian birr", "symbol": "Br"}},
        "languages": {"amh": "Amharic"},
        "borders": ["DJI", "ERI", "KEN", "SOM", "SSD", "SDN"],
        "flag": "🇪🇹",
        "demonym": "Ethiopian",
        "timezones": ["UTC+03:00"],
    },
    {
        "name": "Finland",
        "official_name": "Republic of Finland",
        "cca2": "FI",
        "cca3": "FIN",
        "capital": "Helsinki",
        "region": "Europe",
        "subregion": "Northern Europe",
        "population": 5530719,
        "area_sq_km": 338424,
        "currencies": {"EUR": {"name": "Euro", "symbol": "€"}},
        "languages": {"fin": "Finnish", "swe": "Swedish"},
        "borders": ["NOR", "SWE", "RUS"],
        "flag": "🇫🇮",
        "demonym": "Finnish",
        "timezones": ["UTC+02:00"],
    },
    {
        "name": "France",
        "official_name": "French Republic",
        "cca2": "FR",
        "cca3": "FRA",
        "capital": "Paris",
        "region": "Europe",
        "subregion": "Western Europe",
        "population": 67391582,
        "area_sq_km": 551695,
        "currencies": {"EUR": {"name": "Euro", "symbol": "€"}},
        "languages": {"fra": "French"},
        "borders": ["AND", "BEL", "DEU", "ITA", "LUX", "MCO", "ESP", "CHE"],
        "flag": "🇫🇷",
        "demonym": "French",
        "timezones": ["UTC+01:00"],
    },
    {
        "name": "Germany",
        "official_name": "Federal Republic of Germany",
        "cca2": "DE",
        "cca3": "DEU",
        "capital": "Berlin",
        "region": "Europe",
        "subregion": "Western Europe",
        "population": 83240525,
        "area_sq_km": 357114,
        "currencies": {"EUR": {"name": "Euro", "symbol": "€"}},
        "languages": {"deu": "German"},
        "borders": ["AUT", "BEL", "CZE", "DNK", "FRA", "LUX", "NLD", "POL", "CHE"],
        "flag": "🇩🇪",
        "demonym": "German",
        "timezones": ["UTC+01:00"],
    },
    {
        "name": "Ghana",
        "official_name": "Republic of Ghana",
        "cca2": "GH",
        "cca3": "GHA",
        "capital": "Accra",
        "region": "Africa",
        "subregion": "Western Africa",
        "population": 31072945,
        "area_sq_km": 238533,
        "currencies": {"GHS": {"name": "Ghanaian cedi", "symbol": "₵"}},
        "languages": {"eng": "English"},
        "borders": ["BFA", "CIV", "TGO"],
        "flag": "🇬🇭",
        "demonym": "Ghanaian",
        "timezones": ["UTC+00:00"],
    },
    {
        "name": "Greece",
        "official_name": "Hellenic Republic",
        "cca2": "GR",
        "cca3": "GRC",
        "capital": "Athens",
        "region": "Europe",
        "subregion": "Southern Europe",
        "population": 10715549,
        "area_sq_km": 131990,
        "currencies": {"EUR": {"name": "Euro", "symbol": "€"}},
        "languages": {"ell": "Greek"},
        "borders": ["ALB", "BGR", "MKD", "TUR"],
        "flag": "🇬🇷",
        "demonym": "Greek",
        "timezones": ["UTC+02:00"],
    },
    {
        "name": "Hungary",
        "official_name": "Hungary",
        "cca2": "HU",
        "cca3": "HUN",
        "capital": "Budapest",
        "region": "Europe",
        "subregion": "Central Europe",
        "population": 9749763,
        "area_sq_km": 93028,
        "currencies": {"HUF": {"name": "Hungarian forint", "symbol": "Ft"}},
        "languages": {"hun": "Hungarian"},
        "borders": ["AUT", "HRV", "ROU", "SRB", "SVK", "SVN", "UKR"],
        "flag": "🇭🇺",
        "demonym": "Hungarian",
        "timezones": ["UTC+01:00"],
    },
    {
        "name": "Iceland",
        "official_name": "Iceland",
        "cca2": "IS",
        "cca3": "ISL",
        "capital": "Reykjavik",
        "region": "Europe",
        "subregion": "Northern Europe",
        "population": 366425,
        "area_sq_km": 103000,
        "currencies": {"ISK": {"name": "Icelandic króna", "symbol": "kr"}},
        "languages": {"isl": "Icelandic"},
        "borders": [],
        "flag": "🇮🇸",
        "demonym": "Icelander",
        "timezones": ["UTC+00:00"],
    },
    {
        "name": "India",
        "official_name": "Republic of India",
        "cca2": "IN",
        "cca3": "IND",
        "capital": "New Delhi",
        "region": "Asia",
        "subregion": "Southern Asia",
        "population": 1380004385,
        "area_sq_km": 3287590,
        "currencies": {"INR": {"name": "Indian rupee", "symbol": "₹"}},
        "languages": {"hin": "Hindi", "eng": "English"},
        "borders": ["BGD", "BTN", "MMR", "CHN", "NPL", "PAK"],
        "flag": "🇮🇳",
        "demonym": "Indian",
        "timezones": ["UTC+05:30"],
    },
    {
        "name": "Indonesia",
        "official_name": "Republic of Indonesia",
        "cca2": "ID",
        "cca3": "IDN",
        "capital": "Jakarta",
        "region": "Asia",
        "subregion": "South-Eastern Asia",
        "population": 273523621,
        "area_sq_km": 1904569,
        "currencies": {"IDR": {"name": "Indonesian rupiah", "symbol": "Rp"}},
        "languages": {"ind": "Indonesian"},
        "borders": ["TLS", "MYS", "PNG"],
        "flag": "🇮🇩",
        "demonym": "Indonesian",
        "timezones": ["UTC+07:00", "UTC+08:00", "UTC+09:00"],
    },
    {
        "name": "Ireland",
        "official_name": "Republic of Ireland",
        "cca2": "IE",
        "cca3": "IRL",
        "capital": "Dublin",
        "region": "Europe",
        "subregion": "Northern Europe",
        "population": 4994724,
        "area_sq_km": 70273,
        "currencies": {"EUR": {"name": "Euro", "symbol": "€"}},
        "languages": {"gle": "Irish", "eng": "English"},
        "borders": ["GBR"],
        "flag": "🇮🇪",
        "demonym": "Irish",
        "timezones": ["UTC+00:00"],
    },
    {
        "name": "Israel",
        "official_name": "State of Israel",
        "cca2": "IL",
        "cca3": "ISR",
        "capital": "Jerusalem",
        "region": "Asia",
        "subregion": "Western Asia",
        "population": 9216900,
        "area_sq_km": 20770,
        "currencies": {"ILS": {"name": "Israeli new shekel", "symbol": "₪"}},
        "languages": {"heb": "Hebrew", "ara": "Arabic"},
        "borders": ["EGY", "JOR", "LBN", "SYR"],
        "flag": "🇮🇱",
        "demonym": "Israeli",
        "timezones": ["UTC+02:00"],
    },
    {
        "name": "Italy",
        "official_name": "Italian Republic",
        "cca2": "IT",
        "cca3": "ITA",
        "capital": "Rome",
        "region": "Europe",
        "subregion": "Southern Europe",
        "population": 59554023,
        "area_sq_km": 301336,
        "currencies": {"EUR": {"name": "Euro", "symbol": "€"}},
        "languages": {"ita": "Italian"},
        "borders": ["AUT", "FRA", "SMR", "SVN", "CHE", "VAT"],
        "flag": "🇮🇹",
        "demonym": "Italian",
        "timezones": ["UTC+01:00"],
    },
    {
        "name": "Japan",
        "official_name": "Japan",
        "cca2": "JP",
        "cca3": "JPN",
        "capital": "Tokyo",
        "region": "Asia",
        "subregion": "Eastern Asia",
        "population": 125836021,
        "area_sq_km": 377930,
        "currencies": {"JPY": {"name": "Japanese yen", "symbol": "¥"}},
        "languages": {"jpn": "Japanese"},
        "borders": [],
        "flag": "🇯🇵",
        "demonym": "Japanese",
        "timezones": ["UTC+09:00"],
    },
    {
        "name": "Kenya",
        "official_name": "Republic of Kenya",
        "cca2": "KE",
        "cca3": "KEN",
        "capital": "Nairobi",
        "region": "Africa",
        "subregion": "Eastern Africa",
        "population": 53771300,
        "area_sq_km": 580367,
        "currencies": {"KES": {"name": "Kenyan shilling", "symbol": "Sh"}},
        "languages": {"eng": "English", "swa": "Swahili"},
        "borders": ["ETH", "SOM", "SSD", "TZA", "UGA"],
        "flag": "🇰🇪",
        "demonym": "Kenyan",
        "timezones": ["UTC+03:00"],
    },
    {
        "name": "Mexico",
        "official_name": "United Mexican States",
        "cca2": "MX",
        "cca3": "MEX",
        "capital": "Mexico City",
        "region": "Americas",
        "subregion": "North America",
        "population": 128932753,
        "area_sq_km": 1964375,
        "currencies": {"MXN": {"name": "Mexican peso", "symbol": "$"}},
        "languages": {"spa": "Spanish"},
        "borders": ["BLZ", "GTM", "USA"],
        "flag": "🇲🇽",
        "demonym": "Mexican",
        "timezones": ["UTC-08:00", "UTC-07:00", "UTC-06:00"],
    },
    {
        "name": "Netherlands",
        "official_name": "Kingdom of the Netherlands",
        "cca2": "NL",
        "cca3": "NLD",
        "capital": "Amsterdam",
        "region": "Europe",
        "subregion": "Western Europe",
        "population": 17441139,
        "area_sq_km": 41850,
        "currencies": {"EUR": {"name": "Euro", "symbol": "€"}},
        "languages": {"nld": "Dutch"},
        "borders": ["BEL", "DEU"],
        "flag": "🇳🇱",
        "demonym": "Dutch",
        "timezones": ["UTC+01:00"],
    },
    {
        "name": "New Zealand",
        "official_name": "New Zealand",
        "cca2": "NZ",
        "cca3": "NZL",
        "capital": "Wellington",
        "region": "Oceania",
        "subregion": "Australia and New Zealand",
        "population": 5084300,
        "area_sq_km": 270467,
        "currencies": {"NZD": {"name": "New Zealand dollar", "symbol": "$"}},
        "languages": {"eng": "English", "mri": "Māori"},
        "borders": [],
        "flag": "🇳🇿",
        "demonym": "New Zealander",
        "timezones": ["UTC+12:00", "UTC+12:45"],
    },
    {
        "name": "Nigeria",
        "official_name": "Federal Republic of Nigeria",
        "cca2": "NG",
        "cca3": "NGA",
        "capital": "Abuja",
        "region": "Africa",
        "subregion": "Western Africa",
        "population": 206139587,
        "area_sq_km": 923768,
        "currencies": {"NGN": {"name": "Nigerian naira", "symbol": "₦"}},
        "languages": {"eng": "English"},
        "borders": ["BEN", "CMR", "TCD", "NER"],
        "flag": "🇳🇬",
        "demonym": "Nigerian",
        "timezones": ["UTC+01:00"],
    },
    {
        "name": "Norway",
        "official_name": "Kingdom of Norway",
        "cca2": "NO",
        "cca3": "NOR",
        "capital": "Oslo",
        "region": "Europe",
        "subregion": "Northern Europe",
        "population": 5379475,
        "area_sq_km": 323802,
        "currencies": {"NOK": {"name": "Norwegian krone", "symbol": "kr"}},
        "languages": {"nor": "Norwegian"},
        "borders": ["FIN", "SWE", "RUS"],
        "flag": "🇳🇴",
        "demonym": "Norwegian",
        "timezones": ["UTC+01:00"],
    },
    {
        "name": "Poland",
        "official_name": "Republic of Poland",
        "cca2": "PL",
        "cca3": "POL",
        "capital": "Warsaw",
        "region": "Europe",
        "subregion": "Central Europe",
        "population": 37950802,
        "area_sq_km": 312679,
        "currencies": {"PLN": {"name": "Polish złoty", "symbol": "zł"}},
        "languages": {"pol": "Polish"},
        "borders": ["BLR", "CZE", "DEU", "LTU", "RUS", "SVK", "UKR"],
        "flag": "🇵🇱",
        "demonym": "Polish",
        "timezones": ["UTC+01:00"],
    },
    {
        "name": "Portugal",
        "official_name": "Portuguese Republic",
        "cca2": "PT",
        "cca3": "PRT",
        "capital": "Lisbon",
        "region": "Europe",
        "subregion": "Southern Europe",
        "population": 10305564,
        "area_sq_km": 92090,
        "currencies": {"EUR": {"name": "Euro", "symbol": "€"}},
        "languages": {"por": "Portuguese"},
        "borders": ["ESP"],
        "flag": "🇵🇹",
        "demonym": "Portuguese",
        "timezones": ["UTC-01:00", "UTC+00:00"],
    },
    {
        "name": "Romania",
        "official_name": "Romania",
        "cca2": "RO",
        "cca3": "ROU",
        "capital": "Bucharest",
        "region": "Europe",
        "subregion": "Southeast Europe",
        "population": 19286123,
        "area_sq_km": 238391,
        "currencies": {"RON": {"name": "Romanian leu", "symbol": "lei"}},
        "languages": {"ron": "Romanian"},
        "borders": ["BGR", "HUN", "MDA", "SRB", "UKR"],
        "flag": "🇷🇴",
        "demonym": "Romanian",
        "timezones": ["UTC+02:00"],
    },
    {
        "name": "Saudi Arabia",
        "official_name": "Kingdom of Saudi Arabia",
        "cca2": "SA",
        "cca3": "SAU",
        "capital": "Riyadh",
        "region": "Asia",
        "subregion": "Western Asia",
        "population": 34813867,
        "area_sq_km": 2149690,
        "currencies": {"SAR": {"name": "Saudi riyal", "symbol": "﷼"}},
        "languages": {"ara": "Arabic"},
        "borders": ["IRQ", "JOR", "KWT", "OMN", "QAT", "ARE", "YEM"],
        "flag": "🇸🇦",
        "demonym": "Saudi",
        "timezones": ["UTC+03:00"],
    },
    {
        "name": "South Africa",
        "official_name": "Republic of South Africa",
        "cca2": "ZA",
        "cca3": "ZAF",
        "capital": "Pretoria",
        "region": "Africa",
        "subregion": "Southern Africa",
        "population": 59308690,
        "area_sq_km": 1221037,
        "currencies": {"ZAR": {"name": "South African rand", "symbol": "R"}},
        "languages": {"afr": "Afrikaans", "eng": "English", "zul": "Zulu", "xho": "Xhosa"},
        "borders": ["BWA", "LSO", "MOZ", "NAM", "SWZ", "ZWE"],
        "flag": "🇿🇦",
        "demonym": "South African",
        "timezones": ["UTC+02:00"],
    },
    {
        "name": "South Korea",
        "official_name": "Republic of Korea",
        "cca2": "KR",
        "cca3": "KOR",
        "capital": "Seoul",
        "region": "Asia",
        "subregion": "Eastern Asia",
        "population": 51780579,
        "area_sq_km": 100210,
        "currencies": {"KRW": {"name": "South Korean won", "symbol": "₩"}},
        "languages": {"kor": "Korean"},
        "borders": ["PRK"],
        "flag": "🇰🇷",
        "demonym": "South Korean",
        "timezones": ["UTC+09:00"],
    },
    {
        "name": "Spain",
        "official_name": "Kingdom of Spain",
        "cca2": "ES",
        "cca3": "ESP",
        "capital": "Madrid",
        "region": "Europe",
        "subregion": "Southern Europe",
        "population": 47351567,
        "area_sq_km": 505992,
        "currencies": {"EUR": {"name": "Euro", "symbol": "€"}},
        "languages": {"spa": "Spanish", "cat": "Catalan", "glg": "Galician", "eus": "Basque"},
        "borders": ["AND", "FRA", "GIB", "PRT", "MAR"],
        "flag": "🇪🇸",
        "demonym": "Spanish",
        "timezones": ["UTC+00:00", "UTC+01:00"],
    },
    {
        "name": "Sweden",
        "official_name": "Kingdom of Sweden",
        "cca2": "SE",
        "cca3": "SWE",
        "capital": "Stockholm",
        "region": "Europe",
        "subregion": "Northern Europe",
        "population": 10353442,
        "area_sq_km": 450295,
        "currencies": {"SEK": {"name": "Swedish krona", "symbol": "kr"}},
        "languages": {"swe": "Swedish"},
        "borders": ["FIN", "NOR"],
        "flag": "🇸🇪",
        "demonym": "Swedish",
        "timezones": ["UTC+01:00"],
    },
    {
        "name": "Switzerland",
        "official_name": "Swiss Confederation",
        "cca2": "CH",
        "cca3": "CHE",
        "capital": "Bern",
        "region": "Europe",
        "subregion": "Central Europe",
        "population": 8654622,
        "area_sq_km": 41284,
        "currencies": {"CHF": {"name": "Swiss franc", "symbol": "CHF"}},
        "languages": {"deu": "German", "fra": "French", "ita": "Italian", "roh": "Romansh"},
        "borders": ["AUT", "FRA", "ITA", "LIE", "DEU"],
        "flag": "🇨🇭",
        "demonym": "Swiss",
        "timezones": ["UTC+01:00"],
    },
    {
        "name": "Turkey",
        "official_name": "Republic of Turkey",
        "cca2": "TR",
        "cca3": "TUR",
        "capital": "Ankara",
        "region": "Asia",
        "subregion": "Western Asia",
        "population": 84339067,
        "area_sq_km": 783562,
        "currencies": {"TRY": {"name": "Turkish lira", "symbol": "₺"}},
        "languages": {"tur": "Turkish"},
        "borders": ["ARM", "AZE", "BGR", "GEO", "GRC", "IRN", "IRQ", "SYR"],
        "flag": "🇹🇷",
        "demonym": "Turkish",
        "timezones": ["UTC+03:00"],
    },
    {
        "name": "Ukraine",
        "official_name": "Ukraine",
        "cca2": "UA",
        "cca3": "UKR",
        "capital": "Kyiv",
        "region": "Europe",
        "subregion": "Eastern Europe",
        "population": 44134693,
        "area_sq_km": 603550,
        "currencies": {"UAH": {"name": "Ukrainian hryvnia", "symbol": "₴"}},
        "languages": {"ukr": "Ukrainian"},
        "borders": ["BLR", "HUN", "MDA", "POL", "ROU", "RUS", "SVK"],
        "flag": "🇺🇦",
        "demonym": "Ukrainian",
        "timezones": ["UTC+02:00"],
    },
    {
        "name": "United Arab Emirates",
        "official_name": "United Arab Emirates",
        "cca2": "AE",
        "cca3": "ARE",
        "capital": "Abu Dhabi",
        "region": "Asia",
        "subregion": "Western Asia",
        "population": 9890400,
        "area_sq_km": 83600,
        "currencies": {"AED": {"name": "United Arab Emirates dirham", "symbol": "د.إ"}},
        "languages": {"ara": "Arabic"},
        "borders": ["OMN", "SAU"],
        "flag": "🇦🇪",
        "demonym": "Emirati",
        "timezones": ["UTC+04:00"],
    },
    {
        "name": "United Kingdom",
        "official_name": "United Kingdom of Great Britain and Northern Ireland",
        "cca2": "GB",
        "cca3": "GBR",
        "capital": "London",
        "region": "Europe",
        "subregion": "Northern Europe",
        "population": 67215293,
        "area_sq_km": 242900,
        "currencies": {"GBP": {"name": "British pound", "symbol": "£"}},
        "languages": {"eng": "English"},
        "borders": ["IRL"],
        "flag": "🇬🇧",
        "demonym": "British",
        "timezones": ["UTC+00:00"],
    },
    {
        "name": "United States",
        "official_name": "United States of America",
        "cca2": "US",
        "cca3": "USA",
        "capital": "Washington, D.C.",
        "region": "Americas",
        "subregion": "North America",
        "population": 329484123,
        "area_sq_km": 9372610,
        "currencies": {"USD": {"name": "United States dollar", "symbol": "$"}},
        "languages": {"eng": "English"},
        "borders": ["CAN", "MEX"],
        "flag": "🇺🇸",
        "demonym": "American",
        "timezones": ["UTC-10:00", "UTC-09:00", "UTC-08:00", "UTC-07:00", "UTC-06:00", "UTC-05:00"],
    },
]

# Alias map for standard nicknames and variants
ALIASES: Dict[str, str] = {
    "us": "USA",
    "usa": "USA",
    "america": "USA",
    "united states": "USA",
    "united states of america": "USA",
    "uk": "GBR",
    "britain": "GBR",
    "great britain": "GBR",
    "england": "GBR",
    "uae": "ARE",
    "emirates": "ARE",
    "south korea": "KOR",
    "korea": "KOR",
    "czechia": "CZE",
    "dutch": "NLD",
    "holland": "NLD",
    "russia": "RUS",
}

# Index lookups
BY_CCA3: Dict[str, Dict[str, Any]] = {c["cca3"]: c for c in COUNTRIES_DB}
BY_CCA2: Dict[str, Dict[str, Any]] = {c["cca2"]: c for c in COUNTRIES_DB}
BY_NAME: Dict[str, Dict[str, Any]] = {c["name"].lower(): c for c in COUNTRIES_DB}


def find_country(query: str) -> Optional[Dict[str, Any]]:
    """Resolve a country by name, alias, CCA2, or CCA3 code."""
    cleaned = " ".join(query.strip().lower().split())
    if not cleaned:
        return None

    # Check alias
    if cleaned in ALIASES:
        cca3 = ALIASES[cleaned]
        return BY_CCA3.get(cca3)

    # Check exact CCA3 (upper)
    upper_query = cleaned.upper()
    if upper_query in BY_CCA3:
        return BY_CCA3[upper_query]

    # Check exact CCA2 (upper)
    if upper_query in BY_CCA2:
        return BY_CCA2[upper_query]

    # Check exact name
    if cleaned in BY_NAME:
        return BY_NAME[cleaned]

    # Substring match on country name or official name
    for c in COUNTRIES_DB:
        if cleaned in c["name"].lower() or cleaned in c["official_name"].lower():
            return c

    return None


def search_by_capital_city(capital_query: str) -> List[Dict[str, Any]]:
    """Search countries matching a capital city name."""
    cleaned = capital_query.strip().lower()
    if not cleaned:
        return []

    results = []
    for c in COUNTRIES_DB:
        cap = c.get("capital", "").lower()
        if cleaned in cap:
            results.append(c)
    return results


def search_by_currency_code(currency_query: str) -> List[Dict[str, Any]]:
    """Find countries using a currency code or currency name."""
    cleaned = currency_query.strip().lower()
    results = []
    for c in COUNTRIES_DB:
        for code, details in c.get("currencies", {}).items():
            if cleaned == code.lower() or cleaned in details.get("name", "").lower():
                results.append(c)
                break
    return results


def search_by_language_name(lang_query: str) -> List[Dict[str, Any]]:
    """Find countries speaking a given language."""
    cleaned = lang_query.strip().lower()
    results = []
    for c in COUNTRIES_DB:
        for code, lang in c.get("languages", {}).items():
            if cleaned == code.lower() or cleaned in lang.lower():
                results.append(c)
                break
    return results
