// Generated by backend/scripts/generate_desktop_gemini_attribution.py from backend/config/desktop_gemini_attribution.json.
// Do not edit by hand.

export const GeminiLane = {
  taskExtraction: 'task_extraction',
  focus: 'focus',
  dictation: 'dictation',
  suggestions: 'suggestions',
  liveNotes: 'live_notes',
  screenSynthesis: 'screen_synthesis',
  memory: 'memory',
  insight: 'insight',
  goals: 'goals',
  taskDedup: 'task_dedup',
  taskPrioritization: 'task_prioritization',
  homeSuggestions: 'home_suggestions',
  embedding: 'embedding'
} as const
export type GeminiLane = (typeof GeminiLane)[keyof typeof GeminiLane]

export const GEMINI_WORKLOADS = ['interactive', 'extraction', 'maintenance'] as const
export type GeminiWorkload = (typeof GEMINI_WORKLOADS)[number]
