"""Backward-compatible shim — implementation lives in ``utils.llm.promotion_proposals`` (WS-G11)."""

# pyright: reportPrivateUsage=false

from utils.llm.promotion_proposals import (
    PROMOTION_RUBRIC,
    CandidateOutcome,
    CandidateOutcomeStatus,
    DurableMemoryPatchProposal,
    DurableMemoryPatchProposals,
    DurableMemorySynthesisResult,
    PromotionProposal,
    PromotionProposals,
    PromotionSynthesisResult,
    SynthesisStatus,
    _CLIENT_IMPORT_ERROR,
    _CONTROL_FIELDS,
    _QUOTE_WRAPPER_RE,
    _candidate_outcome_for_patch,
    _canonical_json,
    _content_from_response,
    _is_quote_wrapper,
    _logical_patch_payload,
    _packet_evidence_ids,
    _proposal_to_patch,
    _raw_payload_from_response_text,
    _retrieved_memory_ids,
    _valid_non_quote_wrapper_patches,
    _with_deterministic_patch_ids,
    _with_production_safety_guards,
    _with_server_control_ids,
    durable_memory_patch_prompt,
    get_llm,
    logger,
    promotion_proposal_prompt,
    synthesize_durable_memory_patch_result,
    synthesize_durable_memory_patches,
)

__all__ = [
    "PROMOTION_RUBRIC",
    "CandidateOutcome",
    "CandidateOutcomeStatus",
    "DurableMemoryPatchProposal",
    "DurableMemoryPatchProposals",
    "DurableMemorySynthesisResult",
    "PromotionProposal",
    "PromotionProposals",
    "PromotionSynthesisResult",
    "SynthesisStatus",
    "_CLIENT_IMPORT_ERROR",
    "_CONTROL_FIELDS",
    "_QUOTE_WRAPPER_RE",
    "_candidate_outcome_for_patch",
    "_canonical_json",
    "_content_from_response",
    "_is_quote_wrapper",
    "_logical_patch_payload",
    "_packet_evidence_ids",
    "_proposal_to_patch",
    "_raw_payload_from_response_text",
    "_retrieved_memory_ids",
    "_valid_non_quote_wrapper_patches",
    "_with_deterministic_patch_ids",
    "_with_production_safety_guards",
    "_with_server_control_ids",
    "durable_memory_patch_prompt",
    "get_llm",
    "logger",
    "promotion_proposal_prompt",
    "synthesize_durable_memory_patch_result",
    "synthesize_durable_memory_patches",
]
