apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Chart.Name }}-store
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.gke.projectID }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.gke.clusterLocation }}
          clusterName: {{ .Values.gke.clusterName }}
          serviceAccountRef:
            name: {{ .Values.serviceAccount.name }}
