"""Canonical alias module for ``utils.memory.v17_default_read_rollout`` (WS-G).

New canonical-path code may import from here; the V17 module name remains valid
until a later rename wave. No behavior change — re-exports only.
"""

from utils.memory.v17_default_read_rollout import (
    DEFAULT_READ_OBSERVABILITY_CONSUMERS,
    SUPPORTED_DEFAULT_READ_CONSUMERS,
    V17DefaultReadRolloutDecision,
    V17GlobalReadGateDecision,
    V17LegacyMemoryWriteGuardDecision,
    V17ReadDecision,
    V17WriteConvergencePolicy,
    V17_DEFAULT_READ_ROLLOUT_METRIC_NAME,
    V17_DEFAULT_READ_ROLLOUT_SCHEMA_VERSION,
    V17_DEFAULT_READ_ROLLOUT_TIMEOUT_SECONDS,
    V17_GLOBAL_READ_GATE_PATH,
    V17_WRITE_CONVERGENCE_GATE_PATH,
    assert_legacy_memory_write_allowed_for_default_read_decision,
    build_v17_default_read_rollout_audit_event,
    build_v17_default_read_rollout_audit_events,
    build_v17_default_read_rollout_decision_counters,
    build_v17_default_read_rollout_observability,
    build_v17_default_read_rollout_observability_report,
    disabled_v17_default_read_rollout_decision,
    legacy_safe_v17_default_read_rollout_decision,
    normalize_v17_archive_read_rollout_decision,
    normalize_v17_default_read_rollout_decision,
    normalize_v17_global_read_gate,
    normalize_v17_write_convergence_gate,
    read_v17_archive_read_rollout,
    read_v17_default_read_rollout,
    read_v17_default_read_rollout_decisions,
    read_v17_global_read_gate,
    read_v17_rollout_state_doc,
    read_v17_write_convergence_gate,
    render_v17_default_read_rollout_metrics,
)

__all__ = [
    "DEFAULT_READ_OBSERVABILITY_CONSUMERS",
    "SUPPORTED_DEFAULT_READ_CONSUMERS",
    "V17DefaultReadRolloutDecision",
    "V17GlobalReadGateDecision",
    "V17LegacyMemoryWriteGuardDecision",
    "V17ReadDecision",
    "V17WriteConvergencePolicy",
    "V17_DEFAULT_READ_ROLLOUT_METRIC_NAME",
    "V17_DEFAULT_READ_ROLLOUT_SCHEMA_VERSION",
    "V17_DEFAULT_READ_ROLLOUT_TIMEOUT_SECONDS",
    "V17_GLOBAL_READ_GATE_PATH",
    "V17_WRITE_CONVERGENCE_GATE_PATH",
    "assert_legacy_memory_write_allowed_for_default_read_decision",
    "build_v17_default_read_rollout_audit_event",
    "build_v17_default_read_rollout_audit_events",
    "build_v17_default_read_rollout_decision_counters",
    "build_v17_default_read_rollout_observability",
    "build_v17_default_read_rollout_observability_report",
    "disabled_v17_default_read_rollout_decision",
    "legacy_safe_v17_default_read_rollout_decision",
    "normalize_v17_archive_read_rollout_decision",
    "normalize_v17_default_read_rollout_decision",
    "normalize_v17_global_read_gate",
    "normalize_v17_write_convergence_gate",
    "read_v17_archive_read_rollout",
    "read_v17_default_read_rollout",
    "read_v17_default_read_rollout_decisions",
    "read_v17_global_read_gate",
    "read_v17_rollout_state_doc",
    "read_v17_write_convergence_gate",
    "render_v17_default_read_rollout_metrics",
]
