"""Backward-compatible shim — implementation lives in ``utils.memory.v3_control_reader_contract`` (WS-G8b)."""

from utils.memory.v3_control_reader_contract import (
    decide_v17_v3_control_route,
    V17V3ControlDecisionReason,
    V17V3ControlReader,
    V17V3ControlReaderRequest,
    V17V3ControlReadResult,
    V17V3ControlRouteDecision,
    V17V3ControlRouteFamily,
    V17V3ControlState,
    V3ControlDecisionReason,
    V3ControlReader,
    V3ControlReaderRequest,
    V3ControlReadResult,
    V3ControlRouteDecision,
    V3ControlRouteFamily,
    V3ControlState,
    _decision,
    _fail_closed,
    _generation_is_stale,
    _legacy_primary,
)

__all__ = [
    "decide_v17_v3_control_route",
    "V17V3ControlDecisionReason",
    "V17V3ControlReader",
    "V17V3ControlReaderRequest",
    "V17V3ControlReadResult",
    "V17V3ControlRouteDecision",
    "V17V3ControlRouteFamily",
    "V17V3ControlState",
    "V3ControlDecisionReason",
    "V3ControlReader",
    "V3ControlReaderRequest",
    "V3ControlReadResult",
    "V3ControlRouteDecision",
    "V3ControlRouteFamily",
    "V3ControlState",
    "_decision",
    "_fail_closed",
    "_generation_is_stale",
    "_legacy_primary",
]
