"""Backward-compatible shim — implementation lives in ``utils.memory.v3_projection_reader_contract`` (WS-G8b)."""

from utils.memory.v3_projection_reader_contract import (
    V17_V3_COMPATIBILITY_PROJECTION_SCHEMA_VERSION,
    V17_V3_COMPATIBILITY_PROJECTION_SOURCE,
    V17_V3_COMPATIBILITY_PROJECTION_VERSION,
    V17V3ProjectionCursor,
    V17V3ProjectionFailureReason,
    V17V3ProjectionPage,
    V17V3ProjectionReadError,
    V17V3ProjectionReadRequest,
    V17V3ProjectionState,
    V3_COMPATIBILITY_PROJECTION_SCHEMA_VERSION,
    V3_COMPATIBILITY_PROJECTION_SOURCE,
    V3_COMPATIBILITY_PROJECTION_VERSION,
    V3ProjectionCursor,
    V3ProjectionFailureReason,
    V3ProjectionPage,
    V3ProjectionReadError,
    V3ProjectionReadRequest,
    V3ProjectionState,
)

__all__ = [
    "V17_V3_COMPATIBILITY_PROJECTION_SCHEMA_VERSION",
    "V17_V3_COMPATIBILITY_PROJECTION_SOURCE",
    "V17_V3_COMPATIBILITY_PROJECTION_VERSION",
    "V17V3ProjectionCursor",
    "V17V3ProjectionFailureReason",
    "V17V3ProjectionPage",
    "V17V3ProjectionReadError",
    "V17V3ProjectionReadRequest",
    "V17V3ProjectionState",
    "V3_COMPATIBILITY_PROJECTION_SCHEMA_VERSION",
    "V3_COMPATIBILITY_PROJECTION_SOURCE",
    "V3_COMPATIBILITY_PROJECTION_VERSION",
    "V3ProjectionCursor",
    "V3ProjectionFailureReason",
    "V3ProjectionPage",
    "V3ProjectionReadError",
    "V3ProjectionReadRequest",
    "V3ProjectionState",
]
