"""Backward-compatible shim — implementation lives in ``utils.memory.v3_control_state_adapter`` (WS-G8b)."""

from utils.memory.v3_control_state_adapter import (
    read_v17_global_read_gate,
    read_v17_rollout_state_doc,
    read_v17_v3_control,
    read_v17_write_convergence_gate,
    resolve_v17_v3_effective_mode,
    V17_DEFAULT_READ_ROLLOUT_SCHEMA_VERSION,
    V17_V3_DEFAULT_CONSUMER,
    V17Collections,
    V17ReadDecision,
    V17V3ControlDecisionReason,
    V17V3ControlReadResult,
    V17V3ControlState,
    V3_DEFAULT_CONSUMER,
    _consumer_grants,
    _missing_or_unsupported_schema,
    _mode,
    _MODE_RANK,
    _read_error_reason,
    _READ_ERROR_REASON_MAP,
    _rollout_state_from_data,
)

__all__ = [
    "read_v17_global_read_gate",
    "read_v17_rollout_state_doc",
    "read_v17_v3_control",
    "read_v17_write_convergence_gate",
    "resolve_v17_v3_effective_mode",
    "V17_DEFAULT_READ_ROLLOUT_SCHEMA_VERSION",
    "V17_V3_DEFAULT_CONSUMER",
    "V17Collections",
    "V17ReadDecision",
    "V17V3ControlDecisionReason",
    "V17V3ControlReadResult",
    "V17V3ControlState",
    "V3_DEFAULT_CONSUMER",
    "_consumer_grants",
    "_missing_or_unsupported_schema",
    "_mode",
    "_MODE_RANK",
    "_read_error_reason",
    "_READ_ERROR_REASON_MAP",
    "_rollout_state_from_data",
]
