"""Backward-compatible shim — implementation lives in ``utils.memory.v3_get_dependency_seam`` (WS-G8b)."""

from utils.memory.v3_get_dependency_seam import (
    DecisionKind,
    DependencyAdapter,
    DependencyStatus,
    LOW_CARDINALITY_DECISION_CODES,
    plan_v17_v3_get_dependency_chain,
    V17V3GetDependencyAdapters,
    V17V3GetDependencyChainResult,
    V17V3GetDependencyContext,
    V17V3GetDependencyDecision,
    V3GetDependencyAdapters,
    V3GetDependencyChainResult,
    V3GetDependencyContext,
    V3GetDependencyDecision,
    _assert_low_cardinality,
    _contract_violation_result,
    _decision_contract_valid,
    _logged_fields,
    _NON_ENROLLED_LEGACY_BOUNDARY,
    _normalize_adapter_decision,
    _result,
    _VALID_DECISION_KINDS,
)

__all__ = [
    "DecisionKind",
    "DependencyAdapter",
    "DependencyStatus",
    "LOW_CARDINALITY_DECISION_CODES",
    "plan_v17_v3_get_dependency_chain",
    "V17V3GetDependencyAdapters",
    "V17V3GetDependencyChainResult",
    "V17V3GetDependencyContext",
    "V17V3GetDependencyDecision",
    "V3GetDependencyAdapters",
    "V3GetDependencyChainResult",
    "V3GetDependencyContext",
    "V3GetDependencyDecision",
    "_assert_low_cardinality",
    "_contract_violation_result",
    "_decision_contract_valid",
    "_logged_fields",
    "_NON_ENROLLED_LEGACY_BOUNDARY",
    "_normalize_adapter_decision",
    "_result",
    "_VALID_DECISION_KINDS",
]
