"""Backward-compatible shim — implementation lives in ``utils.memory.v3_cursor`` (WS-G8b)."""

from utils.memory.v3_cursor import (
    create_v17_v3_cursor,
    parse_v17_v3_cursor,
    V17V3CursorClaims,
    V17V3CursorContext,
    V17V3CursorError,
    V17V3CursorPageRequest,
    V17V3Keyset,
    V3CursorClaims,
    V3CursorContext,
    V3CursorError,
    V3CursorPageRequest,
    V3Keyset,
    validate_v17_v3_cursor_request,
    _b64decode,
    _b64encode,
    _canonical_json,
    _CURSOR_PREFIX,
    _CURSOR_SCHEMA_VERSION,
    _DEFAULT_MAX_LIMIT,
    _KEYSET_ORDER,
    _LEGACY_FIRST_PAGE_OVERRIDE_LIMIT,
    _signature,
)

__all__ = [
    "create_v17_v3_cursor",
    "parse_v17_v3_cursor",
    "V17V3CursorClaims",
    "V17V3CursorContext",
    "V17V3CursorError",
    "V17V3CursorPageRequest",
    "V17V3Keyset",
    "V3CursorClaims",
    "V3CursorContext",
    "V3CursorError",
    "V3CursorPageRequest",
    "V3Keyset",
    "validate_v17_v3_cursor_request",
    "_b64decode",
    "_b64encode",
    "_canonical_json",
    "_CURSOR_PREFIX",
    "_CURSOR_SCHEMA_VERSION",
    "_DEFAULT_MAX_LIMIT",
    "_KEYSET_ORDER",
    "_LEGACY_FIRST_PAGE_OVERRIDE_LIMIT",
    "_signature",
]
