"""Backward-compatible shim — implementation lives in ``utils.memory.v3_canary_approval`` (WS-G8b)."""

from utils.memory.v3_canary_approval import (
    APPROVAL_STATUSES,
    build_v17_v3_canary_approval_telemetry_labels,
    CANARY_COHORTS,
    read_v17_v3_canary_approval_artifact_decision,
    ROUTE_SCOPE,
    SCHEMA_VERSION,
    V17V3CanaryApprovalArtifact,
    V17V3CanaryApprovalArtifactReader,
    V17V3CanaryApprovalDecision,
    V3CanaryApprovalArtifact,
    V3CanaryApprovalArtifactReader,
    V3CanaryApprovalDecision,
    validate_v17_v3_canary_approval_artifact,
    _APPROVAL_OWNERS,
    _blocked,
    _find_high_cardinality_or_sensitive_misuse,
    _MONITORING_GATE_IDS,
    _monitoring_gates_valid,
    _MONITORING_METRICS,
    _normalize_now,
    _parse_datetime,
    _ROLLBACK_OWNERS,
    _SENSITIVE_OR_HIGH_CARDINALITY_KEYS,
    _SENSITIVE_OR_HIGH_CARDINALITY_VALUE_MARKERS,
)

__all__ = [
    "APPROVAL_STATUSES",
    "build_v17_v3_canary_approval_telemetry_labels",
    "CANARY_COHORTS",
    "read_v17_v3_canary_approval_artifact_decision",
    "ROUTE_SCOPE",
    "SCHEMA_VERSION",
    "V17V3CanaryApprovalArtifact",
    "V17V3CanaryApprovalArtifactReader",
    "V17V3CanaryApprovalDecision",
    "V3CanaryApprovalArtifact",
    "V3CanaryApprovalArtifactReader",
    "V3CanaryApprovalDecision",
    "validate_v17_v3_canary_approval_artifact",
    "_APPROVAL_OWNERS",
    "_blocked",
    "_find_high_cardinality_or_sensitive_misuse",
    "_MONITORING_GATE_IDS",
    "_monitoring_gates_valid",
    "_MONITORING_METRICS",
    "_normalize_now",
    "_parse_datetime",
    "_ROLLBACK_OWNERS",
    "_SENSITIVE_OR_HIGH_CARDINALITY_KEYS",
    "_SENSITIVE_OR_HIGH_CARDINALITY_VALUE_MARKERS",
]
