"""Backward-compatible shim — implementation lives in ``utils.memory.v3_get_runtime_snapshot`` (WS-G8b)."""

from utils.memory.v3_get_runtime_snapshot import (
    build_v17_v3_get_runtime_snapshot,
    LOW_CARDINALITY_RUNTIME_SNAPSHOT_REASONS,
    SnapshotStatus,
    V17V3GetRuntimeSnapshot,
    V17V3GetRuntimeSnapshotInput,
    V17V3GetRuntimeSnapshotResult,
    V3GetRuntimeSnapshot,
    V3GetRuntimeSnapshotInput,
    V3GetRuntimeSnapshotResult,
    _bool_text,
    _log_fields,
    _malformed,
    _non_empty_string,
    _result,
    _SERVER_OWNED_FLAGS,
    _valid_bool,
    _valid_non_negative_int,
)

__all__ = [
    "build_v17_v3_get_runtime_snapshot",
    "LOW_CARDINALITY_RUNTIME_SNAPSHOT_REASONS",
    "SnapshotStatus",
    "V17V3GetRuntimeSnapshot",
    "V17V3GetRuntimeSnapshotInput",
    "V17V3GetRuntimeSnapshotResult",
    "V3GetRuntimeSnapshot",
    "V3GetRuntimeSnapshotInput",
    "V3GetRuntimeSnapshotResult",
    "_bool_text",
    "_log_fields",
    "_malformed",
    "_non_empty_string",
    "_result",
    "_SERVER_OWNED_FLAGS",
    "_valid_bool",
    "_valid_non_negative_int",
]
