"""Backward-compatible shim — implementation lives in ``utils.memory.v3_route_planner`` (WS-G8b)."""

from utils.memory.v3_route_planner import (
    adapt_v17_v3_memory_response,
    adapt_v17_v3_request_parameters,
    decide_v17_v3_write_convergence,
    plan_v17_v3_memory_read,
    plan_v17_v3_memory_route,
    V17V3AdaptedRequest,
    V17V3CompatibilityReadPath,
    V17V3MemoryReadRequest,
    V17V3MemoryReadServiceInput,
    V17V3MemoryReadServiceResult,
    V17V3MemoryResponse,
    V17V3ProjectionReadinessContext,
    V17V3RouteExecutionPlan,
    V17V3RoutePlanInput,
    V17V3WriteConvergenceContext,
    V17V3WriteConvergenceDecision,
    V3RouteExecutionPlan,
    V3RoutePlanInput,
    _decide_write_convergence,
    _failure_plan,
    _plan_kind_for_envelope,
    _projection_with_write_convergence,
    _read_request,
    _write_context,
    _write_convergence_ready,
)

__all__ = [
    "adapt_v17_v3_memory_response",
    "adapt_v17_v3_request_parameters",
    "decide_v17_v3_write_convergence",
    "plan_v17_v3_memory_read",
    "plan_v17_v3_memory_route",
    "V17V3AdaptedRequest",
    "V17V3CompatibilityReadPath",
    "V17V3MemoryReadRequest",
    "V17V3MemoryReadServiceInput",
    "V17V3MemoryReadServiceResult",
    "V17V3MemoryResponse",
    "V17V3ProjectionReadinessContext",
    "V17V3RouteExecutionPlan",
    "V17V3RoutePlanInput",
    "V17V3WriteConvergenceContext",
    "V17V3WriteConvergenceDecision",
    "V3RouteExecutionPlan",
    "V3RoutePlanInput",
    "_decide_write_convergence",
    "_failure_plan",
    "_plan_kind_for_envelope",
    "_projection_with_write_convergence",
    "_read_request",
    "_write_context",
    "_write_convergence_ready",
]
