"""Backward-compatible shim — implementation lives in ``utils.memory.product_authorization`` (WS-G8a)."""

from utils.memory.product_authorization import (
    AppKeyScopeGrantDecision,
    EXTERNAL_MEMORY_CONSUMERS,
    EXTERNAL_V17_MEMORY_CONSUMERS,
    MEMORY_OPERATION_REQUIRED_SCOPES,
    MemoryGrantOperation,
    ProductAuthorizationContext,
    ProductAuthorizationDecision,
    ReadAppKeyGrantsState,
    ReadGlobalGate,
    ReadRollout,
    V17AppKeyScopeGrantDecision,
    V17MemoryGrantOperation,
    V17ProductAuthorizationContext,
    V17ProductAuthorizationDecision,
    V17_MEMORY_OPERATION_REQUIRED_SCOPES,
    authorize_v17_app_key_scope_memory_grant,
    authorize_v17_external_default_memory_read,
    authorize_v17_product_memory_route,
)

__all__ = [
    "AppKeyScopeGrantDecision",
    "EXTERNAL_MEMORY_CONSUMERS",
    "EXTERNAL_V17_MEMORY_CONSUMERS",
    "MEMORY_OPERATION_REQUIRED_SCOPES",
    "MemoryGrantOperation",
    "ProductAuthorizationContext",
    "ProductAuthorizationDecision",
    "ReadAppKeyGrantsState",
    "ReadGlobalGate",
    "ReadRollout",
    "V17AppKeyScopeGrantDecision",
    "V17MemoryGrantOperation",
    "V17ProductAuthorizationContext",
    "V17ProductAuthorizationDecision",
    "V17_MEMORY_OPERATION_REQUIRED_SCOPES",
    "authorize_v17_app_key_scope_memory_grant",
    "authorize_v17_external_default_memory_read",
    "authorize_v17_product_memory_route",
]
