"""Canonical alias module for ``utils.memory.v17_v3_local_telemetry`` (WS-G).

New canonical-path code may import from here; the V17 module name remains valid
until a later rename wave. No behavior change — re-exports only.
"""

from utils.memory.v17_v3_local_telemetry import (
    APPROVAL_OWNERS,
    APPROVAL_STATUSES,
    ARCHIVE_DEFAULT_VISIBILITY_DECISIONS,
    CANARY_COHORTS,
    CANARY_ENROLLMENTS,
    CURSOR_VALIDATION_REASONS,
    CURSOR_VALIDATION_RESULTS,
    EVENT_NAME,
    EVENT_ROUTE,
    FAILURE_REASONS,
    FORBIDDEN_EXTRA_LABEL_KEYS,
    FakeV17V3TelemetrySink,
    NullV17V3TelemetrySink,
    PROJECTION_SOURCES,
    READ_SOURCES,
    ROLLBACK_READ_DISABLE_GATES,
    ROUTE_DECISIONS,
    SCHEMA_VERSION,
    SHORT_TERM_DEFAULT_VISIBILITY_DECISIONS,
    V17V3LocalTelemetryInput,
    V17V3ReadDisableConfig,
    V17V3ReadDisableDecision,
    V17V3TelemetryEmitResult,
    V17V3TelemetrySink,
    build_v17_v3_get_telemetry_event,
    decide_v17_v3_read_disable,
    emit_v17_v3_get_telemetry,
)

__all__ = [
    "APPROVAL_OWNERS",
    "APPROVAL_STATUSES",
    "ARCHIVE_DEFAULT_VISIBILITY_DECISIONS",
    "CANARY_COHORTS",
    "CANARY_ENROLLMENTS",
    "CURSOR_VALIDATION_REASONS",
    "CURSOR_VALIDATION_RESULTS",
    "EVENT_NAME",
    "EVENT_ROUTE",
    "FAILURE_REASONS",
    "FORBIDDEN_EXTRA_LABEL_KEYS",
    "FakeV17V3TelemetrySink",
    "NullV17V3TelemetrySink",
    "PROJECTION_SOURCES",
    "READ_SOURCES",
    "ROLLBACK_READ_DISABLE_GATES",
    "ROUTE_DECISIONS",
    "SCHEMA_VERSION",
    "SHORT_TERM_DEFAULT_VISIBILITY_DECISIONS",
    "V17V3LocalTelemetryInput",
    "V17V3ReadDisableConfig",
    "V17V3ReadDisableDecision",
    "V17V3TelemetryEmitResult",
    "V17V3TelemetrySink",
    "build_v17_v3_get_telemetry_event",
    "decide_v17_v3_read_disable",
    "emit_v17_v3_get_telemetry",
]
