{{- if .Values.licenseProxy.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.licenseProxy.namePrefix }}-config
  labels:
{{ include "deepgram-self-hosted.labels" . | indent 4}}
    {{- range $key, $val := .Values.licenseProxy.additionalLabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
data:
  license-proxy.toml: |
    [server]
      host = "{{ .Values.licenseProxy.server.host }}"
      port = {{ .Values.licenseProxy.server.port }}
      base_url = "{{ .Values.licenseProxy.server.baseUrl }}"
      status_port = {{ .Values.licenseProxy.server.statusPort }}
{{- end -}}
