// GENERATED by scripts/check_event_registry.py --write; do not edit.
import 'event_context.dart';
sealed class RegisteredEvent {
  const RegisteredEvent();
  String get wireName;
  Map<String, Object> get properties;
}

final class OnboardingCompleted extends RegisteredEvent {
  const OnboardingCompleted();
  @override
  String get wireName => "Onboarding Completed";
  @override
  Map<String, Object> get properties => {};
}

final class PhoneMicRecordingStarted extends RegisteredEvent {
  const PhoneMicRecordingStarted();
  @override
  String get wireName => "Phone Mic Recording Started";
  @override
  Map<String, Object> get properties => {};
}

final class PhoneMicRecordingStopped extends RegisteredEvent {
  const PhoneMicRecordingStopped();
  @override
  String get wireName => "Phone Mic Recording Stopped";
  @override
  Map<String, Object> get properties => {};
}

final class TranscribeLaterToggled extends RegisteredEvent {
  const TranscribeLaterToggled({required this.enabled});
  final bool enabled;
  @override
  String get wireName => "Transcribe Later Toggled";
  @override
  Map<String, Object> get properties => {"enabled": enabled};
}

final class DeviceOnboardingCompleted extends RegisteredEvent {
  const DeviceOnboardingCompleted();
  @override
  String get wireName => "Device Onboarding Completed";
  @override
  Map<String, Object> get properties => {};
}

final class TranscribeLaterRecordingProcessed extends RegisteredEvent {
  const TranscribeLaterRecordingProcessed();
  @override
  String get wireName => "Transcribe Later Recording Processed";
  @override
  Map<String, Object> get properties => {};
}

final class CalendarEnabled extends RegisteredEvent {
  const CalendarEnabled();
  @override
  String get wireName => "Calendar Enabled";
  @override
  Map<String, Object> get properties => {};
}

final class CalendarDisabled extends RegisteredEvent {
  const CalendarDisabled();
  @override
  String get wireName => "Calendar Disabled";
  @override
  Map<String, Object> get properties => {};
}

final class CalendarSelected extends RegisteredEvent {
  const CalendarSelected();
  @override
  String get wireName => "Calendar Selected";
  @override
  Map<String, Object> get properties => {};
}

final class ConversationDisplaySettingsOpened extends RegisteredEvent {
  const ConversationDisplaySettingsOpened();
  @override
  String get wireName => "Conversation Display Settings Opened";
  @override
  Map<String, Object> get properties => {};
}

final class DeveloperModeEnabled extends RegisteredEvent {
  const DeveloperModeEnabled();
  @override
  String get wireName => "Developer Mode Enabled";
  @override
  Map<String, Object> get properties => {};
}

final class DeveloperModeDisabled extends RegisteredEvent {
  const DeveloperModeDisabled();
  @override
  String get wireName => "Developer Mode Disabled";
  @override
  Map<String, Object> get properties => {};
}

final class DeveloperSettingsSaved extends RegisteredEvent {
  const DeveloperSettingsSaved({required this.hasWebhookMemoryCreated, required this.hasWebhookTranscriptReceived});
  final bool hasWebhookMemoryCreated;
  final bool hasWebhookTranscriptReceived;
  @override
  String get wireName => "Developer Settings Saved";
  @override
  Map<String, Object> get properties => {"has_webhook_memory_created": hasWebhookMemoryCreated, "has_webhook_transcript_received": hasWebhookTranscriptReceived};
}

final class VoiceResponseToggled extends RegisteredEvent {
  const VoiceResponseToggled({required this.enabled});
  final bool enabled;
  @override
  String get wireName => "Voice Response Audio Toggled";
  @override
  Map<String, Object> get properties => {"enabled": enabled};
}

final class ShowShortConversationsToggled extends RegisteredEvent {
  const ShowShortConversationsToggled({required this.showShort});
  final bool showShort;
  @override
  String get wireName => "Show Short Conversations Toggled";
  @override
  Map<String, Object> get properties => {"show_short": showShort};
}

final class DeviceOnboardingAbandoned extends RegisteredEvent {
  const DeviceOnboardingAbandoned({required this.step});
  final int step;
  @override
  String get wireName => "Device Onboarding Abandoned";
  @override
  Map<String, Object> get properties => {"step": step};
}

final class DeviceOnboardingDoubleTapConfigured extends RegisteredEvent {
  const DeviceOnboardingDoubleTapConfigured({required this.action});
  final int action;
  @override
  String get wireName => "Device Onboarding Double Tap Configured";
  @override
  Map<String, Object> get properties => {"action": action};
}

final class PhoneCallEnded extends RegisteredEvent {
  const PhoneCallEnded({required this.durationSeconds});
  final int durationSeconds;
  @override
  String get wireName => "Phone Call Ended";
  @override
  Map<String, Object> get properties => {"duration_seconds": durationSeconds};
}

final class ShortConversationThresholdChanged extends RegisteredEvent {
  const ShortConversationThresholdChanged({required this.thresholdSeconds, required this.thresholdMinutes});
  final int thresholdSeconds;
  final int thresholdMinutes;
  @override
  String get wireName => "Short Conversation Threshold Changed";
  @override
  Map<String, Object> get properties => {"threshold_seconds": thresholdSeconds, "threshold_minutes": thresholdMinutes};
}

final class MemorySearchCleared extends RegisteredEvent {
  const MemorySearchCleared({required this.totalFactsCount});
  final int totalFactsCount;
  @override
  String get wireName => "Fact Search Cleared";
  @override
  Map<String, Object> get properties => {"total_facts_count": totalFactsCount};
}

final class MemoriesAllDeleted extends RegisteredEvent {
  const MemoriesAllDeleted({required this.factsCountBeforeDeletion});
  final int factsCountBeforeDeletion;
  @override
  String get wireName => "All Facts Deleted";
  @override
  Map<String, Object> get properties => {"facts_count_before_deletion": factsCountBeforeDeletion};
}

final class NotificationFrequencyChanged extends RegisteredEvent {
  const NotificationFrequencyChanged({required this.oldFrequency, required this.newFrequency});
  final int oldFrequency;
  final int newFrequency;
  @override
  String get wireName => "Notification Frequency Changed";
  @override
  Map<String, Object> get properties => {"old_frequency": oldFrequency, "new_frequency": newFrequency};
}

final class ChangelogDismissed extends RegisteredEvent {
  const ChangelogDismissed({required this.changelogCount});
  final int changelogCount;
  @override
  String get wireName => "Changelog Dismissed";
  @override
  Map<String, Object> get properties => {"changelog_count": changelogCount};
}

final class AppsFilterRating extends RegisteredEvent {
  const AppsFilterRating({required this.rating});
  final int rating;
  @override
  String get wireName => "Apps Filter Rating";
  @override
  Map<String, Object> get properties => {"rating": rating};
}

final class AiAppGeneratorPromptSubmitted extends RegisteredEvent {
  const AiAppGeneratorPromptSubmitted({required this.promptLength});
  final int promptLength;
  @override
  String get wireName => "AI App Generator Prompt Submitted";
  @override
  Map<String, Object> get properties => {"prompt_length": promptLength};
}

enum VoiceResponseModeChangedMode {
  off("off"),
  headphonesOnly("headphones_only"),
  always("always"),
  unknown("unknown");
  const VoiceResponseModeChangedMode(this.wireName);
  final String wireName;
}

final class VoiceResponseModeChanged extends RegisteredEvent {
  const VoiceResponseModeChanged({required this.mode, required this.modeInt});
  final VoiceResponseModeChangedMode mode;
  final int modeInt;
  @override
  String get wireName => "Voice Response Mode Changed";
  @override
  Map<String, Object> get properties => {"mode": mode.wireName, "mode_int": modeInt};
}

enum MemoriesAllVisibilityChangedNewVisibility {
  private("private"),
  public("public"),
  shared("shared");
  const MemoriesAllVisibilityChangedNewVisibility(this.wireName);
  final String wireName;
}

final class MemoriesAllVisibilityChanged extends RegisteredEvent {
  const MemoriesAllVisibilityChanged({required this.newVisibility, required this.factsCount});
  final MemoriesAllVisibilityChangedNewVisibility newVisibility;
  final int factsCount;
  @override
  String get wireName => "All Facts Visibility Changed";
  @override
  Map<String, Object> get properties => {"new_visibility": newVisibility.wireName, "facts_count": factsCount};
}

final class ShowDiscardedMemoriesToggled extends RegisteredEvent {
  const ShowDiscardedMemoriesToggled({required this.showDiscarded});
  final bool showDiscarded;
  @override
  String get wireName => "Show Discarded Memories Toggled";
  @override
  Map<String, Object> get properties => {"show_discarded": showDiscarded};
}

final class ShowDiscardedConversationsToggled extends RegisteredEvent {
  const ShowDiscardedConversationsToggled({required this.showDiscarded});
  final bool showDiscarded;
  @override
  String get wireName => "Show Discarded Conversations Toggled";
  @override
  Map<String, Object> get properties => {"show_discarded": showDiscarded};
}

final class DeletedConversationsFilterToggled extends RegisteredEvent {
  const DeletedConversationsFilterToggled({required this.showDeleted});
  final bool showDeleted;
  @override
  String get wireName => "Deleted Conversations Filter Toggled";
  @override
  Map<String, Object> get properties => {"show_deleted": showDeleted};
}

final class AppsFilterMyApps extends RegisteredEvent {
  const AppsFilterMyApps({required this.enabled});
  final bool enabled;
  @override
  String get wireName => "Apps Filter My Apps";
  @override
  Map<String, Object> get properties => {"enabled": enabled};
}

final class AppsFilterInstalled extends RegisteredEvent {
  const AppsFilterInstalled({required this.enabled});
  final bool enabled;
  @override
  String get wireName => "Apps Filter Installed";
  @override
  Map<String, Object> get properties => {"enabled": enabled};
}

final class DailySummaryToggled extends RegisteredEvent {
  const DailySummaryToggled({required this.enabled});
  final bool enabled;
  @override
  String get wireName => "Daily Summary Toggled";
  @override
  Map<String, Object> get properties => {"enabled": enabled};
}

final class AiAppGeneratorAppGenerated extends RegisteredEvent {
  const AiAppGeneratorAppGenerated({required this.success});
  final bool success;
  @override
  String get wireName => "AI App Generator App Generated";
  @override
  Map<String, Object> get properties => {"success": success};
}

final class ActionItemsViewToggled extends RegisteredEvent {
  const ActionItemsViewToggled({required this.groupedView});
  final bool groupedView;
  @override
  String get wireName => "Action Items View Toggled";
  @override
  Map<String, Object> get properties => {"grouped_view": groupedView};
}

final class PhoneCallStarted extends RegisteredEvent {
  const PhoneCallStarted({required this.hasContactName});
  final bool hasContactName;
  @override
  String get wireName => "Phone Call Started";
  @override
  Map<String, Object> get properties => {"has_contact_name": hasContactName};
}

final class PhoneCallPageOpened extends RegisteredEvent {
  const PhoneCallPageOpened();
  @override
  String get wireName => "Phone Call Page Opened";
  @override
  Map<String, Object> get properties => {};
}

final class PhoneCallVerificationStarted extends RegisteredEvent {
  const PhoneCallVerificationStarted();
  @override
  String get wireName => "Phone Call Verification Started";
  @override
  Map<String, Object> get properties => {};
}

final class PhoneCallVerificationCompleted extends RegisteredEvent {
  const PhoneCallVerificationCompleted();
  @override
  String get wireName => "Phone Call Verification Completed";
  @override
  Map<String, Object> get properties => {};
}

final class PhoneCallConnected extends RegisteredEvent {
  const PhoneCallConnected();
  @override
  String get wireName => "Phone Call Connected";
  @override
  Map<String, Object> get properties => {};
}

final class PhoneCallDialpadOpened extends RegisteredEvent {
  const PhoneCallDialpadOpened();
  @override
  String get wireName => "Phone Call Dialpad Opened";
  @override
  Map<String, Object> get properties => {};
}

final class PhoneCallUpsellUpgradeTapped extends RegisteredEvent {
  const PhoneCallUpsellUpgradeTapped();
  @override
  String get wireName => "Phone Call Upsell Upgrade Tapped";
  @override
  Map<String, Object> get properties => {};
}

final class PhoneCallUpsellDismissed extends RegisteredEvent {
  const PhoneCallUpsellDismissed();
  @override
  String get wireName => "Phone Call Upsell Dismissed";
  @override
  Map<String, Object> get properties => {};
}

final class DeviceDisconnected extends RegisteredEvent {
  const DeviceDisconnected();
  @override
  String get wireName => "Device Disconnected";
  @override
  Map<String, Object> get properties => {};
}

final class SpeechProfileCapturePageClicked extends RegisteredEvent {
  const SpeechProfileCapturePageClicked();
  @override
  String get wireName => "Speech Profile Capture Page Clicked";
  @override
  Map<String, Object> get properties => {};
}

final class SpeechProfileSkipped extends RegisteredEvent {
  const SpeechProfileSkipped();
  @override
  String get wireName => "Speech Profile Skipped";
  @override
  Map<String, Object> get properties => {};
}

final class SpeechProfileUploadSucceeded extends RegisteredEvent {
  const SpeechProfileUploadSucceeded();
  @override
  String get wireName => "Speech Profile Upload Succeeded";
  @override
  Map<String, Object> get properties => {};
}

final class SpeechProfileEmbeddingStored extends RegisteredEvent {
  const SpeechProfileEmbeddingStored();
  @override
  String get wireName => "Speech Profile Embedding Stored";
  @override
  Map<String, Object> get properties => {};
}

final class SpeechProfileContinued extends RegisteredEvent {
  const SpeechProfileContinued();
  @override
  String get wireName => "Onboarding Step Speech Profile Continued";
  @override
  Map<String, Object> get properties => {};
}

final class UseWithoutDeviceOnboardingWelcome extends RegisteredEvent {
  const UseWithoutDeviceOnboardingWelcome();
  @override
  String get wireName => "Use Without Device Onboarding Welcome";
  @override
  Map<String, Object> get properties => {};
}

final class UseWithoutDeviceOnboardingFindDevices extends RegisteredEvent {
  const UseWithoutDeviceOnboardingFindDevices();
  @override
  String get wireName => "Use Without Device Onboarding Find Devices";
  @override
  Map<String, Object> get properties => {};
}

final class MemoriesPageEditedMemory extends RegisteredEvent {
  const MemoriesPageEditedMemory();
  @override
  String get wireName => "Fact Page Edited Fact";
  @override
  Map<String, Object> get properties => {};
}

final class MemoriesPageCreateMemoryBtn extends RegisteredEvent {
  const MemoriesPageCreateMemoryBtn();
  @override
  String get wireName => "Fact Page Create Fact Button Pressed";
  @override
  Map<String, Object> get properties => {};
}

final class MemoriesManagementSheetOpened extends RegisteredEvent {
  const MemoriesManagementSheetOpened();
  @override
  String get wireName => "Facts Management Sheet Opened";
  @override
  Map<String, Object> get properties => {};
}

final class ConversationMergeSelectionModeEntered extends RegisteredEvent {
  const ConversationMergeSelectionModeEntered();
  @override
  String get wireName => "Conversation Merge Selection Mode Entered";
  @override
  Map<String, Object> get properties => {};
}

final class ConversationMergeSelectionModeExited extends RegisteredEvent {
  const ConversationMergeSelectionModeExited();
  @override
  String get wireName => "Conversation Merge Selection Mode Exited";
  @override
  Map<String, Object> get properties => {};
}

final class AddManualConversationClicked extends RegisteredEvent {
  const AddManualConversationClicked();
  @override
  String get wireName => "Add Manual Memory Clicked";
  @override
  Map<String, Object> get properties => {};
}

final class UserIDCopied extends RegisteredEvent {
  const UserIDCopied();
  @override
  String get wireName => "User ID Copied";
  @override
  Map<String, Object> get properties => {};
}

final class ExportMemories extends RegisteredEvent {
  const ExportMemories();
  @override
  String get wireName => "Dev Mode Export Memories";
  @override
  Map<String, Object> get properties => {};
}

final class ImportMemories extends RegisteredEvent {
  const ImportMemories();
  @override
  String get wireName => "Dev Mode Import Memories";
  @override
  Map<String, Object> get properties => {};
}

final class ImportedMemories extends RegisteredEvent {
  const ImportedMemories();
  @override
  String get wireName => "Dev Mode Imported Memories";
  @override
  Map<String, Object> get properties => {};
}

final class SupportContacted extends RegisteredEvent {
  const SupportContacted();
  @override
  String get wireName => "Support Contacted";
  @override
  Map<String, Object> get properties => {};
}

final class UpgradeSucceeded extends RegisteredEvent {
  const UpgradeSucceeded();
  @override
  String get wireName => "Upgrade Succeeded";
  @override
  Map<String, Object> get properties => {};
}

final class UpgradeCancelled extends RegisteredEvent {
  const UpgradeCancelled();
  @override
  String get wireName => "Upgrade Cancelled";
  @override
  Map<String, Object> get properties => {};
}

final class UpgradeModalDismissed extends RegisteredEvent {
  const UpgradeModalDismissed();
  @override
  String get wireName => "Upgrade Modal Dismissed";
  @override
  Map<String, Object> get properties => {};
}

final class UpgradeModalClicked extends RegisteredEvent {
  const UpgradeModalClicked();
  @override
  String get wireName => "Upgrade Modal Clicked";
  @override
  Map<String, Object> get properties => {};
}

final class SubscriptionCancelFlowStarted extends RegisteredEvent {
  const SubscriptionCancelFlowStarted();
  @override
  String get wireName => "Subscription Cancel Flow Started";
  @override
  Map<String, Object> get properties => {};
}

final class ConnectFriendClicked extends RegisteredEvent {
  const ConnectFriendClicked();
  @override
  String get wireName => "Connect Friend Clicked";
  @override
  Map<String, Object> get properties => {};
}

final class DisconnectFriendClicked extends RegisteredEvent {
  const DisconnectFriendClicked();
  @override
  String get wireName => "Disconnect Friend Clicked";
  @override
  Map<String, Object> get properties => {};
}

final class BatteryIndicatorClicked extends RegisteredEvent {
  const BatteryIndicatorClicked();
  @override
  String get wireName => "Battery Indicator Clicked";
  @override
  Map<String, Object> get properties => {};
}

final class AddedPerson extends RegisteredEvent {
  const AddedPerson();
  @override
  String get wireName => "Added Person";
  @override
  Map<String, Object> get properties => {};
}

final class RemovedPerson extends RegisteredEvent {
  const RemovedPerson();
  @override
  String get wireName => "Removed Person";
  @override
  Map<String, Object> get properties => {};
}

final class TagSheetOpened extends RegisteredEvent {
  const TagSheetOpened();
  @override
  String get wireName => "Tag Sheet Opened";
  @override
  Map<String, Object> get properties => {};
}

final class UntaggedSegment extends RegisteredEvent {
  const UntaggedSegment();
  @override
  String get wireName => "Untagged Segment";
  @override
  Map<String, Object> get properties => {};
}

final class EditSegmentTextStarted extends RegisteredEvent {
  const EditSegmentTextStarted();
  @override
  String get wireName => "Edit Segment Text Started";
  @override
  Map<String, Object> get properties => {};
}

final class EditSegmentTextSaved extends RegisteredEvent {
  const EditSegmentTextSaved();
  @override
  String get wireName => "Edit Segment Text Saved";
  @override
  Map<String, Object> get properties => {};
}

final class EditSegmentTextCancelled extends RegisteredEvent {
  const EditSegmentTextCancelled();
  @override
  String get wireName => "Edit Segment Text Cancelled";
  @override
  Map<String, Object> get properties => {};
}

final class EditSummaryStarted extends RegisteredEvent {
  const EditSummaryStarted();
  @override
  String get wireName => "Edit Summary Started";
  @override
  Map<String, Object> get properties => {};
}

final class EditSummarySaved extends RegisteredEvent {
  const EditSummarySaved();
  @override
  String get wireName => "Edit Summary Saved";
  @override
  Map<String, Object> get properties => {};
}

final class EditSummaryCancelled extends RegisteredEvent {
  const EditSummaryCancelled();
  @override
  String get wireName => "Edit Summary Cancelled";
  @override
  Map<String, Object> get properties => {};
}

final class DeleteAccountClicked extends RegisteredEvent {
  const DeleteAccountClicked();
  @override
  String get wireName => "Delete Account Clicked";
  @override
  Map<String, Object> get properties => {};
}

final class DeleteAccountConfirmed extends RegisteredEvent {
  const DeleteAccountConfirmed();
  @override
  String get wireName => "Delete Account Confirmed";
  @override
  Map<String, Object> get properties => {};
}

final class DeleteAccountCancelled extends RegisteredEvent {
  const DeleteAccountCancelled();
  @override
  String get wireName => "Delete Account Cancelled";
  @override
  Map<String, Object> get properties => {};
}

final class DeleteAccountFlowStarted extends RegisteredEvent {
  const DeleteAccountFlowStarted();
  @override
  String get wireName => "Delete Account Flow Started";
  @override
  Map<String, Object> get properties => {};
}

final class AppsFilterOpened extends RegisteredEvent {
  const AppsFilterOpened();
  @override
  String get wireName => "Apps Filter Opened";
  @override
  Map<String, Object> get properties => {};
}

final class AppsFilterApplied extends RegisteredEvent {
  const AppsFilterApplied();
  @override
  String get wireName => "Apps Filter Applied";
  @override
  Map<String, Object> get properties => {};
}

final class AppsClearFilters extends RegisteredEvent {
  const AppsClearFilters();
  @override
  String get wireName => "Apps Clear Filters";
  @override
  Map<String, Object> get properties => {};
}

final class BrainMapOpened extends RegisteredEvent {
  const BrainMapOpened();
  @override
  String get wireName => "Brain Map Opened";
  @override
  Map<String, Object> get properties => {};
}

final class BrainMapShareClicked extends RegisteredEvent {
  const BrainMapShareClicked();
  @override
  String get wireName => "Brain Map Share Clicked";
  @override
  Map<String, Object> get properties => {};
}

final class ActionItemsPageOpened extends RegisteredEvent {
  const ActionItemsPageOpened();
  @override
  String get wireName => "Action Items Page Opened";
  @override
  Map<String, Object> get properties => {};
}

final class ActionItemsDateFilterCleared extends RegisteredEvent {
  const ActionItemsDateFilterCleared();
  @override
  String get wireName => "Action Items Date Filter Cleared";
  @override
  Map<String, Object> get properties => {};
}

final class TrainingDataOptInSubmitted extends RegisteredEvent {
  const TrainingDataOptInSubmitted();
  @override
  String get wireName => "Training Data Opt-In Submitted";
  @override
  Map<String, Object> get properties => {};
}

final class TrainingDataOptInApproved extends RegisteredEvent {
  const TrainingDataOptInApproved();
  @override
  String get wireName => "Training Data Opt-In Approved";
  @override
  Map<String, Object> get properties => {};
}

final class CalendarFilterCleared extends RegisteredEvent {
  const CalendarFilterCleared();
  @override
  String get wireName => "Calendar Filter Cleared";
  @override
  Map<String, Object> get properties => {};
}

final class SearchBarFocused extends RegisteredEvent {
  const SearchBarFocused();
  @override
  String get wireName => "Search Bar Focused";
  @override
  Map<String, Object> get properties => {};
}

final class SearchQueryCleared extends RegisteredEvent {
  const SearchQueryCleared();
  @override
  String get wireName => "Search Query Cleared";
  @override
  Map<String, Object> get properties => {};
}

final class ExportTasksBannerClicked extends RegisteredEvent {
  const ExportTasksBannerClicked();
  @override
  String get wireName => "Export Tasks Banner Clicked";
  @override
  Map<String, Object> get properties => {};
}

final class CreateFolderButtonClicked extends RegisteredEvent {
  const CreateFolderButtonClicked();
  @override
  String get wireName => "Create Folder Button Clicked";
  @override
  Map<String, Object> get properties => {};
}

final class WrappedPageOpened extends RegisteredEvent {
  const WrappedPageOpened();
  @override
  String get wireName => "Wrapped Page Opened";
  @override
  Map<String, Object> get properties => {};
}

final class WrappedBannerClicked extends RegisteredEvent {
  const WrappedBannerClicked();
  @override
  String get wireName => "Wrapped Banner Clicked";
  @override
  Map<String, Object> get properties => {};
}

final class WrappedGenerationStarted extends RegisteredEvent {
  const WrappedGenerationStarted();
  @override
  String get wireName => "Wrapped Generation Started";
  @override
  Map<String, Object> get properties => {};
}

final class DailySummarySettingsOpened extends RegisteredEvent {
  const DailySummarySettingsOpened();
  @override
  String get wireName => "Daily Summary Settings Opened";
  @override
  Map<String, Object> get properties => {};
}

final class PermissionsSettingsOpened extends RegisteredEvent {
  const PermissionsSettingsOpened();
  @override
  String get wireName => "Permissions Settings Opened";
  @override
  Map<String, Object> get properties => {};
}

final class PermissionsInterstitialShown extends RegisteredEvent {
  const PermissionsInterstitialShown();
  @override
  String get wireName => "Permissions Interstitial Shown";
  @override
  Map<String, Object> get properties => {};
}

final class PermissionsInterstitialCompleted extends RegisteredEvent {
  const PermissionsInterstitialCompleted();
  @override
  String get wireName => "Permissions Interstitial Completed";
  @override
  Map<String, Object> get properties => {};
}

final class PermissionsInterstitialSkipped extends RegisteredEvent {
  const PermissionsInterstitialSkipped();
  @override
  String get wireName => "Permissions Interstitial Skipped";
  @override
  Map<String, Object> get properties => {};
}

final class RecapTabOpened extends RegisteredEvent {
  const RecapTabOpened();
  @override
  String get wireName => "Recap Tab Opened";
  @override
  Map<String, Object> get properties => {};
}

final class WhatsNewOpened extends RegisteredEvent {
  const WhatsNewOpened();
  @override
  String get wireName => "Whats New Opened";
  @override
  Map<String, Object> get properties => {};
}

final class DailyScoreHelpTapped extends RegisteredEvent {
  const DailyScoreHelpTapped();
  @override
  String get wireName => "Daily Score Help Tapped";
  @override
  Map<String, Object> get properties => {};
}

final class IntegrationsPageOpened extends RegisteredEvent {
  const IntegrationsPageOpened();
  @override
  String get wireName => "Integrations Page Opened";
  @override
  Map<String, Object> get properties => {};
}

final class PaymentsPageOpened extends RegisteredEvent {
  const PaymentsPageOpened();
  @override
  String get wireName => "Payments Page Opened";
  @override
  Map<String, Object> get properties => {};
}

final class ConnectDevicePageOpened extends RegisteredEvent {
  const ConnectDevicePageOpened();
  @override
  String get wireName => "Connect Device Page Opened";
  @override
  Map<String, Object> get properties => {};
}

final class GetOmiDeviceClicked extends RegisteredEvent {
  const GetOmiDeviceClicked();
  @override
  String get wireName => "Get Omi Device Clicked";
  @override
  Map<String, Object> get properties => {};
}

final class ConnectionGuideOpened extends RegisteredEvent {
  const ConnectionGuideOpened();
  @override
  String get wireName => "Connection Guide Opened";
  @override
  Map<String, Object> get properties => {};
}

final class DataPrivacyPageOpened extends RegisteredEvent {
  const DataPrivacyPageOpened();
  @override
  String get wireName => "Data Privacy Page Opened";
  @override
  Map<String, Object> get properties => {};
}

final class AiAppGeneratorPageOpened extends RegisteredEvent {
  const AiAppGeneratorPageOpened();
  @override
  String get wireName => "AI App Generator Page Opened";
  @override
  Map<String, Object> get properties => {};
}

final class ImportHistoryPageOpened extends RegisteredEvent {
  const ImportHistoryPageOpened();
  @override
  String get wireName => "Import History Page Opened";
  @override
  Map<String, Object> get properties => {};
}

final class LiveTranscriptCardClicked extends RegisteredEvent {
  const LiveTranscriptCardClicked({required this.hasSegments, required this.hasPhotos, required this.segmentCount, required this.photoCount});
  final bool hasSegments;
  final bool hasPhotos;
  final int segmentCount;
  final int photoCount;
  @override
  String get wireName => "Live Transcript Card Clicked";
  @override
  Map<String, Object> get properties => {"has_segments": hasSegments, "has_photos": hasPhotos, "segment_count": segmentCount, "photo_count": photoCount};
}

final class AppleRemindersSyncCompleted extends RegisteredEvent {
  const AppleRemindersSyncCompleted({required this.pendingExported, required this.syncedChecked, required this.completionsPulled, required this.completionsPushed, required this.titleDuePulled, required this.titleDuePushed, required this.remindersUnlinked});
  final int pendingExported;
  final int syncedChecked;
  final int completionsPulled;
  final int completionsPushed;
  final int titleDuePulled;
  final int titleDuePushed;
  final int remindersUnlinked;
  @override
  String get wireName => "Apple Reminders Sync Completed";
  @override
  Map<String, Object> get properties => {"pending_exported": pendingExported, "synced_checked": syncedChecked, "completions_pulled": completionsPulled, "completions_pushed": completionsPushed, "title_due_pulled": titleDuePulled, "title_due_pushed": titleDuePushed, "reminders_unlinked": remindersUnlinked};
}

final class WrappedGenerationCompleted extends RegisteredEvent {
  const WrappedGenerationCompleted({required this.totalConversations, required this.totalMinutes, required this.daysActive});
  final int totalConversations;
  final int totalMinutes;
  final int daysActive;
  @override
  String get wireName => "Wrapped Generation Completed";
  @override
  Map<String, Object> get properties => {"total_conversations": totalConversations, "total_minutes": totalMinutes, "days_active": daysActive};
}

enum TypeExtensionProbeMode {
  off("off"),
  headphonesOnly("headphones_only"),
  always("always");
  const TypeExtensionProbeMode(this.wireName);
  final String wireName;
}

final class TypeExtensionProbe extends RegisteredEvent {
  const TypeExtensionProbe({required this.enabled, required this.count, required this.mode});
  final bool enabled;
  final int count;
  final TypeExtensionProbeMode mode;
  @override
  String get wireName => "Type Extension Probe";
  @override
  Map<String, Object> get properties => {"enabled": enabled, "count": count, "mode": mode.wireName};
}

enum AppReviewOpportunityMoment {
  dailySummaryRead("daily_summary_read"),
  conversationRead("conversation_read");
  const AppReviewOpportunityMoment(this.wireName);
  final String wireName;
}

enum AppReviewOpportunityDecision {
  eligible("eligible"),
  notIosOrAndroid("not_ios_or_android"),
  storageError("storage_error"),
  notFamiliar("not_familiar"),
  migrationCooldown("migration_cooldown"),
  cooldown("cooldown"),
  budgetExhausted("budget_exhausted"),
  versionAlreadyAttempted("version_already_attempted"),
  sessionAlreadyAttempted("session_already_attempted"),
  lifecycleNotAppropriate("lifecycle_not_appropriate"),
  lifecycleChanged("lifecycle_changed"),
  availabilityError("availability_error"),
  unavailable("unavailable"),
  requestError("request_error");
  const AppReviewOpportunityDecision(this.wireName);
  final String wireName;
}

final class AppReviewOpportunity extends RegisteredEvent {
  const AppReviewOpportunity({required this.moment, required this.decision});
  final AppReviewOpportunityMoment moment;
  final AppReviewOpportunityDecision decision;
  @override
  String get wireName => "App Review Opportunity";
  @override
  Map<String, Object> get properties => {"moment": moment.wireName, "decision": decision.wireName};
}

enum AppReviewRequestAttemptedMoment {
  dailySummaryRead("daily_summary_read"),
  conversationRead("conversation_read");
  const AppReviewRequestAttemptedMoment(this.wireName);
  final String wireName;
}

final class AppReviewRequestAttempted extends RegisteredEvent {
  const AppReviewRequestAttempted({required this.moment});
  final AppReviewRequestAttemptedMoment moment;
  @override
  String get wireName => "App Review Request Attempted";
  @override
  Map<String, Object> get properties => {"moment": moment.wireName};
}

enum AppReviewRequestFinishedMoment {
  dailySummaryRead("daily_summary_read"),
  conversationRead("conversation_read");
  const AppReviewRequestFinishedMoment(this.wireName);
  final String wireName;
}

enum AppReviewRequestFinishedResult {
  returned("returned"),
  error("error");
  const AppReviewRequestFinishedResult(this.wireName);
  final String wireName;
}

final class AppReviewRequestFinished extends RegisteredEvent {
  const AppReviewRequestFinished({required this.moment, required this.result});
  final AppReviewRequestFinishedMoment moment;
  final AppReviewRequestFinishedResult result;
  @override
  String get wireName => "App Review Request Finished";
  @override
  Map<String, Object> get properties => {"moment": moment.wireName, "result": result.wireName};
}

enum ProductJourneyStartedJourney {
  search("search"),
  chatText("chat_text"),
  chatVoice("chat_voice"),
  subscriptionCancel("subscription_cancel"),
  summaryFeedback("summary_feedback"),
  recordingFeedback("recording_feedback"),
  notificationOpen("notification_open"),
  integrationConnect("integration_connect"),
  integrationSync("integration_sync"),
  onboarding("onboarding"),
  permission("permission"),
  taskMutation("task_mutation"),
  conversationLoad("conversation_load"),
  capture("capture");
  const ProductJourneyStartedJourney(this.wireName);
  final String wireName;
}

enum ProductJourneyStartedSurface {
  home("home"),
  conversations("conversations"),
  conversationDetail("conversation_detail"),
  chat("chat"),
  tasks("tasks"),
  onboarding("onboarding"),
  settings("settings"),
  notification("notification"),
  integration("integration"),
  background("background"),
  unknown("unknown");
  const ProductJourneyStartedSurface(this.wireName);
  final String wireName;
}

final class ProductJourneyStarted extends RegisteredEvent {
  const ProductJourneyStarted({required this.correlationId, required this.journey, required this.surface, this.objectId});
  final EventCorrelation correlationId;
  final ProductJourneyStartedJourney journey;
  final ProductJourneyStartedSurface surface;
  final RecordReference? objectId;
  @override
  String get wireName => "Product Journey Started";
  @override
  Map<String, Object> get properties => {"correlation_id": correlationId.value, "journey": journey.wireName, "surface": surface.wireName, if (objectId != null) "object_id": objectId!.value};
}

enum ProductJourneyFirstResultJourney {
  search("search"),
  chatText("chat_text"),
  chatVoice("chat_voice"),
  subscriptionCancel("subscription_cancel"),
  summaryFeedback("summary_feedback"),
  recordingFeedback("recording_feedback"),
  notificationOpen("notification_open"),
  integrationConnect("integration_connect"),
  integrationSync("integration_sync"),
  onboarding("onboarding"),
  permission("permission"),
  taskMutation("task_mutation"),
  conversationLoad("conversation_load"),
  capture("capture");
  const ProductJourneyFirstResultJourney(this.wireName);
  final String wireName;
}

enum ProductJourneyFirstResultSurface {
  home("home"),
  conversations("conversations"),
  conversationDetail("conversation_detail"),
  chat("chat"),
  tasks("tasks"),
  onboarding("onboarding"),
  settings("settings"),
  notification("notification"),
  integration("integration"),
  background("background"),
  unknown("unknown");
  const ProductJourneyFirstResultSurface(this.wireName);
  final String wireName;
}

final class ProductJourneyFirstResult extends RegisteredEvent {
  const ProductJourneyFirstResult({required this.correlationId, required this.journey, required this.surface, this.objectId, required this.durationMs});
  final EventCorrelation correlationId;
  final ProductJourneyFirstResultJourney journey;
  final ProductJourneyFirstResultSurface surface;
  final RecordReference? objectId;
  final int durationMs;
  @override
  String get wireName => "Product Journey First Result";
  @override
  Map<String, Object> get properties => {"correlation_id": correlationId.value, "journey": journey.wireName, "surface": surface.wireName, if (objectId != null) "object_id": objectId!.value, "duration_ms": durationMs};
}

enum ProductJourneyOutcomeJourney {
  search("search"),
  chatText("chat_text"),
  chatVoice("chat_voice"),
  subscriptionCancel("subscription_cancel"),
  summaryFeedback("summary_feedback"),
  recordingFeedback("recording_feedback"),
  notificationOpen("notification_open"),
  integrationConnect("integration_connect"),
  integrationSync("integration_sync"),
  onboarding("onboarding"),
  permission("permission"),
  taskMutation("task_mutation"),
  conversationLoad("conversation_load"),
  capture("capture");
  const ProductJourneyOutcomeJourney(this.wireName);
  final String wireName;
}

enum ProductJourneyOutcomeSurface {
  home("home"),
  conversations("conversations"),
  conversationDetail("conversation_detail"),
  chat("chat"),
  tasks("tasks"),
  onboarding("onboarding"),
  settings("settings"),
  notification("notification"),
  integration("integration"),
  background("background"),
  unknown("unknown");
  const ProductJourneyOutcomeSurface(this.wireName);
  final String wireName;
}

enum ProductJourneyOutcomeOutcome {
  success("success"),
  empty("empty"),
  failure("failure"),
  cancelled("cancelled"),
  superseded("superseded"),
  unobserved("unobserved");
  const ProductJourneyOutcomeOutcome(this.wireName);
  final String wireName;
}

enum ProductJourneyOutcomeFailure {
  none("none"),
  network("network"),
  server("server"),
  unauthorized("unauthorized"),
  permissionDenied("permission_denied"),
  quota("quota"),
  timeout("timeout"),
  invalidResponse("invalid_response"),
  incomplete("incomplete"),
  unknown("unknown");
  const ProductJourneyOutcomeFailure(this.wireName);
  final String wireName;
}

final class ProductJourneyOutcome extends RegisteredEvent {
  const ProductJourneyOutcome({required this.correlationId, required this.journey, required this.surface, this.objectId, required this.outcome, required this.failure, required this.durationMs, required this.resultCount});
  final EventCorrelation correlationId;
  final ProductJourneyOutcomeJourney journey;
  final ProductJourneyOutcomeSurface surface;
  final RecordReference? objectId;
  final ProductJourneyOutcomeOutcome outcome;
  final ProductJourneyOutcomeFailure failure;
  final int durationMs;
  final int resultCount;
  @override
  String get wireName => "Product Journey Outcome";
  @override
  Map<String, Object> get properties => {"correlation_id": correlationId.value, "journey": journey.wireName, "surface": surface.wireName, if (objectId != null) "object_id": objectId!.value, "outcome": outcome.wireName, "failure": failure.wireName, "duration_ms": durationMs, "result_count": resultCount};
}

enum ProductValueEventKind {
  resultViewed("result_viewed"),
  copied("copied"),
  shared("shared"),
  taskCompleted("task_completed"),
  memoryKept("memory_kept"),
  feedbackHelpful("feedback_helpful"),
  searchResultOpened("search_result_opened"),
  recordingRecovered("recording_recovered");
  const ProductValueEventKind(this.wireName);
  final String wireName;
}

enum ProductValueEventSurface {
  home("home"),
  conversations("conversations"),
  conversationDetail("conversation_detail"),
  chat("chat"),
  tasks("tasks"),
  onboarding("onboarding"),
  settings("settings"),
  notification("notification"),
  integration("integration"),
  background("background"),
  unknown("unknown");
  const ProductValueEventSurface(this.wireName);
  final String wireName;
}

final class ProductValueEvent extends RegisteredEvent {
  const ProductValueEvent({required this.kind, required this.surface, this.objectId});
  final ProductValueEventKind kind;
  final ProductValueEventSurface surface;
  final RecordReference? objectId;
  @override
  String get wireName => "Product Value";
  @override
  Map<String, Object> get properties => {"kind": kind.wireName, "surface": surface.wireName, if (objectId != null) "object_id": objectId!.value};
}

enum ConversationActionAction {
  askOmi("ask_omi"),
  star("star"),
  unstar("unstar"),
  share("share"),
  rename("rename"),
  moveFolder("move_folder"),
  recordingsOpen("recordings_open"),
  separate("separate"),
  delete("delete"),
  copyTranscript("copy_transcript"),
  copySummary("copy_summary"),
  shareAudio("share_audio"),
  linkEvent("link_event"),
  reprocess("reprocess"),
  search("search"),
  visibility("visibility"),
  open("open"),
  select("select"),
  copyConversationId("copy_conversation_id"),
  testPrompt("test_prompt");
  const ConversationActionAction(this.wireName);
  final String wireName;
}

enum ConversationActionSurface {
  topBar("top_bar"),
  overflow("overflow"),
  detailBody("detail_body"),
  rowLongPress("row_long_press"),
  rowSwipe("row_swipe");
  const ConversationActionSurface(this.wireName);
  final String wireName;
}

final class ConversationAction extends RegisteredEvent {
  const ConversationAction({required this.action, required this.surface});
  final ConversationActionAction action;
  final ConversationActionSurface surface;
  @override
  String get wireName => "Conversation Action";
  @override
  Map<String, Object> get properties => {"action": action.wireName, "surface": surface.wireName};
}

final class SpeakerTagPromptsViewed extends RegisteredEvent {
  const SpeakerTagPromptsViewed({required this.promptCount, required this.firstTime});
  final int promptCount;
  final bool firstTime;
  @override
  String get wireName => "Speaker Tag Prompts Viewed";
  @override
  Map<String, Object> get properties => {"prompt_count": promptCount, "first_time": firstTime};
}

enum SpeakerTagPromptClipPlayedKind {
  ownerCheck("owner_check"),
  confirmPerson("confirm_person"),
  identify("identify"),
  unknown("unknown");
  const SpeakerTagPromptClipPlayedKind(this.wireName);
  final String wireName;
}

final class SpeakerTagPromptClipPlayed extends RegisteredEvent {
  const SpeakerTagPromptClipPlayed({required this.kind, required this.loaded});
  final SpeakerTagPromptClipPlayedKind kind;
  final bool loaded;
  @override
  String get wireName => "Speaker Tag Prompt Clip Played";
  @override
  Map<String, Object> get properties => {"kind": kind.wireName, "loaded": loaded};
}

enum SpeakerTagPromptAnswerSubmittedKind {
  ownerCheck("owner_check"),
  confirmPerson("confirm_person"),
  identify("identify"),
  unknown("unknown");
  const SpeakerTagPromptAnswerSubmittedKind(this.wireName);
  final String wireName;
}

enum SpeakerTagPromptAnswerSubmittedAnswer {
  me("me"),
  notMe("not_me"),
  person("person"),
  newPerson("new_person"),
  someoneElse("someone_else"),
  skip("skip"),
  unknown("unknown");
  const SpeakerTagPromptAnswerSubmittedAnswer(this.wireName);
  final String wireName;
}

final class SpeakerTagPromptAnswerSubmitted extends RegisteredEvent {
  const SpeakerTagPromptAnswerSubmitted({required this.kind, required this.answer, required this.clipPlayed, required this.firstTime, required this.succeeded});
  final SpeakerTagPromptAnswerSubmittedKind kind;
  final SpeakerTagPromptAnswerSubmittedAnswer answer;
  final bool clipPlayed;
  final bool firstTime;
  final bool succeeded;
  @override
  String get wireName => "Speaker Tag Prompt Answer Submitted";
  @override
  Map<String, Object> get properties => {"kind": kind.wireName, "answer": answer.wireName, "clip_played": clipPlayed, "first_time": firstTime, "succeeded": succeeded};
}

final class SpeakerTagPromptsClosed extends RegisteredEvent {
  const SpeakerTagPromptsClosed({required this.answeredCount, required this.promptCount});
  final int answeredCount;
  final int promptCount;
  @override
  String get wireName => "Speaker Tag Prompts Closed";
  @override
  Map<String, Object> get properties => {"answered_count": answeredCount, "prompt_count": promptCount};
}

enum VoiceProfileSettingToggledSetting {
  tagPrompts("tag_prompts"),
  saveOtherVoices("save_other_voices");
  const VoiceProfileSettingToggledSetting(this.wireName);
  final String wireName;
}

enum VoiceProfileSettingToggledSource {
  settings("settings"),
  firstPrompt("first_prompt");
  const VoiceProfileSettingToggledSource(this.wireName);
  final String wireName;
}

final class VoiceProfileSettingToggled extends RegisteredEvent {
  const VoiceProfileSettingToggled({required this.setting, required this.enabled, required this.source, required this.succeeded});
  final VoiceProfileSettingToggledSetting setting;
  final bool enabled;
  final VoiceProfileSettingToggledSource source;
  final bool succeeded;
  @override
  String get wireName => "Voice Profile Setting Toggled";
  @override
  Map<String, Object> get properties => {"setting": setting.wireName, "enabled": enabled, "source": source.wireName, "succeeded": succeeded};
}
