// GENERATED by scripts/check_event_registry.py --write; do not edit.
sealed class RegisteredEvent {
  const RegisteredEvent();
  String get wireName;
  Map<String, Object> get properties;
}

final class OnboardingCompleted extends RegisteredEvent {
  const OnboardingCompleted();
  @override
  String get wireName => "Onboarding Completed";
  @override
  Map<String, Object> get properties => {};
}

final class PhoneMicRecordingStarted extends RegisteredEvent {
  const PhoneMicRecordingStarted();
  @override
  String get wireName => "Phone Mic Recording Started";
  @override
  Map<String, Object> get properties => {};
}

final class PhoneMicRecordingStopped extends RegisteredEvent {
  const PhoneMicRecordingStopped();
  @override
  String get wireName => "Phone Mic Recording Stopped";
  @override
  Map<String, Object> get properties => {};
}

final class TranscribeLaterToggled extends RegisteredEvent {
  const TranscribeLaterToggled({required this.enabled});
  final bool enabled;
  @override
  String get wireName => "Transcribe Later Toggled";
  @override
  Map<String, Object> get properties => {"enabled": enabled};
}

final class DeviceOnboardingCompleted extends RegisteredEvent {
  const DeviceOnboardingCompleted();
  @override
  String get wireName => "Device Onboarding Completed";
  @override
  Map<String, Object> get properties => {};
}

final class TranscribeLaterRecordingProcessed extends RegisteredEvent {
  const TranscribeLaterRecordingProcessed();
  @override
  String get wireName => "Transcribe Later Recording Processed";
  @override
  Map<String, Object> get properties => {};
}

final class CalendarEnabled extends RegisteredEvent {
  const CalendarEnabled();
  @override
  String get wireName => "Calendar Enabled";
  @override
  Map<String, Object> get properties => {};
}

final class CalendarDisabled extends RegisteredEvent {
  const CalendarDisabled();
  @override
  String get wireName => "Calendar Disabled";
  @override
  Map<String, Object> get properties => {};
}

final class CalendarSelected extends RegisteredEvent {
  const CalendarSelected();
  @override
  String get wireName => "Calendar Selected";
  @override
  Map<String, Object> get properties => {};
}

final class ConversationDisplaySettingsOpened extends RegisteredEvent {
  const ConversationDisplaySettingsOpened();
  @override
  String get wireName => "Conversation Display Settings Opened";
  @override
  Map<String, Object> get properties => {};
}

final class DeveloperModeEnabled extends RegisteredEvent {
  const DeveloperModeEnabled();
  @override
  String get wireName => "Developer Mode Enabled";
  @override
  Map<String, Object> get properties => {};
}

final class DeveloperModeDisabled extends RegisteredEvent {
  const DeveloperModeDisabled();
  @override
  String get wireName => "Developer Mode Disabled";
  @override
  Map<String, Object> get properties => {};
}

final class DeveloperSettingsSaved extends RegisteredEvent {
  const DeveloperSettingsSaved({required this.hasWebhookMemoryCreated, required this.hasWebhookTranscriptReceived});
  final bool hasWebhookMemoryCreated;
  final bool hasWebhookTranscriptReceived;
  @override
  String get wireName => "Developer Settings Saved";
  @override
  Map<String, Object> get properties => {"has_webhook_memory_created": hasWebhookMemoryCreated, "has_webhook_transcript_received": hasWebhookTranscriptReceived};
}

final class VoiceResponseToggled extends RegisteredEvent {
  const VoiceResponseToggled({required this.enabled});
  final bool enabled;
  @override
  String get wireName => "Voice Response Audio Toggled";
  @override
  Map<String, Object> get properties => {"enabled": enabled};
}

final class ShowShortConversationsToggled extends RegisteredEvent {
  const ShowShortConversationsToggled({required this.showShort});
  final bool showShort;
  @override
  String get wireName => "Show Short Conversations Toggled";
  @override
  Map<String, Object> get properties => {"show_short": showShort};
}

final class DeviceOnboardingAbandoned extends RegisteredEvent {
  const DeviceOnboardingAbandoned({required this.step});
  final int step;
  @override
  String get wireName => "Device Onboarding Abandoned";
  @override
  Map<String, Object> get properties => {"step": step};
}

final class DeviceOnboardingDoubleTapConfigured extends RegisteredEvent {
  const DeviceOnboardingDoubleTapConfigured({required this.action});
  final int action;
  @override
  String get wireName => "Device Onboarding Double Tap Configured";
  @override
  Map<String, Object> get properties => {"action": action};
}

final class PhoneCallEnded extends RegisteredEvent {
  const PhoneCallEnded({required this.durationSeconds});
  final int durationSeconds;
  @override
  String get wireName => "Phone Call Ended";
  @override
  Map<String, Object> get properties => {"duration_seconds": durationSeconds};
}

final class ShortConversationThresholdChanged extends RegisteredEvent {
  const ShortConversationThresholdChanged({required this.thresholdSeconds, required this.thresholdMinutes});
  final int thresholdSeconds;
  final int thresholdMinutes;
  @override
  String get wireName => "Short Conversation Threshold Changed";
  @override
  Map<String, Object> get properties => {"threshold_seconds": thresholdSeconds, "threshold_minutes": thresholdMinutes};
}

final class MemorySearchCleared extends RegisteredEvent {
  const MemorySearchCleared({required this.totalFactsCount});
  final int totalFactsCount;
  @override
  String get wireName => "Fact Search Cleared";
  @override
  Map<String, Object> get properties => {"total_facts_count": totalFactsCount};
}

final class MemoriesAllDeleted extends RegisteredEvent {
  const MemoriesAllDeleted({required this.factsCountBeforeDeletion});
  final int factsCountBeforeDeletion;
  @override
  String get wireName => "All Facts Deleted";
  @override
  Map<String, Object> get properties => {"facts_count_before_deletion": factsCountBeforeDeletion};
}

final class NotificationFrequencyChanged extends RegisteredEvent {
  const NotificationFrequencyChanged({required this.oldFrequency, required this.newFrequency});
  final int oldFrequency;
  final int newFrequency;
  @override
  String get wireName => "Notification Frequency Changed";
  @override
  Map<String, Object> get properties => {"old_frequency": oldFrequency, "new_frequency": newFrequency};
}

final class ChangelogDismissed extends RegisteredEvent {
  const ChangelogDismissed({required this.changelogCount});
  final int changelogCount;
  @override
  String get wireName => "Changelog Dismissed";
  @override
  Map<String, Object> get properties => {"changelog_count": changelogCount};
}

final class AppsFilterRating extends RegisteredEvent {
  const AppsFilterRating({required this.rating});
  final int rating;
  @override
  String get wireName => "Apps Filter Rating";
  @override
  Map<String, Object> get properties => {"rating": rating};
}

final class AiAppGeneratorPromptSubmitted extends RegisteredEvent {
  const AiAppGeneratorPromptSubmitted({required this.promptLength});
  final int promptLength;
  @override
  String get wireName => "AI App Generator Prompt Submitted";
  @override
  Map<String, Object> get properties => {"prompt_length": promptLength};
}

enum VoiceResponseModeChangedMode {
  off("off"),
  headphonesOnly("headphones_only"),
  always("always"),
  unknown("unknown");
  const VoiceResponseModeChangedMode(this.wireName);
  final String wireName;
}

final class VoiceResponseModeChanged extends RegisteredEvent {
  const VoiceResponseModeChanged({required this.mode, required this.modeInt});
  final VoiceResponseModeChangedMode mode;
  final int modeInt;
  @override
  String get wireName => "Voice Response Mode Changed";
  @override
  Map<String, Object> get properties => {"mode": mode.wireName, "mode_int": modeInt};
}

enum MemoriesAllVisibilityChangedNewVisibility {
  private("private"),
  public("public"),
  shared("shared");
  const MemoriesAllVisibilityChangedNewVisibility(this.wireName);
  final String wireName;
}

final class MemoriesAllVisibilityChanged extends RegisteredEvent {
  const MemoriesAllVisibilityChanged({required this.newVisibility, required this.factsCount});
  final MemoriesAllVisibilityChangedNewVisibility newVisibility;
  final int factsCount;
  @override
  String get wireName => "All Facts Visibility Changed";
  @override
  Map<String, Object> get properties => {"new_visibility": newVisibility.wireName, "facts_count": factsCount};
}

enum TypeExtensionProbeMode {
  off("off"),
  headphonesOnly("headphones_only"),
  always("always");
  const TypeExtensionProbeMode(this.wireName);
  final String wireName;
}

final class TypeExtensionProbe extends RegisteredEvent {
  const TypeExtensionProbe({required this.enabled, required this.count, required this.mode});
  final bool enabled;
  final int count;
  final TypeExtensionProbeMode mode;
  @override
  String get wireName => "Type Extension Probe";
  @override
  Map<String, Object> get properties => {"enabled": enabled, "count": count, "mode": mode.wireName};
}
