// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PhoneMicPigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PhoneMicPigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PhoneMicPigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PhoneMicPigeonError {
  return PhoneMicPigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Native capture state machine, mirrored to Dart on every transition.
enum PhoneMicCaptureState: Int {
  case idle = 0
  case starting = 1
  case running = 2
  case interrupted = 3
  case rebuilding = 4
}

private class PhoneMicPigeonPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PhoneMicCaptureState(rawValue: enumResultAsInt)
      }
      return nil
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PhoneMicPigeonPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PhoneMicCaptureState {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else {
      super.writeValue(value)
    }
  }
}

private class PhoneMicPigeonPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PhoneMicPigeonPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PhoneMicPigeonPigeonCodecWriter(data: data)
  }
}

class PhoneMicPigeonPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PhoneMicPigeonPigeonCodec(readerWriter: PhoneMicPigeonPigeonCodecReaderWriter())
}


/// Dart -> native. start() resolves once the engine is running, or throws a
/// PlatformException with one of: permission_denied, session_config_failed,
/// format_invalid, converter_init_failed, engine_start_failed. stop() resolves
/// only after teardown is fully drained — no frames or events arrive after it.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol PhoneMicHostApi {
  func start(completion: @escaping (Result<Void, Error>) -> Void)
  func stop(completion: @escaping (Result<Void, Error>) -> Void)
  func isRecording() throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class PhoneMicHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PhoneMicPigeonPigeonCodec.shared }
  /// Sets up an instance of `PhoneMicHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: PhoneMicHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_phone_mic.PhoneMicHostApi.start\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startChannel.setMessageHandler { _, reply in
        api.start { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startChannel.setMessageHandler(nil)
    }
    let stopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_phone_mic.PhoneMicHostApi.stop\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopChannel.setMessageHandler { _, reply in
        api.stop { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopChannel.setMessageHandler(nil)
    }
    let isRecordingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.omi_phone_mic.PhoneMicHostApi.isRecording\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isRecordingChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isRecording()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isRecordingChannel.setMessageHandler(nil)
    }
  }
}
/// Native -> Dart.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol PhoneMicFlutterApiProtocol {
  /// PCM16 little-endian mono @16kHz. Chunk sizes vary with the input route.
  func onAudioFrame(pcm16leMono16k pcm16leMono16kArg: FlutterStandardTypedData, completion: @escaping (Result<Void, PhoneMicPigeonError>) -> Void)
  func onStateChanged(state stateArg: PhoneMicCaptureState, completion: @escaping (Result<Void, PhoneMicPigeonError>) -> Void)
  /// Non-fatal runtime failures (capture self-heals): converter_failed,
  /// rebuild_failed, resume_failed, media_services_reset.
  func onCaptureError(code codeArg: String, message messageArg: String, completion: @escaping (Result<Void, PhoneMicPigeonError>) -> Void)
}
class PhoneMicFlutterApi: PhoneMicFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: PhoneMicPigeonPigeonCodec {
    return PhoneMicPigeonPigeonCodec.shared
  }
  /// PCM16 little-endian mono @16kHz. Chunk sizes vary with the input route.
  func onAudioFrame(pcm16leMono16k pcm16leMono16kArg: FlutterStandardTypedData, completion: @escaping (Result<Void, PhoneMicPigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.omi_phone_mic.PhoneMicFlutterApi.onAudioFrame\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([pcm16leMono16kArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PhoneMicPigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onStateChanged(state stateArg: PhoneMicCaptureState, completion: @escaping (Result<Void, PhoneMicPigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.omi_phone_mic.PhoneMicFlutterApi.onStateChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([stateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PhoneMicPigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Non-fatal runtime failures (capture self-heals): converter_failed,
  /// rebuild_failed, resume_failed, media_services_reset.
  func onCaptureError(code codeArg: String, message messageArg: String, completion: @escaping (Result<Void, PhoneMicPigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.omi_phone_mic.PhoneMicFlutterApi.onCaptureError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([codeArg, messageArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PhoneMicPigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
