{{- if .Values.engine.modelManager.volumes.aws.efs.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.engine.modelManager.volumes.aws.efs.namePrefix }}-aws-efs-sc
  labels:
{{ include "deepgram-self-hosted.labels" . | indent 4}}
provisioner: efs.csi.aws.com
{{- end }}
