package omi.v5.host

import android.content.Context
import omi.kit.NativePolicyBridge
import omi.kit.Policy
import skip.lib.Tuple2

/**
 * The Android half of the policy-injection contract: the shared native-core
 * C++ middleware, reached through JNI — never a Kotlin re-derivation.
 *
 * The Swift `NativePolicyBridge` protocol transpiles to this Kotlin interface
 * (omi.kit.NativePolicyBridge, generated by skipstone into the OmiKit
 * output tree); every method maps 1:1 onto a native-core C ABI entry point
 * (see native-core/include/*.h):
 *
 *   routeStrip               → omi_backend_route_strip
 *   isCapturePath            → omi_backend_is_capture_path
 *   requestTimeoutSeconds    → omi_backend_request_timeout_seconds
 *   examplePlatformSupported → omi_backend_example_platform_supported
 *   isLoopbackHostname       → omi_backend_is_loopback_hostname
 *   isCloudHostname          → omi_backend_is_cloud_hostname
 *   isAllowedV5Hostname      → omi_backend_is_allowed_v5_hostname
 *   softwarePlaneIsNew       → omi_backend_software_plane_is_new
 *   recordingCapturedAtValid → omi_backend_recording_captured_at_valid
 *   recordingRetryableStatus → omi_backend_recording_retryable_status
 *   recordingOwnerKeyValid   → omi_backend_recording_owner_key_valid
 *   recordingReceiptValid    → omi_backend_recording_receipt_valid
 *   recordingUUIDValid       → omi_backend_recording_uuid_valid
 *   packetChecksum           → omi_calculate_packet_checksum
 *   normalizePacket          → omi_normalize_packet
 *   nativeCapabilities       → omi_get_native_capabilities
 *   deviceDiscoveredName     → omi_device_discovered_name
 *   deviceIsNotePinAdvertisement → omi_device_is_note_pin_advertisement
 *   deviceIsOmiLike          → omi_device_is_omi_like
 *   deviceShouldPersistBatteryReading → omi_device_should_persist_battery_reading
 *   deviceCharacteristicText → omi_device_characteristic_text
 *   deviceAssembler*         → omi_device_assembler_* (opaque jlong handles)
 *   deviceCapture*           → omi_device_capture_* (opaque jlong handles)
 */
class OmiPolicyJniBridge : NativePolicyBridge {

    companion object {
        init {
            // Built by src/main/cpp/CMakeLists.txt from native-core sources.
            System.loadLibrary("omi_native_core_jni")
        }

        @Volatile
        private var installed = false

        /** Replaces `Policy.bridge` exactly once, at host bootstrap. */
        fun installOnce(@Suppress("unused") context: Context) {
            if (installed) return
            synchronized(this) {
                if (installed) return
                Policy.bridge = OmiPolicyJniBridge()
                installed = true
            }
        }
    }

    override fun routeStrip(path: String): String? {
        val out = ByteArray(2048)
        val written = nativeRouteStrip(path, out)
        return if (written > 0) String(out, 0, written) else null
    }

    override fun isCapturePath(path: String): Boolean =
        nativeIsCapturePath(path) != 0

    override fun requestTimeoutSeconds(method: String, path: String): Int =
        nativeRequestTimeoutSeconds(method, path)

    override fun examplePlatformSupported(method: String, path: String): Boolean =
        nativeExamplePlatformSupported(method, path) != 0

    override fun isLoopbackHostname(hostname: String): Boolean =
        nativeIsLoopbackHostname(hostname) != 0

    override fun isCloudHostname(hostname: String): Boolean =
        nativeIsCloudHostname(hostname) != 0

    override fun isAllowedV5Hostname(hostname: String): Boolean =
        nativeIsAllowedV5Hostname(hostname) != 0

    override fun softwarePlaneIsNew(stored: String?, stampedValid: Boolean): Boolean =
        nativeSoftwarePlaneIsNew(stored, stampedValid) != 0

    override fun recordingCapturedAtValid(capturedAtSeconds: Double): Boolean =
        nativeRecordingCapturedAtValid(capturedAtSeconds) != 0

    override fun recordingRetryableStatus(status: Int): Boolean =
        nativeRecordingRetryableStatus(status) != 0

    override fun recordingOwnerKeyValid(ownerKey: String): Boolean =
        nativeRecordingOwnerKeyValid(ownerKey) != 0

    override fun recordingReceiptValid(receipt: String): Boolean =
        nativeRecordingReceiptValid(receipt) != 0

    override fun recordingUUIDValid(value: String): Boolean =
        nativeRecordingUUIDValid(value) != 0

    override fun packetChecksum(data: UByteArray): ULong =
        nativePacketChecksum(data.toByteArray()).toULong() and 0xFFFFFFFFUL

    override fun normalizePacket(raw: UByteArray): Tuple2<Int, UByteArray> {
        val payload = ByteArray(raw.size)
        val meta = IntArray(1)
        val status = nativeNormalizePacket(raw.toByteArray(), payload, meta)
        val actual =
            if (status == 0) payload.copyOfRange(0, meta[0].coerceIn(0, payload.size))
            else byteArrayOf()
        return Tuple2(status, actual.toUByteArray())
    }

    override fun nativeCapabilities(): String? {
        val out = ByteArray(4096)
        val written = nativeGetNativeCapabilities(out)
        return if (written > 0) String(out, 0, written) else null
    }

    // MARK: omi_device — portable BLE device logic (same C ABI as Apple).

    override fun deviceDiscoveredName(
        advertisedLocalName: String?,
        cachedName: String?,
        manufacturerData: UByteArray?,
    ): String = nativeDeviceDiscoveredName(
        advertisedLocalName,
        cachedName,
        manufacturerData?.toByteArray(),
    )

    override fun deviceIsNotePinAdvertisement(manufacturerData: UByteArray?): Boolean =
        nativeDeviceIsNotePinAdvertisement(manufacturerData?.toByteArray()) != 0

    override fun deviceIsOmiLike(name: String): Boolean =
        nativeDeviceIsOmiLike(name) != 0

    override fun deviceShouldPersistBatteryReading(
        previousLevel: Int?,
        previousTimestampMs: Long?,
        level: Int,
        nowMs: Long,
    ): Boolean = nativeDeviceShouldPersistBatteryReading(
        previousLevel ?: 0,
        previousLevel != null,
        previousTimestampMs ?: 0,
        previousTimestampMs != null,
        level,
        nowMs,
    ) != 0

    override fun deviceCharacteristicText(bytes: UByteArray?): String? =
        nativeDeviceCharacteristicText(bytes?.toByteArray())

    override fun deviceAssemblerCreate(): Long = nativeDeviceAssemblerCreate()

    override fun deviceAssemblerDestroy(handle: Long) =
        nativeDeviceAssemblerDestroy(handle)

    override fun deviceAssemblerReset(handle: Long) = nativeDeviceAssemblerReset(handle)

    override fun deviceAssemblerClassify(handle: Long, raw: UByteArray): DevicePacketDecision {
        val payload = ByteArray(raw.size)
        val meta = nativeDeviceAssemblerClassify(handle, raw.toByteArray(), payload)
            ?: return DevicePacketDecision(3, 0.toUShort(), UByteArray(0), -1)
        val kind = meta[0]
        val index = meta[1].toUShort()
        val codecStatus = meta[3]
        val actual =
            if (kind == 0) payload.copyOfRange(0, meta[2].coerceIn(0, payload.size))
            else byteArrayOf()
        return DevicePacketDecision(kind, index, actual.toUByteArray(), codecStatus)
    }

    override fun deviceCaptureCreate(): Long = nativeDeviceCaptureCreate()

    override fun deviceCaptureDestroy(handle: Long) = nativeDeviceCaptureDestroy(handle)

    override fun deviceCaptureStage(handle: Long): Int = nativeDeviceCaptureStage(handle)

    override fun deviceCaptureIsCapturing(handle: Long): Boolean =
        nativeDeviceCaptureIsCapturing(handle) != 0

    override fun deviceCaptureOpen(
        handle: Long,
        deviceId: String,
        deviceName: String?,
        codec: Int,
        nowMs: Long,
    ): Boolean = nativeDeviceCaptureOpen(handle, deviceId, deviceName, codec, nowMs)

    override fun deviceCaptureIngest(handle: Long, raw: UByteArray, receivedAtMs: Long): Long =
        nativeDeviceCaptureIngest(handle, raw.toByteArray(), receivedAtMs)

    override fun deviceCaptureFail(handle: Long) = nativeDeviceCaptureFail(handle)

    override fun deviceCaptureHandoff(handle: Long, nowMs: Long): DeviceCaptureHandoff? {
        val outs = LongArray(3)
        if (!nativeDeviceCaptureHandoff(handle, nowMs, outs)) return null
        val count = nativeDeviceCapturePacketCount(handle)
        val packets = ArrayList<DeviceCaptureHandoff.Packet>(count)
        for (position in 0 until count) {
            val payload = ByteArray(1024)
            val received = LongArray(1)
            val meta = nativeDeviceCapturePacketAt(handle, position, payload, received)
                ?: continue
            if (meta[0] != 0) continue
            val bytes = payload.copyOfRange(0, meta[2].coerceIn(0, payload.size))
            packets.add(
                DeviceCaptureHandoff.Packet(meta[1].toUShort(), bytes.toUByteArray(), received[0]),
            )
        }
        return DeviceCaptureHandoff(outs[0], outs[1], outs[2].toInt(), packets)
    }

    override fun deviceCaptureBatchCount(handle: Long): Int =
        nativeDeviceCaptureBatchCount(handle)

    override fun deviceCaptureBatchByteCount(handle: Long): Int =
        nativeDeviceCaptureBatchByteCount(handle)

    override fun deviceCaptureStartedAtMs(handle: Long): Long =
        nativeDeviceCaptureStartedAtMs(handle)

    override fun deviceCaptureDeviceId(handle: Long): String =
        nativeDeviceCaptureDeviceId(handle) ?: ""

    override fun deviceCaptureDeviceName(handle: Long): String? =
        nativeDeviceCaptureDeviceName(handle)

    override fun deviceCaptureCodec(handle: Long): Int = nativeDeviceCaptureCodec(handle)

    // Implemented in src/main/cpp/omi_jni.c against the native-core C ABI.
    private external fun nativeRouteStrip(path: String, out: ByteArray): Int
    private external fun nativeIsCapturePath(path: String): Int
    private external fun nativeRequestTimeoutSeconds(method: String, path: String): Int
    private external fun nativeExamplePlatformSupported(method: String, path: String): Int
    private external fun nativeIsLoopbackHostname(hostname: String): Int
    private external fun nativeIsCloudHostname(hostname: String): Int
    private external fun nativeIsAllowedV5Hostname(hostname: String): Int
    private external fun nativeSoftwarePlaneIsNew(stored: String?, stampedValid: Boolean): Int
    private external fun nativeRecordingCapturedAtValid(capturedAtSeconds: Double): Int
    private external fun nativeRecordingRetryableStatus(status: Int): Int
    private external fun nativeRecordingOwnerKeyValid(ownerKey: String): Int
    private external fun nativeRecordingReceiptValid(receipt: String): Int
    private external fun nativeRecordingUUIDValid(value: String): Int
    private external fun nativePacketChecksum(data: ByteArray): Long
    private external fun nativeNormalizePacket(raw: ByteArray, payloadOut: ByteArray, metaOut: IntArray): Int
    private external fun nativeGetNativeCapabilities(out: ByteArray): Int

    private external fun nativeDeviceDiscoveredName(advertised: String?, cached: String?, manufacturer: ByteArray?): String
    private external fun nativeDeviceIsNotePinAdvertisement(manufacturer: ByteArray?): Int
    private external fun nativeDeviceIsOmiLike(name: String): Int
    private external fun nativeDeviceShouldPersistBatteryReading(
        previousLevel: Int,
        hasPreviousLevel: Boolean,
        previousTimestampMs: Long,
        hasPreviousTimestampMs: Boolean,
        level: Int,
        nowMs: Long,
    ): Int
    private external fun nativeDeviceCharacteristicText(bytes: ByteArray?): String?
    private external fun nativeDeviceAssemblerCreate(): Long
    private external fun nativeDeviceAssemblerDestroy(handle: Long)
    private external fun nativeDeviceAssemblerReset(handle: Long)
    private external fun nativeDeviceAssemblerClassify(handle: Long, raw: ByteArray, payloadOut: ByteArray): IntArray?
    private external fun nativeDeviceCaptureCreate(): Long
    private external fun nativeDeviceCaptureDestroy(handle: Long)
    private external fun nativeDeviceCaptureStage(handle: Long): Int
    private external fun nativeDeviceCaptureIsCapturing(handle: Long): Int
    private external fun nativeDeviceCaptureOpen(handle: Long, deviceId: String, deviceName: String?, codec: Int, nowMs: Long): Boolean
    private external fun nativeDeviceCaptureIngest(handle: Long, raw: ByteArray, receivedAtMs: Long): Long
    private external fun nativeDeviceCaptureFail(handle: Long)
    private external fun nativeDeviceCaptureHandoff(handle: Long, nowMs: Long, outs: LongArray): Boolean
    private external fun nativeDeviceCapturePacketCount(handle: Long): Int
    private external fun nativeDeviceCaptureBatchCount(handle: Long): Int
    private external fun nativeDeviceCaptureBatchByteCount(handle: Long): Int
    private external fun nativeDeviceCaptureStartedAtMs(handle: Long): Long
    private external fun nativeDeviceCapturePacketAt(handle: Long, position: Int, payloadOut: ByteArray, outs: LongArray): IntArray?
    private external fun nativeDeviceCaptureDeviceId(handle: Long): String?
    private external fun nativeDeviceCaptureDeviceName(handle: Long): String?
    private external fun nativeDeviceCaptureCodec(handle: Long): Int
}
