package omi.v5.host

import android.content.Context
import omi.kit.NativePolicyBridge
import omi.kit.Policy
import skip.lib.Tuple2

/**
 * The Android half of the policy-injection contract: the shared native-core
 * C++ middleware, reached through JNI — never a Kotlin re-derivation.
 *
 * The Swift `NativePolicyBridge` protocol transpiles to this Kotlin interface
 * (omi.kit.NativePolicyBridge, generated by skipstone into the OmiKit
 * output tree); every method maps 1:1 onto a native-core C ABI entry point
 * (see native-core/include/*.h):
 *
 *   routeStrip               → omi_backend_route_strip
 *   isCapturePath            → omi_backend_is_capture_path
 *   requestTimeoutSeconds    → omi_backend_request_timeout_seconds
 *   examplePlatformSupported → omi_backend_example_platform_supported
 *   isLoopbackHostname       → omi_backend_is_loopback_hostname
 *   isCloudHostname          → omi_backend_is_cloud_hostname
 *   isAllowedV5Hostname      → omi_backend_is_allowed_v5_hostname
 *   softwarePlaneIsNew       → omi_backend_software_plane_is_new
 *   recordingCapturedAtValid → omi_backend_recording_captured_at_valid
 *   recordingRetryableStatus → omi_backend_recording_retryable_status
 *   recordingOwnerKeyValid   → omi_backend_recording_owner_key_valid
 *   recordingReceiptValid    → omi_backend_recording_receipt_valid
 *   recordingUUIDValid       → omi_backend_recording_uuid_valid
 *   packetChecksum           → omi_calculate_packet_checksum
 *   normalizePacket          → omi_normalize_packet
 *   nativeCapabilities       → omi_get_native_capabilities
 */
class OmiPolicyJniBridge : NativePolicyBridge {

    companion object {
        init {
            // Built by src/main/cpp/CMakeLists.txt from native-core sources.
            System.loadLibrary("omi_native_core_jni")
        }

        @Volatile
        private var installed = false

        /** Replaces `Policy.bridge` exactly once, at host bootstrap. */
        fun installOnce(@Suppress("unused") context: Context) {
            if (installed) return
            synchronized(this) {
                if (installed) return
                Policy.bridge = OmiPolicyJniBridge()
                installed = true
            }
        }
    }

    override fun routeStrip(path: String): String? {
        val out = ByteArray(2048)
        val written = nativeRouteStrip(path, out)
        return if (written > 0) String(out, 0, written) else null
    }

    override fun isCapturePath(path: String): Boolean =
        nativeIsCapturePath(path) != 0

    override fun requestTimeoutSeconds(method: String, path: String): Int =
        nativeRequestTimeoutSeconds(method, path)

    override fun examplePlatformSupported(method: String, path: String): Boolean =
        nativeExamplePlatformSupported(method, path) != 0

    override fun isLoopbackHostname(hostname: String): Boolean =
        nativeIsLoopbackHostname(hostname) != 0

    override fun isCloudHostname(hostname: String): Boolean =
        nativeIsCloudHostname(hostname) != 0

    override fun isAllowedV5Hostname(hostname: String): Boolean =
        nativeIsAllowedV5Hostname(hostname) != 0

    override fun softwarePlaneIsNew(stored: String?, stampedValid: Boolean): Boolean =
        nativeSoftwarePlaneIsNew(stored, stampedValid) != 0

    override fun recordingCapturedAtValid(capturedAtSeconds: Double): Boolean =
        nativeRecordingCapturedAtValid(capturedAtSeconds) != 0

    override fun recordingRetryableStatus(status: Int): Boolean =
        nativeRecordingRetryableStatus(status) != 0

    override fun recordingOwnerKeyValid(ownerKey: String): Boolean =
        nativeRecordingOwnerKeyValid(ownerKey) != 0

    override fun recordingReceiptValid(receipt: String): Boolean =
        nativeRecordingReceiptValid(receipt) != 0

    override fun recordingUUIDValid(value: String): Boolean =
        nativeRecordingUUIDValid(value) != 0

    override fun packetChecksum(data: UByteArray): ULong =
        nativePacketChecksum(data.toByteArray()).toULong() and 0xFFFFFFFFUL

    override fun normalizePacket(raw: UByteArray): Tuple2<Int, UByteArray> {
        val payload = ByteArray(raw.size)
        val status = nativeNormalizePacket(raw.toByteArray(), payload)
        val actual = if (status == 0) payload else byteArrayOf()
        return Tuple2(status, actual.toUByteArray())
    }

    override fun nativeCapabilities(): String? {
        val out = ByteArray(4096)
        val written = nativeGetNativeCapabilities(out)
        return if (written > 0) String(out, 0, written) else null
    }

    // Implemented in src/main/cpp/omi_jni.c against the native-core C ABI.
    private external fun nativeRouteStrip(path: String, out: ByteArray): Int
    private external fun nativeIsCapturePath(path: String): Int
    private external fun nativeRequestTimeoutSeconds(method: String, path: String): Int
    private external fun nativeExamplePlatformSupported(method: String, path: String): Int
    private external fun nativeIsLoopbackHostname(hostname: String): Int
    private external fun nativeIsCloudHostname(hostname: String): Int
    private external fun nativeIsAllowedV5Hostname(hostname: String): Int
    private external fun nativeSoftwarePlaneIsNew(stored: String?, stampedValid: Boolean): Int
    private external fun nativeRecordingCapturedAtValid(capturedAtSeconds: Double): Int
    private external fun nativeRecordingRetryableStatus(status: Int): Int
    private external fun nativeRecordingOwnerKeyValid(ownerKey: String): Int
    private external fun nativeRecordingReceiptValid(receipt: String): Int
    private external fun nativeRecordingUUIDValid(value: String): Int
    private external fun nativePacketChecksum(data: ByteArray): Long
    private external fun nativeNormalizePacket(raw: ByteArray, payloadOut: ByteArray): Int
    private external fun nativeGetNativeCapabilities(out: ByteArray): Int
}
