---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dev-omi-backend-listen-scale-down
  namespace: dev-omi-backend
spec:
  schedule: "0 0 * * *"  # Reduce minReplicas to 1 at 00:00 UTC
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  timeZone: UTC
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: dev-omi-backend-listen-scaler-sa
          containers:
          - name: dev-omi-backend-listen-scale-down
            image: bitnami/kubectl:1.33
            command: ["/bin/sh", "-c"]
            args:
            - kubectl -n dev-omi-backend patch hpa dev-omi-backend-listen
              --patch '{"spec":{"minReplicas":1}}'
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dev-omi-backend-listen-scale-up
  namespace: dev-omi-backend
spec:
  schedule: "0 12 * * *"  # Increase minReplicas to 2 at 12:00 UTC
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  timeZone: UTC
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: dev-omi-backend-listen-scaler-sa
          containers:
          - name: dev-omi-backend-listen-scale-up
            image: bitnami/kubectl:1.33
            command: ["/bin/sh", "-c"]
            args:
            - kubectl -n dev-omi-backend patch hpa dev-omi-backend-listen
              --patch '{"spec":{"minReplicas":2}}'
          restartPolicy: OnFailure
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-omi-backend-listen-scaler-sa
  namespace: dev-omi-backend
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-omi-backend-listen-scaler-role
  namespace: dev-omi-backend
rules:
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-omi-backend-listen-scaler-role-binding
  namespace: dev-omi-backend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  name: dev-omi-backend-listen-scaler-role
  kind: Role
subjects:
- kind: ServiceAccount
  name: dev-omi-backend-listen-scaler-sa
  namespace: dev-omi-backend
