"""
AUTO-GENERATED by backend/scripts/generate_integration_sdks.py from docs/api-reference/integration-public-openapi.json.
Do not edit by hand. Re-run the generator after OpenAPI changes.
Spec sha256[0:16]=8d7149a8abe86509
"""

from .client import OmiIntegrationClient, OmiIntegrationError

__all__ = ["OmiIntegrationClient", "OmiIntegrationError"]
