{
 "title": "Plugins",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Request count (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "aliasBy": "{{metric.label.response_code_class}}",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.location",
       "=",
       "us-central1",
       "AND",
       "resource.label.project_id",
       "=",
       "based-hardware",
       "AND",
       "resource.label.service_name",
       "=",
       "plugins",
       "AND",
       "metric.type",
       "=",
       "run.googleapis.com/request_count"
      ],
      "groupBys": [
       "metric.label.response_code_class"
      ],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": " Max concurrent requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "aliasBy": "p50",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "filters": [
       "resource.label.location",
       "=",
       "us-central1",
       "AND",
       "resource.label.project_id",
       "=",
       "based-hardware",
       "AND",
       "resource.label.service_name",
       "=",
       "plugins",
       "AND",
       "metric.type",
       "=",
       "run.googleapis.com/container/max_request_concurrencies"
      ],
      "groupBys": [ "resource.label.service_name" ],
      "perSeriesAligner": "ALIGN_SUM",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    },
    {
     "aliasBy": "p95",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "filters": [
       "resource.label.location",
       "=",
       "us-central1",
       "AND",
       "resource.label.project_id",
       "=",
       "based-hardware",
       "AND",
       "resource.label.service_name",
       "=",
       "plugins",
       "AND",
       "metric.type",
       "=",
       "run.googleapis.com/container/max_request_concurrencies"
      ],
      "groupBys": [ "resource.label.service_name" ],
      "perSeriesAligner": "ALIGN_SUM",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    },
    {
     "aliasBy": "p99",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_99",
      "filters": [
       "resource.label.location",
       "=",
       "us-central1",
       "AND",
       "resource.label.project_id",
       "=",
       "based-hardware",
       "AND",
       "resource.label.service_name",
       "=",
       "plugins",
       "AND",
       "metric.type",
       "=",
       "run.googleapis.com/container/max_request_concurrencies"
      ],
      "groupBys": [ "resource.label.service_name" ],
      "perSeriesAligner": "ALIGN_SUM",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": " Request latencies",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "aliasBy": "p50",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "filters": [
       "resource.label.location",
       "=",
       "us-central1",
       "AND",
       "resource.label.project_id",
       "=",
       "based-hardware",
       "AND",
       "resource.label.service_name",
       "=",
       "plugins",
       "AND",
       "metric.type",
       "=",
       "run.googleapis.com/request_latencies"
      ],
      "groupBys": [ "resource.label.service_name" ],
      "perSeriesAligner": "ALIGN_SUM",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    },
    {
     "aliasBy": "p95",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "filters": [
       "resource.label.location",
       "=",
       "us-central1",
       "AND",
       "resource.label.project_id",
       "=",
       "based-hardware",
       "AND",
       "resource.label.service_name",
       "=",
       "plugins",
       "AND",
       "metric.type",
       "=",
       "run.googleapis.com/request_latencies"
      ],
      "groupBys": [ "resource.label.service_name" ],
      "perSeriesAligner": "ALIGN_SUM",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    },
    {
     "aliasBy": "p99",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_99",
      "filters": [
       "resource.label.location",
       "=",
       "us-central1",
       "AND",
       "resource.label.project_id",
       "=",
       "based-hardware",
       "AND",
       "resource.label.service_name",
       "=",
       "plugins",
       "AND",
       "metric.type",
       "=",
       "run.googleapis.com/request_latencies"
      ],
      "groupBys": [ "resource.label.service_name" ],
      "perSeriesAligner": "ALIGN_SUM",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Instance count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "aliasBy": "{{metric.label.state}}",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MAX",
      "filters": [
       "resource.label.service_name",
       "=",
       "plugins",
       "AND",
       "metric.type",
       "=",
       "run.googleapis.com/container/instance_count"
      ],
      "groupBys": [ "metric.label.state" ],
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Container CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "aliasBy": "p50",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "filters": [
       "resource.label.location",
       "=",
       "us-central1",
       "AND",
       "resource.label.project_id",
       "=",
       "based-hardware",
       "AND",
       "resource.label.service_name",
       "=",
       "plugins",
       "AND",
       "metric.type",
       "=",
       "run.googleapis.com/container/cpu/utilizations"
      ],
      "groupBys": [ "resource.label.service_name" ],
      "perSeriesAligner": "ALIGN_SUM",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    },
    {
     "aliasBy": "p95",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "filters": [
       "resource.label.location",
       "=",
       "us-central1",
       "AND",
       "resource.label.project_id",
       "=",
       "based-hardware",
       "AND",
       "resource.label.service_name",
       "=",
       "plugins",
       "AND",
       "metric.type",
       "=",
       "run.googleapis.com/container/cpu/utilizations"
      ],
      "groupBys": [ "resource.label.service_name" ],
      "perSeriesAligner": "ALIGN_SUM",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    },
    {
     "aliasBy": "p99",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_99",
      "filters": [
       "resource.label.location",
       "=",
       "us-central1",
       "AND",
       "resource.label.project_id",
       "=",
       "based-hardware",
       "AND",
       "resource.label.service_name",
       "=",
       "plugins",
       "AND",
       "metric.type",
       "=",
       "run.googleapis.com/container/cpu/utilizations"
      ],
      "groupBys": [ "resource.label.service_name" ],
      "perSeriesAligner": "ALIGN_SUM",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Container memory utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "aliasBy": "p50",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "filters": [
       "resource.label.location",
       "=",
       "us-central1",
       "AND",
       "resource.label.project_id",
       "=",
       "based-hardware",
       "AND",
       "resource.label.service_name",
       "=",
       "plugins",
       "AND",
       "metric.type",
       "=",
       "run.googleapis.com/container/memory/utilizations"
      ],
      "groupBys": [ "resource.label.service_name" ],
      "perSeriesAligner": "ALIGN_SUM",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    },
    {
     "aliasBy": "p95",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "filters": [
       "resource.label.location",
       "=",
       "us-central1",
       "AND",
       "resource.label.project_id",
       "=",
       "based-hardware",
       "AND",
       "resource.label.service_name",
       "=",
       "plugins",
       "AND",
       "metric.type",
       "=",
       "run.googleapis.com/container/memory/utilizations"
      ],
      "groupBys": [ "resource.label.service_name" ],
      "perSeriesAligner": "ALIGN_SUM",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    },
    {
     "aliasBy": "p99",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_99",
      "filters": [
       "resource.label.location",
       "=",
       "us-central1",
       "AND",
       "resource.label.project_id",
       "=",
       "based-hardware",
       "AND",
       "resource.label.service_name",
       "=",
       "plugins",
       "AND",
       "metric.type",
       "=",
       "run.googleapis.com/container/memory/utilizations"
      ],
      "groupBys": [ "resource.label.service_name" ],
      "perSeriesAligner": "ALIGN_SUM",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Sent bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "aliasBy": "{{metric.label.kind}}",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.location",
       "=",
       "us-central1",
       "AND",
       "resource.label.project_id",
       "=",
       "based-hardware",
       "AND",
       "resource.label.service_name",
       "=",
       "plugins",
       "AND",
       "metric.type",
       "=",
       "run.googleapis.com/container/network/sent_bytes_count"
      ],
      "groupBys": [ "metric.label.kind" ],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Received bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "aliasBy": "{{metric.label.kind}}",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_NONE",
      "filters": [
       "resource.label.location",
       "=",
       "us-central1",
       "AND",
       "resource.label.project_id",
       "=",
       "based-hardware",
       "AND",
       "resource.label.service_name",
       "=",
       "plugins",
       "AND",
       "metric.type",
       "=",
       "run.googleapis.com/container/network/received_bytes_count"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Container startup latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "aliasBy": "p50",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_50",
      "filters": [
       "resource.label.location",
       "=",
       "us-central1",
       "AND",
       "resource.label.project_id",
       "=",
       "based-hardware",
       "AND",
       "resource.label.service_name",
       "=",
       "plugins",
       "AND",
       "metric.type",
       "=",
       "run.googleapis.com/container/startup_latencies"
      ],
      "groupBys": [ "resource.label.service_name" ],
      "perSeriesAligner": "ALIGN_SUM",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    },
    {
     "aliasBy": "p95",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_95",
      "filters": [
       "resource.label.location",
       "=",
       "us-central1",
       "AND",
       "resource.label.project_id",
       "=",
       "based-hardware",
       "AND",
       "resource.label.service_name",
       "=",
       "plugins",
       "AND",
       "metric.type",
       "=",
       "run.googleapis.com/container/startup_latencies"
      ],
      "groupBys": [ "resource.label.service_name" ],
      "perSeriesAligner": "ALIGN_SUM",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    },
    {
     "aliasBy": "p99",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_99",
      "filters": [
       "resource.label.location",
       "=",
       "us-central1",
       "AND",
       "resource.label.project_id",
       "=",
       "based-hardware",
       "AND",
       "resource.label.service_name",
       "=",
       "plugins",
       "AND",
       "metric.type",
       "=",
       "run.googleapis.com/container/startup_latencies"
      ],
      "groupBys": [ "resource.label.service_name" ],
      "perSeriesAligner": "ALIGN_SUM",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  }
 ]
}