// AUTO-GENERATED by backend/scripts/generate_integration_sdks.py from docs/api-reference/integration-public-openapi.json.
// Do not edit by hand. Re-run the generator after OpenAPI changes.
// Spec sha256[0:16]=726f4b3a685da076


#pragma once

#include <map>
#include <memory>
#include <optional>
#include <stdexcept>
#include <string>
#include <vector>

namespace omi {
namespace integration {

struct JsonValue {
  // Opaque JSON text payload (object/array/scalar). Callers parse with their JSON lib.
  std::string raw;
};

class ApiError : public std::runtime_error {
 public:
  ApiError(int status, std::string body)
      : std::runtime_error("Omi Integration API error: HTTP " + std::to_string(status)),
        status_(status),
        body_(std::move(body)) {}
  int status() const { return status_; }
  const std::string& body() const { return body_; }

 private:
  int status_;
  std::string body_;
};

class Client {
 public:
  Client(std::string api_key, std::string app_id, std::string base_url = "https://api.omi.me");
  ~Client();

  Client(const Client&) = delete;
  Client& operator=(const Client&) = delete;


  // Send App Notification To User
  JsonValue send_notification_v1(const std::string& json_body);

  // Get Conversations Via Integration
  JsonValue list_conversations(const std::string& uid, std::optional<int> limit = std::nullopt, std::optional<int> offset = std::nullopt, std::optional<bool> include_discarded = std::nullopt, std::optional<std::vector<std::string>> statuses = std::nullopt, std::optional<std::string> start_date = std::nullopt, std::optional<std::string> end_date = std::nullopt, std::optional<int> max_transcript_segments = std::nullopt);

  // Get Memories Via Integration
  JsonValue list_memories(const std::string& uid, std::optional<int> limit = std::nullopt, std::optional<int> offset = std::nullopt);

  // Send Notification Via Integration
  JsonValue send_notification(const std::string& message, const std::string& uid);

  // Search Conversations Via Integration
  JsonValue search_conversations(const std::string& uid, const std::string& json_body, std::optional<int> max_transcript_segments = std::nullopt);

  // Get Tasks Via Integration
  JsonValue list_tasks(const std::string& uid, std::optional<int> limit = std::nullopt, std::optional<int> offset = std::nullopt, std::optional<bool> completed = std::nullopt, std::optional<std::string> conversation_id = std::nullopt, std::optional<std::string> start_date = std::nullopt, std::optional<std::string> end_date = std::nullopt, std::optional<std::string> due_start_date = std::nullopt, std::optional<std::string> due_end_date = std::nullopt);

  // Create Conversation Via Integration
  JsonValue create_conversation(const std::string& uid, const std::string& json_body);

  // Create Memories Via Integration
  JsonValue create_memories(const std::string& uid, const std::string& json_body);

 private:
  JsonValue request(const std::string& method, const std::string& path,
                    const std::map<std::string, std::string>& query,
                    const std::string* json_body);

  std::string api_key_;
  std::string app_id_;
  std::string base_url_;
};

}  // namespace integration
}  // namespace omi

