{{- if .Values.objstore.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: rustfs
  labels:
    {{- include "omi-onprem.labels" . | nindent 4 }}
    app.kubernetes.io/component: rustfs
spec:
  selector:
    app.kubernetes.io/component: rustfs
  ports:
    - name: s3
      port: 9000
      targetPort: 9000
{{- end }}
