"""Words the introduction patterns can capture that are never real names.

Lives apart from ``speaker_identification`` so the pure text-gating paths can
share the list without importing ``av``, numpy and Firestore.
"""

# Pronouns and filler words the introduction patterns can capture from run-on
# transcripts (e.g. "I'm It was great", "I'm You know...") — never real names (#5223).
SPEAKER_NAME_STOPWORDS = frozenset(
    {
        'it',
        'you',
        'they',
        'them',
        'he',
        'she',
        'we',
        'us',
        'me',
        'him',
        'her',
        'his',
        'hers',
        'its',
        'my',
        'mine',
        'your',
        'yours',
        'our',
        'ours',
        'their',
        'theirs',
        'this',
        'that',
        'these',
        'those',
        'here',
        'there',
        'what',
        'who',
        'when',
        'where',
        'why',
        'how',
        'which',
        'the',
        'and',
        'but',
        'not',
        'yes',
        'no',
        'okay',
        'ok',
        'yeah',
        'just',
        'like',
        'so',
        'very',
        'really',
        'now',
        'then',
        'well',
        'still',
        'also',
        'too',
        'gonna',
        'going',
        'sure',
        'sorry',
        'good',
        'fine',
        'right',
        'everyone',
        'everybody',
        'someone',
        'somebody',
        'nobody',
        'anyone',
        'anybody',
        'something',
        'nothing',
        'one',
        'all',
        'some',
    }
)
