#!/usr/bin/env bash
# Side-effect-free helpers for run.sh's incremental development bundle lane.
# A successful full bundle records this fingerprint outside the app bundle. A
# later launch may reuse that bundle only when every packaged input and launch
# configuration still matches.

omi_fast_bundle_fingerprint() {
  local macos_dir="$1"
  shift

  python3 - "$macos_dir" "$@" <<'PY'
import hashlib
import os
import stat
import sys

root = os.path.abspath(sys.argv[1])
config = sys.argv[2:]
digest = hashlib.sha256()


def record(value: str) -> None:
    digest.update(value.encode("utf-8"))
    digest.update(b"\0")


def record_file(relative: str, include_content: bool = True) -> None:
    path = os.path.join(root, relative)
    if not os.path.lexists(path):
        record(f"missing:{relative}")
        return
    mode = os.lstat(path).st_mode
    if stat.S_ISLNK(mode):
        record(f"link:{relative}:{os.readlink(path)}")
        return
    if not stat.S_ISREG(mode):
        record(f"unsupported:{relative}:{mode:o}")
        return
    details = os.stat(path)
    record(f"file:{relative}:{mode & 0o7777:o}:{details.st_size}")
    if include_content:
        with open(path, "rb") as handle:
            for chunk in iter(lambda: handle.read(1024 * 1024), b""):
                digest.update(chunk)
    else:
        # The universal Node executable is large and generated by the agent
        # preparation step. Its size/mtime detects a changed staged runtime;
        # agent source/package changes are already content-hashed below.
        record(f"metadata:{details.st_size}:{details.st_mtime_ns}")


def record_tree(relative: str, *, exclude_names=None) -> None:
    path = os.path.join(root, relative)
    if not os.path.lexists(path):
        record(f"missing-tree:{relative}")
        return
    if not os.path.isdir(path) or os.path.islink(path):
        record_file(relative)
        return

    exclude_names = exclude_names or set()
    record(f"tree:{relative}")
    for current, dirs, files in os.walk(path, followlinks=False):
        dirs[:] = sorted(name for name in dirs if name not in exclude_names)
        files.sort()
        for name in files:
            nested = os.path.relpath(os.path.join(current, name), root)
            record_file(nested)
        for name in dirs:
            nested = os.path.relpath(os.path.join(current, name), root)
            if os.path.islink(os.path.join(current, name)):
                record_file(nested)


record("schema:1")
for value in config:
    record(f"config:{value}")

for path in [
    "run.sh",
    "omi_icon.icns",
    "Desktop/Package.swift",
    "Desktop/Package.resolved",
    "Desktop/Info.plist",
    "Desktop/Omi.entitlements",
    "Desktop/Node.entitlements",
    "Desktop/Omi-Release.entitlements",
    "Desktop/Sources/GoogleService-Info.plist",
    "Desktop/Sources/GoogleService-Info-Dev.plist",
    "Desktop/Sources/GoogleService-Info-Local.plist",
    "Backend-Rust/.env.app",
    "Backend-Rust/.env.app.dev",
    "scripts/app-config.sh",
    "scripts/prepare-agent-runtime.sh",
    "scripts/agent-runtime-cache.sh",
    "scripts/prepare-desktop-bundle-native-deps.sh",
    "scripts/prepare-local-dev-entitlements.sh",
    "scripts/audit-desktop-bundle-deps.sh",
    "agent/package.json",
    "agent/package-lock.json",
    "agent/tsconfig.json",
    "pi-mono-extension/package.json",
    "pi-mono-extension/package-lock.json",
    "pi-mono-extension/index.ts",
]:
    record_file(path)

for path, excluded in [
    ("Desktop/CWebP", set()),
    ("Desktop/ObjCExceptionCatcher", set()),
    ("Desktop/Sources/Resources", {"node"}),
    ("agent/src", set()),
    ("agent/scripts", set()),
]:
    record_tree(path, exclude_names=excluded)

record_file("Desktop/Sources/Resources/node", include_content=False)
print(digest.hexdigest())
PY
}

omi_fast_bundle_stamp_matches() {
  local stamp="$1"
  local expected_fingerprint="$2"
  [ -f "$stamp" ] || return 1
  [ "$(sed -n 's/^fingerprint=//p' "$stamp" | head -1)" = "$expected_fingerprint" ]
}

omi_fast_bundle_write_stamp() {
  local stamp="$1"
  local fingerprint="$2"
  local temp
  mkdir -p "$(dirname "$stamp")"
  temp="$(mktemp "${stamp}.tmp.XXXXXX")"
  printf 'version=1\nfingerprint=%s\n' "$fingerprint" > "$temp"
  mv -f "$temp" "$stamp"
}
