{
 "title": "Deepgram self-hosted",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Engine active requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(kind) (engine_active_requests)",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Deepgram Engine Replicas",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{deployment=\"deepgram-engine\"})",
     "legendFormat": "Replicas"
    }
   ]
  },
  {
   "title": "Engine Stream latency by quantile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "histogram_quantile(0.10, sum by (le) (rate(engine_stream_latency_bucket[5m]))) or vector(0)",
     "legendFormat": "p10"
    },
    {
     "expr": "histogram_quantile(0.25, sum by (le) (rate(engine_stream_latency_bucket[5m]))) or vector(0)",
     "legendFormat": "p20"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(engine_stream_latency_bucket[5m]))) or vector(0)",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by (le) (rate(engine_stream_latency_bucket[5m]))) or vector(0)",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(engine_stream_latency_bucket[5m]))) or vector(0)",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(engine_stream_latency_bucket[5m]))) or vector(0)",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(engine_stream_latency_bucket[5m]))) or vector(0)",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Engine active requests per pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by(instance) (engine_active_requests)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Engine estimated stream capacity per instance",
   "type": "timeseries",
   "description": "The number of streams the node believes it can serve with acceptable latency",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "engine_estimated_stream_capacity",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Engine Requests per second by Request kind",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum by (kind)(rate(engine_requests_total[5m]))",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Engine Requests per second by Response status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by (response_status)(rate(engine_requests_total[5m]))",
     "legendFormat": "{{response_status}}"
    }
   ]
  },
  {
   "title": "Avg. GPU VRAM utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_FB_USED{container=\"deepgram-engine\"} * 100 / DCGM_FI_DEV_FB_TOTAL{container=\"deepgram-engine\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Avg. GPU utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(DCGM_FI_DEV_GPU_UTIL{container=\"deepgram-engine\"}[1m]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "GPU utilization per pod (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{container=\"deepgram-engine\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GPU VRAM utilization per pod (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{container=\"deepgram-engine\"} * 100 / DCGM_FI_DEV_FB_TOTAL{container=\"deepgram-engine\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}