{
 "title": "Diarizer",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Request count (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "aliasBy": "RPS",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "k8s1-5245918b-prod-omi-backend-prod-omi-diarizer-8080-cb654677",
       "AND",
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/internal/backend_request_count"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "promQLQuery": {
      "expr": "histogram_quantile(0.50, sum by (\"le\")(rate({\"__name__\"=\"loadbalancing_googleapis_com:https_internal_backend_latencies_bucket\",\"monitored_resource\"=\"internal_http_lb_rule\",\"backend_target_name\"=\"k8s1-5245918b-prod-omi-backend-prod-omi-diarizer-8080-cb654677\"}[1m])))",
      "projectName": "based-hardware",
      "step": "10s"
     },
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "custom-domains-api-omi-me-backend-listen-49a4-be",
       "AND",
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/backend_latencies"
      ],
      "groupBys": [
       "resource.label.backend_target_name"
      ],
      "perSeriesAligner": "ALIGN_SUM",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    },
    {
     "promQLQuery": {
      "expr": "histogram_quantile(0.95, sum by (\"le\")(rate({\"__name__\"=\"loadbalancing_googleapis_com:https_internal_backend_latencies_bucket\",\"monitored_resource\"=\"internal_http_lb_rule\",\"backend_target_name\"=\"k8s1-5245918b-prod-omi-backend-prod-omi-diarizer-8080-cb654677\"}[1m])))",
      "projectName": "based-hardware",
      "step": "10s"
     },
     "timeSeriesList": {
      "filters": [],
      "projectName": "based-hardware",
      "view": "FULL"
     }
    },
    {
     "promQLQuery": {
      "expr": "histogram_quantile(0.99, sum by (\"le\")(rate({\"__name__\"=\"loadbalancing_googleapis_com:https_internal_backend_latencies_bucket\",\"monitored_resource\"=\"internal_http_lb_rule\",\"backend_target_name\"=\"k8s1-5245918b-prod-omi-backend-prod-omi-diarizer-8080-cb654677\"}[1m])))",
      "projectName": "based-hardware",
      "step": "10s"
     },
     "timeSeriesList": {
      "filters": [],
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "aliasBy": "4XX",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "k8s1-5245918b-prod-omi-backend-prod-omi-diarizer-8080-cb654677",
       "AND",
       "metric.label.response_code_class",
       "=",
       "400",
       "AND",
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/internal/backend_request_count"
      ],
      "groupBys": [
       "metric.label.response_code_class"
      ],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    },
    {
     "aliasBy": "5XX",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "k8s1-5245918b-prod-omi-backend-prod-omi-diarizer-8080-cb654677",
       "AND",
       "metric.label.response_code_class",
       "=",
       "500",
       "AND",
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/internal/backend_request_count"
      ],
      "groupBys": [
       "metric.label.response_code_class"
      ],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Response code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "aliasBy": "{{metric.label.response_code}}",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.backend_target_name",
       "=",
       "k8s1-5245918b-prod-omi-backend-prod-omi-diarizer-8080-cb654677",
       "AND",
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/internal/backend_request_count"
      ],
      "groupBys": [ "metric.label.response_code" ],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Replica count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{deployment=\"prod-omi-diarizer\"})",
     "legendFormat": "Replicas"
    }
   ]
  },
  {
   "title": "HPA replica status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{deployment=\"prod-omi-diarizer\"})",
     "legendFormat": "Current replicas"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_min_replicas{horizontalpodautoscaler=\"prod-omi-diarizer\"}",
     "legendFormat": "Min replicas"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_max_replicas{horizontalpodautoscaler=\"prod-omi-diarizer\"}",
     "legendFormat": "Max replicas"
    }
   ]
  },
  {
   "title": "HPA metric status - Request Latency P99",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_target_metric{horizontalpodautoscaler=\"prod-omi-diarizer\",metric_name=\"diarizer_request_latency_p99\"}",
     "legendFormat": "{{metric_name}} - Current"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_target_metric{horizontalpodautoscaler=\"prod-omi-diarizer\",metric_name=\"diarizer_request_latency_p99\"}",
     "legendFormat": "{{metric_name}} - Target"
    }
   ]
  },
  {
   "title": "GPU active time",
   "type": "timeseries",
   "description": "Ratio of time the graphics engine is active.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_GR_ENGINE_ACTIVE{container=\"diarizer\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "HPA metric status - %CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_target_metric{horizontalpodautoscaler=\"prod-omi-diarizer\",metric_name=\"cpu\",metric_target_type=\"utilization\"}",
     "legendFormat": "{{metric_name}} - Current"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_target_metric{horizontalpodautoscaler=\"prod-omi-diarizer\",metric_name=\"cpu\"}",
     "legendFormat": "{{metric_name}} - Target"
    }
   ]
  },
  {
   "title": "HPA metric status - %Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_target_metric{horizontalpodautoscaler=\"prod-omi-diarizer\",metric_name=\"memory\",metric_target_type=\"utilization\"}",
     "legendFormat": "{{metric_name}} - Current"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_target_metric{horizontalpodautoscaler=\"prod-omi-diarizer\",metric_name=\"memory\"}",
     "legendFormat": "{{metric_name}} - Target"
    }
   ]
  }
 ]
}