import { expect, test } from "bun:test";
import { projectTreeInputSnapshot, type GraphSnapshot } from "./index";
import { buildDeterministicAnchors, nodeId } from "./tree";

const entity = (id: string, handle: string) => ({ entity_id: id, owner_account_id: "owner", entity_revision_id: `${id}:r1`, handle, labels: [] });
const c = (id: string, subject: string, labels: string[] = [], status: "canonical" | "provisional_unresolved_subject" = "canonical") => ({ revision_id: id, placement_status: status, claim: { claim_lineage_id: `lineage:${id}`, claim_revision_id: id, owner_account_id: "owner", predicate: "met", arguments: [{ slot_id: "subject", role: "subject", value: { kind: "entity_ref" as const, ref: subject } }], temporal_scope: { observed_at: "2026-01-02T10:00:00Z", precision: "instant", ...(status === "canonical" ? { valid_time: { typed_expression: { kind: "absolute" as const, granularity: "instant" as const, value: "2026-01-02T10:00:00Z" }, resolved_interval: { kind: "instant" as const, start: "2026-01-02T10:00:00.000Z", end: "2026-01-02T10:00:00.000Z", timezone: "UTC", granularity: "instant" as const }, derivation: { resolver_version: "g0-v1", timezone: "UTC" } } } : {}) }, evidence_refs: ["e1"], policy_labels: labels, source_language: "en", scope: { locality: "durable" as const, scope_ref: subject }, lifecycle: status === "canonical" ? "canonical" as const : "provisional" as const, ...(status === "canonical" ? { canonical_claim_id: `canon:${id}`, source_provisional_revision_ids: [] } : { ambiguity_markers: ["unresolved_subject"], context_packet: null }) } });
const snapshot = (merged = true): GraphSnapshot => ({ owner_account_id: "owner", graph_generation: merged ? 1 : 2, claims: [c("a", "old"), c("provisional", "old", [], "provisional_unresolved_subject"), c("private", "old", ["sensitivity:private"])], entities: [{ revision_id: "old:r1", entity: entity("old", "z") }, { revision_id: "survivor:r1", entity: entity("survivor", "a") }], identity_constraints: [{ revision_id: "merge", constraint: { constraint_id: "merge", owner_account_id: "owner", endpoints: [{ kind: "entity", entity_id: "old" }, { kind: "entity", entity_id: "survivor" }], left_handle: "legacy:z", right_handle: "legacy:a", relation: "same", evidence_refs: ["e1"], identity_authorization: { authorization_id: "auth:merge", owner_account_id: "owner", endpoints: [{ kind: "entity", entity_id: "old" }, { kind: "entity", entity_id: "survivor" }], relation: "same", support: { kind: "owner_confirmation", confirmation_ref: "confirm:merge" }, standing_policy_ref: null, namespace_scope: { namespace_instance_ref: null, identity_domain: null, scope_ref: null }, authority_policy_version: "identity-policy:v1", evaluated_frontier: 1, actor_provenance: { actor_ref: "owner", producer_ref: null }, lifecycle: "active", superseded_by: null }, effective_at: 1, reversed_at: merged ? null : 2 } }], events: [{ revision_id: "event", event: { event_id: "event", event_revision_id: "event", owner_account_id: "owner", capture_session_id: "capture", stream_id: "s", event_kind: "text", payload_schema_ref: "text", schema_version: "v1", payload: {}, event_time: "2026-01-02", ingest_time: "2026-01-02", source_sequence: 0, evidence_addressable_refs: ["e1"], source_trust: "test", policy_labels: [], canonical_redacted_hash: "h" } }], evidence: [{ revision_id: "e", evidence: { evidence_id: "e1", event_revision_id: "event", source_unit_ref: null, range: { start: 0, end: 1 }, excerpt: "x", source_identity_ref: null, speaker_rendering: null, source_local_mention_ref: null, state: "active", source_trust: "test", policy_labels: [], source_independence_key: "k" } }], adjacency: [] });

test("R1 merge moves entity members to survivor and split restores the original root", () => {
  const merged = buildDeterministicAnchors(projectTreeInputSnapshot(snapshot(), { account_timezone: "UTC" }));
  expect(new Set(merged.nodes.filter((node) => node.view_kind === "entity").map((node) => node.anchor_key))).toEqual(new Set(["entity:old"]));
  const split = buildDeterministicAnchors(projectTreeInputSnapshot(snapshot(false), { account_timezone: "UTC" }));
  expect(split.nodes.filter((node) => node.view_kind === "entity").map((node) => node.anchor_key)).toContain("entity:old");
});

test("R1 keeps provisional content only in source anchors and partitions node identities", () => {
  const input = projectTreeInputSnapshot(snapshot(), { account_timezone: "UTC" });
  const tree = buildDeterministicAnchors(input);
  expect(tree.nodes.filter((node) => node.view_kind === "entity").flatMap((node) => node.member_claim_revision_ids)).not.toContain("provisional");
  expect(tree.nodes.filter((node) => node.view_kind === "source").flatMap((node) => node.member_claim_revision_ids)).toContain("provisional");
  const sameAnchor = tree.nodes.filter((node) => node.view_kind === "temporal" && node.anchor_key.endsWith("day:02"));
  expect(new Set(sameAnchor.map((node) => node.node_id)).size).toBe(2);
  expect(nodeId("owner", "temporal", sameAnchor[0]!.anchor_key, sameAnchor[0]!.policy_partition_label)).toBe(sameAnchor[0]!.node_id);
});
