package com.rnruntime;

public final class BleLeaseTest {
  public static void main(String[] args) {
    OmiBleLease.Scan<String> scan = new OmiBleLease.Scan<>();
    int[] scanStops = {0}, scanResults = {0}, scanFailures = {0};
    scan.begin(value -> { assert value.equals("devices"); scanResults[0]++; }, error -> scanFailures[0]++);
    long scanTicket = scan.started();
    assert scan.active() && scan.accepts(scanTicket);
    scan.stop(() -> scanStops[0]++, () -> "devices");
    assert !scan.active() && !scan.accepts(scanTicket) && scanStops[0] == 1 && scanResults[0] == 1;
    scan.stop(() -> scanStops[0]++, () -> "devices");
    assert scanStops[0] == 1 && scanResults[0] == 1;
    scan.begin(value -> { assert value.equals("new devices"); scanResults[0]++; }, error -> scanFailures[0]++);
    long nextScanTicket = scan.started();
    if (scan.accepts(scanTicket)) scan.stop(() -> scanStops[0]++, () -> "wrong devices");
    assert scan.active() && scan.accepts(nextScanTicket) && scanResults[0] == 1;
    assert !scan.stop(() -> { throw new SecurityException(); }, () -> { throw new AssertionError("Failure must not resolve devices"); });
    assert !scan.active() && scanResults[0] == 1 && scanFailures[0] == 1;
    scan.begin(value -> { assert value.equals("unavailable"); scanResults[0]++; }, error -> scanFailures[0]++);
    scan.stop(() -> { throw new AssertionError("Hardware never started"); }, () -> "unavailable");
    assert scanResults[0] == 2;
    scan.begin(value -> { throw new AssertionError("Failed start resolved"); }, error -> scanFailures[0]++);
    scan.fail(new SecurityException());
    assert !scan.active() && scanFailures[0] == 2;
    scan.stop(() -> { throw new AssertionError("Failed scan never started"); }, () -> "devices");
    assert scanFailures[0] == 2;

    OmiBleLease.FirstAudio audio = new OmiBleLease.FirstAudio();
    assert OmiBleLease.FirstAudio.WINDOW_MS == 4000;
    assert audio.begin();
    long audioTicket = audio.token();
    assert !audio.begin();
    assert !audio.receive(0);
    assert audio.timeout(audioTicket) == 1;
    assert audio.timeout(audioTicket) == 0;
    assert audio.timeout(audio.token()) == -1;
    assert audio.timeout(audio.token()) == 0;
    assert audio.receive(4);
    assert audio.observed();
    assert !audio.receive(4);
    audio.cancel();
    assert audio.receive(4);
    assert !audio.begin();
    assert audio.timeout(audio.token()) == 0;
    audio.cancel();
    assert audio.begin();
    audioTicket = audio.token();
    audio.cancel();
    assert audio.begin();
    assert audio.timeout(audioTicket) == 0;
    assert audio.receive(4);
    assert audio.timeout(audio.token()) == 0;
    assert OmiBleLease.recordingReady(true, true, true);
    assert !OmiBleLease.recordingReady(true, false, true);
    assert !OmiBleLease.recordingReady(true, true, false);
    assert !OmiBleLease.recordingReady(false, true, true);
    OmiBleLease.Reconnect reconnect = new OmiBleLease.Reconnect();
    assert reconnect.nextDelayMillis() == -1;
    reconnect.ready();
    assert reconnect.nextDelayMillis() == 1000;
    long retry = reconnect.token();
    assert reconnect.accepts(retry);
    assert reconnect.nextDelayMillis() == 2000;
    assert !reconnect.accepts(retry);
    assert reconnect.nextDelayMillis() == 4000;
    assert reconnect.nextDelayMillis() == -1;
    assert !reconnect.accepts(reconnect.token());
    reconnect.ready();
    assert reconnect.nextDelayMillis() == 1000;
    retry = reconnect.token();
    reconnect.cancel();
    assert !reconnect.accepts(retry);
    assert reconnect.nextDelayMillis() == -1;
    reconnect.ready();
    assert !reconnect.accepts(retry);
    OmiBleLease lease = new OmiBleLease();
    long first = lease.begin();
    Object firstGatt = new Object();
    Object nextGatt = new Object();
    assert lease.acceptsGatt(first, firstGatt, firstGatt);
    assert !lease.acceptsGatt(first, nextGatt, firstGatt);
    assert !lease.acceptsGatt(first, null, firstGatt);
    long operation = lease.operation();
    assert lease.accepts(first);
    assert lease.operationPending(first, operation);
    lease.operation();
    assert !lease.operationPending(first, operation);
    lease.retire();
    assert !lease.accepts(first);
    assert !lease.acceptsGatt(first, firstGatt, firstGatt);
    assert !lease.operationPending(first, operation);
    long second = lease.begin();
    long nextOperation = lease.operation();
    assert !lease.accepts(first);
    assert !lease.operationPending(first, nextOperation);
    assert lease.accepts(second);
    assert lease.operationPending(second, nextOperation);
    lease.retire();
    assert !lease.operationPending(second, nextOperation);
    System.out.println("BLE retired connection and operation timeout fencing passed");
  }
}
