#!/usr/bin/env node
// Generates the barrel index.ts files from directory listings, so parallel
// workers never touch a shared file (wave-1 ratchet). `--check` verifies the
// committed barrels match (CI mode); default rewrites them.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname;
const HEADER = "// GENERATED by scripts/gen-barrels.mjs — do not edit by hand.\n";

/** [barrelPath, sourceDirs (relative to the barrel's dir)] */
const BARRELS = [
  ["contracts/src/index.ts", ["", "bridge", "domain"]],
  ["packages/adapters-legacy/src/index.ts", [""]],
  ["packages/domain/src/index.ts", [""]],
  ["packages/testkit/src/index.ts", [""]],
  ["packages/kernel/src/index.ts", [""]],
  ["packages/sync/src/index.ts", [""]],
];

const check = process.argv.includes("--check");
let failed = false;

for (const [barrelRel, dirs] of BARRELS) {
  const barrelAbs = join(ROOT, barrelRel);
  const baseDir = join(barrelAbs, "..");
  const lines = [];
  for (const dir of dirs) {
    const abs = join(baseDir, dir);
    for (const name of readdirSync(abs).sort()) {
      if (!name.endsWith(".ts") || name.endsWith(".test.ts") || name === "index.ts") continue;
      const spec = (dir ? `./${dir}/` : "./") + name.replace(/\.ts$/, ".js");
      lines.push(`export * from "${spec}";`);
    }
  }
  const content = HEADER + lines.join("\n") + "\n";
  const current = safeRead(barrelAbs);
  if (check) {
    if (current !== content) {
      console.error(`barrel drift: ${barrelRel} — run \`node scripts/gen-barrels.mjs\``);
      failed = true;
    }
  } else if (current !== content) {
    writeFileSync(barrelAbs, content);
    console.log(`wrote ${barrelRel}`);
  }
}

function safeRead(p) {
  try {
    return readFileSync(p, "utf8");
  } catch {
    return null;
  }
}

if (check && failed) process.exit(1);
console.log(check ? "barrels in sync." : "barrels generated.");
