#!/usr/bin/env node
// Generates the typed shell<->surface bridge from contract/bridge.contract.json.
//   node tools/gen-bridge.mjs
// Outputs:
//   app/lib/gen/bridge.g.dart      (Dart: envelope codec, typed models, handler interface, channel wiring)
//   surface/src/bridge.g.ts        (TS: typed client for the surface)
// Prototype-grade stand-in for what Pigeon does for Flutter<->native
// (see omi:app/lib/gen/pigeon_communicator.g.dart, the in-repo precedent).

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const contract = JSON.parse(readFileSync(join(root, 'contract/bridge.contract.json'), 'utf8'));

const DART = { bool: 'bool', int: 'int', double: 'double', string: 'String' };
const TS = { bool: 'boolean', int: 'number', double: 'number', string: 'string' };

const parse = (t) => ({ base: t.replace(/\?$/, ''), opt: t.endsWith('?') });
const dartType = (t) => {
  const { base, opt } = parse(t);
  return (DART[base] ?? base) + (opt ? '?' : '');
};
const tsField = (n, t) => {
  const { base, opt } = parse(t);
  return `  ${n}${opt ? '?' : ''}: ${TS[base] ?? base}${opt ? ' | null' : ''};`;
};
const cap = (s) => s[0].toUpperCase() + s.slice(1);

// ---------------------------------------------------------------- Dart
const dartModels = Object.entries(contract.types).map(([name, fields]) => {
  const ctor = Object.entries(fields)
    .map(([f, t]) => `${parse(t).opt ? '' : 'required '}this.${f}`)
    .join(', ');
  const decl = Object.entries(fields).map(([f, t]) => `  final ${dartType(t)} ${f};`).join('\n');
  const toJson = Object.keys(fields).map((f) => `'${f}': ${f}`).join(', ');
  const fromJson = Object.entries(fields)
    .map(([f, t]) => {
      const { base, opt } = parse(t);
      const raw = `json['${f}']`;
      if (DART[base]) return `      ${f}: ${raw} as ${DART[base]}${opt ? '?' : ''},`;
      return `      ${f}: ${opt ? `${raw} == null ? null : ` : ''}${base}.fromJson(${raw} as Map<String, Object?>),`;
    })
    .join('\n');
  return `class ${name} {
  const ${name}({${ctor}});
${decl}

  Map<String, Object?> toJson() => {${toJson}};

  static ${name} fromJson(Map<String, Object?> json) {
    return ${name}(
${fromJson}
    );
  }
}`;
}).join('\n\n');

const inbound = contract.messages.filter((m) => m.direction === 'ui->shell');
const outbound = contract.messages.filter((m) => m.direction === 'shell->ui');

const handlerMethods = inbound.map((m) => {
  const arg = m.params ? `${m.params} params` : '';
  const ret = m.result ? m.result : 'void';
  return `  /// ${m.doc}\n  Future<${ret}> ${m.name}(${arg});`;
}).join('\n');

const dispatchCases = inbound.map((m) => {
  const call = m.params
    ? `${m.name}(${m.params}.fromJson(params))`
    : `${m.name}()`;
  const body = m.result
    ? `        final r = await handler.${call};\n        return r.toJson();`
    : `        await handler.${call};\n        return const <String, Object?>{};`;
  return `      case '${m.name}':\n${body}`;
}).join('\n');

const pushMethods = outbound.map((m) => `  /// ${m.doc}
  Future<void> ${m.name}(${m.params} payload) => _push('${m.name}', payload.toJson());`).join('\n\n');

const dart = `// GENERATED by tools/gen-bridge.mjs from contract/bridge.contract.json
// contract version ${contract.version} -- do not edit by hand.
// ignore_for_file: unused_import
import 'dart:convert';
import 'package:webview_flutter/webview_flutter.dart';

const String kBridgeChannel = '${contract.channel}';
const String kBridgeContractVersion = '${contract.version}';

${dartModels}

/// Implement this in the shell. One method per ui->shell message; the compiler
/// tells you when the contract adds one.
abstract class ${contract.name}Handler {
${handlerMethods}
}

/// Wires a [WebViewController] to a [${contract.name}Handler] and exposes the
/// shell->ui push messages.
class ${contract.name} {
  ${contract.name}(this.controller, this.handler);

  final WebViewController controller;
  final ${contract.name}Handler handler;

  /// Registers the javascript channel. Call before loading the surface.
  Future<void> attach() {
    return controller.addJavaScriptChannel(
      kBridgeChannel,
      onMessageReceived: (JavaScriptMessage message) => _onMessage(message.message),
    );
  }

  Future<void> _onMessage(String raw) async {
    final envelope = jsonDecode(raw) as Map<String, Object?>;
    final String id = envelope['id'] as String;
    final String method = envelope['method'] as String;
    final Map<String, Object?> params =
        (envelope['params'] as Map<String, Object?>?) ?? const <String, Object?>{};
    try {
      final Object? result = await _dispatch(method, params);
      await _reply({'id': id, 'ok': true, 'result': result});
    } catch (e) {
      await _reply({'id': id, 'ok': false, 'error': e.toString()});
    }
  }

  Future<Object?> _dispatch(String method, Map<String, Object?> params) async {
    switch (method) {
${dispatchCases}
      default:
        throw StateError('unknown bridge method: \$method');
    }
  }

  Future<void> _reply(Map<String, Object?> envelope) {
    return controller.runJavaScript(
        'window.__omiBridge.__reply(\${jsonEncode(jsonEncode(envelope))})');
  }

  Future<void> _push(String name, Map<String, Object?> payload) {
    final envelope = jsonEncode({'method': name, 'params': payload});
    return controller
        .runJavaScript('window.__omiBridge.__push(\${jsonEncode(envelope)})');
  }

${pushMethods}
}
`;

// ---------------------------------------------------------------- TypeScript
const tsModels = Object.entries(contract.types).map(([name, fields]) =>
  `export interface ${name} {\n${Object.entries(fields).map(([f, t]) => tsField(f, t)).join('\n')}\n}`
).join('\n\n');

const tsCalls = inbound.map((m) => {
  const arg = m.params ? `params: ${m.params}` : '';
  const ret = m.result ?? 'void';
  const passed = m.params ? 'params' : 'undefined';
  return `  /** ${m.doc} */
  ${m.name}(${arg}): Promise<${ret}> {
    return this.#call<${ret}>('${m.name}', ${passed});
  }`;
}).join('\n\n');

const tsSubs = outbound.map((m) => `  /** ${m.doc} */
  on${cap(m.name)}(cb: (p: ${m.params}) => void): void {
    this.#subscribe('${m.name}', cb as (p: unknown) => void);
  }`).join('\n\n');

const ts = `// GENERATED by tools/gen-bridge.mjs from contract/bridge.contract.json
// contract version ${contract.version} -- do not edit by hand.

export const BRIDGE_CONTRACT_VERSION = '${contract.version}';

${tsModels}

type Pending = { resolve: (v: unknown) => void; reject: (e: Error) => void };

declare global {
  interface Window {
    ${contract.channel}?: { postMessage: (msg: string) => void };
    __omiBridge?: {
      __reply: (raw: string) => void;
      __push: (raw: string) => void;
    };
  }
}

class ${contract.name} {
  #seq = 0;
  #pending = new Map<string, Pending>();
  #subs = new Map<string, ((p: unknown) => void)[]>();

  constructor() {
    window.__omiBridge = {
      __reply: (raw: string) => {
        const e = JSON.parse(raw) as { id: string; ok: boolean; result?: unknown; error?: string };
        const p = this.#pending.get(e.id);
        if (!p) return;
        this.#pending.delete(e.id);
        e.ok ? p.resolve(e.result) : p.reject(new Error(e.error ?? 'bridge error'));
      },
      __push: (raw: string) => {
        const e = JSON.parse(raw) as { method: string; params: unknown };
        for (const cb of this.#subs.get(e.method) ?? []) cb(e.params);
      },
    };
  }

  get available(): boolean {
    return typeof window.${contract.channel}?.postMessage === 'function';
  }

  #call<T>(method: string, params: unknown): Promise<T> {
    const ch = window.${contract.channel};
    if (!ch) return Promise.reject(new Error('shell bridge unavailable (running outside the shell?)'));
    const id = 'c' + ++this.#seq;
    return new Promise<T>((resolve, reject) => {
      this.#pending.set(id, { resolve: resolve as (v: unknown) => void, reject });
      ch.postMessage(JSON.stringify({ id, method, params: params ?? null }));
    });
  }

  #subscribe(method: string, cb: (p: unknown) => void): void {
    const list = this.#subs.get(method) ?? [];
    list.push(cb);
    this.#subs.set(method, list);
  }

${tsCalls}

${tsSubs}
}

export const bridge = new ${contract.name}();
`;

for (const [rel, body] of [
  ['app/lib/gen/bridge.g.dart', dart],
  ['surface/src/bridge.g.ts', ts],
]) {
  const out = join(root, rel);
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, body);
  console.log('wrote', rel, `(${body.split('\n').length} lines)`);
}
