{{- if .Values.licenseProxy.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.licenseProxy.namePrefix }}-status
  labels:
{{ include "deepgram-self-hosted.labels" . | indent 4}}
    {{- range $key, $val := .Values.licenseProxy.additionalLabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
spec:
  selector:
    app: deepgram-license-proxy
    {{ include "deepgram-self-hosted.selectorLabels" . }}
  type: NodePort
  ports:
    - name: "status"
      port: {{ .Values.licenseProxy.server.statusPort }}
      targetPort: {{ .Values.licenseProxy.server.statusPort }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.licenseProxy.namePrefix }}-internal
  labels:
{{ include "deepgram-self-hosted.labels" . | indent 4}}
    {{- range $key, $val := .Values.licenseProxy.additionalLabels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
spec:
  selector:
    app: deepgram-license-proxy
    {{ include "deepgram-self-hosted.selectorLabels" . }}
  ports:
    - name: "primary"
      port: {{ .Values.licenseProxy.server.port }}
      targetPort: {{ .Values.licenseProxy.server.port }}
{{- end -}}
