final Map<String, String> availableLanguages = {
  'Chinese 🇨🇳': 'zh',
  'Dutch 🇳🇱': 'nl',
  'English 🇬🇧': 'en',
  'French 🇫🇷': 'fr',
  'German 🇩🇪': 'de',
  'Greek 🇬🇷': 'el',
  'Hindi 🇮🇳': 'hi',
  'Italian 🇮🇹': 'it',
  'Japanese 🇯🇵': 'ja',
  'Korean 🇰🇷': 'ko',
  'Malay 🇲🇾': 'ms',
  'Norwegian 🇳🇴': 'no',
  'Polish 🇵🇱': 'pl',
  'Portuguese 🇵🇹': 'pt',
  'Russian 🇷🇺': 'ru',
  'Spanish 🇪🇸': 'es',
  'Vietnamese 🇻🇳': 'vi',
};
