-- Offline/PostHog SQL projection: bind one namespace and build; never infer identity from person properties.
SELECT event, count(*) AS emitted
FROM events
WHERE app_namespace = :app_namespace AND build_number = :build_number
  AND event IN (
    'Onboarding Completed',
    'Phone Mic Recording Started',
    'Phone Mic Recording Stopped',
    'Transcribe Later Toggled',
    'Device Onboarding Completed',
    'Transcribe Later Recording Processed',
    'Calendar Enabled',
    'Calendar Disabled',
    'Calendar Selected',
    'Conversation Display Settings Opened',
    'Developer Mode Enabled',
    'Developer Mode Disabled',
    'Developer Settings Saved',
    'Voice Response Audio Toggled',
    'Show Short Conversations Toggled',
    'Device Onboarding Abandoned',
    'Device Onboarding Double Tap Configured',
    'Phone Call Ended',
    'Short Conversation Threshold Changed',
    'Fact Search Cleared',
    'All Facts Deleted',
    'Notification Frequency Changed',
    'Changelog Dismissed',
    'Apps Filter Rating',
    'AI App Generator Prompt Submitted',
    'Voice Response Mode Changed',
    'All Facts Visibility Changed',
    'Show Discarded Memories Toggled',
    'Show Discarded Conversations Toggled',
    'Deleted Conversations Filter Toggled',
    'Apps Filter My Apps',
    'Apps Filter Installed',
    'Daily Summary Toggled',
    'AI App Generator App Generated',
    'Action Items View Toggled',
    'Phone Call Started',
    'Phone Call Page Opened',
    'Phone Call Verification Started',
    'Phone Call Verification Completed',
    'Phone Call Connected',
    'Phone Call Dialpad Opened',
    'Phone Call Upsell Upgrade Tapped',
    'Phone Call Upsell Dismissed',
    'Device Disconnected',
    'Speech Profile Capture Page Clicked',
    'Speech Profile Skipped',
    'Speech Profile Upload Succeeded',
    'Speech Profile Embedding Stored',
    'Onboarding Step Speech Profile Continued',
    'Use Without Device Onboarding Welcome',
    'Use Without Device Onboarding Find Devices',
    'Fact Page Edited Fact',
    'Fact Page Create Fact Button Pressed',
    'Facts Management Sheet Opened',
    'Conversation Merge Selection Mode Entered',
    'Conversation Merge Selection Mode Exited',
    'Add Manual Memory Clicked',
    'User ID Copied',
    'Dev Mode Export Memories',
    'Dev Mode Import Memories',
    'Dev Mode Imported Memories',
    'Support Contacted',
    'Upgrade Succeeded',
    'Upgrade Cancelled',
    'Upgrade Modal Dismissed',
    'Upgrade Modal Clicked',
    'Subscription Cancel Flow Started',
    'Connect Friend Clicked',
    'Disconnect Friend Clicked',
    'Battery Indicator Clicked',
    'Added Person',
    'Removed Person',
    'Tag Sheet Opened',
    'Untagged Segment',
    'Edit Segment Text Started',
    'Edit Segment Text Saved',
    'Edit Segment Text Cancelled',
    'Edit Summary Started',
    'Edit Summary Saved',
    'Edit Summary Cancelled',
    'Delete Account Clicked',
    'Delete Account Confirmed',
    'Delete Account Cancelled',
    'Delete Account Flow Started',
    'Apps Filter Opened',
    'Apps Filter Applied',
    'Apps Clear Filters',
    'Brain Map Opened',
    'Brain Map Share Clicked',
    'Action Items Page Opened',
    'Action Items Date Filter Cleared',
    'Training Data Opt-In Submitted',
    'Training Data Opt-In Approved',
    'Calendar Filter Cleared',
    'Search Bar Focused',
    'Search Query Cleared',
    'Export Tasks Banner Clicked',
    'Create Folder Button Clicked',
    'Wrapped Page Opened',
    'Wrapped Banner Clicked',
    'Wrapped Generation Started',
    'Daily Summary Settings Opened',
    'Permissions Settings Opened',
    'Permissions Interstitial Shown',
    'Permissions Interstitial Completed',
    'Permissions Interstitial Skipped',
    'Recap Tab Opened',
    'Whats New Opened',
    'Daily Score Help Tapped',
    'Integrations Page Opened',
    'Payments Page Opened',
    'Connect Device Page Opened',
    'Get Omi Device Clicked',
    'Connection Guide Opened',
    'Data Privacy Page Opened',
    'AI App Generator Page Opened',
    'Import History Page Opened',
    'Live Transcript Card Clicked',
    'Apple Reminders Sync Completed',
    'Wrapped Generation Completed'
  )
GROUP BY event ORDER BY event;
