#!/usr/bin/env python3
"""
Convert Omi action items JSON export to a self-contained HTML checklist report.

Usage:
    python action_items_to_html.py action_items.json report.html [--title "My Tasks"]
"""

import argparse
import html
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

DEFAULT_TITLE = "Omi Action Items"

PAGE_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>
  :root {{ color-scheme: light dark; }}
  body {{
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    max-width: 760px;
    margin: 2rem auto;
    padding: 0 1rem;
    line-height: 1.4;
  }}
  h1 {{ font-size: 1.4rem; }}
  h2 {{ font-size: 1.05rem; margin-top: 2rem; opacity: 0.8; }}
  ul {{ list-style: none; padding: 0; margin: 0; }}
  li {{
    display: flex;
    align-items: baseline;
    gap: 0.6rem;
    border: 1px solid rgba(128, 128, 128, 0.35);
    border-radius: 8px;
    padding: 0.6rem 0.9rem;
    margin: 0.4rem 0;
  }}
  li.done {{ opacity: 0.6; text-decoration: line-through; }}
  .box {{ flex: none; }}
  .due {{ margin-left: auto; font-size: 0.8rem; opacity: 0.7; white-space: nowrap; text-decoration: none; }}
  .overdue {{ color: #e05252; opacity: 1; font-weight: 600; }}
  .generated {{ font-size: 0.8rem; opacity: 0.6; margin-top: 2.5rem; }}
</style>
</head>
<body>
<h1>{title}</h1>
{sections}
<p class="generated">Generated by action_items_to_html — reads a local JSON export, makes no network requests.</p>
</body>
</html>
"""


def escape(value):
    if value is None:
        return ""
    return html.escape(str(value), quote=True)


def format_due(due_at, now):
    if not due_at:
        return None, False
    try:
        parsed = datetime.fromisoformat(str(due_at).replace("Z", "+00:00"))
    except ValueError:
        return escape(due_at), False
    if parsed.tzinfo is not None:
        parsed = parsed.astimezone(timezone.utc)
    else:
        parsed = parsed.replace(tzinfo=timezone.utc)
    overdue = parsed < now
    return parsed.strftime("%Y-%m-%d"), overdue


def render_item(item, now):
    if not isinstance(item, dict):
        raise ValueError("Each action item must be an object")

    description = escape(item.get("description") or "(no description)")
    completed = bool(item.get("completed"))
    due_text, overdue = format_due(item.get("due_at"), now)

    box = "☑" if completed else "☐"
    li_class = "done" if completed else ""
    due_html = ""
    if due_text:
        due_class = "due overdue" if (overdue and not completed) else "due"
        due_html = f'<span class="{due_class}">Due {escape(due_text)}</span>'

    return f'<li class="{li_class}"><span class="box">{box}</span><span>{description}</span>{due_html}</li>'


def convert(source, destination, title=DEFAULT_TITLE):
    raw_content = Path(source).read_text(encoding="utf-8")
    if raw_content.startswith("﻿"):
        raw_content = raw_content[1:]
    items = json.loads(raw_content)

    if isinstance(items, dict):
        if "action_items" in items and isinstance(items["action_items"], list):
            items = items["action_items"]
        elif "data" in items and isinstance(items["data"], list):
            items = items["data"]
        else:
            items = [items]

    if not isinstance(items, list):
        raise ValueError("Expected a JSON array or object from omi --json action-item list")
    for item in items:
        if not isinstance(item, dict):
            raise ValueError("Each action item must be an object")

    now = datetime.now(timezone.utc)
    open_items = [i for i in items if not i.get("completed")]
    done_items = [i for i in items if i.get("completed")]

    sections = []
    if open_items:
        sections.append("<h2>Open</h2>\n<ul>\n" + "\n".join(render_item(i, now) for i in open_items) + "\n</ul>")
    if done_items:
        sections.append("<h2>Completed</h2>\n<ul>\n" + "\n".join(render_item(i, now) for i in done_items) + "\n</ul>")
    if not sections:
        sections.append("<p>No action items found in this export.</p>")

    page = PAGE_TEMPLATE.format(title=escape(title), sections="\n".join(sections))

    output_path = Path(destination)
    if output_path.exists():
        raise FileExistsError(f"Refusing to overwrite existing {output_path}")

    partial = output_path.with_name(output_path.name + ".partial")
    try:
        partial.write_text(page, encoding="utf-8")
        os.replace(partial, output_path)
    except OSError:
        partial.unlink(missing_ok=True)
        raise


def main(argv):
    parser = argparse.ArgumentParser(
        description="Convert an Omi action items JSON export to a self-contained HTML checklist report."
    )
    parser.add_argument("source", help="Path to a JSON export from `omi --json action-item list`.")
    parser.add_argument("destination", help="Path to write the .html report to.")
    parser.add_argument("--title", default=DEFAULT_TITLE, help="Report page title.")
    args = parser.parse_args(argv)
    convert(args.source, args.destination, args.title)


if __name__ == "__main__":
    try:
        main(sys.argv[1:])
    except (OSError, ValueError) as exc:
        sys.exit(f"HTML export failed: {exc}")
