#!/usr/bin/env python3
"""
Convert Omi tracked goals JSON export to a self-contained HTML progress report.

Usage:
    python goals_to_html.py goals.json report.html [--title "My Goals"]
"""

import argparse
import html
import json
import os
import sys
from pathlib import Path

DEFAULT_TITLE = "Omi Goals — Progress Report"

PAGE_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>
  :root {{ color-scheme: light dark; }}
  body {{
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    max-width: 760px;
    margin: 2rem auto;
    padding: 0 1rem;
    line-height: 1.4;
  }}
  h1 {{ font-size: 1.4rem; }}
  h2 {{ font-size: 1.05rem; margin-top: 2rem; opacity: 0.8; }}
  .goal {{
    border: 1px solid rgba(128, 128, 128, 0.35);
    border-radius: 8px;
    padding: 0.75rem 1rem;
    margin: 0.6rem 0;
  }}
  .goal-header {{ display: flex; justify-content: space-between; align-items: baseline; gap: 0.5rem; }}
  .goal-title {{ font-weight: 600; }}
  .goal-meta {{ font-size: 0.85rem; opacity: 0.7; white-space: nowrap; }}
  .bar-track {{
    background: rgba(128, 128, 128, 0.25);
    border-radius: 6px;
    height: 10px;
    margin-top: 0.5rem;
    overflow: hidden;
  }}
  .bar-fill {{ background: #4c8dff; height: 100%; }}
  .bar-fill.done {{ background: #3fbf6f; }}
  .badge {{
    font-size: 0.75rem;
    border-radius: 999px;
    padding: 0.1rem 0.55rem;
    background: rgba(128, 128, 128, 0.2);
  }}
  .generated {{ font-size: 0.8rem; opacity: 0.6; margin-top: 2.5rem; }}
</style>
</head>
<body>
<h1>{title}</h1>
{sections}
<p class="generated">Generated by goals_to_html — reads a local JSON export, makes no network requests.</p>
</body>
</html>
"""


def escape(value):
    if value is None:
        return ""
    return html.escape(str(value), quote=True)


def progress_pct(current, target, min_value, max_value):
    """Fraction of a goal completed, clamped to [0, 1].

    Prefers current/target (matches the convention used by goals_to_csv.py);
    falls back to the min/max range when target is not usable (e.g. 0 or
    missing), so a boolean- or scale-type goal without a positive target
    still renders a sensible bar instead of an empty one.
    """
    try:
        c = float(current)
    except (TypeError, ValueError):
        return 0.0
    try:
        t = float(target)
        if t > 0:
            return max(0.0, min(1.0, c / t))
    except (TypeError, ValueError):
        pass
    try:
        lo, hi = float(min_value), float(max_value)
        if hi > lo:
            return max(0.0, min(1.0, (c - lo) / (hi - lo)))
    except (TypeError, ValueError):
        pass
    return 0.0


def format_value(value):
    try:
        f = float(value)
    except (TypeError, ValueError):
        return escape(value)
    if f == int(f):
        return str(int(f))
    return f"{f:g}"


def render_goal(item):
    if not isinstance(item, dict):
        raise ValueError("Each goal must be an object")

    title = escape(item.get("title") or "Untitled goal")
    unit = escape(item.get("unit") or "")
    current = item.get("current_value")
    target = item.get("target_value")
    pct = progress_pct(current, target, item.get("min_value"), item.get("max_value"))
    is_active = item.get("is_active", True)
    badge = "Active" if is_active else "Completed / Inactive"
    fill_class = "bar-fill done" if pct >= 1.0 else "bar-fill"

    summary_bits = [f"{format_value(current)} / {format_value(target)} {unit}".strip()]
    summary_bits.append(f"{pct * 100:.0f}%")
    summary = " · ".join(b for b in summary_bits if b)

    return f"""<div class="goal">
  <div class="goal-header">
    <span class="goal-title">{title}</span>
    <span class="goal-meta"><span class="badge">{escape(badge)}</span> {escape(summary)}</span>
  </div>
  <div class="bar-track"><div class="{fill_class}" style="width: {pct * 100:.1f}%"></div></div>
</div>"""


def convert(source, destination, title=DEFAULT_TITLE):
    raw_content = Path(source).read_text(encoding="utf-8")
    if raw_content.startswith("﻿"):
        raw_content = raw_content[1:]
    items = json.loads(raw_content)

    if isinstance(items, dict):
        if "goals" in items and isinstance(items["goals"], list):
            items = items["goals"]
        elif "data" in items and isinstance(items["data"], list):
            items = items["data"]
        else:
            items = [items]

    if not isinstance(items, list):
        raise ValueError("Expected a JSON array or object from omi --json goal list")
    for item in items:
        if not isinstance(item, dict):
            raise ValueError("Each goal must be an object")

    active = [g for g in items if g.get("is_active", True)]
    inactive = [g for g in items if not g.get("is_active", True)]

    sections = []
    if active:
        sections.append("<h2>Active</h2>\n" + "\n".join(render_goal(g) for g in active))
    if inactive:
        sections.append("<h2>Completed / Inactive</h2>\n" + "\n".join(render_goal(g) for g in inactive))
    if not sections:
        sections.append("<p>No goals found in this export.</p>")

    page = PAGE_TEMPLATE.format(title=escape(title), sections="\n".join(sections))

    output_path = Path(destination)
    if output_path.exists():
        raise FileExistsError(f"Refusing to overwrite existing {output_path}")

    partial = output_path.with_name(output_path.name + ".partial")
    try:
        partial.write_text(page, encoding="utf-8")
        os.replace(partial, output_path)
    except OSError:
        partial.unlink(missing_ok=True)
        raise


def main(argv):
    parser = argparse.ArgumentParser(description="Convert an Omi goals JSON export to a self-contained HTML report.")
    parser.add_argument("source", help="Path to a JSON export from `omi --json goal list`.")
    parser.add_argument("destination", help="Path to write the .html report to.")
    parser.add_argument("--title", default=DEFAULT_TITLE, help="Report page title.")
    args = parser.parse_args(argv)
    convert(args.source, args.destination, args.title)


if __name__ == "__main__":
    try:
        main(sys.argv[1:])
    except (OSError, ValueError) as exc:
        sys.exit(f"HTML export failed: {exc}")
