#!/usr/bin/env python3
"""
Convert Omi memories JSON export to a self-contained HTML report, grouped by category.

Usage:
    python memories_to_html.py memories.json report.html [--title "My Memories"]
"""

import argparse
import html
import json
import os
import sys
from pathlib import Path

DEFAULT_TITLE = "Omi Memories"

PAGE_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>
  :root {{ color-scheme: light dark; }}
  body {{
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    max-width: 760px;
    margin: 2rem auto;
    padding: 0 1rem;
    line-height: 1.4;
  }}
  h1 {{ font-size: 1.4rem; }}
  h2 {{ font-size: 1.05rem; margin-top: 2rem; opacity: 0.8; text-transform: capitalize; }}
  .memory {{
    border: 1px solid rgba(128, 128, 128, 0.35);
    border-radius: 8px;
    padding: 0.6rem 0.9rem;
    margin: 0.4rem 0;
  }}
  .tags {{ font-size: 0.8rem; opacity: 0.7; margin-top: 0.3rem; }}
  .tag {{
    display: inline-block;
    background: rgba(128, 128, 128, 0.2);
    border-radius: 999px;
    padding: 0.05rem 0.5rem;
    margin-right: 0.3rem;
  }}
  .generated {{ font-size: 0.8rem; opacity: 0.6; margin-top: 2.5rem; }}
</style>
</head>
<body>
<h1>{title}</h1>
{sections}
<p class="generated">Generated by memories_to_html — reads a local JSON export, makes no network requests.</p>
</body>
</html>
"""


def escape(value):
    if value is None:
        return ""
    return html.escape(str(value), quote=True)


def render_memory(item):
    if not isinstance(item, dict):
        raise ValueError("Each memory must be an object")

    content = escape(item.get("content") or "")
    tags_raw = item.get("tags") or []
    tags = [str(t).strip() for t in tags_raw if t] if isinstance(tags_raw, list) else []

    tags_html = ""
    if tags:
        tags_html = '<div class="tags">' + "".join(f'<span class="tag">{escape(t)}</span>' for t in tags) + "</div>"

    return f'<div class="memory">{content}{tags_html}</div>'


def convert(source, destination, title=DEFAULT_TITLE):
    raw_content = Path(source).read_text(encoding="utf-8")
    if raw_content.startswith("﻿"):
        raw_content = raw_content[1:]
    items = json.loads(raw_content)

    if isinstance(items, dict):
        if "memories" in items and isinstance(items["memories"], list):
            items = items["memories"]
        elif "data" in items and isinstance(items["data"], list):
            items = items["data"]
        else:
            items = [items]

    if not isinstance(items, list):
        raise ValueError("Expected a JSON array or object from omi --json memory list")
    for item in items:
        if not isinstance(item, dict):
            raise ValueError("Each memory must be an object")

    grouped = {}
    for item in items:
        category = str(item.get("category") or "uncategorized")
        grouped.setdefault(category, []).append(item)

    sections = []
    for category in sorted(grouped):
        entries = "\n".join(render_memory(m) for m in grouped[category])
        sections.append(f"<h2>{escape(category)}</h2>\n{entries}")
    if not sections:
        sections.append("<p>No memories found in this export.</p>")

    page = PAGE_TEMPLATE.format(title=escape(title), sections="\n".join(sections))

    output_path = Path(destination)
    if output_path.exists():
        raise FileExistsError(f"Refusing to overwrite existing {output_path}")

    partial = output_path.with_name(output_path.name + ".partial")
    try:
        partial.write_text(page, encoding="utf-8")
        os.replace(partial, output_path)
    except OSError:
        partial.unlink(missing_ok=True)
        raise


def main(argv):
    parser = argparse.ArgumentParser(
        description="Convert an Omi memories JSON export to a self-contained HTML report grouped by category."
    )
    parser.add_argument("source", help="Path to a JSON export from `omi --json memory list`.")
    parser.add_argument("destination", help="Path to write the .html report to.")
    parser.add_argument("--title", default=DEFAULT_TITLE, help="Report page title.")
    args = parser.parse_args(argv)
    convert(args.source, args.destination, args.title)


if __name__ == "__main__":
    try:
        main(sys.argv[1:])
    except (OSError, ValueError) as exc:
        sys.exit(f"HTML export failed: {exc}")
