import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  shell: {backgroundColor: '#141414', flex: 1},
  shellCompact: {backgroundColor: '#1c1c1a'},
  shellWide: {flexDirection: 'row'},
  macShell: {
    backgroundColor: 'transparent',
    paddingTop: 0,
  },
  macPrimaryText: {color: '#f2f4f1'},
  navigation: {backgroundColor: '#141414'},
  rail: {paddingHorizontal: 8, paddingVertical: 24},
  railHeader: {alignItems: 'flex-start', gap: 8},
  railHeaderExpanded: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  railToggle: {
    alignItems: 'center',
    borderRadius: 12,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  wordmark: {
    color: '#ffffff',
    fontSize: 25,
    fontWeight: '900',
    letterSpacing: -1,
    paddingHorizontal: 2,
  },
  navItems: {gap: 4, marginTop: 32},
  navItemsCompact: {flexDirection: 'row', marginTop: 0},
  navItem: {
    alignItems: 'center',
    borderRadius: 12,
    flexDirection: 'row',
    gap: 12,
    minHeight: 48,
    paddingHorizontal: 18,
  },
  navItemCompact: {
    flex: 1,
    flexDirection: 'column',
    gap: 2,
    justifyContent: 'center',
    paddingHorizontal: 2,
  },
  navItemActive: {backgroundColor: '#ffffff'},
  activePill: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    height: 48,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  activePillHidden: {opacity: 0},
  focusRing: {
    borderColor: '#78bda5',
    borderWidth: 1,
  },
  navText: {color: '#b0b0b0', fontSize: 14, fontWeight: '600'},
  navTextCollapsed: {opacity: 0, width: 0},
  navTextActive: {color: '#141414'},
  bottomNav: {
    borderTopColor: '#2a2a2a',
    borderTopWidth: 1,
    paddingHorizontal: 4,
    paddingTop: 4,
  },
  paneInset: {flex: 1, padding: 12},
  macPaneInset: {
    alignSelf: 'stretch',
    paddingBottom: 0,
    paddingHorizontal: 0,
    paddingTop: 0,
    zIndex: 0,
  },
  paneInsetCompact: {padding: 0},
  paneFrame: {
    flex: 1,
  },
  paneFrameWide: {
    width: '100%',
  },
  paneFrameCompact: {},
  paneDepth: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  paneDepthLayer: {
    backgroundColor: '#000000',
    borderRadius: 26,
    bottom: -14,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 14,
  },
  paneDepthWide: {opacity: 0.05, transform: [{scaleX: 1.015}]},
  paneDepthMid: {bottom: -10, opacity: 0.07, top: 10},
  paneDepthNear: {bottom: -6, opacity: 0.1, top: 6},
  pane: {
    backgroundColor: '#1a1a1a',
    borderColor: '#303030',
    borderRadius: 26,
    borderWidth: 1,
    flex: 1,
    overflow: 'hidden',
  },
  desktopPane: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderRadius: 0,
    borderWidth: 0,
  },
  macPane: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
    borderRadius: 0,
    borderWidth: 0,
  },
  macRoot: {flex: 1, position: 'relative'},
  macHomeTimeline: {flex: 1, width: '100%'},
  macHomeTimelineContent: {
    flexGrow: 1,
    paddingBottom: 18,
    paddingHorizontal: 4,
    paddingTop: 8,
  },
  macHomeDayHeading: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    marginBottom: 8,
  },
  macHomeSpineDot: {
    backgroundColor: '#78bda5',
    borderRadius: 4,
    height: 7,
    width: 7,
  },
  macHomeDayLabel: {
    color: '#d7dad5',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  macHomeDayItems: {
    borderLeftColor: 'rgba(120, 189, 165, 0.28)',
    borderLeftWidth: StyleSheet.hairlineWidth,
    marginLeft: 3,
    paddingLeft: 14,
  },
  macHomeInlineState: {
    alignItems: 'flex-start',
    gap: 5,
    maxWidth: 520,
    paddingHorizontal: 4,
    paddingVertical: 12,
  },
  macHomeInlineTitle: {color: '#eef0ed', fontSize: 14, fontWeight: '600'},
  macHomeInlineCopy: {color: '#d7dad5', fontSize: 13, lineHeight: 19},
  macHomeRecovery: {
    alignItems: 'flex-start',
    gap: 8,
    maxWidth: 440,
    paddingBottom: 8,
    paddingHorizontal: 0,
    paddingTop: 10,
  },
  macHomeRecoveryTitle: {
    color: '#f2f4f1',
    fontSize: 17,
    fontWeight: '600',
    letterSpacing: -0.2,
    lineHeight: 22,
  },
  macHomeRecoveryCopy: {color: '#dfe2dd', fontSize: 13, lineHeight: 19},
  macHomeRecoveryRetry: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderColor: 'rgba(255, 255, 255, 0.16)',
    borderRadius: 14,
    borderWidth: 1,
    justifyContent: 'center',
    marginTop: 2,
    minHeight: 32,
    paddingHorizontal: 14,
  },
  macHomeRecoveryRetryText: {color: '#f2f4f1', fontSize: 13, fontWeight: '600'},
  macHomeRecoverySignIn: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#f2f4f1',
    borderRadius: 14,
    justifyContent: 'center',
    marginTop: 2,
    minHeight: 34,
    paddingHorizontal: 16,
  },
  macHomeRecoverySignInText: {
    color: '#171918',
    fontSize: 13,
    fontWeight: '700',
  },
  paneCompact: {borderRadius: 0, borderWidth: 0},
  paneCompactSurface: {backgroundColor: '#1c1c1a'},
  stageMotion: {flex: 1},
  stage: {flexGrow: 1, paddingBottom: 16, paddingHorizontal: 16},
  desktopStage: {flex: 1, paddingBottom: 0, paddingHorizontal: 0},
  stageCompact: {paddingHorizontal: 12},
  searchHome: {
    alignSelf: 'center',
    flex: 1,
    maxWidth: 820,
    paddingTop: 28,
    width: '100%',
  },
  homeHeading: {paddingBottom: 22, paddingHorizontal: 2},
  homeEyebrow: {
    color: '#78bda5',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.6,
  },
  homeTitle: {
    color: '#f5f5f2',
    fontSize: 30,
    fontWeight: '700',
    letterSpacing: -0.8,
    lineHeight: 36,
    marginTop: 7,
  },
  homeSubtitle: {color: '#9b9b96', fontSize: 14, lineHeight: 21, marginTop: 5},
  homeOverview: {flex: 1, width: '100%'},
  homeOverviewContent: {paddingBottom: 28, paddingTop: 10},
  pendantHero: {alignItems: 'center', paddingBottom: 18},
  pendantHeroCompact: {paddingBottom: 24},
  pendantStage: {
    alignItems: 'center',
    height: 184,
    justifyContent: 'center',
    position: 'relative',
    width: 160,
  },
  pendantStageCompact: {height: 232, width: '100%'},
  pendantAura: {
    backgroundColor: '#45b79b',
    borderRadius: 120,
    height: 220,
    opacity: 0.09,
    position: 'absolute',
    width: 220,
  },
  pendantAuraDisconnected: {backgroundColor: '#d9826f', opacity: 0.07},
  pendantName: {
    color: '#ffffff',
    fontSize: 28,
    fontWeight: '700',
    letterSpacing: -0.6,
    marginTop: -12,
  },
  pendantNameCompact: {
    fontSize: 38,
    letterSpacing: -1.2,
    marginTop: -4,
  },
  pendantStatusRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    marginTop: 5,
  },
  pendantStatusDot: {borderRadius: 4, height: 8, width: 8},
  pendantStatus: {color: '#b8b8b8', fontSize: 14, marginTop: 3},
  pendantStatusCompact: {color: '#a6a49c', fontSize: 15, marginTop: 0},
  pendantBatteryPill: {
    alignItems: 'center',
    backgroundColor: '#242a26',
    borderColor: '#39443c',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 7,
    marginTop: 10,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  pendantBatteryDot: {
    backgroundColor: '#45b79b',
    borderRadius: 3,
    height: 6,
    width: 6,
  },
  pendantBattery: {
    color: '#d8d8d8',
    fontSize: 13,
    fontWeight: '600',
  },
  homeSection: {gap: 10, marginTop: 24, width: '100%'},
  homeSectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 9,
    minHeight: 20,
  },
  homeSectionAccent: {
    backgroundColor: '#45b79b',
    borderRadius: 2,
    height: 16,
    width: 3,
  },
  homeSectionLabel: {color: '#a6a49c', marginBottom: 0},
  homeHint: {color: '#929292', fontSize: 13, paddingVertical: 4},
  homeDeviceCard: {
    backgroundColor: '#222522',
    borderColor: '#343b36',
    borderRadius: 24,
    borderWidth: 1,
    gap: 10,
    padding: 14,
  },
  homeDevicesSection: {marginTop: 24},
  homeDeviceHeading: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 9,
  },
  homeDeviceState: {color: '#e4e8e1', fontSize: 15, marginTop: 3},
  homeScanButton: {
    backgroundColor: '#e4eee6',
    borderColor: '#e4eee6',
    borderRadius: 17,
    minHeight: 34,
    paddingHorizontal: 14,
  },
  homeScanButtonText: {color: '#1c1c1a'},
  homeDeviceRow: {
    backgroundColor: '#292d29',
    borderColor: '#3b443d',
    borderRadius: 16,
    minHeight: 62,
  },
  homeDeviceRowLead: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 10,
  },
  homeDeviceRowDot: {
    backgroundColor: '#d9826f',
    borderRadius: 5,
    height: 10,
    width: 10,
  },
  homeDeviceRowDotConnected: {backgroundColor: '#45b79b'},
  homeCurrentRow: {
    backgroundColor: '#252925',
    borderColor: '#374039',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 15,
  },
  homeCurrentKindLead: {alignItems: 'center', flexDirection: 'row', gap: 7},
  homeCurrentKindDot: {
    backgroundColor: '#45b79b',
    borderRadius: 4,
    height: 7,
    width: 7,
  },
  homeCurrentKindDotMemory: {backgroundColor: '#d8a17b'},
  homeCurrentKind: {color: '#9eb8aa'},
  homeCurrentTitle: {fontSize: 16, lineHeight: 21, marginTop: 8},
  homeCurrentSummary: {color: '#9a9e98', lineHeight: 18, marginTop: 6},
  homeSpineRow: {
    backgroundColor: 'transparent',
    borderBottomColor: 'rgba(255, 255, 255, 0.07)',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: 'transparent',
    borderRadius: 0,
    borderWidth: 0,
    paddingHorizontal: 18,
    paddingVertical: 11,
  },
  homeSpineKind: {color: '#78bda5'},
  homeSpineMeta: {color: '#bfc3bd'},
  homeSpineTitle: {color: '#eef0ed', fontSize: 15, marginTop: 5},
  homeSpineSummary: {color: '#c7cac5', marginTop: 3},
  homeSpineEmpty: {
    alignItems: 'flex-start',
    flex: 0,
    justifyContent: 'flex-start',
    paddingBottom: 14,
    paddingHorizontal: 18,
    paddingTop: 18,
  },
  homeSpineEmptyTitle: {color: '#eef0ed'},
  homeSpineEmptyCopy: {color: '#c7cac5', textAlign: 'left'},
  homeSpineList: {flexGrow: 1, paddingBottom: 0},
  homeResults: {flex: 1},
  homeResultsWide: {flex: 0, flexGrow: 0, maxHeight: 430, minHeight: 210},
  macHomeReadStatuses: {gap: 8},
  macHomeReadStatus: {
    gap: 3,
    paddingHorizontal: 18,
    paddingVertical: 8,
  },
  macHomeReadStatusText: {color: '#d7dad5', fontSize: 12, fontWeight: '600'},
  macHomeRetryButton: {
    alignSelf: 'flex-start',
    marginTop: 10,
    minHeight: 32,
    paddingHorizontal: 12,
  },
  macHomeRetryButtonText: {color: '#eef0ed', fontSize: 12, fontWeight: '600'},
  macHomeDeviceAffordance: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    minHeight: 36,
    paddingHorizontal: 0,
    paddingTop: 12,
  },
  macHomeDeviceStatus: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 7,
  },
  macHomeDeviceStatusText: {color: '#d7dad5', fontSize: 12},
  macHomeDeviceActions: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    justifyContent: 'flex-end',
  },
  macHomeDeviceChip: {
    borderColor: 'rgba(255, 255, 255, 0.18)',
    borderRadius: 14,
    borderWidth: 1,
    minHeight: 30,
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  macHomeDeviceChipText: {color: '#d7dad5', fontSize: 11, fontWeight: '600'},
  macHomeDeviceHint: {color: '#d7dad5', fontSize: 11},
  deviceHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  deviceState: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
    marginTop: 2,
  },
  scanButton: {
    borderColor: '#525252',
    borderRadius: 16,
    borderWidth: 1,
    minHeight: 34,
    paddingHorizontal: 12,
    justifyContent: 'center',
  },
  scanButtonText: {color: '#ffffff', fontSize: 12, fontWeight: '700'},
  deviceRow: {
    alignItems: 'center',
    backgroundColor: '#232323',
    borderColor: '#353535',
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 60,
    paddingHorizontal: 14,
  },
  deviceName: {color: '#ffffff', fontSize: 15, fontWeight: '700'},
  deviceMeta: {color: '#9b9b9b', fontSize: 12, marginTop: 2},
  deviceBattery: {color: '#d8d8d8', fontSize: 13, fontWeight: '700'},
  deviceHint: {color: '#9b9b9b', fontSize: 13},
  chatScroll: {flex: 1},
  chatScrollContent: {flexGrow: 1},
  chatHistory: {
    alignSelf: 'center',
    flex: 1,
    maxWidth: 760,
    minHeight: 500,
    paddingBottom: 40,
    paddingTop: 72,
    width: '100%',
  },
  chatHistoryCompact: {paddingTop: 64},
  home: {
    alignSelf: 'center',
    flex: 1,
    justifyContent: 'center',
    maxWidth: 560,
    minHeight: 500,
    paddingVertical: 40,
    width: '100%',
  },
  homeCompact: {paddingVertical: 32},
  restingStage: {alignItems: 'center', width: '100%'},
  backButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    flexDirection: 'row',
    gap: 4,
    minHeight: 40,
    paddingHorizontal: 4,
    position: 'absolute',
    top: 18,
  },
  backButtonText: {color: '#b0b0b0', fontSize: 13, fontWeight: '600'},
  mark: {
    alignItems: 'center',
    alignSelf: 'center',
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  markImage: {borderRadius: 20, height: 40, width: 40},
  greeting: {
    color: '#ffffff',
    fontSize: 25,
    fontWeight: '600',
    marginTop: 20,
    textAlign: 'center',
  },
  currents: {marginTop: 34, width: '100%'},
  sectionLabel: {
    color: '#888888',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.5,
    marginBottom: 12,
  },
  prompts: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'center',
    marginTop: 28,
  },
  promptsCompact: {alignSelf: 'stretch'},
  promptChip: {
    alignItems: 'center',
    backgroundColor: '#252525',
    borderColor: '#363636',
    borderRadius: 22,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 14,
  },
  promptChipCompact: {flexBasis: '48%', flexGrow: 1, paddingHorizontal: 12},
  promptText: {
    color: '#e5e5e5',
    fontSize: 13,
    fontWeight: '500',
    textAlign: 'center',
  },
  empty: {color: '#666666', fontSize: 12, textAlign: 'center'},
  transcript: {gap: 24},
  loadOlderButton: {
    alignItems: 'center',
    alignSelf: 'center',
    borderColor: '#484848',
    borderRadius: 18,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 18,
  },
  loadOlderText: {color: '#b0b0b0', fontSize: 13, fontWeight: '600'},
  message: {color: '#e5e5e5', fontSize: 14, lineHeight: 20},
  chatMessageRow: {flexDirection: 'row', width: '100%'},
  chatMessageRowHuman: {justifyContent: 'flex-end'},
  chatMessageRowAi: {
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'flex-start',
  },
  chatMessageColumn: {minWidth: 0},
  chatMessageColumnCompact: {maxWidth: '85%'},
  chatMessageColumnDesktop: {maxWidth: '75%'},
  chatMessageColumnHuman: {alignItems: 'flex-end'},
  chatBubble: {borderRadius: 16, paddingHorizontal: 20, paddingVertical: 12},
  chatBubbleHuman: {backgroundColor: '#2c2c33'},
  chatBubbleAi: {
    backgroundColor: '#202020',
    borderColor: '#343434',
    borderWidth: 1,
  },
  chatAvatar: {
    alignItems: 'center',
    height: 40,
    justifyContent: 'center',
    position: 'relative',
    width: 40,
  },
  chatAvatarDot: {
    backgroundColor: '#ffffff',
    borderRadius: 3,
    height: 5,
    position: 'absolute',
    width: 5,
  },
  chatTimestamp: {color: '#666666', fontSize: 12, marginTop: 4},
  chatTimestampHuman: {textAlign: 'right'},
  cancelledMessage: {borderColor: '#666666', opacity: 0.72},
  cancelledLabel: {color: '#888888', fontSize: 11, marginTop: 4},
  failedLabel: {color: '#d8a0a0', fontSize: 12, marginTop: 4},
  thinkingText: {color: '#888888', fontSize: 12},
  thinkingDots: {flexDirection: 'row', gap: 5, paddingVertical: 4},
  thinkingDot: {
    backgroundColor: '#888888',
    borderRadius: 3,
    height: 6,
    width: 6,
  },
  error: {color: '#d8a0a0', fontSize: 12, textAlign: 'center'},
  memoryPage: {flex: 1, paddingHorizontal: 28, paddingTop: 24},
  memorySearchBox: {
    alignItems: 'center',
    backgroundColor: '#202020',
    borderColor: '#343434',
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 9,
    marginTop: 16,
    paddingHorizontal: 14,
  },
  memorySearchInput: {color: '#ffffff', flex: 1, fontSize: 14, minHeight: 44},
  memoryList: {gap: 8, paddingBottom: 28, paddingTop: 14},
  memoryCard: {
    backgroundColor: '#202020',
    borderColor: '#303030',
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 15,
    paddingVertical: 13,
  },
  memoryMetaRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  memoryTimestamp: {color: '#898989', fontSize: 11, fontWeight: '600'},
  memoryCitationCount: {color: '#707070', fontSize: 11},
  memoryBody: {
    color: '#eeeeee',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 8,
  },
  memoryProvenance: {color: '#888888', fontSize: 11, marginTop: 9},
  memoryFooter: {gap: 10, paddingVertical: 8},
  tasksPage: {flex: 1, paddingHorizontal: 28, paddingTop: 24},
  taskSearchBox: {
    alignItems: 'center',
    backgroundColor: '#202020',
    borderColor: '#343434',
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 9,
    marginTop: 16,
    paddingHorizontal: 14,
  },
  taskList: {gap: 20, paddingBottom: 78, paddingTop: 18},
  taskGroup: {gap: 7},
  taskGroupHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 3,
  },
  taskGroupTitle: {
    color: '#d8d8d8',
    fontSize: 13,
    fontWeight: '700',
  },
  taskGroupCount: {color: '#737373', fontSize: 11},
  taskCard: {
    alignItems: 'center',
    backgroundColor: '#202020',
    borderColor: '#303030',
    borderRadius: 13,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 54,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  taskCardSelected: {backgroundColor: '#292929', borderColor: '#686868'},
  taskCompletion: {
    alignItems: 'center',
    borderColor: '#777777',
    borderRadius: 9,
    borderWidth: 1,
    height: 18,
    justifyContent: 'center',
    width: 18,
  },
  taskCompletionDone: {backgroundColor: '#d8d8d8', borderColor: '#d8d8d8'},
  taskCheck: {color: '#1a1a1a', fontSize: 12, fontWeight: '800'},
  taskCardText: {flex: 1},
  taskDescription: {color: '#eeeeee', fontSize: 14, lineHeight: 19},
  taskDescriptionDone: {
    color: '#858585',
    textDecorationLine: 'line-through',
  },
  taskDue: {color: '#707070', fontSize: 11, marginTop: 3},
  taskShortcuts: {
    alignItems: 'center',
    backgroundColor: '#1d1d1d',
    borderColor: '#303030',
    borderRadius: 13,
    borderWidth: 1,
    bottom: 14,
    flexDirection: 'row',
    gap: 18,
    left: 28,
    paddingHorizontal: 14,
    paddingVertical: 9,
    position: 'absolute',
  },
  taskShortcut: {color: '#858585', fontSize: 11, fontWeight: '600'},
  destinationPage: {
    alignItems: 'stretch',
    flexGrow: 1,
    paddingHorizontal: 28,
    paddingVertical: 24,
  },
  destinationIntro: {color: '#a0a0a0', fontSize: 14, marginTop: 8},
  destinationSections: {gap: 10, marginTop: 20},
  destinationSection: {
    backgroundColor: '#202020',
    borderColor: '#303030',
    borderRadius: 14,
    borderWidth: 1,
    padding: 16,
  },
  destinationSectionTitle: {
    color: '#e5e5e5',
    fontSize: 14,
    fontWeight: '600',
  },
  destinationUnavailable: {
    color: '#d0d0d0',
    fontSize: 14,
    fontWeight: '600',
    marginTop: 20,
    textAlign: 'center',
  },
  destinationTabs: {flexDirection: 'row', gap: 8, marginVertical: 20},
  destinationTab: {
    borderColor: '#3a3a3a',
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  destinationTabActive: {backgroundColor: '#eeeeee', borderColor: '#eeeeee'},
  destinationTabText: {color: '#a0a0a0', fontSize: 13, fontWeight: '600'},
  destinationTabTextActive: {color: '#181818'},
  recapStatus: {
    backgroundColor: '#202020',
    borderColor: '#303030',
    borderRadius: 14,
    borderWidth: 1,
    marginTop: 16,
    padding: 14,
  },
  projectionTitle: {color: '#ffffff', fontSize: 22, fontWeight: '600'},
  projectionEmpty: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    paddingBottom: 48,
  },
  projectionEmptyTitle: {color: '#e5e5e5', fontSize: 16, fontWeight: '600'},
  projectionEmptyCopy: {
    color: '#888888',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 8,
    textAlign: 'center',
  },
  readStatuses: {gap: 8, paddingTop: 12},
  readStatus: {
    backgroundColor: '#202020',
    borderColor: '#303030',
    borderRadius: 12,
    borderWidth: 1,
    gap: 3,
    paddingHorizontal: 14,
    paddingVertical: 11,
  },
  readStatusCopy: {color: '#8d8d8d', fontSize: 12, lineHeight: 18},
  macReadStatus: {
    backgroundColor: 'rgba(255, 255, 255, 0.56)',
    borderColor: 'rgba(20, 20, 20, 0.18)',
  },
  macReadStatusText: {color: '#343434'},
  readStatusText: {color: '#b0b0b0', fontSize: 13, fontWeight: '600'},
  retryButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderColor: '#484848',
    borderRadius: 16,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 18,
  },
  retryButtonText: {color: '#ffffff', fontSize: 13, fontWeight: '600'},
  macRetryButton: {borderColor: 'rgba(20, 20, 20, 0.36)'},
  macRetryButtonText: {color: '#141414'},
  resultList: {flexGrow: 1, gap: 8, paddingBottom: 28},
  resultRow: {
    backgroundColor: '#202020',
    borderColor: '#303030',
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  resultKindRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  resultKind: {
    color: '#777777',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  resultMeta: {color: '#777777', fontSize: 11},
  resultTitle: {
    color: '#f2f2f2',
    fontSize: 15,
    fontWeight: '600',
    lineHeight: 20,
    marginTop: 7,
  },
  resultSummary: {color: '#888888', fontSize: 12, lineHeight: 17, marginTop: 5},
  conversationPage: {flex: 1, paddingHorizontal: 28, paddingVertical: 24},
  conversationDiscovery: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 9,
    marginTop: 16,
  },
  conversationSearchBox: {
    alignItems: 'center',
    backgroundColor: '#202020',
    borderColor: '#343434',
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: 9,
    paddingHorizontal: 14,
  },
  conversationStarFilter: {
    alignItems: 'center',
    borderColor: '#3a3a3a',
    borderRadius: 14,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 46,
    paddingHorizontal: 15,
  },
  conversationStarFilterActive: {
    backgroundColor: '#ffffff',
    borderColor: '#ffffff',
  },
  conversationStarFilterText: {
    color: '#a0a0a0',
    fontSize: 12,
    fontWeight: '600',
  },
  conversationStarFilterTextActive: {color: '#141414'},
  conversationContent: {flex: 1, flexDirection: 'row', gap: 16, marginTop: 18},
  conversationListPane: {flex: 1},
  conversationList: {gap: 16, paddingBottom: 28},
  conversationGroup: {gap: 7},
  conversationGroupTitle: {
    color: '#858585',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.7,
    paddingHorizontal: 3,
    textTransform: 'uppercase',
  },
  conversationRow: {
    backgroundColor: '#202020',
    borderColor: '#303030',
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  conversationRowSelected: {borderColor: '#ffffff'},
  conversationRowMeta: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  conversationRowTime: {color: '#777777', fontSize: 11, fontWeight: '600'},
  conversationRowStar: {color: '#d0d0d0', fontSize: 16, lineHeight: 18},
  conversationRowDuration: {color: '#777777', fontSize: 11, marginTop: 9},
  conversationDetail: {
    backgroundColor: '#202020',
    borderColor: '#303030',
    borderRadius: 16,
    borderWidth: 1,
    flex: 1,
    padding: 20,
  },
  conversationDetailEmpty: {flex: 1, justifyContent: 'center'},
  conversationDetailEyebrow: {
    color: '#777777',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1.2,
  },
  conversationDetailTitle: {
    color: '#f2f2f2',
    fontSize: 21,
    fontWeight: '600',
    lineHeight: 27,
    marginTop: 10,
  },
  conversationDetailSummary: {
    color: '#a0a0a0',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 8,
  },
  conversationDetailFields: {gap: 8, marginTop: 22},
  conversationDetailField: {color: '#d0d0d0', fontSize: 13, lineHeight: 18},
  conversationDetailNotice: {
    color: '#777777',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 24,
  },
  composerWrap: {paddingBottom: 16, paddingHorizontal: 20, paddingTop: 12},
  composerWrapCompact: {paddingHorizontal: 16},
  composer: {
    alignSelf: 'center',
    backgroundColor: '#252525',
    borderColor: '#3a3a3a',
    borderRadius: 28,
    borderWidth: 1,
    minHeight: 62,
    paddingHorizontal: 10,
    paddingVertical: 7,
    width: '100%',
  },
  composerFocused: {borderColor: '#626262'},
  composerInput: {
    color: '#ffffff',
    fontSize: 16,
    maxHeight: 200,
    minHeight: 44,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  composerActions: {alignItems: 'center', flexDirection: 'row'},
  iconButton: {
    alignItems: 'center',
    borderRadius: 20,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  actionSpacer: {flex: 1},
  sendButton: {
    alignItems: 'center',
    backgroundColor: '#555555',
    borderRadius: 20,
    height: 44,
    justifyContent: 'center',
    opacity: 0.35,
    width: 44,
  },
  sendButtonEnabled: {backgroundColor: '#ffffff', opacity: 1},
  stopButton: {backgroundColor: '#ffffff', opacity: 1},
  cloudSections: {marginTop: 0},
  cloudRow: {
    alignItems: 'flex-start',
    borderColor: '#303030',
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 12,
    marginTop: 12,
    paddingTop: 12,
  },
  cloudRowBody: {flex: 1, gap: 4},
  cloudRowTitle: {color: '#eeeeee', fontSize: 14, fontWeight: '600'},
  cloudRowMeta: {color: '#888888', fontSize: 12, lineHeight: 17},
  cloudAction: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderColor: '#484848',
    borderRadius: 16,
    borderWidth: 1,
    justifyContent: 'center',
    marginTop: 10,
    minHeight: 36,
    paddingHorizontal: 14,
  },
  cloudActionText: {color: '#ffffff', fontSize: 13, fontWeight: '600'},
  cloudActionError: {
    color: '#d9826f',
    fontSize: 13,
    lineHeight: 18,
    marginTop: 8,
  },
  pressed: {opacity: 0.72, transform: [{scale: 0.98}]},
});
