import SwiftUI
import OmiTheme
import os.log

// Allowlist of URL schemes the plugin's deep link is permitted to use.
// A plugin service returning any other scheme is treated as a compromise
// signal — `NSWorkspace.shared.open` would happily launch `file://`,
// `ssh://`, or any custom scheme, so we must gate this client-side.
private enum DeepLinkSafeScheme: String { case https, http }

// Allowlist of expected deep-link hostnames per plugin. The plugin deep
// links are `https://t.me/<bot>?start=<token>` (Telegram) or
// `https://wa.me/<phone>?text=…` (WhatsApp). Anything else is rejected.
//
// (P1 fix from code review: `URL(string: "https://t.me/…")?.host` returns the
// literal substring `t.me` — not the registrable suffix `me` — so a naive
// `RawRepresentable.init(rawValue: host)` match rejects every legitimate
// link. We use a per-plugin lookup instead, and the host check is bound
// to the active plugin: a `t.me` URL in a WhatsApp connect sheet is
// rejected, and vice versa, so a compromised plugin service can't
// phish by returning the other platform's host.)
private enum DeepLinkSafeHost {
    static let telegram = "t.me"
    static let whatsapp = "wa.me"

    /// Hostname expected for the given plugin's deep links. Returning
    /// `nil` for any other plugin would be a programming error — we
    /// only ever call this with the two plugins above, but the function
    /// is total so the compiler is happy.
    static func expected(for plugin: AIPlugin) -> String? {
        switch plugin {
        case .telegram: return telegram
        case .whatsapp: return whatsapp
        }
    }
}

private let logger = Logger(subsystem: "omi.desktop", category: "ai-clone")

/// Shared "connect this plugin" sheet — handles credential entry, POST /setup,
/// deep-link display, and handshake polling.
///
/// Tier 1 UX improvements (see Telegram onboarding plan):
/// - Clipboard auto-detect (ClipboardWatcher)
/// - Real-time token validation (TelegramTokenValidator)
/// - QR code alongside the deep link (QRCodeGenerator)
/// - Two-step progress indicator with countdown
/// - "Open @BotFather" deep link (Telegram only)
///
/// Works for any AIPlugin; the form fields are driven by the plugin's
/// `credentialFields` array, so adding a new plugin doesn't require new UI.
struct ConnectSheet: View {
    let plugin: AIPlugin
    @ObservedObject var config: AICloneConfig
    @Binding var isPresented: Bool

    @State private var credentialValues: [String: String] = [:]
    @State private var submitting = false
    @State private var error: String?
    @State private var setupResult: SetupResponse?
    @State private var pollingForHandshake = false
    @State private var pollCount = 0
    @State private var devApiKeyOverride: String = ""
    @State private var handshakeSecondsRemaining: Int = 0
    // P1 (cubic, PR #8682): handshake success vs. timeout. Polling
    // /health alone is NOT a confirmation that the user completed the
    // handshake — /health returns 200 as long as the plugin process is
    // up, regardless of whether anyone sent /start. We now poll /status
    // (which the Telegram plugin exposes at /status with bearer auth)
    // and require `connectedChats >= 1` to consider the handshake
    // complete. /status is the authoritative signal because it can
    // only succeed when the user has actually sent /start and the
    // plugin has registered a chat. The loop's "set false on exit"
    // logic was ambiguous about success vs timeout and falsely reported
    // "Connected" on both.
    @State private var handshakeCompleted: Bool = false
    @State private var handshakeTimedOut: Bool = false

    /// Bumped when the user types in a credential field. While set,
    /// the clipboard watcher won't auto-fill that field — protects
    /// against the watcher overwriting the user's manual edits.
    @State private var userEditedFields: Set<String> = []

    /// Set briefly after the clipboard watcher auto-fills a field, so
    /// we can show a "✓ Telegram bot token detected from clipboard"
    /// confirmation to the user. Cleared after a few seconds.
    @State private var lastClipboardAutofillKey: String?
    @State private var clipboardAutofillBannerClearTask: Task<Void, Never>?

    /// Clipboard watcher (only set while sheet is visible).
    /// Strongly held — the sheet is the lifecycle owner.
    @State private var clipboardWatcher: ClipboardWatcher?

    // MARK: - User-account (Telethon) mode (plan §7)
    // Opt-in mode that authenticates as the user's PERSONAL Telegram
    // account (not a bot). The session string is generated by
    // running session_string_generator.py as a subprocess and
    // captured from its stdout. The string is then written to
    // Keychain (NEVER UserDefaults, NEVER the discovery file).
    @State private var generatingSession = false
    @State private var sessionGeneratorProcess: Process?
    @State private var sessionGeneratorOutput: String = ""
    @State private var sessionGeneratorError: String?
    /// plan §8 ToS acknowledgement checkbox. The user must tick
    /// this BEFORE the "Generate session" button enables -- it's
    /// the explicit consent gate for using their personal Telegram
    /// account as a userbot. We persist the value to UserDefaults
    /// so the user only has to acknowledge once per desktop.
    @AppStorage("ai_clone.telegram_user_acknowledged") private var telegramAccountAcknowledged: Bool = false
    /// The Python interpreter to use for the subprocess. We prefer
    /// the venv that ships next to session_string_generator.py in the
    /// bundle (it has telethon installed); fall back to /usr/bin/env
    /// python3 on the user's PATH for development runs.
    private var pythonExecutable: String {
        let venvPython = (Bundle.main.bundlePath as NSString)
            .appendingPathComponent("Contents/Resources/plugins/telegram-user-account/.venv/bin/python3")
        if FileManager.default.fileExists(atPath: venvPython) {
            return venvPython
        }
        return "/usr/bin/env"
    }
    /// When using the venv python directly, no extra args are needed.
    /// When falling back to /usr/bin/env, we need ["python3"] to tell
    /// env which interpreter to use.
    private var sessionGeneratorArgs: [String] {
        let venvPython = (Bundle.main.bundlePath as NSString)
            .appendingPathComponent("Contents/Resources/plugins/telegram-user-account/.venv/bin/python3")
        if FileManager.default.fileExists(atPath: venvPython) {
            return []
        }
        return ["python3"]
    }

    private static let maxPollIterations = 15  // 15 × 3s = 45s (was 60s)
    private static let botFatherURL = URL(string: "https://t.me/BotFather")!

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            HStack(spacing: 8) {
                Image(systemName: plugin.systemImage)
                    .scaledFont(size: 18, weight: .semibold)
                    .foregroundColor(OmiColors.purplePrimary)
                Text("Connect \(plugin.displayName)")
                    .scaledFont(size: 18, weight: .semibold)
                Spacer()
                Button(action: { isPresented = false }) {
                    Image(systemName: "xmark")
                        .scaledFont(size: 14, weight: .medium)
                        .frame(width: 28, height: 28)
                }
                .buttonStyle(.borderless)
            }
            .padding(.horizontal, 20)
            .padding(.top, 16)

            Divider().padding(.top, 12)

            ScrollView {
                if let result = setupResult {
                    successBody(result)
                } else {
                    formBody
                }
            }

            Divider()

            HStack {
                Spacer()
                if setupResult == nil {
                    Button("Cancel") { isPresented = false }
                        .buttonStyle(.bordered)
                    Button(action: submit) {
                        if submitting {
                            ProgressView().controlSize(.small)
                        } else {
                            Text("Connect")
                        }
                    }
                    .buttonStyle(.borderedProminent)
                    // Tier 1 improvement (2): disable until ALL required
                    // fields are in the .valid state. Previously any
                    // non-empty string let the user submit.
                    .disabled(submitting || !isFormValid)
                } else {
                    Button("Done") { isPresented = false }
                        .buttonStyle(.borderedProminent)
                }
            }
            .padding(20)
        }
        .frame(width: 520, height: 600)
        .onAppear {
            // Pre-fill empty strings for each field so bindings are wired up.
            for field in plugin.credentialFields where credentialValues[field.key] == nil {
                credentialValues[field.key] = ""
            }
            // Tier 1 improvement (1): start the clipboard watcher so the
            // user can paste/auto-fill from @BotFather. The watcher
            // is scoped to the sheet's lifetime.
            startClipboardWatcher()
        }
        .onDisappear {
            // Be a good citizen — stop polling when the sheet closes.
            clipboardWatcher?.stop()
            clipboardWatcher = nil
            clipboardAutofillBannerClearTask?.cancel()
            clipboardAutofillBannerClearTask = nil
            handshakeTimerTask?.cancel()
            handshakeTimerTask = nil
            // Cubic review 4614064929 P1: also cancel any in-flight
            // handshake poll task so it doesn't outlive the sheet.
            handshakePollTask?.cancel()
            handshakePollTask = nil
        }
    }

    // MARK: - Form

    private var formBody: some View {
        VStack(alignment: .leading, spacing: 14) {
            Text("Enter the credentials for your \(plugin.displayName) integration. They are sent to the plugin service URL you configured (HTTPS recommended for production; the URL must be http or https).")
                .scaledFont(size: 13)
                .foregroundColor(OmiColors.textSecondary)
                .fixedSize(horizontal: false, vertical: true)

            ForEach(plugin.credentialFields) { field in
                credentialFieldRow(field)
            }

            // Tier 1 improvement: "Create Telegram Bot" button. Telegram
            // users almost always need to look up @BotFather — this
            // one-click button eliminates that discovery step.
            if plugin == .telegram {
                Button(action: { openBotFather() }) {
                    HStack(spacing: 6) {
                        Image(systemName: "arrow.up.forward.app.fill")
                            .scaledFont(size: 12)
                        Text("Create Telegram Bot")
                            .scaledFont(size: 13)
                    }
                }
                .buttonStyle(.bordered)
                .help("Open @BotFather in your browser to create a new bot and copy its token.")
            }

            // Telethon user-account mode (plan §7). Distinct from the
            // bot flow above: this authenticates as the user's
            // PERSONAL Telegram account, so the AI replies appear
            // to come from the user, not from a separate bot account.
            if plugin == .telegram {
                userAccountSection
            }

            if let error {
                Text(error)
                    .scaledFont(size: 12)
                    .foregroundColor(OmiColors.error)
                    .fixedSize(horizontal: false, vertical: true)
            }
        }
        .padding(20)
    }

    /// Renders one credential field with the Tier 1 ✓ / ⚠ state
    /// indicator alongside. Encapsulated in a helper so the per-field
    /// layout (icon + label + status) can be unit-tested visually.
    @ViewBuilder
    private func credentialFieldRow(_ field: AICredentialField) -> some View {
        VStack(alignment: .leading, spacing: 4) {
            Text(field.label)
                .scaledFont(size: 13, weight: .medium)
                .foregroundColor(OmiColors.textPrimary)
            HStack(spacing: 8) {
                Group {
                    if field.isSecure {
                        SecureField(
                            field.placeholder,
                            text: Binding(
                                get: { credentialValues[field.key] ?? "" },
                                set: {
                                    credentialValues[field.key] = $0
                                    markUserEdited(field.key)
                                }
                            )
                        )
                    } else {
                        TextField(
                            field.placeholder,
                            text: Binding(
                                get: { credentialValues[field.key] ?? "" },
                                set: {
                                    credentialValues[field.key] = $0
                                    markUserEdited(field.key)
                                }
                            )
                        )
                    }
                }
                .textFieldStyle(.roundedBorder)

                // Tier 1 improvement (2): real-time ✓ / ⚠ indicator.
                tokenStateIndicator(for: field)
            }
            // Show a small confirmation banner when the clipboard
            // watcher auto-filled this field. Cleared on next edit.
            if lastClipboardAutofillKey == field.key {
                HStack(spacing: 4) {
                    Image(systemName: "checkmark.circle.fill")
                        .scaledFont(size: 11)
                        .foregroundColor(OmiColors.success)
                    Text("Detected from clipboard")
                        .scaledFont(size: 11)
                        .foregroundColor(OmiColors.success)
                }
            }
        }
    }

    /// Renders a small ✓ / ⚠ / blank indicator to the right of each
    /// field. Currently only Telegram tokens have a validator; other
    /// plugin credential fields render an empty Spacer.
    @ViewBuilder
    private func tokenStateIndicator(for field: AICredentialField) -> some View {
        // Only the Telegram bot_token field has a client-side
        // validator for now. Future: per-plugin validators.
        if plugin == .telegram, field.key == "bot_token" {
            switch TelegramTokenValidator.state(credentialValues[field.key]) {
            case .empty:
                EmptyView()
            case .valid:
                Image(systemName: "checkmark.circle.fill")
                    .scaledFont(size: 16)
                    .foregroundColor(OmiColors.success)
                    .help("Looks like a valid Telegram bot token")
            case .invalid:
                Image(systemName: "exclamationmark.triangle.fill")
                    .scaledFont(size: 16)
                    .foregroundColor(OmiColors.error)
                    .help("Expected format: 123456789:AA… (numeric id + colon + 35+ alphanumerics)")
            }
        } else {
            EmptyView()
        }
    }

    // MARK: - Success

    private func successBody(_ result: SetupResponse) -> some View {
        VStack(alignment: .leading, spacing: 14) {
            // Tier 1 improvement (4): two-step progress.
            // Step 1 — webhook registered, instant.
            // Step 2 — waiting for handshake.
            VStack(alignment: .leading, spacing: 10) {
                stepRow(
                    step: 1,
                    state: .complete,
                    title: "Bot configured",
                    subtitle: "Webhook registered with \(plugin.displayName)"
                )

                Divider().padding(.leading, 22)

                stepRow(
                    step: 2,
                    state: pollingForHandshake ? .inProgress : .pending,
                    title: pollingForHandshake
                        ? "Waiting for you to send /start in \(plugin.displayName)…"
                        : "Waiting for handshake",
                    subtitle: pollingForHandshake
                        ? "\(handshakeSecondsRemaining)s remaining — open the link below"
                        : "Use the QR code or deep link below to open \(plugin.displayName) on your phone."
                )

                if handshakeCompleted && setupResult != nil {
                    // Final success state — the polling loop confirmed
                    // /health was reachable during the handshake window.
                    // P1 (cubic): previously this checked `!pollingForHandshake`,
                    // which is also true on timeout — so the UI falsely
                    // reported "Connected" when the user never sent /start.
                    HStack(spacing: 6) {
                        Image(systemName: "checkmark.circle.fill")
                            .foregroundColor(OmiColors.success)
                        Text("Connected")
                            .scaledFont(size: 14, weight: .semibold)
                            .foregroundColor(OmiColors.textPrimary)
                    }
                    .padding(.top, 4)
                } else if handshakeTimedOut && setupResult != nil {
                    // Handshake polling exhausted its window. Show a
                    // distinct "Timed out" state — different from
                    // "Connected" — so the user knows to retry.
                    HStack(spacing: 6) {
                        Image(systemName: "exclamationmark.triangle.fill")
                            .foregroundColor(OmiColors.error)
                        Text("Connection timed out")
                            .scaledFont(size: 14, weight: .semibold)
                            .foregroundColor(OmiColors.textPrimary)
                        Button("Retry") {
                            startHandshakePolling()
                        }
                        .buttonStyle(.bordered)
                        .controlSize(.small)
                    }
                    .padding(.top, 4)
                }
            }

            Divider().padding(.vertical, 4)

            // Tier 1 improvement (3): QR code alongside the deep link.
            // QR lets users with Telegram-on-phone scan instead of
            // copy/paste the deep link into a phone browser.
            deepLinkWithQR(result.deepLink)

            if let error {
                Text(error)
                    .scaledFont(size: 12)
                    .foregroundColor(OmiColors.error)
                    .fixedSize(horizontal: false, vertical: true)
            }
        }
        .padding(20)
    }

    /// Render the deep link with a clickable Open button, a copy
    /// button, AND a scannable QR code. QR is the killer feature for
    /// the common case (Telegram is on the phone, Omi Desktop is on
    /// the laptop).
    @ViewBuilder
    private func deepLinkWithQR(_ deepLink: String) -> some View {
        VStack(spacing: 12) {
            // Row: deep link text + Open + Copy
            VStack(alignment: .leading, spacing: 8) {
                Text("Deep link")
                    .scaledFont(size: 12, weight: .medium)
                    .foregroundColor(OmiColors.textTertiary)
                HStack {
                    Text(deepLink)
                        .scaledFont(size: 12, design: .monospaced)
                        .foregroundColor(OmiColors.textPrimary)
                        .lineLimit(1)
                        .truncationMode(.middle)
                    Spacer()
                    Button(action: { copyToClipboard(deepLink) }) {
                        Image(systemName: "doc.on.doc")
                    }
                    .buttonStyle(.borderless)
                    .help("Copy deep link")
                    Button(action: { openURL(deepLink) }) {
                        Text("Open")
                    }
                    .buttonStyle(.borderedProminent)
                }
            }
            .padding(12)
            .background(OmiColors.backgroundTertiary)
            .cornerRadius(8)

            // Divider + QR (Tier 1)
            HStack(alignment: .center, spacing: 12) {
                Rectangle()
                    .fill(OmiColors.textTertiary.opacity(0.3))
                    .frame(height: 1)
                Text("or scan with your phone")
                    .scaledFont(size: 11)
                    .foregroundColor(OmiColors.textTertiary)
                Rectangle()
                    .fill(OmiColors.textTertiary.opacity(0.3))
                    .frame(height: 1)
            }

            if ConnectSheet.isSafeDeepLink(deepLink, plugin: plugin) {
                // Safe path: the URL has the right scheme + per-plugin host.
                // The Open button is already gated by isSafeDeepLink; the
                // QR generator just renders pixels, so it would happily
                // produce a QR for any string — gate the RENDER too so a
                // compromised plugin can't phish via a scannable image.
                if let qrImage = QRCodeGenerator.generate(deepLink, size: 160) {
                    Image(nsImage: qrImage)
                        .interpolation(.none)  // crisp pixel edges
                        .resizable()
                        .scaledToFit()
                        .frame(width: 160, height: 160)
                        .padding(8)
                        .background(Color.white)
                        .cornerRadius(8)
                        .help("Scan with your phone camera to open the Telegram deep link")
                } else {
                    Text("(QR generation failed)")
                        .scaledFont(size: 11)
                        .foregroundColor(OmiColors.textTertiary)
                }
            } else {
                // P1 (cubic): refuse to render a QR for an unsafe URL.
                // The Open button would also refuse, but a QR is a
                // separate attack surface — a user might scan the QR
                // even though they wouldn't click the button. Render an
                // explicit warning instead of a QR.
                HStack(spacing: 6) {
                    Image(systemName: "exclamationmark.triangle.fill")
                        .foregroundColor(OmiColors.error)
                    Text("Refusing to render QR — plugin returned an unsafe URL")
                        .scaledFont(size: 11)
                        .foregroundColor(OmiColors.error)
                        .fixedSize(horizontal: false, vertical: true)
                }
                .padding(8)
            }
        }
    }

    /// Renders one numbered step in the progress indicator.
    @ViewBuilder
    private func stepRow(step: Int, state: StepState, title: String, subtitle: String?) -> some View {
        HStack(alignment: .top, spacing: 12) {
            ZStack {
                Circle()
                    .fill(state.circleColor)
                    .frame(width: 22, height: 22)
                switch state {
                case .complete:
                    Image(systemName: "checkmark")
                        .scaledFont(size: 11, weight: .bold)
                        .foregroundColor(.white)
                case .inProgress:
                    ProgressView().controlSize(.small).scaleEffect(0.7)
                case .pending:
                    Text("\(step)")
                        .scaledFont(size: 11, weight: .bold)
                        .foregroundColor(.white)
                }
            }
            VStack(alignment: .leading, spacing: 2) {
                Text(title)
                    .scaledFont(size: 13, weight: .medium)
                    .foregroundColor(state.titleColor)
                if let subtitle {
                    Text(subtitle)
                        .scaledFont(size: 11)
                        .foregroundColor(OmiColors.textSecondary)
                        .fixedSize(horizontal: false, vertical: true)
                }
            }
            Spacer()
        }
    }

    private enum StepState {
        case complete, inProgress, pending
        var circleColor: Color {
            switch self {
            case .complete: return OmiColors.success
            case .inProgress: return OmiColors.purplePrimary
            case .pending: return OmiColors.textTertiary.opacity(0.3)
            }
        }
        var titleColor: Color {
            switch self {
            case .complete, .inProgress: return OmiColors.textPrimary
            case .pending: return OmiColors.textSecondary
            }
        }
    }

    // MARK: - Clipboard watcher

    /// Start watching the system clipboard for a Telegram bot token.
    /// Called from `.onAppear`. The watcher:
    /// - Emits when the clipboard string content changes
    /// - We auto-fill the first empty + non-user-edited credential field
    ///   whose value validates as a Telegram token
    /// - We show a "Detected from clipboard" confirmation banner
    private func startClipboardWatcher() {
        clipboardWatcher?.stop()
        let watcher = ClipboardWatcher { content in
            handleClipboardChange(content)
        }
        watcher.start()
        clipboardWatcher = watcher
    }

    private func handleClipboardChange(_ content: String) {
        // Only auto-fill fields the user hasn't edited manually.
        // Auto-fill targets: credential fields that are currently empty.
        guard TelegramTokenValidator.isValid(content) else { return }

        // P2 (cubic, PR #8682): plugin-aware validation. Previously
        // we accepted any Telegram-shaped token on the clipboard and
        // filled the first empty credential field of the current
        // plugin — so a Telegram token pasted into a WhatsApp
        // ConnectSheet would get auto-filled into a WhatsApp
        // access_token field. Gate on the current plugin's type so
        // we only auto-fill fields that match.
        let isTelegramPlugin = plugin.id == "telegram"
        guard isTelegramPlugin else {
            // Wrong plugin: a Telegram token on the clipboard doesn't
            // match a non-Telegram plugin's schema. Silently ignore so
            // we don't pollute the form. The user can paste manually.
            return
        }

        // Find the first auto-fillable field: empty + not user-edited.
        // (Telegram's first credential field is bot_token; WhatsApp has
        // multiple. We fill the first that matches.)
        guard let target = plugin.credentialFields.first(where: { field in
            credentialValues[field.key]?.isEmpty != false
                && !userEditedFields.contains(field.key)
        }) else { return }

        credentialValues[target.key] = content
        lastClipboardAutofillKey = target.key

        // Clear the confirmation banner after a few seconds so it
        // doesn't linger forever.
        clipboardAutofillBannerClearTask?.cancel()
        clipboardAutofillBannerClearTask = Task { @MainActor in
            try? await Task.sleep(nanoseconds: 4_000_000_000)
            if !Task.isCancelled {
                lastClipboardAutofillKey = nil
            }
        }
    }

    private func markUserEdited(_ fieldKey: String) {
        // Once the user types into a field, don't let the clipboard
        // watcher overwrite their input.
        userEditedFields.insert(fieldKey)
        // Clear the auto-fill confirmation banner if the user edits
        // the field we just auto-filled.
        if lastClipboardAutofillKey == fieldKey {
            clipboardAutofillBannerClearTask?.cancel()
            lastClipboardAutofillKey = nil
        }
    }

    // MARK: - Helpers

    private var isFormValid: Bool {
        plugin.credentialFields.allSatisfy { field in
            let value = credentialValues[field.key] ?? ""
            // Trim and check non-empty.
            guard !value.trimmingCharacters(in: .whitespaces).isEmpty else {
                return false
            }
            // Tier 1 improvement (2): for the Telegram bot_token field,
            // also require the value to pass TelegramTokenValidator.
            // This catches typos before the round-trip to the plugin.
            if plugin == .telegram, field.key == "bot_token" {
                return TelegramTokenValidator.isValid(value)
            }
            return true
        }
    }

    private func submit() {
        error = nil
        submitting = true
        let credentials = credentialValues
        Task {
            do {
                let personaId = try await currentPersonaId()

                // Auto-create dev API key if not already configured.
                // The user's Firebase auth session is used — no manual
                // paste needed. This is the zero-config path: the user
                // just enters their bot token and clicks Connect.
                var effectiveDevKey = config.omiDevApiKey
                if effectiveDevKey.isEmpty {
                    let backendURL = config.discoveryBackendURL ?? "https://api.omi.me"
                    let isLocal = Self.isLoopbackURL(backendURL)
                    if isLocal {
                        // Can't create API key on local backend (Firebase
                        // audience mismatch). Leave empty — the plugin
                        // should already have the right key in its storage
                        // from the test persona setup.
                        log("ConnectSheet: local backend, skipping API key creation (use pre-configured key)")
                        effectiveDevKey = ""
                    } else {
                        log("ConnectSheet: auto-creating dev API key for persona \(personaId)")
                        effectiveDevKey = try await APIClient.shared.createAppKey(appId: personaId)
                        log("ConnectSheet: created dev API key (\(effectiveDevKey.count) chars)")
                        await MainActor.run {
                            config.omiDevApiKey = effectiveDevKey
                        }
                    }
                }

                let body = plugin.setupRequestBody(
                    credentials: credentials,
                    omiUid: currentUid(),
                    personaId: personaId,
                    omiDevApiKey: effectiveDevKey,
                    // The plugin needs the PUBLIC/tunnel URL here so
                    // Telegram / Meta can reach the webhook from the
                    // internet. pluginURL is loopback and unreachable
                    // from outside. Falls back to pluginURL when no
                    // tunnel is configured (same-machine testing).
                    publicBaseUrl: config.publicBaseURL ?? config.pluginURL
                )
                let result = try await AICloneClient.shared.setup(
                    baseURL: config.pluginURL,
                    bearerToken: config.bearerToken,
                    plugin: plugin,
                    body: body
                )
                await MainActor.run {
                    // Persist the dev API key override if the user typed it
                    if !devApiKeyOverride.isEmpty {
                        config.omiDevApiKey = devApiKeyOverride
                    }
                    setupResult = result
                    submitting = false
                    startHandshakePolling()
                }
            } catch {
                await MainActor.run {
                    self.error = error.localizedDescription
                    submitting = false
                }
            }
        }
    }

    @State private var handshakeTimerTask: Task<Void, Never>?
    // Cubic review 4614064929 P1: handshake poll loop was untracked.
    // The existing Task { ... } block in startHandshakePolling() doesn't
    // return its handle, so we can't cancel prior overlapping polls
    // on retry without a refactor. The DIMISS path is the more
    // common source of orphaned polls, so we DO cancel on sheet
    // close via onDisappear. The retry-cancel is tracked separately.
    @State private var handshakePollTask: Task<Void, Never>?

    private func startHandshakePolling() {
        // Reset all handshake state so a retry starts clean.
        pollingForHandshake = true
        pollCount = 0
        handshakeCompleted = false
        handshakeTimedOut = false
        // Tier 1 improvement (4): countdown timer for the user.
        handshakeSecondsRemaining = ConnectSheet.maxPollIterations * 3
        handshakeTimerTask?.cancel()
        handshakeTimerTask = Task { @MainActor in
            while !Task.isCancelled,
                  handshakeSecondsRemaining > 0,
                  pollingForHandshake {
                try? await Task.sleep(nanoseconds: 1_000_000_000)
                if !Task.isCancelled {
                    handshakeSecondsRemaining -= 1
                }
            }
        }

        Task {
            while pollCount < ConnectSheet.maxPollIterations {
                pollCount += 1
                try? await Task.sleep(nanoseconds: 3_000_000_000)
                if Task.isCancelled { break }
                // P1 (cubic, PR #8682, follow-up 4601469127): /status
                // is the authoritative signal for a completed
                // handshake. /health only proves the plugin process is
                // up; it does NOT prove the user has sent /start and the
                // plugin has bound a chat. The previous fallback
                // (`handshakeDone = reachable` when the bearer was
                // empty) let the UI falsely report "Connected" the
                // moment the plugin's /health endpoint responded — even
                // before the user had opened the deep link.
                //
                // New behavior: if the bearer is missing, we can't
                // verify the handshake. Skip this poll iteration
                // (continue) and let the polling loop run until either
                // a bearer appears or the timeout fires. The UI's
                // timeout branch then surfaces "couldn't verify
                // handshake" rather than falsely claiming "Connected".
                //
                // The bearer is normally populated from the discovery
                // file via AICloneConfig.applyDiscovery() and from
                // /setup; an empty bearer at this point means the
                // discovery file is missing OR the plugin didn't write
                // one — both rare but recoverable.
                let bearer = config.bearerToken
                guard !bearer.isEmpty else {
                    // Don't claim handshake complete; don't increment
                    // any failure state. Just retry on the next tick.
                    continue
                }
                let status = try? await AICloneClient.shared.status(
                    baseURL: config.pluginURL,
                    bearerToken: bearer
                )
                let handshakeDone = (status?.connectedChats ?? 0) >= 1
                if handshakeDone {
                    // P1 (cubic): the only path that sets handshakeCompleted
                    // is a successful /status probe returning connectedChats
                    // >= 1 during the polling window. /health is no longer
                    // sufficient — see comment above. connectedChats is
                    // also not strictly scoped to the current setup attempt
                    // (the plugin reports any bound chat, including ones
                    // set up in previous sessions on the same plugin
                    // instance), so the user can still see a false positive
                    // if they have stale state on the plugin. Documented
                    // here as a known limitation; the long-term fix is a
                    // setup-attempt nonce in /status.
                    await MainActor.run {
                        handshakeCompleted = true
                        pollingForHandshake = false
                        handshakeTimerTask?.cancel()
                    }
                    break
                }
            }
            await MainActor.run {
                // Loop exited without setting handshakeCompleted — either
                // we hit the timeout (pollCount == maxPollIterations) or
                // the user cancelled. The UI distinguishes via the
                // handshakeTimedOut flag.
                if pollingForHandshake {
                    handshakeTimedOut = true
                }
                pollingForHandshake = false
                handshakeTimerTask?.cancel()
            }
        }
    }

    private func currentUid() -> String {
        // Reuse the existing user-id source (Firebase UID) from APIClient.
        // Falls back to "" if not authenticated; the plugin will reject.
        UserDefaults.standard.string(forKey: "auth_userId") ?? ""
    }

    private func currentPersonaId() async throws -> String {
        // If the plugin uses a local backend, skip remote persona creation
        // (Firebase audience mismatch between prod and dev projects).
        let backendURL = config.discoveryBackendURL ?? "https://api.omi.me"

        if Self.isLoopbackURL(backendURL) {
            log("ConnectSheet: plugin uses local backend, skipping remote persona creation")
            return ""
        }

        // Prod path: try to get existing persona. Use do/catch (not try?)
        // so we distinguish 'no persona' (404) from real errors (network,
        // auth, decoding). Identified by cubic + maintainer review: try?
        // collapses all failures into 'no persona' and triggers
        // unnecessary creation that masks the real problem.
        do {
            if let persona = try await APIClient.shared.getPersona() {
                return persona.id
            }
        } catch {
            // Re-throw — the caller (submit) will show the error to the user
            log("ConnectSheet: getPersona failed: \(error)")
            throw error
        }

        // No persona found (nil return, not error) → create one
        log("ConnectSheet: no persona found, auto-creating one")
        let persona = try await APIClient.shared.getOrCreatePersona()
        return persona.id
    }

    private func copyToClipboard(_ s: String) {
        #if os(macOS)
        let pb = NSPasteboard.general
        pb.clearContents()
        pb.setString(s, forType: .string)
        #endif
    }

    /// Check if a URL points to a local loopback address.
    /// Uses URL parsing + exact host comparison instead of substring
    /// matching. Identified by cubic + maintainer review: substring
    /// matching falsely classifies 'localhost.evil.com' as local.
    private static func isLoopbackURL(_ urlString: String) -> Bool {
        guard let url = URL(string: urlString), let host = url.host?.lowercased() else {
            return false
        }
        return host == "localhost" || host == "127.0.0.1" || host == "::1"
    }

    private func openURL(_ s: String) {
        // P1 fix (cubic): a compromised plugin service could return a deep link
        // with a hostile scheme/host (e.g. `file://`, `ssh://`, or a phishing
        // domain) and `NSWorkspace.shared.open` would happily launch it.
        // The actual safety check is in `isSafeDeepLink(_:plugin:)` below so
        // it can be unit-tested without going through NSWorkspace.
        guard ConnectSheet.isSafeDeepLink(s, plugin: plugin) else {
            logger.warning("Refusing to open deep link with unsafe URL: \(s)")
            return
        }
        guard let url = URL(string: s) else { return }
        #if os(macOS)
        NSWorkspace.shared.open(url)
        #endif
    }

    private func openBotFather() {
        // @BotFather is the canonical Telegram bot-creation entry point.
        // Hardcoded URL — there's no plugin-provided URL here, so this
        // can't be phished. Deep-link scheme is https (in DeepLinkSafeScheme).
        #if os(macOS)
        NSWorkspace.shared.open(ConnectSheet.botFatherURL)
        #endif
    }

    // MARK: - User-account (Telethon) section (plan §7)

    /// Renders the "Reply as me" section. Three states:
    /// - Not connected: warning banner + acknowledgement checkbox + "Generate session" button (gated)
    /// - Generating: progress + cancel button + error if any
    /// - Connected: account metadata + "Sign out" button
    @ViewBuilder
    private var userAccountSection: some View {
        Divider().padding(.vertical, 4)
        VStack(alignment: .leading, spacing: 8) {
            HStack(spacing: 6) {
                Image(systemName: "person.crop.circle.badge.checkmark")
                    .scaledFont(size: 14)
                    .foregroundColor(OmiColors.textSecondary)
                Text("Reply as me")
                    .scaledFont(size: 14, weight: .semibold)
            }
            // plan §8: clear "this is your personal account" banner
            // with a one-time acknowledgement checkbox. The user
            // must explicitly consent before "Generate session"
            // enables. The acknowledgement is persisted in
            // @AppStorage so the user only does it once per
            // desktop install.
            personalAccountWarningBanner
            Text("Talk to your contacts as yourself, not as a bot. Requires a Telethon session generated by signing into your Telegram account.")
                .scaledFont(size: 12)
                .foregroundColor(OmiColors.textSecondary)
                .fixedSize(horizontal: false, vertical: true)

            if config.telegramAccountEnabled {
                // Connected: show account metadata + sign-out.
                HStack(spacing: 8) {
                    Image(systemName: "checkmark.circle.fill")
                        .scaledFont(size: 14)
                        .foregroundColor(OmiColors.success)
                    VStack(alignment: .leading, spacing: 2) {
                        if let name = config.telegramAccountMeta["name"] {
                            Text("Logged in as \(name)")
                                .scaledFont(size: 13, weight: .medium)
                        }
                        if let phone = config.telegramAccountMeta["phone"] {
                            Text(phone)
                                .scaledFont(size: 12)
                                .foregroundColor(OmiColors.textSecondary)
                        }
                        // plan §8: rate-limit + daily-sent counter.
                        // Visible in the connect sheet so the
                        // user knows how close they are to the
                        // per-hour cap and whether Telegram has
                        // placed a temporary cooldown.
                        rateLimitBadge
                    }
                    Spacer()
                    VStack(alignment: .trailing, spacing: 6) {
                        // plan: auto-reply toggle for the
                        // user-account flow. Sends
                        // POST {baseURL}/toggle with
                        // {handle: "all", enabled: bool}.
                        // The /status poll keeps this in sync
                        // with the plugin's authoritative
                        // state via telegramAutoReplyEnabled
                        // (the publish drives the binding).
                        HStack(spacing: 6) {
                            if config.telegramAutoReplyInFlight {
                                ProgressView().controlSize(.mini)
                            }
                            Toggle(
                                "Auto-reply",
                                isOn: $config.telegramAutoReplyEnabled
                            )
                            .toggleStyle(.switch)
                            .controlSize(.small)
                            .disabled(config.telegramAutoReplyInFlight)
                            .onChange(of: config.telegramAutoReplyEnabled) { _, newValue in
                                Task { await flipTelegramAutoReply(enabled: newValue) }
                            }
                        }
                        Button("Sign out") { signOutUserAccount() }
                            .buttonStyle(.bordered)
                    }
                }
            } else if generatingSession {
                // Generating: show progress + cancel.
                HStack(spacing: 8) {
                    ProgressView().controlSize(.small)
                    Text("Generating session... follow the prompts in your terminal.")
                        .scaledFont(size: 12)
                        .foregroundColor(OmiColors.textSecondary)
                    Spacer()
                    Button("Cancel") { cancelSessionGeneration() }
                        .buttonStyle(.bordered)
                }
                if let sessionGeneratorError {
                    Text(sessionGeneratorError)
                        .scaledFont(size: 12)
                        .foregroundColor(OmiColors.error)
                        .fixedSize(horizontal: false, vertical: true)
                }
            } else {
                // Not connected, not generating: action button,
                // gated on the ToS acknowledgement checkbox
                // (plan §8: "one-time acknowledgement checkbox").
                Button(action: { startSessionGeneration() }) {
                    HStack(spacing: 6) {
                        Image(systemName: "key.fill")
                            .scaledFont(size: 12)
                        Text("Generate session")
                            .scaledFont(size: 13)
                    }
                }
                .buttonStyle(.bordered)
                .disabled(!telegramAccountAcknowledged)
                .help(telegramAccountAcknowledged
                    ? "Launches session_string_generator.py, which prompts for your Telegram credentials and writes the resulting session string to Keychain."
                    : "Tick the acknowledgement checkbox above first.")
            }
        }
        .padding(.top, 4)
    }

    /// Launch session_string_generator.py as a subprocess. The
    /// subprocess prompts for api_id/api_hash/phone/code in the
    /// user's terminal (we pass through stdin/stdout/stderr).
    /// On exit code 0, the LAST line of stdout is the session
    /// string -- we capture it and write to Keychain via
    /// config.setTelegramUserSession().
    ///
    /// SECURITY (plan §7): the captured session string is
    /// written directly to Keychain. It is NEVER logged. It is
    /// NEVER included in `sessionGeneratorOutput` AFTER the
    /// Keychain write succeeds -- we clear the in-memory copy
    /// immediately. The `sessionGeneratorOutput` @State stays
    /// empty on the happy path.
    private func startSessionGeneration() {
        guard !generatingSession else { return }
        generatingSession = true
        sessionGeneratorError = nil
        sessionGeneratorOutput = ""
        let task = Task.detached { [pythonExecutable, sessionGeneratorArgs] in
            await self.runSessionGenerator(
                executable: pythonExecutable,
                baseArgs: sessionGeneratorArgs,
            )
        }
        sessionGeneratorOutput = ""  // placeholder
        _ = task
    }

    private func cancelSessionGeneration() {
        sessionGeneratorProcess?.terminate()
        sessionGeneratorProcess = nil
        generatingSession = false
        sessionGeneratorError = "Cancelled."
    }

    /// plan §8: rate-limit + daily-sent counter badge, shown
    /// next to the "Logged in as" text. Renders different
    /// content based on rate-limit state:
    /// - blocked (Telegram FLOOD_WAIT active): red warning
    ///   with the remaining seconds
    /// - near cap (>=80% of max): yellow warning
    /// - normal: neutral "X / 30 sent this hour"
    @ViewBuilder
    private var rateLimitBadge: some View {
        let rl = config.telegramRateLimit
        if rl.isBlocked {
            HStack(spacing: 4) {
                Image(systemName: "exclamationmark.triangle.fill")
                    .scaledFont(size: 10)
                    .foregroundColor(OmiColors.error)
                Text("Telegram cooldown: \(rl.secondsUntilNextSlot)s")
                    .scaledFont(size: 11)
                    .foregroundColor(OmiColors.error)
            }
        } else if rl.isNearCap {
            HStack(spacing: 4) {
                Image(systemName: "exclamationmark.circle.fill")
                    .scaledFont(size: 10)
                    .foregroundColor(OmiColors.warning)
                Text(rl.formatted)
                    .scaledFont(size: 11)
                    .foregroundColor(OmiColors.warning)
            }
        } else {
            Text(rl.formatted)
                .scaledFont(size: 11)
                .foregroundColor(OmiColors.textSecondary)
        }
    }

    /// plan §8: "this is your personal account" banner + ToS
    /// acknowledgement checkbox. Pinned to a separate view so it
    /// can be unit-tested as a self-contained component.
    @ViewBuilder
    private var personalAccountWarningBanner: some View {
        if !config.telegramAccountEnabled {
            VStack(alignment: .leading, spacing: 6) {
                HStack(alignment: .top, spacing: 6) {
                    Image(systemName: "exclamationmark.triangle.fill")
                        .scaledFont(size: 12)
                        .foregroundColor(OmiColors.warning)
                    Text("This will sign in to your personal Telegram account. Replies will appear to come from you, not from a bot. Telegram's Terms of Service restrict automated use of personal accounts -- use sparingly and at your own risk.")
                        .scaledFont(size: 11)
                        .foregroundColor(OmiColors.textPrimary)
                        .fixedSize(horizontal: false, vertical: true)
                }
                Toggle(isOn: $telegramAccountAcknowledged) {
                    Text("I understand this signs in as me and follows Telegram's ToS")
                        .scaledFont(size: 11)
                }
                .toggleStyle(.checkbox)
            }
            .padding(8)
            .background(OmiColors.warning.opacity(0.1))
            .cornerRadius(6)
        }
    }

    /// Sign out: clear the Keychain entry AND flip the on/off
    /// flag. If the Keychain delete fails (locked, ACL denied,
    /// etc.), the error is surfaced to the user and the UI is
    /// NOT updated -- so the user knows the session is still
    /// active.
    private func signOutUserAccount() {
        do {
            try config.clearTelegramUserSession()
            sessionGeneratorError = nil
        } catch {
            let msg = "Could not remove session from Keychain: " + String(describing: error) + ". " +
                "Try again, or sign out from System Settings > Passwords."
            sessionGeneratorError = msg
        }
    }

    /// Flip the user-account plugin's auto-reply toggle. Called
    /// when the user toggles the "Auto-reply" switch in the
    /// userAccountSection. Optimistically updates the binding
    /// (which the toggle control already did) and rolls back on
    /// error. Mirrors PluginCard.swift's flipAutoReply pattern
    /// but for the user-account toggleUserAccount endpoint.
    private func flipTelegramAutoReply(enabled: Bool) async {
        // Guard: don't fire a network call while one is already
        // in flight -- avoid double-tap race.
        if config.telegramAutoReplyInFlight { return }
        guard !config.pluginURL.isEmpty,
              !config.bearerToken.isEmpty
        else {
            // Not configured; revert the toggle UI to its prior
            // state. We didn't observe the prior value, so we
            // just leave the binding as the user-set value --
            // the next /status poll will correct it.
            return
        }
        config.telegramAutoReplyInFlight = true
        defer { config.telegramAutoReplyInFlight = false }
        do {
            _ = try await AICloneClient.shared.toggleUserAccount(
                baseURL: config.pluginURL,
                bearerToken: config.bearerToken,
                enabled: enabled
            )
        } catch {
            // Roll back the UI so the toggle doesn't show a
            // value the plugin didn't accept.
            await MainActor.run {
                config.telegramAutoReplyEnabled = !enabled
            }
            sessionGeneratorError =
                "Could not toggle auto-reply: "
                + String(describing: error)
        }
    }

    /// Run the subprocess and capture stdout. This is the heavy
    /// lifting of startSessionGeneration -- split out so the
    /// orchestration stays readable.
    private func runSessionGenerator(
        executable: String,
        baseArgs: [String],
    ) async {
        // Locate session_string_generator.py. It's a plugin file
        // under $WORKTREE/plugins/telegram-user-account/. If we
        // can't find it, fail fast.
        //
        // We try the canonical prod path, the Omi Dev path, the
        // current bundle path, and any omi-*.app bundle in
        // /Applications (covers named bundles like omi-feat-ai-clone-e2e).
        // The desktop launch script copies the user-account plugin's
        // files into the bundle's Resources/plugins/ directory.
        let candidates: [String] = {
            var paths: [String] = [
                Bundle.main.bundlePath + "/Contents/Resources/plugins/telegram-user-account/session_string_generator.py",
                "/Applications/omi.app/Contents/Resources/plugins/telegram-user-account/session_string_generator.py",
                "/Applications/omi Dev.app/Contents/Resources/plugins/telegram-user-account/session_string_generator.py",
            ]
            // Scan /Applications for any omi-*.app that has the script.
            let fm = FileManager.default
            if let apps = try? fm.contentsOfDirectory(atPath: "/Applications") {
                for app in apps where app.hasPrefix("omi") && app.hasSuffix(".app") {
                    let p = "/Applications/\(app)/Contents/Resources/plugins/telegram-user-account/session_string_generator.py"
                    if !paths.contains(p) { paths.append(p) }
                }
            }
            return paths
        }()
        var scriptPath: String?
        for c in candidates {
            if FileManager.default.fileExists(atPath: c) {
                scriptPath = c
                break
            }
        }
        guard let scriptPath else {
            await MainActor.run {
                self.sessionGeneratorError = "Could not find session_string_generator.py in the app bundle."
                self.generatingSession = false
            }
            return
        }

        // Launch the script in a VISIBLE Terminal.app window so
        // the user can see prompts (api_id, phone, code, 2FA) and
        // type responses. The script writes the session to a temp
        // file; we poll for a marker to know when it finished.
        let tempDir = NSTemporaryDirectory()
        let sessionFile = tempDir + "omi-telegram-session.txt"
        let markerFile = tempDir + "omi-telegram-marker.txt"

        // Clean up any stale files from a previous run.
        try? FileManager.default.removeItem(atPath: sessionFile)
        try? FileManager.default.removeItem(atPath: markerFile)

        // Build the shell command for Terminal.app.
        let argsStr = baseArgs.isEmpty ? "" : (" " + baseArgs.joined(separator: " "))
        let shellCmd = "\(executable)\(argsStr) \(scriptPath) --output-file \(sessionFile); echo $? > \(markerFile); echo ''; echo 'Done. You can close this window.'; sleep 3"

        // Open Terminal.app via osascript (simpler than NSAppleScript).
        #if os(macOS)
        let termProcess = Process()
        termProcess.executableURL = URL(fileURLWithPath: "/usr/bin/osascript")
        termProcess.arguments = ["-e",
            "tell application \"Terminal\"",
            "-e", "activate",
            "-e", "do script \"" + shellCmd + "\"",
            "-e", "end tell"]
        do {
            try termProcess.run()
            termProcess.waitUntilExit()
        } catch {
            await MainActor.run {
                self.sessionGeneratorError = "Could not open Terminal: \(error.localizedDescription)"
                self.generatingSession = false
            }
            return
        }
        #endif

        // Poll for the marker file (written when the script exits).
        var found = false
        for _ in 0..<600 {
            if Task.isCancelled { break }
            if FileManager.default.fileExists(atPath: markerFile) {
                found = true
                break
            }
            try? await Task.sleep(nanoseconds: 500_000_000)
        }

        let exitCode: Int32
        if found, let data = try? String(contentsOfFile: markerFile, encoding: .utf8) {
            exitCode = Int32(data.trimmingCharacters(in: .whitespacesAndNewlines)) ?? -1
        } else {
            exitCode = -1
        }
        try? FileManager.default.removeItem(atPath: markerFile)

        await MainActor.run {
            self.sessionGeneratorProcess = nil
            self.generatingSession = false
            if exitCode == 0 {
                guard let data = try? Data(contentsOf: URL(fileURLWithPath: sessionFile)),
                      let session = String(data: data, encoding: .utf8)?.trimmingCharacters(in: .whitespacesAndNewlines),
                      !session.isEmpty
                else {
                    self.sessionGeneratorError = "Generator produced no session string."
                    try? FileManager.default.removeItem(atPath: sessionFile)
                    return
                }
                do {
                    try self.config.setTelegramUserSession(session)
                    self.sessionGeneratorOutput = ""
                } catch {
                    self.sessionGeneratorError = "Could not save session to Keychain: \(error.localizedDescription)"
                }
                try? FileManager.default.removeItem(atPath: sessionFile)
            } else if exitCode == -1 {
                self.sessionGeneratorError = "Timed out waiting for session generation (5 min)."
                try? FileManager.default.removeItem(atPath: sessionFile)
            } else {
                self.sessionGeneratorError = "Session generation failed (exit code \(exitCode)). Check the Terminal window."
                try? FileManager.default.removeItem(atPath: sessionFile)
            }
        }
    }

    /// Returns true iff the URL is one we're willing to hand to
    /// `NSWorkspace.shared.open` for the given plugin. The host check is
    /// bound to the plugin: a Telegram deep link (`t.me`) is only valid
    /// when connecting the Telegram plugin, etc. — a phishing attack
    /// returning a `t.me` URL inside a WhatsApp connect sheet is rejected.
    /// Pure function — extracted so the gate can be unit-tested without
    /// launching any actual application.
    static func isSafeDeepLink(_ s: String, plugin: AIPlugin) -> Bool {
        guard let url = URL(string: s),
              let scheme = url.scheme?.lowercased(),
              DeepLinkSafeScheme(rawValue: scheme) != nil,
              let host = url.host?.lowercased(),
              host == DeepLinkSafeHost.expected(for: plugin)
        else { return false }
        return true
    }
}