// GENERATED by core/scripts/gen-bridge-http-conformance.mjs from contracts/fixtures/bridge-http-host-conformance.json — do not edit by hand.
// The runner calls BridgeHttpPolicy, the same policy seam BridgeHttpHandler uses.
import Foundation

struct BridgeHttpConformanceExpectation {
  let outcome: String
  let failureReason: String?
  let servedDelta: Int
  let backendHit: Int
  let method: String?
  let pathAndQuery: String?
  let body: String?
  let headers: [String: String]
  let forbiddenDropped: [String]
  let bodyAfterHeaders: Bool?
  let followRedirects: Bool?
  let responseStatus: Int?
  let responseBody: String?
  let retryAfterMs: Int?
  let correlationId: String?
  let duplicateReplyDroppedBySurface: Bool?
  let redirectLocationForwarded: Bool?
  let responseHeadersExposed: Bool?
  let swiftReply: String?
  let dartReply: String?
}

struct BridgeHttpConformanceCase {
  let id: String
  let scope: String
  let requestId: String?
  let method: String?
  let path: String?
  let missingId: Bool
  let malformed: Bool
  let requestHeaders: [String: String]
  let body: String?
  let credential: String?
  let transportFailure: String?
  let responseStatus: Int?
  let responseBody: String?
  let retryAfterSeconds: Int?
  let expected: BridgeHttpConformanceExpectation
}

enum BridgeHttpConformanceFixture {
  static let rows: [BridgeHttpConformanceCase] = [
    BridgeHttpConformanceCase(
      id: "bodyless-get", scope: "all",
      requestId: "hc-bodyless-get", method: "GET", path: "/v1/tasks?limit=2", missingId: false, malformed: false,
      requestHeaders: [:], body: nil, credential: "fixture-token",
      transportFailure: nil, responseStatus: nil, responseBody: nil, retryAfterSeconds: nil,
      expected: BridgeHttpConformanceExpectation(
        outcome: "dispatch", failureReason: nil, servedDelta: 1, backendHit: 1,
        method: "GET", pathAndQuery: "/v1/tasks?limit=2", body: nil, headers: ["authorization": "Bearer fixture-token"], forbiddenDropped: [],
        bodyAfterHeaders: nil, followRedirects: false, responseStatus: nil, responseBody: nil, retryAfterMs: nil,
        correlationId: nil, duplicateReplyDroppedBySurface: nil, redirectLocationForwarded: nil, responseHeadersExposed: nil,
        swiftReply: nil, dartReply: nil
      )
    ),
    BridgeHttpConformanceCase(
      id: "body-write-order", scope: "all",
      requestId: "hc-body-write-order", method: "POST", path: "/v1/tasks", missingId: false, malformed: false,
      requestHeaders: ["x-trace": "wave-9"], body: "{\"title\":\"fixture\"}", credential: "fixture-token",
      transportFailure: nil, responseStatus: nil, responseBody: nil, retryAfterSeconds: nil,
      expected: BridgeHttpConformanceExpectation(
        outcome: "dispatch", failureReason: nil, servedDelta: 1, backendHit: 1,
        method: "POST", pathAndQuery: "/v1/tasks", body: "{\"title\":\"fixture\"}", headers: ["authorization": "Bearer fixture-token", "content-type": "application/json", "x-trace": "wave-9"], forbiddenDropped: [],
        bodyAfterHeaders: true, followRedirects: false, responseStatus: nil, responseBody: nil, retryAfterMs: nil,
        correlationId: nil, duplicateReplyDroppedBySurface: nil, redirectLocationForwarded: nil, responseHeadersExposed: nil,
        swiftReply: nil, dartReply: nil
      )
    ),
    BridgeHttpConformanceCase(
      id: "forbidden-mixed-case-keeps-safe-header", scope: "all",
      requestId: "hc-forbidden-headers", method: "GET", path: "/v1/tasks", missingId: false, malformed: false,
      requestHeaders: ["AuThOrIzAtIoN": "Bearer forged", "COOKIE": "session=forged", "Proxy-Authorization": "Basic forged", "X-Trace": "kept"], body: nil, credential: "fixture-token",
      transportFailure: nil, responseStatus: nil, responseBody: nil, retryAfterSeconds: nil,
      expected: BridgeHttpConformanceExpectation(
        outcome: "dispatch", failureReason: nil, servedDelta: 1, backendHit: 1,
        method: "GET", pathAndQuery: "/v1/tasks", body: nil, headers: ["authorization": "Bearer fixture-token", "x-trace": "kept"], forbiddenDropped: ["authorization", "cookie", "proxy-authorization"],
        bodyAfterHeaders: nil, followRedirects: false, responseStatus: nil, responseBody: nil, retryAfterMs: nil,
        correlationId: nil, duplicateReplyDroppedBySurface: nil, redirectLocationForwarded: nil, responseHeadersExposed: nil,
        swiftReply: nil, dartReply: nil
      )
    ),
    BridgeHttpConformanceCase(
      id: "relative-query", scope: "all",
      requestId: "hc-relative-query", method: "PATCH", path: "/v1/tasks/task-1?dry_run=true", missingId: false, malformed: false,
      requestHeaders: [:], body: nil, credential: "fixture-token",
      transportFailure: nil, responseStatus: nil, responseBody: nil, retryAfterSeconds: nil,
      expected: BridgeHttpConformanceExpectation(
        outcome: "dispatch", failureReason: nil, servedDelta: 1, backendHit: 1,
        method: "PATCH", pathAndQuery: "/v1/tasks/task-1?dry_run=true", body: nil, headers: ["authorization": "Bearer fixture-token"], forbiddenDropped: [],
        bodyAfterHeaders: nil, followRedirects: false, responseStatus: nil, responseBody: nil, retryAfterMs: nil,
        correlationId: nil, duplicateReplyDroppedBySurface: nil, redirectLocationForwarded: nil, responseHeadersExposed: nil,
        swiftReply: nil, dartReply: nil
      )
    ),
    BridgeHttpConformanceCase(
      id: "absolute-path-rejected", scope: "all",
      requestId: "hc-absolute", method: "GET", path: "https://evil.example/v1/tasks", missingId: false, malformed: false,
      requestHeaders: [:], body: nil, credential: "fixture-token",
      transportFailure: nil, responseStatus: nil, responseBody: nil, retryAfterSeconds: nil,
      expected: BridgeHttpConformanceExpectation(
        outcome: "failure", failureReason: "shell-error", servedDelta: 0, backendHit: 0,
        method: nil, pathAndQuery: nil, body: nil, headers: [:], forbiddenDropped: [],
        bodyAfterHeaders: nil, followRedirects: nil, responseStatus: nil, responseBody: nil, retryAfterMs: nil,
        correlationId: nil, duplicateReplyDroppedBySurface: nil, redirectLocationForwarded: nil, responseHeadersExposed: nil,
        swiftReply: nil, dartReply: nil
      )
    ),
    BridgeHttpConformanceCase(
      id: "scheme-relative-path-rejected", scope: "all",
      requestId: "hc-scheme-relative", method: "GET", path: "//evil.example/v1/tasks", missingId: false, malformed: false,
      requestHeaders: [:], body: nil, credential: "fixture-token",
      transportFailure: nil, responseStatus: nil, responseBody: nil, retryAfterSeconds: nil,
      expected: BridgeHttpConformanceExpectation(
        outcome: "failure", failureReason: "shell-error", servedDelta: 0, backendHit: 0,
        method: nil, pathAndQuery: nil, body: nil, headers: [:], forbiddenDropped: [],
        bodyAfterHeaders: nil, followRedirects: nil, responseStatus: nil, responseBody: nil, retryAfterMs: nil,
        correlationId: nil, duplicateReplyDroppedBySurface: nil, redirectLocationForwarded: nil, responseHeadersExposed: nil,
        swiftReply: nil, dartReply: nil
      )
    ),
    BridgeHttpConformanceCase(
      id: "no-leading-slash-rejected", scope: "all",
      requestId: "hc-no-leading-slash", method: "GET", path: "v1/tasks", missingId: false, malformed: false,
      requestHeaders: [:], body: nil, credential: "fixture-token",
      transportFailure: nil, responseStatus: nil, responseBody: nil, retryAfterSeconds: nil,
      expected: BridgeHttpConformanceExpectation(
        outcome: "failure", failureReason: "shell-error", servedDelta: 0, backendHit: 0,
        method: nil, pathAndQuery: nil, body: nil, headers: [:], forbiddenDropped: [],
        bodyAfterHeaders: nil, followRedirects: nil, responseStatus: nil, responseBody: nil, retryAfterMs: nil,
        correlationId: nil, duplicateReplyDroppedBySurface: nil, redirectLocationForwarded: nil, responseHeadersExposed: nil,
        swiftReply: nil, dartReply: nil
      )
    ),
    BridgeHttpConformanceCase(
      id: "missing-credential", scope: "all",
      requestId: "hc-no-credential", method: "GET", path: "/v1/tasks", missingId: false, malformed: false,
      requestHeaders: [:], body: nil, credential: nil,
      transportFailure: nil, responseStatus: nil, responseBody: nil, retryAfterSeconds: nil,
      expected: BridgeHttpConformanceExpectation(
        outcome: "failure", failureReason: "not-authenticated", servedDelta: 0, backendHit: 0,
        method: nil, pathAndQuery: nil, body: nil, headers: [:], forbiddenDropped: [],
        bodyAfterHeaders: nil, followRedirects: nil, responseStatus: nil, responseBody: nil, retryAfterMs: nil,
        correlationId: nil, duplicateReplyDroppedBySurface: nil, redirectLocationForwarded: nil, responseHeadersExposed: nil,
        swiftReply: nil, dartReply: nil
      )
    ),
    BridgeHttpConformanceCase(
      id: "missing-correlation-id", scope: "transport-scoped",
      requestId: nil, method: "GET", path: "/v1/tasks", missingId: true, malformed: false,
      requestHeaders: [:], body: nil, credential: "fixture-token",
      transportFailure: nil, responseStatus: nil, responseBody: nil, retryAfterSeconds: nil,
      expected: BridgeHttpConformanceExpectation(
        outcome: "missing-id", failureReason: nil, servedDelta: 0, backendHit: 0,
        method: nil, pathAndQuery: nil, body: nil, headers: [:], forbiddenDropped: [],
        bodyAfterHeaders: nil, followRedirects: nil, responseStatus: nil, responseBody: nil, retryAfterMs: nil,
        correlationId: nil, duplicateReplyDroppedBySurface: nil, redirectLocationForwarded: nil, responseHeadersExposed: nil,
        swiftReply: "shell-error", dartReply: "none"
      )
    ),
    BridgeHttpConformanceCase(
      id: "malformed-message", scope: "transport-scoped",
      requestId: "hc-malformed", method: "", path: "", missingId: false, malformed: true,
      requestHeaders: [:], body: nil, credential: "fixture-token",
      transportFailure: nil, responseStatus: nil, responseBody: nil, retryAfterSeconds: nil,
      expected: BridgeHttpConformanceExpectation(
        outcome: "malformed", failureReason: "shell-error", servedDelta: 0, backendHit: 0,
        method: nil, pathAndQuery: nil, body: nil, headers: [:], forbiddenDropped: [],
        bodyAfterHeaders: nil, followRedirects: nil, responseStatus: nil, responseBody: nil, retryAfterMs: nil,
        correlationId: nil, duplicateReplyDroppedBySurface: nil, redirectLocationForwarded: nil, responseHeadersExposed: nil,
        swiftReply: "shell-error", dartReply: "shell-error"
      )
    ),
    BridgeHttpConformanceCase(
      id: "transport-offline", scope: "all",
      requestId: "hc-offline", method: "GET", path: "/v1/tasks", missingId: false, malformed: false,
      requestHeaders: [:], body: nil, credential: "fixture-token",
      transportFailure: "offline", responseStatus: nil, responseBody: nil, retryAfterSeconds: nil,
      expected: BridgeHttpConformanceExpectation(
        outcome: "transport-failure", failureReason: "offline", servedDelta: 1, backendHit: 1,
        method: nil, pathAndQuery: nil, body: nil, headers: [:], forbiddenDropped: [],
        bodyAfterHeaders: nil, followRedirects: nil, responseStatus: nil, responseBody: nil, retryAfterMs: nil,
        correlationId: nil, duplicateReplyDroppedBySurface: nil, redirectLocationForwarded: nil, responseHeadersExposed: nil,
        swiftReply: nil, dartReply: nil
      )
    ),
    BridgeHttpConformanceCase(
      id: "transport-timeout", scope: "all",
      requestId: "hc-timeout", method: "GET", path: "/v1/tasks", missingId: false, malformed: false,
      requestHeaders: [:], body: nil, credential: "fixture-token",
      transportFailure: "timeout", responseStatus: nil, responseBody: nil, retryAfterSeconds: nil,
      expected: BridgeHttpConformanceExpectation(
        outcome: "transport-failure", failureReason: "timeout", servedDelta: 1, backendHit: 1,
        method: nil, pathAndQuery: nil, body: nil, headers: [:], forbiddenDropped: [],
        bodyAfterHeaders: nil, followRedirects: nil, responseStatus: nil, responseBody: nil, retryAfterMs: nil,
        correlationId: nil, duplicateReplyDroppedBySurface: nil, redirectLocationForwarded: nil, responseHeadersExposed: nil,
        swiftReply: nil, dartReply: nil
      )
    ),
    BridgeHttpConformanceCase(
      id: "transport-cancelled", scope: "all",
      requestId: "hc-cancelled", method: "GET", path: "/v1/tasks", missingId: false, malformed: false,
      requestHeaders: [:], body: nil, credential: "fixture-token",
      transportFailure: "cancelled", responseStatus: nil, responseBody: nil, retryAfterSeconds: nil,
      expected: BridgeHttpConformanceExpectation(
        outcome: "transport-failure", failureReason: "cancelled", servedDelta: 1, backendHit: 1,
        method: nil, pathAndQuery: nil, body: nil, headers: [:], forbiddenDropped: [],
        bodyAfterHeaders: nil, followRedirects: nil, responseStatus: nil, responseBody: nil, retryAfterMs: nil,
        correlationId: nil, duplicateReplyDroppedBySurface: nil, redirectLocationForwarded: nil, responseHeadersExposed: nil,
        swiftReply: nil, dartReply: nil
      )
    ),
    BridgeHttpConformanceCase(
      id: "transport-shell-error", scope: "all",
      requestId: "hc-shell-error", method: "GET", path: "/v1/tasks", missingId: false, malformed: false,
      requestHeaders: [:], body: nil, credential: "fixture-token",
      transportFailure: "shell-error", responseStatus: nil, responseBody: nil, retryAfterSeconds: nil,
      expected: BridgeHttpConformanceExpectation(
        outcome: "transport-failure", failureReason: "shell-error", servedDelta: 1, backendHit: 1,
        method: nil, pathAndQuery: nil, body: nil, headers: [:], forbiddenDropped: [],
        bodyAfterHeaders: nil, followRedirects: nil, responseStatus: nil, responseBody: nil, retryAfterMs: nil,
        correlationId: nil, duplicateReplyDroppedBySurface: nil, redirectLocationForwarded: nil, responseHeadersExposed: nil,
        swiftReply: nil, dartReply: nil
      )
    ),
    BridgeHttpConformanceCase(
      id: "server-422-no-retry", scope: "all",
      requestId: "hc-422", method: "POST", path: "/v1/tasks", missingId: false, malformed: false,
      requestHeaders: [:], body: "{\"title\":\"invalid\"}", credential: "fixture-token",
      transportFailure: nil, responseStatus: 422, responseBody: "{\"detail\":\"invalid\"}", retryAfterSeconds: nil,
      expected: BridgeHttpConformanceExpectation(
        outcome: "response", failureReason: nil, servedDelta: 1, backendHit: 1,
        method: nil, pathAndQuery: nil, body: "{\"title\":\"invalid\"}", headers: [:], forbiddenDropped: [],
        bodyAfterHeaders: nil, followRedirects: nil, responseStatus: 422, responseBody: "{\"detail\":\"invalid\"}", retryAfterMs: nil,
        correlationId: nil, duplicateReplyDroppedBySurface: nil, redirectLocationForwarded: nil, responseHeadersExposed: false,
        swiftReply: nil, dartReply: nil
      )
    ),
    BridgeHttpConformanceCase(
      id: "server-429-integer-retry-after", scope: "all",
      requestId: "hc-429", method: "POST", path: "/v1/tasks", missingId: false, malformed: false,
      requestHeaders: [:], body: "{\"title\":\"busy\"}", credential: "fixture-token",
      transportFailure: nil, responseStatus: 429, responseBody: "{\"detail\":\"busy\"}", retryAfterSeconds: 3,
      expected: BridgeHttpConformanceExpectation(
        outcome: "response", failureReason: nil, servedDelta: 1, backendHit: 1,
        method: nil, pathAndQuery: nil, body: "{\"title\":\"busy\"}", headers: [:], forbiddenDropped: [],
        bodyAfterHeaders: nil, followRedirects: nil, responseStatus: 429, responseBody: "{\"detail\":\"busy\"}", retryAfterMs: 3000,
        correlationId: nil, duplicateReplyDroppedBySurface: nil, redirectLocationForwarded: nil, responseHeadersExposed: false,
        swiftReply: nil, dartReply: nil
      )
    ),
    BridgeHttpConformanceCase(
      id: "one-way-correlation", scope: "one-way",
      requestId: "hc-correlation", method: "GET", path: "/v1/tasks", missingId: false, malformed: false,
      requestHeaders: [:], body: nil, credential: "fixture-token",
      transportFailure: nil, responseStatus: 200, responseBody: "[]", retryAfterSeconds: nil,
      expected: BridgeHttpConformanceExpectation(
        outcome: "response", failureReason: nil, servedDelta: 1, backendHit: 1,
        method: nil, pathAndQuery: nil, body: nil, headers: [:], forbiddenDropped: [],
        bodyAfterHeaders: nil, followRedirects: nil, responseStatus: 200, responseBody: "[]", retryAfterMs: nil,
        correlationId: "hc-correlation", duplicateReplyDroppedBySurface: nil, redirectLocationForwarded: nil, responseHeadersExposed: false,
        swiftReply: nil, dartReply: nil
      )
    ),
    BridgeHttpConformanceCase(
      id: "one-way-duplicate-is-correlated-by-id", scope: "one-way",
      requestId: "hc-duplicate", method: "GET", path: "/v1/tasks", missingId: false, malformed: false,
      requestHeaders: [:], body: nil, credential: "fixture-token",
      transportFailure: nil, responseStatus: 200, responseBody: "[]", retryAfterSeconds: nil,
      expected: BridgeHttpConformanceExpectation(
        outcome: "response", failureReason: nil, servedDelta: 1, backendHit: 1,
        method: nil, pathAndQuery: nil, body: nil, headers: [:], forbiddenDropped: [],
        bodyAfterHeaders: nil, followRedirects: nil, responseStatus: 200, responseBody: "[]", retryAfterMs: nil,
        correlationId: "hc-duplicate", duplicateReplyDroppedBySurface: true, redirectLocationForwarded: nil, responseHeadersExposed: false,
        swiftReply: nil, dartReply: nil
      )
    ),
    BridgeHttpConformanceCase(
      id: "redirect-no-follow", scope: "all",
      requestId: "hc-redirect", method: "GET", path: "/redirect", missingId: false, malformed: false,
      requestHeaders: [:], body: nil, credential: "fixture-token",
      transportFailure: nil, responseStatus: 302, responseBody: nil, retryAfterSeconds: nil,
      expected: BridgeHttpConformanceExpectation(
        outcome: "response", failureReason: nil, servedDelta: 1, backendHit: 1,
        method: nil, pathAndQuery: nil, body: nil, headers: [:], forbiddenDropped: [],
        bodyAfterHeaders: nil, followRedirects: false, responseStatus: 302, responseBody: nil, retryAfterMs: nil,
        correlationId: nil, duplicateReplyDroppedBySurface: nil, redirectLocationForwarded: false, responseHeadersExposed: false,
        swiftReply: nil, dartReply: nil
      )
    ),
    BridgeHttpConformanceCase(
      id: "response-headers-not-exposed", scope: "all",
      requestId: "hc-no-response-headers", method: "GET", path: "/v1/tasks", missingId: false, malformed: false,
      requestHeaders: [:], body: nil, credential: "fixture-token",
      transportFailure: nil, responseStatus: 200, responseBody: "[]", retryAfterSeconds: nil,
      expected: BridgeHttpConformanceExpectation(
        outcome: "response", failureReason: nil, servedDelta: 1, backendHit: 1,
        method: nil, pathAndQuery: nil, body: nil, headers: [:], forbiddenDropped: [],
        bodyAfterHeaders: nil, followRedirects: nil, responseStatus: 200, responseBody: "[]", retryAfterMs: nil,
        correlationId: nil, duplicateReplyDroppedBySurface: nil, redirectLocationForwarded: nil, responseHeadersExposed: false,
        swiftReply: nil, dartReply: nil
      )
    )
  ]
}

private struct BridgeHttpConformanceBackend {
  private(set) var hits = 0

  mutating func receive(_ request: URLRequest) {
    // A separate sink models the backend boundary; served and backend-hit
    // counters must not be the same assignment in disguise.
    hits += 1
    _ = request
  }
}

private struct BridgeHttpConformanceReplyGate {
  private var settled = Set<String>()

  mutating func accept(_ id: String) -> Bool {
    settled.insert(id).inserted
  }
}

enum BridgeHttpConformanceRunner {
  static func run() -> [String] {
    let base = URL(string: "https://api.example")!
    var failures: [String] = []
    let sessionConfiguration = BridgeHttpPolicy.sessionConfiguration()
    // red-proof: re-enable cookie storage/acceptance in the live factory and
    // this host conformance runner fails before any fixture can pass.
    if sessionConfiguration.httpCookieStorage != nil || sessionConfiguration.httpShouldSetCookies || sessionConfiguration.httpCookieAcceptPolicy != .never {
      failures.append("session configuration must reject cookie persistence and acceptance")
    }
    for row in BridgeHttpConformanceFixture.rows {
      var served = 0
      var backend = BridgeHttpConformanceBackend()
      if row.missingId {
        if row.expected.outcome != "missing-id" || row.expected.servedDelta != 0 || row.expected.backendHit != 0 {
          failures.append("\(row.id): missing-id row must be zero-hit and transport-scoped")
        }
        if row.expected.swiftReply != "shell-error" { failures.append("\(row.id): Swift must reply shell-error for malformed input") }
        continue
      }
      guard let requestId = row.requestId, let method = row.method, let path = row.path else {
        failures.append("\(row.id): request id unexpectedly absent")
        continue
      }
      let decision = BridgeHttpPolicy.prepare(
        id: requestId, method: method, path: path,
        headers: row.requestHeaders, body: row.body, baseURL: base, token: row.credential)
      switch decision {
      case let .failure(reason, _):
        let expectedOutcome = row.malformed ? "malformed" : "failure"
        if row.expected.outcome != expectedOutcome { failures.append("\(row.id): expected dispatch, got failure") }
        if reason.rawValue != row.expected.failureReason { failures.append("\(row.id): failure reason") }
        if row.malformed && row.expected.swiftReply != "shell-error" { failures.append("\(row.id): Swift malformed input must reply shell-error") }
      case let .dispatch(prepared):
        served = 1
        let request = prepared.request
        // red-proof: remove backend.receive(request) and independent
        // backend-hit assertions fail.
        backend.receive(request)
        if row.expected.outcome == "failure" { failures.append("\(row.id): expected failure, got dispatch") }
        if let method = row.expected.method, request.httpMethod != method { failures.append("\(row.id): method") }
        if let path = row.expected.pathAndQuery, let url = request.url,
           url.path + (url.query.map { "?\($0)" } ?? "") != path { failures.append("\(row.id): path/query") }
        if let body = row.expected.body {
          let actual = request.httpBody.flatMap { String(data: $0, encoding: .utf8) }
          if actual != body { failures.append("\(row.id): body") }
        } else if request.httpBody != nil { failures.append("\(row.id): unexpected body") }
        for (name, value) in row.expected.headers where request.value(forHTTPHeaderField: name) != value {
          failures.append("\(row.id): header \(name)")
        }
        for forbidden in row.expected.forbiddenDropped {
          let callerValue = row.requestHeaders.first { $0.key.lowercased() == forbidden }?.value
          if let callerValue, request.value(forHTTPHeaderField: forbidden) == callerValue {
            failures.append("\(row.id): forbidden header \(forbidden) survived")
          }
        }
        var applyEvents: [String] = []
        // red-proof: move body before headers in BridgeHttpPolicy.apply and
        // the body-write-order fixture fails on this event sequence.
        BridgeHttpPolicy.apply(
          prepared,
          setHeader: { name, _ in applyEvents.append("header:\(name.lowercased())") },
          setBody: { _ in applyEvents.append("body") })
        if let expected = row.expected.bodyAfterHeaders {
          if expected && (applyEvents.last != "body" || (applyEvents.firstIndex(of: "body") ?? -1) <= (applyEvents.firstIndex(of: "header:content-type") ?? Int.max)) {
            failures.append("\(row.id): body write ordering")
          }
          if !expected && applyEvents.contains("body") { failures.append("\(row.id): unexpected body write") }
        }
        if let redirectResponse = HTTPURLResponse(url: base, statusCode: 302, httpVersion: nil, headerFields: nil) {
          // red-proof: make redirectedRequest return proposed and the
          // redirect-no-follow fixture fails against the live delegate seam.
          let redirected = BridgeHttpPolicy.redirectedRequest(response: redirectResponse, proposed: request)
          if let expected = row.expected.followRedirects, (redirected != nil) != expected { failures.append("\(row.id): redirect policy") }
          if let expected = row.expected.redirectLocationForwarded, (redirected != nil) != expected { failures.append("\(row.id): redirect location forwarded") }
        }
        if row.expected.duplicateReplyDroppedBySurface == true {
          // red-proof: remove the second accept rejection and duplicate-gate
          // conformance fails instead of accepting a late reply.
          var gate = BridgeHttpConformanceReplyGate()
          if !gate.accept(requestId) || gate.accept(requestId) { failures.append("\(row.id): duplicate reply was not dropped") }
        }
        if let failure = row.transportFailure {
          let actual = BridgeHttpPolicy.transportFailure(id: requestId, name: failure).reason.rawValue
          if actual != row.expected.failureReason { failures.append("\(row.id): transport failure") }
        }
        if let status = row.responseStatus {
          let normalized = BridgeHttpPolicy.normalizeResponse(id: requestId, status: status, body: row.responseBody, retryAfterSeconds: row.retryAfterSeconds)
          if normalized.status != row.expected.responseStatus || normalized.body != row.expected.responseBody || normalized.retryAfterMs != row.expected.retryAfterMs { failures.append("\(row.id): response normalization") }
          let payload = BridgeHttpPolicy.responsePayload(normalized)
          let exposed = payload["headers"] != nil || payload["set-cookie"] != nil || payload["www-authenticate"] != nil
          // red-proof: add response headers in the live reply factory and this
          // fixture fails instead of treating normalization as sufficient.
          if let expected = row.expected.responseHeadersExposed, exposed != expected { failures.append("\(row.id): response headers exposure") }
          if let id = row.expected.correlationId, normalized.id != id { failures.append("\(row.id): correlation id") }
        }
      }
      if served != row.expected.servedDelta { failures.append("\(row.id): servedCount delta \(served) != \(row.expected.servedDelta)") }
      if backend.hits != row.expected.backendHit { failures.append("\(row.id): backend-hit delta \(backend.hits) != \(row.expected.backendHit)") }
    }
    return failures
  }
}

#if BRIDGE_HTTP_CONFORMANCE_RUNNER
@main
enum BridgeHttpConformanceMain {
  static func main() {
    let failures = BridgeHttpConformanceRunner.run()
    if failures.isEmpty {
      print("bridge-http Swift conformance: \(BridgeHttpConformanceFixture.rows.count)/\(BridgeHttpConformanceFixture.rows.count) passed")
    } else {
      failures.forEach { print("FAIL: \($0)") }
      Foundation.exit(1)
    }
  }
}
#endif
