apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    {{- include "omi-oss.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  selector:
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: http
