{{- if .Values.push.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: ntfy
  labels:
    {{- include "omi-oss.labels" . | nindent 4 }}
    app.kubernetes.io/component: ntfy
spec:
  selector:
    app.kubernetes.io/component: ntfy
  ports:
    - name: http
      port: 80
      targetPort: 80
{{- end }}
