// GENERATED by tools/gen-bridge.mjs from contract/bridge.contract.json
// contract version 0.1.0 -- do not edit by hand.

export const BRIDGE_CONTRACT_VERSION = '0.1.0';

export interface DeviceState {
  connected: boolean;
  deviceId?: string | null;
  batteryPct?: number | null;
}

export interface StartListeningParams {
  sampleRateHz: number;
  language?: string | null;
}

export interface ListenSession {
  sessionId: string;
}

export interface TranscriptEvent {
  sessionId: string;
  text: string;
  isFinal: boolean;
  shellSentAtMs: number;
}

type Pending = { resolve: (v: unknown) => void; reject: (e: Error) => void };

declare global {
  interface Window {
    OmiBridge?: { postMessage: (msg: string) => void };
    __omiBridge?: {
      __reply: (raw: string) => void;
      __push: (raw: string) => void;
    };
  }
}

class OmiShellBridge {
  #seq = 0;
  #pending = new Map<string, Pending>();
  #subs = new Map<string, ((p: unknown) => void)[]>();

  constructor() {
    window.__omiBridge = {
      __reply: (raw: string) => {
        const e = JSON.parse(raw) as { id: string; ok: boolean; result?: unknown; error?: string };
        const p = this.#pending.get(e.id);
        if (!p) return;
        this.#pending.delete(e.id);
        e.ok ? p.resolve(e.result) : p.reject(new Error(e.error ?? 'bridge error'));
      },
      __push: (raw: string) => {
        const e = JSON.parse(raw) as { method: string; params: unknown };
        for (const cb of this.#subs.get(e.method) ?? []) cb(e.params);
      },
    };
  }

  get available(): boolean {
    return typeof window.OmiBridge?.postMessage === 'function';
  }

  #call<T>(method: string, params: unknown): Promise<T> {
    const ch = window.OmiBridge;
    if (!ch) return Promise.reject(new Error('shell bridge unavailable (running outside the shell?)'));
    const id = 'c' + ++this.#seq;
    return new Promise<T>((resolve, reject) => {
      this.#pending.set(id, { resolve: resolve as (v: unknown) => void, reject });
      ch.postMessage(JSON.stringify({ id, method, params: params ?? null }));
    });
  }

  #subscribe(method: string, cb: (p: unknown) => void): void {
    const list = this.#subs.get(method) ?? [];
    list.push(cb);
    this.#subs.set(method, list);
  }

  /** Surface asks the Flutter shell for current BLE device state. Shell owns BLE lifecycle (see constraints-and-conventions.md). */
  getDeviceState(): Promise<DeviceState> {
    return this.#call<DeviceState>('getDeviceState', undefined);
  }

  /** Surface commands the shell to open a capture session. Shell owns audio capture and the /listen socket. */
  startListening(params: StartListeningParams): Promise<ListenSession> {
    return this.#call<ListenSession>('startListening', params);
  }

  /** Shell pushes transcript segments to the surface. shellSentAtMs is set by the shell for latency measurement. */
  onTranscriptEvent(cb: (p: TranscriptEvent) => void): void {
    this.#subscribe('transcriptEvent', cb as (p: unknown) => void);
  }
}

export const bridge = new OmiShellBridge();
