"""Backward-compatible shim — canonical definitions live in ``models.memory_contracts`` (WS-G G6)."""

from models.memory_contracts import (
    DURABLE_MEMORY_PATCH_FACT_SOURCE,
    DurableMemoryPatch,
    DurablePatchDecision,
    EvidenceRef,
    L1MemoryArchiveClass,
    L1MemoryArchiveItem,
    L2MemoryRoute,
    L2SearchPlan,
    L2SearchRequest,
    L2SearchResult,
    LifecycleState,
    PromotionRoute,
    SourceBackedMemoryCandidate,
    V17_DURABLE_MEMORY_PATCH_FACT_SOURCE,
    WorkingMemoryObservation,
    WorkingObservation,
    WorkingObservationArchiveItem,
    derive_allowed_use,
    deterministic_contract_id,
    filter_l1_archive_for_normal_search,
)
from models.product_memory import MemoryTier

__all__ = [
    "DURABLE_MEMORY_PATCH_FACT_SOURCE",
    "DurableMemoryPatch",
    "DurablePatchDecision",
    "EvidenceRef",
    "L1MemoryArchiveClass",
    "L1MemoryArchiveItem",
    "L2MemoryRoute",
    "L2SearchPlan",
    "L2SearchRequest",
    "L2SearchResult",
    "LifecycleState",
    "MemoryTier",
    "PromotionRoute",
    "SourceBackedMemoryCandidate",
    "V17_DURABLE_MEMORY_PATCH_FACT_SOURCE",
    "WorkingMemoryObservation",
    "WorkingObservation",
    "WorkingObservationArchiveItem",
    "derive_allowed_use",
    "deterministic_contract_id",
    "filter_l1_archive_for_normal_search",
]
