{
 "title": "Cloud Armor denied requests",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Denied requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "aliasBy": "Denied requests",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "metric.type",
       "=",
       "logging.googleapis.com/user/cloud_armor_policy_denied_requests"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_SUM",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Denied requests per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "aliasBy": "Denied RPS",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "metric.type",
       "=",
       "logging.googleapis.com/user/cloud_armor_policy_denied_requests"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Denied request logs",
   "type": "logs",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "projectId": "based-hardware",
     "queryText": "resource.type=\"http_load_balancer\"\njsonPayload.enforcedSecurityPolicy.outcome=\"DENY\"\n",
     "viewId": "_AllLogs"
    }
   ]
  }
 ]
}