{
 "title": "Global External ALB",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "RPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS by Response Code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "aliasBy": "{{metric.label.response_code}}",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/request_count"
      ],
      "groupBys": [ "metric.label.response_code" ],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "RPS by Backend Name",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "aliasBy": "{{resource.label.backend_name}}",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/request_count"
      ],
      "groupBys": [ "resource.label.backend_name" ],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "RPS by Matched URL Path Rule",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "aliasBy": "{{resource.label.matched_url_path_rule}}",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/request_count"
      ],
      "groupBys": [
       "resource.label.matched_url_path_rule"
      ],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "RPS by Client Country",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "aliasBy": "{{metric.label.client_country}}",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/request_count"
      ],
      "groupBys": [ "metric.label.client_country" ],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Latency by Backend Name",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "aliasBy": "{{resource.label.backend_name}}",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/total_latencies"
      ],
      "groupBys": [ "resource.label.backend_name" ],
      "perSeriesAligner": "ALIGN_DELTA",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Latency by Client Country",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "aliasBy": "{{metric.label.client_country}}",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/total_latencies"
      ],
      "groupBys": [ "metric.label.client_country" ],
      "perSeriesAligner": "ALIGN_DELTA",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Latency by Matched URL Path Rule",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "aliasBy": "{{resource.label.matched_url_path_rule}}",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/total_latencies"
      ],
      "groupBys": [
       "resource.label.matched_url_path_rule"
      ],
      "perSeriesAligner": "ALIGN_DELTA",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Request bytes (Incoming traffic)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }
  },
  {
   "title": "Request bytes by Backend Name",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "aliasBy": "{{resource.label.backend_name}}",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/request_bytes_count"
      ],
      "groupBys": [ "resource.label.backend_name" ],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Request bytes by Client Country",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "aliasBy": "{{metric.label.client_country}}",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/request_bytes_count"
      ],
      "groupBys": [ "metric.label.client_country" ],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Request bytes by Matched URL Path Rule",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "aliasBy": "{{resource.label.matched_url_path_rule}}",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/request_bytes_count"
      ],
      "groupBys": [
       "resource.label.matched_url_path_rule"
      ],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Response bytes (Outgoing traffic)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 }
  },
  {
   "title": "Response bytes by Backend Name",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "aliasBy": "{{resource.label.backend_name}}",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/response_bytes_count"
      ],
      "groupBys": [ "resource.label.backend_name" ],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Response bytes by Backend Name",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "aliasBy": "{{metric.label.client_country}}",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/response_bytes_count"
      ],
      "groupBys": [ "metric.label.client_country" ],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Response bytes by Backend Name",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "aliasBy": "{{resource.label.matched_url_path_rule}}",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/response_bytes_count"
      ],
      "groupBys": [
       "resource.label.matched_url_path_rule"
      ],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  },
  { "title": "Frontend Round-trip Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Frontend RTT by Client Country",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "aliasBy": "{{metric.label.client_country}}",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [
       "metric.type",
       "=",
       "loadbalancing.googleapis.com/https/frontend_tcp_rtt"
      ],
      "groupBys": [ "metric.label.client_country" ],
      "perSeriesAligner": "ALIGN_DELTA",
      "preprocessor": "none",
      "projectName": "based-hardware",
      "view": "FULL"
     }
    }
   ]
  }
 ]
}