{{- if .Values.worker.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "node-feature-discovery.fullname" . }}-worker-conf
  namespace: {{ include "node-feature-discovery.namespace" . }}
  labels:
  {{- include "node-feature-discovery.labels" . | nindent 4 }}
data:
  nfd-worker.conf: |-
    {{- .Values.worker.config | toYaml | nindent 4 }}
{{- end }}
