{{- if .Values.master.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "node-feature-discovery.fullname" . }}-master-conf
  namespace: {{ include "node-feature-discovery.namespace" . }}
  labels:
  {{- include "node-feature-discovery.labels" . | nindent 4 }}
data:
  nfd-master.conf: |-
    {{- .Values.master.config | toYaml | nindent 4 }}
{{- end }}
