{{- if .Values.topologyUpdater.enable -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "node-feature-discovery.fullname" . }}-topology-updater-conf
  namespace: {{ include "node-feature-discovery.namespace" . }}
  labels:
  {{- include "node-feature-discovery.labels" . | nindent 4 }}
data:
  nfd-topology-updater.conf: |-
    {{- .Values.topologyUpdater.config | toYaml | nindent 4 }}
{{- end }}
