gke:
  projectID: <PROJECT_ID>
  clusterLocation: <CLUSTER_LOCATION>
  clusterName: <CLUSTER_NAME>

gsa:
  name: <GSA_NAME>

serviceAccount:
  name: <SERVICE_ACCOUNT_NAME>

externalSecret:
  name: <EXTERNAL_SECRET_NAME>
  targetSecretName: <TARGET_SECRET_NAME>
  refreshInterval: 1h
  secretKeys:   # secretKey is the key in the Kubernetes secret, remoteKey is the key in the Secrets Manager
    - secretKey: HUGGINGFACE_TOKEN
      remoteKey: HUGGINGFACE_TOKEN
