gke:
  projectID: based-hardware-dev
  clusterLocation: us-central1
  clusterName: dev-omi-gke

gsa:
  name: dev-omi-backend-eso-gsa@based-hardware-dev.iam.gserviceaccount.com

serviceAccount:
  name: dev-omi-backend-eso-ksa

externalSecret:
  name: dev-omi-backend-external-secret
  targetSecretName: dev-omi-backend-secrets
  refreshInterval: 1h
  secretKeys:   # secretKey is the key in the Kubernetes secret, remoteKey is the key in the Secrets Manager
    - secretKey: HUGGINGFACE_TOKEN
      remoteKey: HUGGINGFACE_TOKEN
    - secretKey: DEEPGRAM_API_KEY
      remoteKey: DEEPGRAM_API_KEY
    - secretKey: FAL_KEY
      remoteKey: FAL_KEY
    - secretKey: OPENAI_API_KEY
      remoteKey: OPENAI_API_KEY
    - secretKey: GOOGLE_MAPS_API_KEY
      remoteKey: GOOGLE_MAPS_API_KEY
    - secretKey: GITHUB_TOKEN
      remoteKey: GITHUB_TOKEN
    - secretKey: SONIOX_API_KEY
      remoteKey: SONIOX_API_KEY
    - secretKey: PINECONE_API_KEY
      remoteKey: PINECONE_API_KEY
    - secretKey: REDIS_DB_HOST
      remoteKey: REDIS_DB_HOST
    - secretKey: REDIS_DB_PASSWORD
      remoteKey: REDIS_DB_PASSWORD
    - secretKey: ADMIN_KEY
      remoteKey: ADMIN_KEY
    - secretKey: WORKFLOW_API_KEY
      remoteKey: WORKFLOW_API_KEY
    - secretKey: GOOGLE_APPLICATION_CREDENTIALS
      remoteKey: GOOGLE_APPLICATION_CREDENTIALS
    - secretKey: DD_API_KEY
      remoteKey: DD_API_KEY
    - secretKey: LANGCHAIN_API_KEY
      remoteKey: LANGCHAIN_API_KEY
    - secretKey: STRIPE_API_KEY
      remoteKey: STRIPE_API_KEY
    - secretKey: STRIPE_WEBHOOK_SECRET
      remoteKey: STRIPE_WEBHOOK_SECRET
    - secretKey: MARKETPLACE_APP_REVIEWERS
      remoteKey: MARKETPLACE_APP_REVIEWERS
    - secretKey: TYPESENSE_HOST
      remoteKey: TYPESENSE_HOST
    - secretKey: TYPESENSE_API_KEY
      remoteKey: TYPESENSE_API_KEY
    - secretKey: STT_SERVICE_MODELS
      remoteKey: STT_SERVICE_MODELS
    - secretKey: ENCRYPTION_SECRET
      remoteKey: ENCRYPTION_SECRET
