gke:
  projectID: <PROJECT_ID>
  clusterLocation: <CLUSTER_LOCATION>
  clusterName: <CLUSTER_NAME>

gsa:
  name: <GSA_NAME>

serviceAccount:
  name: <SERVICE_ACCOUNT_NAME>

externalSecret:
  name: <EXTERNAL_SECRET_NAME>
  targetSecretName: <TARGET_SECRET_NAME>
  refreshInterval: 1h
  secretKeys:   # secretKey is the key in the Kubernetes secret, remoteKey is the key in the Secrets Manager
    - secretKey: HUGGINGFACE_TOKEN
      remoteKey: HUGGINGFACE_TOKEN
    - secretKey: GITHUB_TOKEN
      remoteKey: GITHUB_TOKEN
    - secretKey: OPENAI_API_KEY
      remoteKey: OPENAI_API_KEY
    - secretKey: FAL_KEY
      remoteKey: FAL_KEY
    - secretKey: GROQ_API_KEY
      remoteKey: GROQ_API_KEY
    - secretKey: SONIOX_API_KEY
      remoteKey: SONIOX_API_KEY
    - secretKey: PINECONE_API_KEY
      remoteKey: PINECONE_API_KEY
    - secretKey: REDIS_DB_HOST
      remoteKey: REDIS_DB_HOST
    - secretKey: REDIS_DB_PASSWORD
      remoteKey: REDIS_DB_PASSWORD
    - secretKey: ADMIN_KEY
      remoteKey: ADMIN_KEY
    - secretKey: DEEPGRAM_API_KEY
      remoteKey: DEEPGRAM_API_KEY
    - secretKey: GOOGLE_MAPS_API_KEY
      remoteKey: GOOGLE_MAPS_API_KEY
    - secretKey: WORKFLOW_API_KEY
      remoteKey: WORKFLOW_API_KEY
    - secretKey: GOOGLE_APPLICATION_CREDENTIALS
      remoteKey: GOOGLE_APPLICATION_CREDENTIALS
    - secretKey: LANGCHAIN_API_KEY
      remoteKey: LANGCHAIN_API_KEY
    - secretKey: DD_API_KEY
      remoteKey: DD_API_KEY
    - secretKey: STRIPE_API_KEY
      remoteKey: STRIPE_API_KEY
    - secretKey: STRIPE_WEBHOOK_SECRET
      remoteKey: STRIPE_WEBHOOK_SECRET
    - secretKey: MARKETPLACE_APP_REVIEWERS
      remoteKey: MARKETPLACE_APP_REVIEWERS
    - secretKey: TYPESENSE_HOST
      remoteKey: TYPESENSE_HOST
    - secretKey: TYPESENSE_API_KEY
      remoteKey: TYPESENSE_API_KEY
    - secretKey: RAPID_API_HOST
      remoteKey: RAPID_API_HOST
    - secretKey: RAPID_API_KEY
      remoteKey: RAPID_API_KEY
    - secretKey: OPENROUTER_API_KEY
      remoteKey: OPENROUTER_API_KEY
    - secretKey: CONVERSATION_SUMMARIZED_APP_IDS
      remoteKey: CONVERSATION_SUMMARIZED_APP_IDS
