{{- if .Values.stackdriver.serviceAccountKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "stackdriver-exporter.fullname" . }}
  labels:
    {{- include "stackdriver-exporter.labels" . | indent 4 }}
    {{- if .Values.secret.labels }}
      {{- toYaml .Values.secret.labels | nindent 4 }}
    {{- end }}
type: Opaque
data:
  credentials.json: {{ .Values.stackdriver.serviceAccountKey | b64enc | quote }}
{{- end }}
