#!/usr/bin/env python3
"""B1 constrained Dart token scan: page/route inventory and changed-file key debt."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
CATALOG = 'app/contracts/addressability/catalog.json'
BASELINE = 'app/contracts/addressability/unkeyed-baseline.json'
GENERATED = 'app/lib/services/dev_controls/addressability_catalog.dart'
# Deliberately finite, shared with the widget contract. Custom wrappers need a
# review here; this is not Dart name/type resolution.
INTERACTIVE = set('IconButton TextButton ElevatedButton OutlinedButton FilledButton FloatingActionButton CupertinoButton GestureDetector InkWell InkResponse TextField TextFormField CupertinoTextField Checkbox Radio Switch Slider RangeSlider DropdownButton DropdownButtonFormField PopupMenuButton ListTile CheckboxListTile RadioListTile SwitchListTile'.split())
ROUTES = set('MaterialPageRoute CupertinoPageRoute PageRouteBuilder showModalBottomSheet showDialog routeToPage pushNamed pushReplacementNamed'.split())
TOKEN = re.compile(r'''//[^\n]*|/\*[\s\S]*?\*/|r?(?:"""[\s\S]*?"""|''' + "'''[\\s\\S]*?'''" + r'''|"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*')|[A-Za-z_$][\w$]*|[^\s]''')
ROUTE_HELP = (f'Add a routes entry in {CATALOG} with id, source, widget, root, reach, fixture, auth, profile, '
              'and ready_provider; add its root to keys. For each new navigation call, append the destination route id '
              'to navigation_sites[file] (do not add legacy/deferred entries). Then run '
              'python3 scripts/check_app_addressability.py --generate. '
              'Examples: app/lib/services/dev_controls/ADDRESSABILITY.md.')
KEY = re.compile(r'omi\.[a-z][a-z0-9_]*\.[a-z][a-z0-9_]*(?:\.[a-z0-9][a-z0-9_-]*)?\Z')


def tokens(source):
    return [m.group() for m in TOKEN.finditer(source) if not m.group().startswith(('//', '/*'))]


def calls(source, names):
    ts = tokens(source)
    for index, name in enumerate(ts):
        if name not in names:
            continue
        j = index + 1
        # Generic type arguments and named constructors (Switch.adaptive).
        if j < len(ts) and ts[j] == '<':
            depth = 1
            j += 1
            while j < len(ts) and depth:
                depth += (ts[j] == '<') - (ts[j] == '>')
                j += 1
        if j + 1 < len(ts) and ts[j] == '.':
            j += 2
        if j >= len(ts) or ts[j] != '(':
            continue
        start, depth = j + 1, 1
        j += 1
        while j < len(ts) and depth:
            depth += (ts[j] == '(') - (ts[j] == ')')
            j += 1
        if depth:
            raise ValueError(f'unbalanced {name} call')
        yield name, ts[start:j-1]


def named_args(ts):
    fields, start, depth = {}, 0, 0
    for i, token in enumerate(ts + [',']):
        if token in ('(', '[', '{'):
            depth += 1
        elif token in (')', ']', '}'):
            depth = max(0, depth - 1)
        if token == ',' and depth == 0:
            part = ts[start:i]
            if len(part) >= 3 and part[1] == ':':
                fields[part[0]] = part[2:]
            start = i + 1
    return fields


def debt(source, key_names):
    violations = []
    for name, ts in calls(source, INTERACTIVE):
        args = named_args(ts)
        if name in {'ListTile', 'GestureDetector', 'InkWell', 'InkResponse'} and not any(
            k.startswith(('onTap', 'onLongPress', 'onDoubleTap', 'onPan', 'onHorizontal', 'onVertical', 'onScale'))
            for k in args
        ):
            continue
        key = ''.join(args.get('key', []))
        valid = key in {f'OmiKeys.{k}' for k in key_names}
        literal = re.fullmatch(r'''(?:const)?(?:ValueKey(?:<String>)?|Key)\(['"]([^'"]+)['"]\)''', key)
        valid |= bool(literal and KEY.fullmatch(literal[1]) and literal[1] in key_names.values())
        valid |= bool(re.fullmatch(r'(?:ValueKey(?:<String>)?|Key)\(AddressKey.row\(.+\)\)', key))
        if not valid:
            violations.append(name)
    return violations


def generated(catalog):
    lines = ["// Generated by scripts/check_app_addressability.py --generate; do not edit.",
             "import 'package:flutter/widgets.dart';", '', 'abstract final class OmiKeys {']
    for name, value in catalog['keys'].items():
        lines.append(f"  static const {name} = ValueKey<String>('{value}');")
    lines.extend(['}', '', "const addressableRoutesJson =\n    r'''" + json.dumps(catalog['routes'], separators=(',', ':')) + "''';", ''])
    return '\n'.join(lines)


def read_base(base, path):
    p = subprocess.run(['git', 'show', f'{base}:{path}'], cwd=ROOT, capture_output=True, text=True)
    return p.stdout if p.returncode == 0 else None


def screen_classes(source):
    # Conventional screen declarations, including screens added to old files.
    # Tokenization removes comments/literals before matching declarations.
    return set(re.findall(
        r'\bclass\s+(\w+(?:Page|Screen|Drawer|Sheet))\s+extends\s+(?:StatefulWidget|StatelessWidget)\b',
        ' '.join(tokens(source))))


def validate_catalog(catalog, sources):
    errors = []
    ids, roots = set(), set()
    if len(set(catalog['keys'].values())) != len(catalog['keys']):
        errors.append('static keys must be unique')
    for key in catalog['keys'].values():
        if not KEY.fullmatch(key):
            errors.append(f'invalid namespaced key: {key}')
    for route in catalog['routes']:
        rid = route['id']
        if set(route) != {'id', 'source', 'widget', 'root', 'reach', 'fixture', 'auth', 'profile', 'ready_provider'}:
            errors.append(f'{rid}: route fields differ from route-registry-v1 schema')
        if not re.fullmatch(r'[a-z][a-z0-9_]*', rid):
            errors.append(f'{rid}: invalid route id')
        if route['source'] in sources and not re.search(r'\bclass\s+' + re.escape(route['widget']) + r'\b', sources[route['source']]):
            errors.append(f'{rid}: declared widget is absent from source')
        if route['reach']['kind'] == 'tab' and route['reach'].get('tab') not in range(4):
            errors.append(f'{rid}: missing tab index')
        if rid in ids or route['root'] in roots:
            errors.append(f'duplicate route/root: {rid}')
        ids.add(rid); roots.add(route['root'])
        if not KEY.fullmatch(route['root']) or route['root'] not in catalog['keys'].values():
            errors.append(f'{rid}: root missing from shared key namespace')
        if route['source'] not in sources or route['reach']['kind'] not in ('tab', 'push', 'sheet', 'onboarding'):
            errors.append(f'{rid}: source/reach missing')
        if route['profile'] != 'local_dev' or route['auth'] not in ('signed_in', 'signed_out'):
            errors.append(f'{rid}: invalid dev route precondition')
        if route['fixture'] not in catalog['fixtures']:
            errors.append(f'{rid}: unknown fixture')
    known_pages = set(catalog['deferred_pages']) | {r['source'] for r in catalog['routes']}
    for path, source in sources.items():
        registered_widgets = {r['widget'] for r in catalog['routes'] if r['source'] == path}
        registered_widgets.update(catalog.get('deferred_widgets', {}).get(path, []))
        for widget in screen_classes(source) - registered_widgets:
            errors.append(f'{path}: new screen class {widget} needs a route registry entry; {ROUTE_HELP}')
        if path.startswith('app/lib/pages/') and path not in known_pages:
            errors.append(f'{path}: new page file needs a route registry entry; {ROUTE_HELP}')
        actual = len(list(calls(source, ROUTES)))
        registered = catalog['navigation_sites'].get(path, [])
        if actual != len(registered):
            errors.append(f'{path}: {actual} navigation sites != registered {len(registered)}; describe new route in catalog; {ROUTE_HELP}')
    for path, sites in catalog['navigation_sites'].items():
        for site in sites:
            if not site.startswith('legacy:') and site not in ids:
                errors.append(f'{path}: navigation site {site} is not a registered route id; {ROUTE_HELP}')
        if path not in sources:
            errors.append(f'{path}: stale navigation inventory')
    return errors


def inventory_growth(catalog, previous):
    errors = []
    if set(catalog['deferred_pages']) - set(previous['deferred_pages']):
        errors.append(f'new pages cannot be deferred; register their route; {ROUTE_HELP}')
    for path, widgets in catalog.get('deferred_widgets', {}).items():
        if set(widgets) - set(previous.get('deferred_widgets', {}).get(path, [])):
            errors.append(f'{path}: legacy screen-class inventory cannot grow; register routes; {ROUTE_HELP}')
    for path, sites in catalog['navigation_sites'].items():
        old_sites = previous['navigation_sites'].get(path, [])
        for legacy in (site for site in sites if site.startswith('legacy:')):
            if sites.count(legacy) > old_sites.count(legacy):
                errors.append(f'{path}: legacy navigation inventory cannot grow; use route ids; {ROUTE_HELP}')
    return errors


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--changed-files')
    parser.add_argument('--base', default='origin/main')
    parser.add_argument('--generate', action='store_true')
    parser.add_argument('--surface')
    args = parser.parse_args()
    catalog = json.loads((ROOT / CATALOG).read_text())
    if args.generate:
        (ROOT / GENERATED).write_text(generated(catalog))
        return 0
    paths = subprocess.check_output(['git', 'ls-files', '--cached', '--others', '--exclude-standard', 'app/lib'], cwd=ROOT, text=True).splitlines()
    sources = {p: (ROOT / p).read_text() for p in set(paths) if p.endswith('.dart') and (ROOT / p).exists() and not p.endswith(('.g.dart', '.gen.dart'))}
    if args.surface:
        route = next(r for r in catalog['routes'] if r['id'] == args.surface)
        directory = str(Path(route['source']).parent) + '/'
        violations = {p: debt(s, catalog['keys']) for p, s in sources.items() if p.startswith(directory)}
        violations = {p: v for p, v in violations.items() if v}
        for p, v in violations.items():
            print(f'{p}: {len(v)} unkeyed controls', file=sys.stderr)
        return int(bool(violations))
    errors = validate_catalog(catalog, sources)
    if (ROOT / GENERATED).read_text() != generated(catalog):
        errors.append(f'{GENERATED}: regenerate from catalog')
    baseline = json.loads((ROOT / BASELINE).read_text())
    prior_catalog = read_base(args.base, CATALOG)
    if prior_catalog:
        errors.extend(inventory_growth(catalog, json.loads(prior_catalog)))
    old = read_base(args.base, BASELINE)
    if old:
        old = json.loads(old)
        for p, count in baseline.items():
            if count > old.get(p, 0):
                errors.append(f'{p}: baseline cannot grow')
    changed = Path(args.changed_files).read_text().splitlines() if args.changed_files else list(sources)
    for path in changed:
        if path not in sources:
            continue
        count = len(debt(sources[path], catalog['keys']))
        limit = baseline.get(path, 0)
        base_source = read_base(args.base, path)
        if base_source is not None:
            limit = min(limit, len(debt(base_source, catalog['keys'])))
        if count > limit:
            errors.append(f'{path}: {count} unkeyed interactive widgets > {limit}; use OmiKeys or namespaced ValueKey')
    for error in errors:
        print(error, file=sys.stderr)
    print(f'Addressability: {len(catalog["routes"])} routes; {len(sources)} Dart files; {len(errors)} errors')
    return int(bool(errors))


if __name__ == '__main__':
    raise SystemExit(main())
