#!/usr/bin/env python3
"""B1 constrained Dart token scan: explicit route/control catalog and changed-file key debt."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
CATALOG = 'app/contracts/addressability/catalog.json'
BASELINE = 'app/contracts/addressability/unkeyed-baseline.json'
ADOPTED = 'app/contracts/addressability/adopted-files.json'
GENERATED = 'app/lib/services/dev_controls/addressability_catalog.dart'
# One constructor/callback vocabulary generates the runtime predicate too.
INTERACTIVE = json.loads((ROOT / CATALOG).read_text())['interactive_widgets']
INTERACTIVE_GENERATED = 'app/test/support/addressability_widgets.dart'
TOKEN = re.compile(r'''//[^\n]*|/\*[\s\S]*?\*/|r?(?:"""[\s\S]*?"""|''' + "'''[\\s\\S]*?'''" + r'''|"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*')|[A-Za-z_$][\w$]*|[^\s]''')
ROUTE_HELP = (f'Add a routes entry and root key in {CATALOG}, then add the controls needed by your journey '
              'to controls[route_id] and run python3 scripts/check_app_addressability.py --generate. '
              'Implement navigation and the surface test; see app/lib/services/dev_controls/ADDRESSABILITY.md.')
KEY = re.compile(r'omi\.[a-z][a-z0-9_]*\.[a-z][a-z0-9_]*(?:\.[a-z0-9][a-z0-9_-]*)?\Z')


def tokens(source):
    return [m.group() for m in TOKEN.finditer(source) if not m.group().startswith(('//', '/*'))]


def calls(source, names):
    ts = tokens(source)
    for index, name in enumerate(ts):
        if name not in names:
            continue
        j = index + 1
        # Generic type arguments and named constructors (Switch.adaptive).
        if j < len(ts) and ts[j] == '<':
            depth = 1
            j += 1
            while j < len(ts) and depth:
                depth += (ts[j] == '<') - (ts[j] == '>')
                j += 1
        if j + 1 < len(ts) and ts[j] == '.':
            j += 2
        if j >= len(ts) or ts[j] != '(':
            continue
        start, depth = j + 1, 1
        j += 1
        while j < len(ts) and depth:
            depth += (ts[j] == '(') - (ts[j] == ')')
            j += 1
        if depth:
            raise ValueError(f'unbalanced {name} call')
        yield name, ts[start:j-1]


def named_args(ts):
    fields, start, depth = {}, 0, 0
    for i, token in enumerate(ts + [',']):
        if token in ('(', '[', '{'):
            depth += 1
        elif token in (')', ']', '}'):
            depth = max(0, depth - 1)
        if token == ',' and depth == 0:
            part = ts[start:i]
            if len(part) >= 3 and part[1] == ':':
                fields[part[0]] = part[2:]
            start = i + 1
    return fields


def debt(source, key_names):
    violations = []
    for name, ts in calls(source, INTERACTIVE):
        args = named_args(ts)
        callbacks = INTERACTIVE[name]
        if callbacks is not None and not set(callbacks).intersection(args):
            continue
        key = ''.join(args.get('key', []))
        valid = key in {f'OmiKeys.{k}' for k in key_names}
        literal = re.fullmatch(r'''(?:const)?(?:ValueKey(?:<String>)?|Key)\(['"]([^'"]+)['"]\)''', key)
        valid |= bool(literal and KEY.fullmatch(literal[1]) and literal[1] in key_names.values())
        valid |= bool(re.fullmatch(r'(?:ValueKey(?:<String>)?|Key)\(AddressKey.row\(.+\)\)', key))
        if not valid:
            violations.append(name)
    return violations


def generated(catalog):
    lines = ["// Generated by scripts/check_app_addressability.py --generate; do not edit.",
             "import 'package:flutter/widgets.dart';", '', 'abstract final class OmiKeys {']
    for name, value in catalog['keys'].items():
        lines.append(f"  static const {name} = ValueKey<String>('{value}');")
    lines.extend(['}', '', "const addressableControlsJson =\n    r'''" + json.dumps(catalog['controls'], separators=(',', ':')) + "''';", '', "const addressableRoutesJson =\n    r'''" + json.dumps(catalog['routes'], separators=(',', ':')) + "''';", ''])
    return '\n'.join(lines)


def read_base(base, path):
    p = subprocess.run(['git', 'show', f'{base}:{path}'], cwd=ROOT, capture_output=True, text=True)
    return p.stdout if p.returncode == 0 else None


def generated_interactive(catalog):
    lines = ["// Generated by scripts/check_app_addressability.py --generate; do not edit.",
             "import 'package:flutter/material.dart';", "import 'package:flutter/cupertino.dart';", '',
             'bool isCatalogInteractive(Widget widget, {bool includeDisabled = false}) {']
    for name, callbacks in catalog['interactive_widgets'].items():
        lines.append(f'  if (widget is {name}) {{')
        if callbacks is None:
            lines.append('    return true;')
        elif len(callbacks) == 2:
            lines.append('    return includeDisabled || ' + ' || '.join(f'widget.{c} != null' for c in callbacks) + ';')
        else:
            lines.append('    return includeDisabled ||')
            for index, callback in enumerate(callbacks):
                suffix = ';' if index == len(callbacks) - 1 else ' ||'
                lines.append(f'        widget.{callback} != null{suffix}')
        lines.append('  }')
    lines.extend(['  return false;', '}', ''])
    return '\n'.join(lines)


def declared_routes(source):
    # Explicit opt-in only. A lexical scan cannot decide whether a dialog,
    # helper, or even a class named FooPage is a separately reachable screen.
    return re.findall(r'^\s*// omi-route: ([a-z][a-z0-9_]*)\s*$', source, re.M)


def surface_errors(catalog, rid, sources):
    route = next(r for r in catalog['routes'] if r['id'] == rid)
    errors = []
    if rid not in declared_routes(sources.get(route['source'], '')):
        errors.append(f"{route['source']}: add // omi-route: {rid} beside the screen declaration; {ROUTE_HELP}")
    for control in catalog['controls'][rid]:
        source = sources.get(control['source'], '')
        if control['row_id']:
            found = 'AddressKey.row' in ''.join(tokens(source))
        else:
            names = [name for name, key in catalog['keys'].items() if key == control['key']]
            found = any(f'OmiKeys.{name}' in ''.join(tokens(source)) for name in names)
        if not found:
            errors.append(f"{control['source']}: reference catalogued key {control['key']}; the widget contract proves actual placement")
    return errors


def validate_catalog(catalog, sources):
    errors = []
    ids, roots = set(), set()
    if len(set(catalog['keys'].values())) != len(catalog['keys']):
        errors.append('static keys must be unique')
    for key in catalog['keys'].values():
        if not KEY.fullmatch(key):
            errors.append(f'invalid namespaced key: {key}')
    for route in catalog['routes']:
        rid = route['id']
        if set(route) != {'id', 'source', 'widget', 'root', 'reach', 'fixture', 'auth', 'profile', 'ready_provider'}:
            errors.append(f'{rid}: route fields differ from route-registry-v1 schema')
        if not re.fullmatch(r'[a-z][a-z0-9_]*', rid):
            errors.append(f'{rid}: invalid route id')
        if route['source'] in sources and not re.search(r'\bclass\s+' + re.escape(route['widget']) + r'\b', sources[route['source']]):
            errors.append(f'{rid}: declared widget is absent from source')
        if route['reach']['kind'] == 'tab' and route['reach'].get('tab') not in range(4):
            errors.append(f'{rid}: missing tab index')
        if rid in ids or route['root'] in roots:
            errors.append(f'duplicate route/root: {rid}')
        ids.add(rid); roots.add(route['root'])
        if not KEY.fullmatch(route['root']) or route['root'] not in catalog['keys'].values():
            errors.append(f'{rid}: root missing from shared key namespace')
        if route['reach']['kind'] not in ('tab', 'push', 'sheet', 'onboarding'):
            errors.append(f'{rid}: source/reach missing')
        if route['profile'] != 'local_dev' or route['auth'] not in ('signed_in', 'signed_out'):
            errors.append(f'{rid}: invalid dev route precondition')
        if route['fixture'] not in catalog['fixtures']:
            errors.append(f'{rid}: unknown fixture')
    for rid, controls in catalog['controls'].items():
        if rid not in ids or not controls:
            errors.append(f'{rid}: controls need a registered route and nonempty explicit catalog')
        seen = set()
        for control in controls:
            key = control['key']
            if key in seen or not KEY.fullmatch(key):
                errors.append(f'{rid}: invalid/duplicate control key {key}')
            seen.add(key)
            if not control['row_id'] and key not in catalog['keys'].values():
                errors.append(f'{rid}: control key missing from keys: {key}')
            if control['role'] not in ('button', 'textField') or control['action'] != ('setText' if control['role'] == 'textField' else 'tap'):
                errors.append(f'{rid}: unsupported catalog role/action')
            if not control['label_en'].strip() or 'omi.' in control['label_en'] or 'seeded-' in control['label_en']:
                errors.append(f'{rid}: catalog needs a human label')
    if set(catalog['controls']) != ids:
        errors.append('every registered route needs a controls catalog')
    for path, source in sources.items():
        for rid in declared_routes(source):
            if not any(r['id'] == rid and r['source'] == path for r in catalog['routes']):
                errors.append(f'{path}: declared route {rid} is not registered; {ROUTE_HELP}')
    return errors


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--changed-files')
    parser.add_argument('--base', default='origin/main')
    parser.add_argument('--generate', action='store_true')
    parser.add_argument('--surface')
    args = parser.parse_args()
    catalog = json.loads((ROOT / CATALOG).read_text())
    if args.generate:
        (ROOT / GENERATED).write_text(generated(catalog))
        (ROOT / INTERACTIVE_GENERATED).write_text(generated_interactive(catalog))
        return 0
    if args.changed_files:
        changed = Path(args.changed_files).read_text().splitlines()
    else:
        # origin/main may advance while a stacked contract branch is reviewed.
        # Its unrelated incoming changes are not contributor changes here.
        args.base = subprocess.check_output(['git', 'merge-base', 'HEAD', args.base], cwd=ROOT, text=True).strip()
        changed = subprocess.check_output(
            ['git', 'diff', '--name-only', args.base, '--', 'app/lib', 'app/contracts/addressability'], cwd=ROOT, text=True).splitlines()
        changed += subprocess.check_output(
            ['git', 'ls-files', '--others', '--exclude-standard', '--', 'app/lib'], cwd=ROOT, text=True).splitlines()
    paths = set(changed)
    if args.surface:
        route = next(r for r in catalog['routes'] if r['id'] == args.surface)
        paths = {route['source']} | {c['source'] for c in catalog['controls'][args.surface]}
    elif CATALOG in paths:
        paths.update(r['source'] for r in catalog['routes'])
        paths.update(c['source'] for controls in catalog['controls'].values() for c in controls)
    sources = {p: (ROOT / p).read_text() for p in paths if p.endswith('.dart') and (ROOT / p).exists()
               and p.startswith('app/lib/') and not p.endswith(('.g.dart', '.gen.dart'))}
    if args.surface:
        errors = surface_errors(catalog, args.surface, sources)
    else:
        errors = validate_catalog(catalog, sources)
    catalog_sources = {r['source'] for r in catalog['routes']} | {c['source'] for controls in catalog['controls'].values() for c in controls}
    for path in catalog_sources if CATALOG in paths else catalog_sources.intersection(paths):
        if not (ROOT / path).is_file():
            errors.append(f'{path}: catalog source is missing; update its registered source; {ROUTE_HELP}')
    for path, expected in [(GENERATED, generated(catalog)), (INTERACTIVE_GENERATED, generated_interactive(catalog))]:
        if (ROOT / path).read_text() != expected:
            errors.append(f'{path}: run python3 scripts/check_app_addressability.py --generate')
    adopted = set(json.loads((ROOT / ADOPTED).read_text()))
    old_adopted = set(json.loads(read_base(args.base, ADOPTED) or '[]'))
    if not old_adopted <= adopted:
        errors.append(f'{ADOPTED}: adopted files cannot be removed')
    baseline = json.loads((ROOT / BASELINE).read_text())
    old = read_base(args.base, BASELINE)
    if old:
        old = json.loads(old)
        for p, count in baseline.items():
            if p in adopted and count > old.get(p, 0):
                errors.append(f'{p}: baseline cannot grow')
    for path in ([] if args.surface else changed):
        if path not in sources:
            continue
        base_source = read_base(args.base, path)
        if base_source is not None and path not in adopted:
            continue
        count = len(debt(sources[path], catalog['keys']))
        limit = baseline.get(path, 0)
        if base_source is not None:
            limit = min(limit, len(debt(base_source, catalog['keys'])))
        if count > limit:
            errors.append(f'{path}: {count} unkeyed interactive widgets > {limit}; add a unique omi.<surface>.<control> '
                          f'to keys in {CATALOG}, run python3 scripts/check_app_addressability.py --generate, '
                          'then put OmiKeys.<name> on the interactive widget (a child key does not cover its parent)')
    for error in errors:
        print(error, file=sys.stderr)
    print(f'Addressability: {len(catalog["routes"])} routes; {len(sources)} Dart files; {len(errors)} errors')
    return int(bool(errors))


if __name__ == '__main__':
    raise SystemExit(main())
