name: Push to Replicate

on:
  #  push:
  #    branches: [ "master" ]
  workflow_dispatch:
#    inputs:
#      model_name:
#        required: true
#        description: "basedhardware/speechbrain-vad"

jobs:
  create-runner:
    environment: prod
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.create-runner.outputs.label }}
    steps:
      - id: create-runner
        uses: related-sciences/gce-github-runner@v0.11
        with:
          token: ${{ secrets.GH_SA_TOKEN }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          image_project: ubuntu-os-cloud
          image_family: ubuntu-2004-lts
  build:
    environment: prod
    needs: create-runner
    runs-on: ${{ needs.create-runner.outputs.label }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}

      - name: Push to Replicate
        run: |
          cd replicate/vad/; cog push r8.im/basedhardware/speechbrain-vad