export const SESSION_UNREACHABLE_COPY =
  "Couldn't reach Omi to check your session. Try Sign in again when you are online.";

export const PRIVACY_URL = 'https://www.omi.me/pages/privacy';
export const TERMS_URL = 'https://www.omi.me/pages/terms-of-service';

// Mirrors the desktop app's supportedLanguages list (AssistantSettings.swift)
// so every surface offers the identical language set, in the same order.
export const PRIMARY_LANGUAGES = [
  {code: 'ar', name: 'Arabic'},
  {code: 'ar-AE', name: 'Arabic (United Arab Emirates)'},
  {code: 'ar-SA', name: 'Arabic (Saudi Arabia)'},
  {code: 'ar-QA', name: 'Arabic (Qatar)'},
  {code: 'ar-KW', name: 'Arabic (Kuwait)'},
  {code: 'ar-SY', name: 'Arabic (Syria)'},
  {code: 'ar-LB', name: 'Arabic (Lebanon)'},
  {code: 'ar-PS', name: 'Arabic (Palestine)'},
  {code: 'ar-JO', name: 'Arabic (Jordan)'},
  {code: 'ar-EG', name: 'Arabic (Egypt)'},
  {code: 'ar-SD', name: 'Arabic (Sudan)'},
  {code: 'ar-TD', name: 'Arabic (Chad)'},
  {code: 'ar-MA', name: 'Arabic (Morocco)'},
  {code: 'ar-DZ', name: 'Arabic (Algeria)'},
  {code: 'ar-TN', name: 'Arabic (Tunisia)'},
  {code: 'ar-IQ', name: 'Arabic (Iraq)'},
  {code: 'ar-IR', name: 'Arabic (Iran)'},
  {code: 'be', name: 'Belarusian'},
  {code: 'bn', name: 'Bengali'},
  {code: 'bs', name: 'Bosnian'},
  {code: 'en', name: 'English'},
  {code: 'en-US', name: 'English (US)'},
  {code: 'en-GB', name: 'English (UK)'},
  {code: 'en-AU', name: 'English (Australia)'},
  {code: 'en-IN', name: 'English (India)'},
  {code: 'en-NZ', name: 'English (New Zealand)'},
  {code: 'bg', name: 'Bulgarian'},
  {code: 'ca', name: 'Catalan'},
  {code: 'zh-CN', name: 'Chinese (Simplified)'},
  {code: 'zh-HK', name: 'Chinese (Hong Kong)'},
  {code: 'zh-TW', name: 'Chinese (Taiwan)'},
  {code: 'cs', name: 'Czech'},
  {code: 'da', name: 'Danish'},
  {code: 'da-DK', name: 'Danish (Denmark)'},
  {code: 'nl', name: 'Dutch'},
  {code: 'nl-BE', name: 'Dutch (Belgium)'},
  {code: 'et', name: 'Estonian'},
  {code: 'fa', name: 'Persian'},
  {code: 'fi', name: 'Finnish'},
  {code: 'fr', name: 'French'},
  {code: 'fr-CA', name: 'French (Canada)'},
  {code: 'de', name: 'German'},
  {code: 'de-CH', name: 'German (Switzerland)'},
  {code: 'el', name: 'Greek'},
  {code: 'he', name: 'Hebrew'},
  {code: 'hi', name: 'Hindi'},
  {code: 'hr', name: 'Croatian'},
  {code: 'hu', name: 'Hungarian'},
  {code: 'id', name: 'Indonesian'},
  {code: 'it', name: 'Italian'},
  {code: 'ja', name: 'Japanese'},
  {code: 'kn', name: 'Kannada'},
  {code: 'ko', name: 'Korean'},
  {code: 'ko-KR', name: 'Korean (South Korea)'},
  {code: 'lv', name: 'Latvian'},
  {code: 'lt', name: 'Lithuanian'},
  {code: 'mk', name: 'Macedonian'},
  {code: 'mr', name: 'Marathi'},
  {code: 'ms', name: 'Malay'},
  {code: 'no', name: 'Norwegian'},
  {code: 'pl', name: 'Polish'},
  {code: 'pt', name: 'Portuguese'},
  {code: 'pt-BR', name: 'Portuguese (Brazil)'},
  {code: 'pt-PT', name: 'Portuguese (Portugal)'},
  {code: 'ro', name: 'Romanian'},
  {code: 'ru', name: 'Russian'},
  {code: 'sk', name: 'Slovak'},
  {code: 'sl', name: 'Slovenian'},
  {code: 'sr', name: 'Serbian'},
  {code: 'es', name: 'Spanish'},
  {code: 'es-419', name: 'Spanish (Latin America)'},
  {code: 'sv', name: 'Swedish'},
  {code: 'sv-SE', name: 'Swedish (Sweden)'},
  {code: 'ta', name: 'Tamil'},
  {code: 'te', name: 'Telugu'},
  {code: 'th', name: 'Thai'},
  {code: 'th-TH', name: 'Thai (Thailand)'},
  {code: 'tl', name: 'Tagalog'},
  {code: 'tr', name: 'Turkish'},
  {code: 'uk', name: 'Ukrainian'},
  {code: 'ur', name: 'Urdu'},
  {code: 'vi', name: 'Vietnamese'},
] as const;

export const ACQUISITION_SOURCES = [
  'TikTok',
  'YouTube',
  'Instagram',
  'X (Twitter)',
  'Reddit',
  'LinkedIn',
  'Friend',
  'Coworker',
  'Event',
  'App Store',
  'Google Search',
  'Other',
] as const;

export const DESKTOP_VALUE_CLAIMS = [
  'I watch your screen — the frames, and the text in your windows.',
  'I listen — your microphone, and the audio of your calls.',
  'It lands in your Omi account, and you read it back from Home.',
] as const;
