import Foundation

/// Participant context extracted from the active conversational environment
struct ActionContextEnvironment: Equatable, Sendable {
  let isMultiPartyCall: Bool
  let participantLabels: [String]

  init(isMultiPartyCall: Bool = false, participantLabels: [String] = []) {
    self.isMultiPartyCall = isMultiPartyCall
    self.participantLabels = participantLabels
  }
}

/// Represents a proposed action generated by the agent after inspecting
/// conversational context and memory facts.
struct ActionProposal: Equatable, Sendable, Identifiable {
  let id: String
  let actionType: String
  let title: String
  let summary: String
  let items: [String]
  let participants: [String]
  let estimatedCost: String?
  let isReversible: Bool
  let cancellationWindowSeconds: TimeInterval
  let createdAt: Date

  init(
    id: String = UUID().uuidString,
    actionType: String,
    title: String,
    summary: String,
    items: [String],
    participants: [String],
    estimatedCost: String? = nil,
    isReversible: Bool = true,
    cancellationWindowSeconds: TimeInterval = 30.0,
    createdAt: Date = Date()
  ) {
    self.id = id
    self.actionType = actionType
    self.title = title
    self.summary = summary
    self.items = items
    self.participants = participants
    self.estimatedCost = estimatedCost
    self.isReversible = isReversible
    self.cancellationWindowSeconds = cancellationWindowSeconds
    self.createdAt = createdAt
  }
}

/// Execution status of a chained action
enum ActionExecutionStatus: String, Equatable, Sendable {
  case pending
  case executed
  case cancelled
  case failed
}

/// A receipt produced upon executing a chained action, supporting reversible rollback
struct ActionReceipt: Equatable, Sendable, Identifiable {
  let id: String
  let proposalId: String
  let title: String
  let summary: String
  let executedAt: Date
  var status: ActionExecutionStatus
  let cancellationDeadline: Date?

  init(
    id: String = UUID().uuidString,
    proposalId: String,
    title: String,
    summary: String,
    executedAt: Date = Date(),
    status: ActionExecutionStatus = .executed,
    cancellationDeadline: Date? = nil
  ) {
    self.id = id
    self.proposalId = proposalId
    self.title = title
    self.summary = summary
    self.executedAt = executedAt
    self.status = status
    self.cancellationDeadline = cancellationDeadline
  }

  func canUndo(now: Date = Date()) -> Bool {
    guard status == .executed, let deadline = cancellationDeadline else { return false }
    return now <= deadline
  }
}

/// Pure coordinator for multi-step action chaining (Inspect Context -> Plan -> Execute -> Reverse/Cancel)
enum ActionChainingPipeline {

  /// Plan an action proposal from user intent, speaker environment, and memory facts
  static func plan(
    intent: String,
    environmentalContext: ActionContextEnvironment? = nil,
    memoryPreferences: [String: String] = [:],
    now: Date = Date()
  ) -> ActionProposal? {
    let lower = intent.lowercased()

    // Detect food ordering intent
    if lower.contains("order") || lower.contains("food") || lower.contains("lunch") || lower.contains("dinner") {
      var participants: [String] = ["You"]
      var items: [String] = []

      // Check if another participant is present in the environmental context
      if let env = environmentalContext, env.isMultiPartyCall {
        for label in env.participantLabels {
          participants.append(label)
        }
      }

      // Resolve items from memory preferences
      for participant in participants {
        if let pref = memoryPreferences[participant] {
          items.append("\(participant): \(pref)")
        } else if participant == "You", let userPref = memoryPreferences["User"] ?? memoryPreferences["You"] {
          items.append("You: \(userPref)")
        } else {
          items.append("\(participant): Chef's Special / Pad Thai")
        }
      }

      let participantSummary = participants.joined(separator: " and ")
      return ActionProposal(
        actionType: "food_order",
        title: "Food Order for \(participantSummary)",
        summary: "Order prepared from conversation context & saved food preferences",
        items: items,
        participants: participants,
        estimatedCost: "$\(items.count * 16).00",
        isReversible: true,
        cancellationWindowSeconds: 30.0,
        createdAt: now
      )
    }

    return nil
  }

  /// Execute an action proposal and return a reversible receipt
  static func execute(
    proposal: ActionProposal,
    now: Date = Date()
  ) -> ActionReceipt {
    let deadline =
      proposal.isReversible
      ? now.addingTimeInterval(proposal.cancellationWindowSeconds)
      : nil

    return ActionReceipt(
      proposalId: proposal.id,
      title: "✓ \(proposal.title)",
      summary: proposal.summary,
      executedAt: now,
      status: .executed,
      cancellationDeadline: deadline
    )
  }

  /// Cancel/rollback an executed action within its cancellation window
  static func cancel(
    receipt: ActionReceipt,
    now: Date = Date()
  ) -> ActionReceipt? {
    guard receipt.canUndo(now: now) else { return nil }

    var updated = receipt
    updated.status = .cancelled
    return updated
  }
}
