"""Shared bounds for hosted MCP tool inputs, schemas, and the POST transport."""

MCP_MEMORY_LIST_DEFAULT_LIMIT = 20
MCP_MEMORY_LIST_MAX_LIMIT = 100
MCP_MEMORY_LIST_MAX_SCAN = 200
MCP_CONVERSATION_LIST_MAX_LIMIT = 100
MCP_CONVERSATION_FETCH_DEFAULT_MAX_SEGMENTS = 120
MCP_CONVERSATION_FETCH_MAX_SEGMENTS = 500
MCP_CONVERSATION_FETCH_DEFAULT_MAX_CHARS = 24_000
MCP_CONVERSATION_FETCH_MAX_CHARS = 100_000
MCP_CONVERSATION_SEARCH_SNIPPET_CHARS = 240

# JSON-RPC batch (array) requests are a pre-2025-06-18 transport feature. The
# cap keeps a single POST from fanning out into unbounded per-message work.
MCP_MAX_BATCH_MESSAGES = 20
