// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Production [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with actual production Firebase configuration
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_PRODUCTION_ANDROID_API_KEY',
    appId: 'YOUR_PRODUCTION_ANDROID_APP_ID',
    messagingSenderId: 'YOUR_PRODUCTION_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PRODUCTION_PROJECT_ID',
    storageBucket: 'YOUR_PRODUCTION_STORAGE_BUCKET',
  );

  // TODO: Replace with actual production Firebase configuration
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_PRODUCTION_IOS_API_KEY',
    appId: 'YOUR_PRODUCTION_IOS_APP_ID',
    messagingSenderId: 'YOUR_PRODUCTION_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PRODUCTION_PROJECT_ID',
    storageBucket: 'YOUR_PRODUCTION_STORAGE_BUCKET',
    androidClientId: 'YOUR_PRODUCTION_ANDROID_CLIENT_ID',
    iosClientId: 'YOUR_PRODUCTION_IOS_CLIENT_ID',
    iosBundleId: 'YOUR_PRODUCTION_IOS_BUNDLE_ID',
  );
}