// Generated by scripts/check_app_addressability.py --generate; do not edit.
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';

bool isCatalogInteractive(Widget widget, {bool includeDisabled = false}) {
  if (widget is IconButton) {
    return true;
  }
  if (widget is TextButton) {
    return true;
  }
  if (widget is ElevatedButton) {
    return true;
  }
  if (widget is OutlinedButton) {
    return true;
  }
  if (widget is FilledButton) {
    return true;
  }
  if (widget is FloatingActionButton) {
    return true;
  }
  if (widget is CupertinoButton) {
    return true;
  }
  if (widget is GestureDetector) {
    return includeDisabled ||
        widget.onTapDown != null ||
        widget.onTapUp != null ||
        widget.onTap != null ||
        widget.onTapMove != null ||
        widget.onTapCancel != null ||
        widget.onDoubleTapDown != null ||
        widget.onDoubleTap != null ||
        widget.onDoubleTapCancel != null ||
        widget.onLongPressDown != null ||
        widget.onLongPressCancel != null ||
        widget.onLongPress != null ||
        widget.onLongPressStart != null ||
        widget.onLongPressMoveUpdate != null ||
        widget.onLongPressUp != null ||
        widget.onLongPressEnd != null ||
        widget.onVerticalDragDown != null ||
        widget.onVerticalDragStart != null ||
        widget.onVerticalDragUpdate != null ||
        widget.onVerticalDragEnd != null ||
        widget.onVerticalDragCancel != null ||
        widget.onHorizontalDragDown != null ||
        widget.onHorizontalDragStart != null ||
        widget.onHorizontalDragUpdate != null ||
        widget.onHorizontalDragEnd != null ||
        widget.onHorizontalDragCancel != null ||
        widget.onPanDown != null ||
        widget.onPanStart != null ||
        widget.onPanUpdate != null ||
        widget.onPanEnd != null ||
        widget.onPanCancel != null ||
        widget.onScaleStart != null ||
        widget.onScaleUpdate != null ||
        widget.onScaleEnd != null;
  }
  if (widget is InkWell) {
    return includeDisabled ||
        widget.onTap != null ||
        widget.onTapDown != null ||
        widget.onTapUp != null ||
        widget.onTapCancel != null ||
        widget.onDoubleTap != null ||
        widget.onLongPress != null ||
        widget.onLongPressUp != null;
  }
  if (widget is InkResponse) {
    return includeDisabled ||
        widget.onTap != null ||
        widget.onTapDown != null ||
        widget.onTapUp != null ||
        widget.onTapCancel != null ||
        widget.onDoubleTap != null ||
        widget.onLongPress != null ||
        widget.onLongPressUp != null;
  }
  if (widget is TextField) {
    return true;
  }
  if (widget is TextFormField) {
    return true;
  }
  if (widget is CupertinoTextField) {
    return true;
  }
  if (widget is Checkbox) {
    return true;
  }
  if (widget is Radio) {
    return true;
  }
  if (widget is Switch) {
    return true;
  }
  if (widget is Slider) {
    return true;
  }
  if (widget is RangeSlider) {
    return true;
  }
  if (widget is DropdownButton) {
    return true;
  }
  if (widget is DropdownButtonFormField) {
    return true;
  }
  if (widget is PopupMenuButton) {
    return true;
  }
  if (widget is ListTile) {
    return includeDisabled || widget.onTap != null || widget.onLongPress != null;
  }
  if (widget is CheckboxListTile) {
    return true;
  }
  if (widget is RadioListTile) {
    return true;
  }
  if (widget is SwitchListTile) {
    return true;
  }
  return false;
}
