"""Backward-compatible shim — implementation in ``utils.memory.v3_f6.redaction`` (WS-G8b)."""

from utils.memory.v3_f6.redaction import (
    AUDIT_FIELDS,
    fingerprint,
    FINGERPRINT_RE,
    FingerprintContractError,
    FORBIDDEN_FIELD_FRAGMENTS,
    FORBIDDEN_VALUE_PATTERNS,
    HMAC_KEY,
    OBSERVATION_FIELDS,
    READ_BOUNDS_FIELDS,
    RedactionContractError,
    render_redacted_evidence_json,
    require_exact_fields,
    TOP_LEVEL_FIELDS,
    validate_redacted_evidence,
    _check_field_name,
    _check_string_value,
    _require_exact_top_level,
    _validate_audit,
    _validate_read_bounds,
    _walk,
)

__all__ = [
    "AUDIT_FIELDS",
    "fingerprint",
    "FINGERPRINT_RE",
    "FingerprintContractError",
    "FORBIDDEN_FIELD_FRAGMENTS",
    "FORBIDDEN_VALUE_PATTERNS",
    "HMAC_KEY",
    "OBSERVATION_FIELDS",
    "READ_BOUNDS_FIELDS",
    "RedactionContractError",
    "render_redacted_evidence_json",
    "require_exact_fields",
    "TOP_LEVEL_FIELDS",
    "validate_redacted_evidence",
    "_check_field_name",
    "_check_string_value",
    "_require_exact_top_level",
    "_validate_audit",
    "_validate_read_bounds",
    "_walk",
]
