"""Backward-compatible shim — implementation in ``utils.memory.v3_f6.run_record`` (WS-G8b)."""

from utils.memory.v3_f6.run_record import (
    APPROVAL_FIELDS,
    EvidenceTargetRegistry,
    ExecutionWindow,
    READ_BOUNDS_FIELDS,
    require_exact_fields,
    RUN_RECORD_FIELDS,
    RunRecordValidationError,
    validate_run_record,
    ValidatedRunRecord,
    ValidationError,
    WINDOW_FIELDS,
    _parse_time,
    _parse_window,
    _require_exact_fields,
    _require_str,
    _validate_approvals,
    _validate_hash_map,
)

__all__ = [
    "APPROVAL_FIELDS",
    "EvidenceTargetRegistry",
    "ExecutionWindow",
    "READ_BOUNDS_FIELDS",
    "require_exact_fields",
    "RUN_RECORD_FIELDS",
    "RunRecordValidationError",
    "validate_run_record",
    "ValidatedRunRecord",
    "ValidationError",
    "WINDOW_FIELDS",
    "_parse_time",
    "_parse_window",
    "_require_exact_fields",
    "_require_str",
    "_validate_approvals",
    "_validate_hash_map",
]
