// AUTO-GENERATED by backend/scripts/generate_integration_sdks.py from docs/api-reference/integration-public-openapi.json.
// Do not edit by hand. Re-run the generator after OpenAPI changes.
// Spec sha256[0:16]=726f4b3a685da076

library;

export 'omi_integration.g.dart';
