apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: deepgram-self-hosted-cluster
  region: us-west-2
  version: "1.30"

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: cluster-autoscaler-sa
        namespace: dg-self-hosted
      wellKnownPolicies:
        autoScaler: true
      roleName: cluster-autoscaler-role
      roleOnly: true
    - metadata:
        name: efs-csi-controller-sa
        namespace: kube-system
      wellKnownPolicies:
        efsCSIController: true
      roleName: efs-csi-driver-role
      roleOnly: true

managedNodeGroups:
  - name: control-plane-node-group
    minSize: 1
    desiredCapacity: 1
    maxSize: 3
    instanceType: t3.large
    amiFamily: Ubuntu2204
    iam:
      withAddonPolicies:
        autoScaler: true
    propagateASGTags: true
  - name: engine-node-group
    minSize: 0
    desiredCapacity: 0
    maxSize: 8
    instanceType: g6.2xlarge
    amiFamily: AmazonLinux2023
    labels:
      k8s.deepgram.com/node-type: engine
      k8s.amazonaws.com/accelerator: nvidia-l4
    iam:
      withAddonPolicies:
        efs: true
        autoScaler: true
    taints:
      - key: efs.csi.aws.com/agent-not-ready
        value: "true"
        effect: NoExecute
    propagateASGTags: true
  - name: api-node-group
    minSize: 0
    desiredCapacity: 0
    maxSize: 2
    instanceType: c5n.xlarge
    amiFamily: AmazonLinux2023
    labels:
      k8s.deepgram.com/node-type: api
    iam:
      withAddonPolicies:
        autoScaler: true
    propagateASGTags: true
  - name: license-proxy-node-group
    minSize: 0
    desiredCapacity: 0
    maxSize: 2
    instanceType: t3.large
    amiFamily: AmazonLinux2023
    labels:
      k8s.deepgram.com/node-type: license-proxy
    iam:
      withAddonPolicies:
        autoScaler: true
    propagateASGTags: true
