// The scoped assistant-settings bridge: the whitelist (only its 6 keys may be
// written, nothing else), the sanitizer contract carried through from
// appSettings (a junk frequency lands as 0, never louder), the projection shape,
// and the dev-only debugNotify hook. Uses the REAL appSettings store (round-trips
// a throwaway file) so the sanitizer isn't re-declared here — only `notify` and
// electron's shell are mocked.
import { describe, it, expect, beforeEach, afterAll, vi } from 'vitest'
import { mkdtempSync, rmSync } from 'fs'
import { tmpdir } from 'os'
import { join } from 'path'

// Point the store at a throwaway userData dir (mirrors appSettings.test.ts) and
// capture ipcMain handlers so the test can invoke them like the renderer would.
const dir = mkdtempSync(join(tmpdir(), 'omi-assistant-ipc-'))
const handlers = new Map<string, (...args: unknown[]) => unknown>()
// Hoisted so the vi.mock factory (also hoisted) can reference it without hitting
// the temporal-dead-zone of a plain top-level const.
const notifyProactive = vi.hoisted(() => vi.fn(() => true))

vi.mock('electron', () => ({
  app: { getPath: (): string => dir },
  globalShortcut: {
    register: (): boolean => true,
    unregister: (): void => {},
    isRegistered: (): boolean => false
  },
  ipcMain: {
    handle: (channel: string, fn: (...args: unknown[]) => unknown): void => {
      handlers.set(channel, fn)
    }
  },
  BrowserWindow: { getAllWindows: (): unknown[] => [] }
}))
// is.dev true so the dev-only assistants:debugNotify hook is registered + covered.
vi.mock('@electron-toolkit/utils', () => ({ is: { dev: true } }))
vi.mock('../assistants/core/notify', () => ({ notifyProactive }))

import {
  filterAssistantPatch,
  projectAssistantSettings,
  registerAssistantSettingsHandlers,
  _resetAssistantSettingsForTests
} from './assistantSettings'
import { getAppSettings, _resetForTests } from '../appSettings'
import type { AssistantSettingsView } from '../../shared/types'

afterAll(() => rmSync(dir, { recursive: true, force: true }))

// Invoke a captured handler with a fake IpcMainInvokeEvent as the first arg.
const invoke = (channel: string, ...args: unknown[]): unknown => {
  const fn = handlers.get(channel)
  if (!fn) throw new Error(`no handler registered for ${channel}`)
  return fn({}, ...args)
}

const VIEW_KEYS: (keyof AssistantSettingsView)[] = [
  'notificationsEnabled',
  'notificationFrequency',
  'focusNotificationsEnabled',
  'memoryEnabled',
  'glowOverlayEnabled',
  'screenAnalysisEnabled'
]

describe('assistantSettings IPC', () => {
  beforeEach(() => {
    _resetForTests()
    try {
      rmSync(join(dir, 'app-settings.json'), { force: true })
    } catch {
      /* ignore */
    }
    handlers.clear()
    notifyProactive.mockClear()
    _resetAssistantSettingsForTests()
    registerAssistantSettingsHandlers()
  })

  describe('filterAssistantPatch (whitelist)', () => {
    it('keeps only the whitelisted keys and drops everything else', () => {
      const filtered = filterAssistantPatch({
        notificationFrequency: 3,
        memoryEnabled: true,
        recordHotkey: 'X',
        goalAutoGeneratedIds: [{ id: 'g', createdAt: 1 }],
        summonHotkey: 'Y'
      })
      expect(filtered).toEqual({ notificationFrequency: 3, memoryEnabled: true })
      expect(filtered).not.toHaveProperty('recordHotkey')
      expect(filtered).not.toHaveProperty('goalAutoGeneratedIds')
      expect(filtered).not.toHaveProperty('summonHotkey')
    })

    it('returns an empty patch for non-object input', () => {
      expect(filterAssistantPatch(null)).toEqual({})
      expect(filterAssistantPatch(undefined)).toEqual({})
      expect(filterAssistantPatch('notificationFrequency')).toEqual({})
      expect(filterAssistantPatch(5)).toEqual({})
    })
  })

  describe('assistants:setSettings', () => {
    it('writes a whitelisted key and never touches a non-whitelisted one', () => {
      const before = getAppSettings().recordHotkey
      const view = invoke('assistants:setSettings', {
        notificationFrequency: 3,
        recordHotkey: 'ZZZ+All'
      }) as AssistantSettingsView
      expect(view.notificationFrequency).toBe(3)
      // The out-of-band key must never have reached the store.
      expect(getAppSettings().recordHotkey).toBe(before)
    })

    it('sanitizes a junk frequency to 0 (Off), never louder', () => {
      for (const junk of [7, 1.5, '3', -1, NaN]) {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const view = invoke('assistants:setSettings', {
          notificationFrequency: junk as any
        }) as AssistantSettingsView
        expect(view.notificationFrequency).toBe(0)
      }
    })

    it('persists a valid toggle write and reflects it in the projection', () => {
      const view = invoke('assistants:setSettings', {
        memoryEnabled: true,
        notificationsEnabled: false
      }) as AssistantSettingsView
      expect(view.memoryEnabled).toBe(true)
      expect(view.notificationsEnabled).toBe(false)
      expect(getAppSettings().memoryEnabled).toBe(true)
    })
  })

  describe('projection', () => {
    it('exposes exactly the assistant-view keys', () => {
      expect(Object.keys(projectAssistantSettings()).sort()).toEqual([...VIEW_KEYS].sort())
    })

    it('assistants:getSettings returns the current projection', () => {
      invoke('assistants:setSettings', { notificationFrequency: 4 })
      const view = invoke('assistants:getSettings') as AssistantSettingsView
      expect(view.notificationFrequency).toBe(4)
      expect(Object.keys(view).sort()).toEqual([...VIEW_KEYS].sort())
    })
  })

  describe('assistants:debugNotify (dev only)', () => {
    it('pushes one notification through the real throttle and returns its result', () => {
      const result = invoke('assistants:debugNotify') as boolean
      expect(result).toBe(true)
      expect(notifyProactive).toHaveBeenCalledTimes(1)
      expect(notifyProactive).toHaveBeenCalledWith(
        'assistants-debug',
        expect.objectContaining({ headline: expect.any(String) })
      )
    })
  })
})
