// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrJ-FLwWCKX3Q4BYXickMscw1t70beKEQ',
    appId: '1:628811116024:web:a41eedc39ce4f6a074fa0d',
    messagingSenderId: '628811116024',
    projectId: 'friend-test-c07c1',
    authDomain: 'friend-test-c07c1.firebaseapp.com',
    storageBucket: 'friend-test-c07c1.appspot.com',
    measurementId: 'G-5LDYGCL0ZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIQHi1NpYSg2_SmRLuejYKUDtfy5zKh-I',
    appId: '1:628811116024:android:417f18fab4fb5b8474fa0d',
    messagingSenderId: '628811116024',
    projectId: 'friend-test-c07c1',
    storageBucket: 'friend-test-c07c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH6ychmlZLEF6pVh6HtfZFbGfawhXjCZ4',
    appId: '1:628811116024:ios:000228d8bd5fabdb74fa0d',
    messagingSenderId: '628811116024',
    projectId: 'friend-test-c07c1',
    storageBucket: 'friend-test-c07c1.appspot.com',
    iosBundleId: 'com.friend-app-with-wearable.ios12.develop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH6ychmlZLEF6pVh6HtfZFbGfawhXjCZ4',
    appId: '1:628811116024:ios:f40e8cd76edeea9274fa0d',
    messagingSenderId: '628811116024',
    projectId: 'friend-test-c07c1',
    storageBucket: 'friend-test-c07c1.appspot.com',
    iosBundleId: 'com.friend.ios',
  );
}
