name: Deploy Plugins to Cloud RUN

# TODO: determine if changes to backend folder before pushing

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy to'
        required: true
        default: 'development'
      branch:
        description: 'Branch to deploy from'
        required: true
        default: 'main'

env:
  SERVICE: plugins
  REGION: us-central1

jobs:
  deploy:
    environment: ${{ github.event.inputs.environment }}
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Validate Environment Input
        env:
          INPUT_ENV: ${{ github.event.inputs.environment }}
        run: |
          if [[ "$INPUT_ENV" != "development" && "$INPUT_ENV" != "prod" ]]; then
            echo "Invalid environment: $INPUT_ENV. Must be 'development' or 'prod'."
            exit 1
          fi

      # To workaround "no space left on device" issue of GitHub-hosted runner
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - run: gcloud auth configure-docker

      - name: Build and Push Docker image
        run: |
          docker build -t gcr.io/${{ vars.GCP_PROJECT_ID }}/${{ env.SERVICE }} -f plugins/Dockerfile .
          docker push gcr.io/${{ vars.GCP_PROJECT_ID }}/${{ env.SERVICE }}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: gcr.io/${{ vars.GCP_PROJECT_ID }}/${{ env.SERVICE }}

      # If required, use the Cloud Run url output in later steps
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}