name: Sync Documentation to READMEs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/docs/docs/developer/sdk/**'

jobs:
  sync-docs-to-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Create sync script
        run: |
          cat > sync-docs.js << 'EOF'
          const fs = require('fs');
          const path = require('path');

          // Define mapping of MDX files to README locations
          const fileMapping = {
            'docs/docs/docs/developer/sdk/ReactNative.mdx': 'sdks/react-native/README.md',
            'docs/docs/docs/developer/sdk/swift.mdx': 'sdks/swift/README.md',
            'docs/docs/docs/developer/sdk/python.mdx': 'sdks/python/README.md'
          };

          // Process each MDX file
          Object.entries(fileMapping).forEach(([mdxFile, readmeFile]) => {
            if (!fs.existsSync(mdxFile)) {
              console.warn(`Warning: Source file ${mdxFile} does not exist`);
              return;
            }

            console.log(`Processing ${mdxFile} -> ${readmeFile}`);
            
            // Create directory if it doesn't exist
            const readmeDir = path.dirname(readmeFile);
            if (!fs.existsSync(readmeDir)) {
              fs.mkdirSync(readmeDir, { recursive: true });
            }
            
            // Read the MDX file
            const mdxContent = fs.readFileSync(mdxFile, 'utf8');
            
            // Extract content without frontmatter
            const frontmatterRegex = /^---\s*\n([\s\S]*?)\n---\s*\n/;
            const frontmatterMatch = mdxContent.match(frontmatterRegex);
            
            let content = mdxContent;
            if (frontmatterMatch) {
              content = mdxContent.replace(frontmatterRegex, '');
            }
            
            // Add auto-generation note
            const header = `<!-- DO NOT EDIT THIS FILE MANUALLY -->\n<!-- This file is automatically generated from the Mintlify docs -->\n<!-- Source: ${mdxFile} -->\n\n`;
            const readmeContent = header + content;
            
            // Write to README
            fs.writeFileSync(readmeFile, readmeContent);
            
            console.log(`Successfully synced ${mdxFile} to ${readmeFile}`);
          });
          EOF
          
      - name: Run sync script
        run: node sync-docs.js
          
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: GitHub Action
          author_email: action@github.com
          message: 'Sync docs to READMEs'
          add: |
            sdks/react-native/README.md
            sdks/swift/README.md
            sdks/python/README.md 